// @generated by protoc-gen-pbtkurl -- do not edit.

#pragma once

#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iomanip>
#include <sstream>
#include <string>

namespace example {

class Address {
  private:
    std::string street_ = "";
    std::string city_ = "";
    std::string state_ = "";
    int32_t zip_ = 0;

  public:
    Address() = default;

    Address(const Address&) = default;
    Address(Address&&) = default;
    Address& operator=(const Address&) = default;
    Address& operator=(Address&&) = default;

    const std::string& street() const { return street_; }
    void set_street(const std::string& value) { street_ = value; }
    void set_street(std::string&& value) { street_ = std::move(value); }

    const std::string& city() const { return city_; }
    void set_city(const std::string& value) { city_ = value; }
    void set_city(std::string&& value) { city_ = std::move(value); }

    const std::string& state() const { return state_; }
    void set_state(const std::string& value) { state_ = value; }
    void set_state(std::string&& value) { state_ = std::move(value); }

    int32_t zip() const { return zip_; }
    void set_zip(int32_t value) { zip_ = value; }

    bool SerializeToString(std::string* output) const;
    bool ParseFromString(const std::string& input);
};

namespace pbtk_detail_Address {

inline std::string url_encode(const std::string& input) {
  std::ostringstream oss;
  oss << std::hex << std::uppercase;
  for (unsigned char c : input) {
    if (std::isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~') {
      oss << c;
    }
    else {
      oss << '%%' << std::setw(2) << std::setfill('0') << static_cast<int>(c);
    }
  }
  return oss.str();
}

inline std::string url_decode(const std::string& input) {
  std::string result;
  result.reserve(input.size());
  for (size_t i = 0; i < input.size(); i++) {
    if (input[i] == '%' && i + 2 < input.size()) {
      char hi = input[i + 1], lo = input[i + 2];
      auto hex_val = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        if (c >= 'A' && c <= 'F') return c - 'A' + 10;
        if (c >= 'a' && c <= 'f') return c - 'a' + 10;
        return -1;
      };
      int h = hex_val(hi), l = hex_val(lo);
      if (h >= 0 && l >= 0) {
        result += static_cast<char>((h << 4) | l);
        i += 2;
        continue;
      }
    }
    result += input[i];
  }
  return result;
}

inline std::string base64_encode(const std::vector<uint8_t>& data) {
  static const char table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  std::string result;
  size_t len = data.size();
  result.reserve(4 * ((len + 2) / 3));
  for (size_t i = 0; i < len; i += 3) {
    uint32_t a = data[i];
    uint32_t b = (i + 1 < len) ? data[i + 1] : 0;
    uint32_t c = (i + 2 < len) ? data[i + 2] : 0;
    uint32_t triple = (a << 16) | (b << 8) | c;
    result += table[(triple >> 18) & 0x3F];
    result += table[(triple >> 12) & 0x3F];
    result += (i + 1 < len) ? table[(triple >> 6) & 0x3F] : '=';
    result += (i + 2 < len) ? table[triple & 0x3F] : '=';
  }
  return result;
}

inline std::vector<uint8_t> base64_decode(const std::string& input) {
  auto b64_val = [](char c) -> int {
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a' + 26;
    if (c >= '0' && c <= '9') return c - '0' + 52;
    if (c == '+') return 62;
    if (c == '/') return 63;
    return -1;
  };
  std::vector<uint8_t> result;
  size_t len = input.size();
  if (len == 0) return result;
  size_t padding = 0;
  if (input[len - 1] == '=') padding++;
  if (len > 1 && input[len - 2] == '=') padding++;
  result.reserve((len / 4) * 3 - padding);
  for (size_t i = 0; i < len; i += 4) {
    int a = b64_val(input[i]);
    int b = (i + 1 < len) ? b64_val(input[i + 1]) : 0;
    int c = (i + 2 < len) ? b64_val(input[i + 2]) : 0;
    int d = (i + 3 < len) ? b64_val(input[i + 3]) : 0;
    if (a < 0) a = 0; if (b < 0) b = 0; if (c < 0) c = 0; if (d < 0) d = 0;
    uint32_t triple = ((uint32_t)a << 18) | ((uint32_t)b << 12) | ((uint32_t)c << 6) | (uint32_t)d;
    result.push_back((triple >> 16) & 0xFF);
    if (i + 2 < len && input[i + 2] != '=') result.push_back((triple >> 8) & 0xFF);
    if (i + 3 < len && input[i + 3] != '=') result.push_back(triple & 0xFF);
  }
  return result;
}

} // namespace pbtk_detail_Address

inline int Address_count_pbtk_fields(const Address& msg) {
  int count = 0;
  count++;
  count++;
  count++;
  count++;
  return count;
}

inline void Address_append_pbtk_fields(std::ostringstream& oss, const Address& msg) {
  oss << "!1s" << pbtk_detail_::url_encode(msg.street());
  oss << "!2s" << pbtk_detail_::url_encode(msg.city());
  oss << "!3s" << pbtk_detail_::url_encode(msg.state());
  oss << "!4i" << msg.zip();
}

inline bool Address::SerializeToString(std::string* output) const {
  if (!output) return false;
  std::ostringstream oss;
  Address_append_pbtk_fields(oss, *this);
  *output = oss.str();
  return true;
}

inline std::vector<std::string> Address_tokenize_pbtk(const std::string& input) {
  std::vector<std::string> tokens;
  size_t i = 0;
  if (!input.empty() && input[0] == '!') i = 1;
  while (i < input.size()) {
    size_t next = input.find('!', i);
    if (next == std::string::npos) {
      tokens.push_back(input.substr(i));
      break;
    }
    tokens.push_back(input.substr(i, next - i));
    i = next + 1;
  }
  return tokens;
}

inline Address Address_parse_pbtk_tokens(const std::vector<std::string>& tokens, int field_count, size_t& offset) {
  Address obj;
  int consumed = 0;
  while (consumed < field_count && offset < tokens.size()) {
    const std::string& token = tokens[offset];
    size_t num_end = 0;
    while (num_end < token.size() && std::isdigit(token[num_end])) num_end++;
    if (num_end == 0 || num_end >= token.size()) { offset++; consumed++; continue; }
    int field_num = [&]() -> int { try { return std::stoi(token.substr(0, num_end)); } catch (...) { return 0; } }();
    std::string value = token.substr(num_end + 1);

    switch (field_num) {
      case 1: {
        obj.set_street(pbtk_detail_Address::url_decode(value));
        offset++;
        consumed++;
        break;
      }
      case 2: {
        obj.set_city(pbtk_detail_Address::url_decode(value));
        offset++;
        consumed++;
        break;
      }
      case 3: {
        obj.set_state(pbtk_detail_Address::url_decode(value));
        offset++;
        consumed++;
        break;
      }
      case 4: {
        obj.set_zip([&]() -> int { try { return std::stoi(value); } catch (...) { return 0; } }());
        offset++;
        consumed++;
        break;
      }
      default: offset++; consumed++; break;
    }
  }
  return obj;
}

inline bool Address::ParseFromString(const std::string& input) {
  if (input.empty()) { *this = Address{}; return true; }
  auto tokens = Address_tokenize_pbtk(input);
  size_t offset = 0;
  *this = Address_parse_pbtk_tokens(tokens, static_cast<int>(tokens.size()), offset);
  return true;
}

} // namespace example
