/*
 * Copyright 2024 protobuf-text-codecs contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.pbtkurl.codegen.kotlin;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.LanguageGenerator;
import dev.protocgen.textcodecs.jsonarray.codegen.kotlin.KotlinNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.kotlin.KotlinTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import dev.protocgen.textcodecs.jsonarray.model.TypeRegistry;
import java.util.ArrayList;
import java.util.List;

/**
 * Kotlin language code generator for pbtk URL encoding. Produces Kotlin source files with
 * toPbtkUrl()/fromPbtkUrl() serialization methods. Generated code uses only Kotlin/JVM stdlib
 * (StringBuilder, URLEncoder, URLDecoder, Base64).
 *
 * <p>The pbtk format encodes protobuf messages as URL strings: {@code
 * !<fieldNumber><typeChar><value>} where type chars are: b=bool(0/1), i=integer, f=float, d=double,
 * s=string(URL-encoded), e=enum(int), m=message(count of sub-fields), z=bytes(base64).
 */
public class PbtkKotlinGenerator implements LanguageGenerator {

  private static final String GENERATED_MARKER =
      "// @generated by protoc-gen-pbtkurl \u2014 do not edit.";

  private final KotlinNameResolver nameResolver = new KotlinNameResolver();
  private final KotlinTypeMapper typeMapper = new KotlinTypeMapper();

  @Override
  public List<CodeGeneratorResponse.File> generate(ProtoFile file, TypeRegistry registry) {
    List<CodeGeneratorResponse.File> result = new ArrayList<>();

    for (ProtoMessage message : file.getMessages()) {
      nameResolver.validateFieldNames(message.getFields());
      String sourceCode = emitMessage(message, file);
      String outputPath = nameResolver.outputFilePath(file, message.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    for (ProtoEnum protoEnum : file.getEnums()) {
      String sourceCode = emitTopLevelEnum(protoEnum, file);
      String outputPath = nameResolver.outputFilePath(file, protoEnum.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    return result;
  }

  @Override
  public String languageId() {
    return "kotlin";
  }

  // ---------------------------------------------------------------------------
  // Top-level message / enum emission
  // ---------------------------------------------------------------------------

  private String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String pkg = nameResolver.resolvePackage(file);
    String className = nameResolver.messageClassName(message.getName());

    w.line(GENERATED_MARKER);
    w.blankLine();

    if (!pkg.isEmpty()) {
      w.line("package %s", pkg);
      w.blankLine();
    }

    emitDocComment(w, message.getComment());

    w.block(
        "class " + className + " private constructor(builder: Builder)",
        () -> {
          emitMessageBody(w, message, className);
        });

    return w.toString();
  }

  private String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String pkg = nameResolver.resolvePackage(file);

    w.line(GENERATED_MARKER);
    w.blankLine();

    if (!pkg.isEmpty()) {
      w.line("package %s", pkg);
      w.blankLine();
    }

    emitEnum(w, protoEnum);
    return w.toString();
  }

  // ---------------------------------------------------------------------------
  // Message body
  // ---------------------------------------------------------------------------

  private void emitMessageBody(CodeWriter w, ProtoMessage message, String className) {
    // Immutable val fields
    emitFields(w, message);

    // Presence tracking
    if (hasPresenceTrackedFields(message)) {
      w.blankLine();
      w.line("private val presentFields_: java.util.BitSet");
    }

    // Oneof case tracking
    emitOneofCaseFields(w, message);

    // Init block
    emitInitBlock(w, message);

    // Getters
    emitGetters(w, message);

    // Oneof case enums
    emitOneofCaseEnums(w, message);

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
    }

    // Nested messages
    for (ProtoMessage nested : message.getNestedMessages()) {
      w.blankLine();
      emitNestedMessage(w, nested);
    }

    // pbtk serializer
    emitSerializer(w, message);

    // toString, equals, hashCode
    emitToString(w, message, className);
    emitEquals(w, message, className);
    emitHashCode(w, message);

    // Builder
    emitBuilder(w, message, className);

    // Companion object
    emitCompanionObject(w, message, className);
  }

  // ---------------------------------------------------------------------------
  // Fields
  // ---------------------------------------------------------------------------

  private void emitFields(CodeWriter w, ProtoMessage message) {
    if (!message.getFields().isEmpty()) {
      w.blankLine();
    }
    for (ProtoField field : message.getFields()) {
      String ktType = typeMapper.immutableType(field);
      String ktName = nameResolver.fieldName(field.getName());
      w.line("val %s: %s", ktName, ktType);
    }
  }

  private void emitOneofCaseFields(CodeWriter w, ProtoMessage message) {
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      w.blankLine();
      String caseName = nameResolver.fieldName(group.name()) + "Case_";
      w.line("private val %s: Int", caseName);
    }
  }

  private void emitInitBlock(CodeWriter w, ProtoMessage message) {
    w.blankLine();
    w.block(
        "init",
        () -> {
          for (ProtoField field : message.getFields()) {
            String ktName = nameResolver.fieldName(field.getName());
            if (field.isRepeated()) {
              w.line("this.%s = builder.%s.toList()", ktName, ktName);
            } else if (field.isMap()) {
              w.line("this.%s = builder.%s.toMap()", ktName, ktName);
            } else {
              w.line("this.%s = builder.%s", ktName, ktName);
            }
          }
          if (hasPresenceTrackedFields(message)) {
            w.line("this.presentFields_ = builder.presentFields_.clone() as java.util.BitSet");
          }
          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            String caseName = nameResolver.fieldName(group.name()) + "Case_";
            w.line("this.%s = builder.%s", caseName, caseName);
          }
        });
  }

  // ---------------------------------------------------------------------------
  // Getters
  // ---------------------------------------------------------------------------

  private void emitGetters(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String ktName = nameResolver.fieldName(field.getName());
      String pascalName = KotlinNameResolver.snakeToPascal(field.getName());

      if (field.isRepeated()) {
        w.blankLine();
        w.block(
            "fun get" + pascalName + "Count(): Int", () -> w.line("return this.%s.size", ktName));
        w.blankLine();
        w.block(
            "fun get" + pascalName + "(index: Int): " + elementType(field),
            () -> w.line("return this.%s[index]", ktName));
      }

      if (field.isMap()) {
        String keyType = typeMapper.scalarType(field.getMapKeyType());
        String valueType = mapValueType(field);
        w.blankLine();
        w.block(
            "fun get" + pascalName + "Count(): Int", () -> w.line("return this.%s.size", ktName));
        w.blankLine();
        w.block(
            "fun contains" + pascalName + "(key: " + keyType + "): Boolean",
            () -> w.line("return this.%s.containsKey(key)", ktName));
        w.blankLine();
        w.block(
            "fun get"
                + pascalName
                + "OrDefault(key: "
                + keyType
                + ", defaultValue: "
                + valueType
                + "): "
                + valueType,
            () -> w.line("return this.%s.getOrDefault(key, defaultValue)", ktName));
        w.blankLine();
        w.block(
            "fun get" + pascalName + "OrThrow(key: " + keyType + "): " + valueType,
            () -> {
              w.block(
                  "if (!this." + ktName + ".containsKey(key))",
                  () -> w.line("throw IllegalArgumentException(\"Key not found: $key\")"));
              w.line("return this.%s[key]!!", ktName);
            });
      }

      if (field.hasExplicitPresence()
          || field.getKind() == ProtoField.FieldKind.MESSAGE
          || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
        w.blankLine();
        w.block(
            "fun has" + pascalName + "(): Boolean",
            () -> {
              if (field.hasExplicitPresence()) {
                w.line("return this.presentFields_.get(%d)", field.getArrayPosition());
              } else {
                w.line("return this.%s != null", ktName);
              }
            });
      }
    }

    // Oneof getXxxCase()
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String pascalOneof = KotlinNameResolver.snakeToPascal(group.name());
      String enumName = pascalOneof + "Case";
      String caseName = nameResolver.fieldName(group.name()) + "Case_";
      w.blankLine();
      w.block(
          "fun get" + pascalOneof + "Case(): " + enumName,
          () -> w.line("return %s.forNumber(%s)", enumName, caseName));
    }
  }

  // ---------------------------------------------------------------------------
  // Oneof case enums
  // ---------------------------------------------------------------------------

  private void emitOneofCaseEnums(CodeWriter w, ProtoMessage message) {
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      w.blankLine();
      String enumName = KotlinNameResolver.snakeToPascal(group.name()) + "Case";
      w.block(
          "enum class " + enumName + "(val number: Int)",
          () -> {
            w.line("%s_NOT_SET(0),", snakeToUpperSnake(group.name()));
            for (int i = 0; i < group.members().size(); i++) {
              ProtoField member = group.members().get(i);
              String suffix = i < group.members().size() - 1 ? "," : ";";
              w.line(
                  "%s(%d)%s", snakeToUpperSnake(member.getName()), member.getFieldNumber(), suffix);
            }

            w.blankLine();
            w.block("fun getNumber(): Int", () -> w.line("return number"));
            w.blankLine();
            w.block(
                "companion object",
                () -> {
                  w.block(
                      "fun forNumber(number: Int): " + enumName,
                      () -> {
                        w.block(
                            "for (v in entries)",
                            () -> w.block("if (v.number == number)", () -> w.line("return v")));
                        w.line("return %s_NOT_SET", snakeToUpperSnake(group.name()));
                      });
                });
          });
    }
  }

  // ---------------------------------------------------------------------------
  // Nested message
  // ---------------------------------------------------------------------------

  private void emitNestedMessage(CodeWriter w, ProtoMessage nested) {
    String className = nameResolver.messageClassName(nested.getName());
    emitDocComment(w, nested.getComment());
    w.block(
        "class " + className + " private constructor(builder: Builder)",
        () -> emitMessageBody(w, nested, className));
  }

  // ---------------------------------------------------------------------------
  // Serializer (toPbtkUrl)
  // ---------------------------------------------------------------------------

  private void emitSerializer(CodeWriter w, ProtoMessage message) {
    // appendPbtkFields
    w.blankLine();
    w.block(
        "internal fun appendPbtkFields(sb: StringBuilder)",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldSerialize(w, field);
          }
        });

    // countPbtkFields
    w.blankLine();
    w.block(
        "internal fun countPbtkFields(): Int",
        () -> {
          w.line("var count = 0");
          for (ProtoField field : message.getFields()) {
            emitFieldCount(w, field);
          }
          w.line("return count");
        });

    // toPbtkUrl
    w.blankLine();
    w.block(
        "fun toPbtkUrl(): String",
        () -> {
          w.line("val sb = StringBuilder()");
          w.line("appendPbtkFields(sb)");
          w.line("return sb.toString()");
        });
  }

  private void emitFieldSerialize(CodeWriter w, ProtoField field) {
    String ktField = "this." + nameResolver.fieldName(field.getName());
    int fieldNum = field.getFieldNumber();

    if (field.isOneofMember()) {
      String caseName = nameResolver.fieldName(field.getOneofName()) + "Case_";
      String enumConst = field.getName().toUpperCase() + "Case_";
      w.block(
          "if (" + caseName + " == " + enumConst + ")",
          () -> emitSingleFieldSerialize(w, field, ktField, fieldNum));
      return;
    }

    if (field.isMap()) {
      emitMapSerialize(w, field, ktField, fieldNum);
    } else if (field.isRepeated()) {
      emitRepeatedSerialize(w, field, ktField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      emitMessageSerialize(w, field, ktField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, ktField, fieldNum);
    } else {
      emitScalarSerialize(w, field, ktField, fieldNum);
    }
  }

  private void emitSingleFieldSerialize(
      CodeWriter w, ProtoField field, String ktField, int fieldNum) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      emitMessageSerialize(w, field, ktField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, ktField, fieldNum);
    } else {
      emitScalarSerialize(w, field, ktField, fieldNum);
    }
  }

  private void emitScalarSerialize(CodeWriter w, ProtoField field, String ktField, int fieldNum) {
    if (field.hasExplicitPresence() && !field.isRequired()) {
      String bitCheck = "presentFields_.get(" + field.getArrayPosition() + ")";
      w.block("if (" + bitCheck + ")", () -> emitScalarAppend(w, field, ktField, fieldNum));
      return;
    }
    emitScalarAppend(w, field, ktField, fieldNum);
  }

  private void emitScalarAppend(CodeWriter w, ProtoField field, String ktField, int fieldNum) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    switch (type) {
      case TYPE_BOOL:
        w.line(
            "sb.append(\"!%d%s\").append(if (%s) \"1\" else \"0\")", fieldNum, typeChar, ktField);
        break;
      case TYPE_BYTES:
        w.line(
            "sb.append(\"!%d%s\").append(java.util.Base64.getEncoder().encodeToString(%s))",
            fieldNum, typeChar, ktField);
        break;
      case TYPE_STRING:
        w.line(
            "sb.append(\"!%d%s\").append(java.net.URLEncoder.encode(%s, Charsets.UTF_8))",
            fieldNum, typeChar, ktField);
        break;
      case TYPE_DOUBLE:
        w.block(
            "if (!(" + ktField + ").isNaN() && !(" + ktField + ").isInfinite())",
            () -> w.line("sb.append(\"!%d%s\").append(%s)", fieldNum, typeChar, ktField));
        break;
      case TYPE_FLOAT:
        w.block(
            "if (!(" + ktField + ").isNaN() && !(" + ktField + ").isInfinite())",
            () -> w.line("sb.append(\"!%d%s\").append(%s)", fieldNum, typeChar, ktField));
        break;
      case TYPE_UINT32, TYPE_FIXED32:
        w.line(
            "sb.append(\"!%d%s\").append(Integer.toUnsignedLong(%s))", fieldNum, typeChar, ktField);
        break;
      case TYPE_UINT64, TYPE_FIXED64:
        w.line(
            "sb.append(\"!%d%s\").append(java.lang.Long.toUnsignedString(%s))",
            fieldNum, typeChar, ktField);
        break;
      default:
        w.line("sb.append(\"!%d%s\").append(%s)", fieldNum, typeChar, ktField);
        break;
    }
  }

  private void emitEnumSerialize(CodeWriter w, ProtoField field, String ktField, int fieldNum) {
    if (field.hasExplicitPresence() && !field.isRequired()) {
      String bitCheck = "presentFields_.get(" + field.getArrayPosition() + ")";
      w.block(
          "if (" + bitCheck + ")",
          () -> w.line("sb.append(\"!%de\").append(%s?.getNumber() ?: 0)", fieldNum, ktField));
    } else {
      w.line("sb.append(\"!%de\").append(%s?.getNumber() ?: 0)", fieldNum, ktField);
    }
  }

  private void emitMessageSerialize(CodeWriter w, ProtoField field, String ktField, int fieldNum) {
    w.block(
        "if (" + ktField + " != null)",
        () -> {
          w.line("sb.append(\"!%dm\").append(%s!!.countPbtkFields())", fieldNum, ktField);
          w.line("%s!!.appendPbtkFields(sb)", ktField);
        });
  }

  private void emitRepeatedSerialize(CodeWriter w, ProtoField field, String ktField, int fieldNum) {
    String boxedType = elementType(field);
    w.block(
        "for (__item in " + ktField + ")",
        () -> {
          if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
            w.block(
                "if (__item != null)",
                () -> {
                  w.line("sb.append(\"!%dm\").append(__item.countPbtkFields())", fieldNum);
                  w.line("__item.appendPbtkFields(sb)");
                });
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            w.line("sb.append(\"!%de\").append(__item?.getNumber() ?: 0)", fieldNum);
          } else {
            emitScalarAppend(w, field, "__item", fieldNum);
          }
        });
  }

  private void emitMapSerialize(CodeWriter w, ProtoField field, String ktField, int fieldNum) {
    w.block(
        "for ((__key, __value) in " + ktField + ")",
        () -> {
          w.line("sb.append(\"!%dm2\")", fieldNum);

          // Key (field 1)
          String keyTypeChar = pbtkTypeChar(field.getMapKeyType());
          if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line(
                "sb.append(\"!1%s\").append(java.net.URLEncoder.encode(__key as String, Charsets.UTF_8))",
                keyTypeChar);
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line(
                "sb.append(\"!1%s\").append(if (__key as Boolean) \"1\" else \"0\")", keyTypeChar);
          } else {
            w.line("sb.append(\"!1%s\").append(__key)", keyTypeChar);
          }

          // Value (field 2)
          if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
            String msgType = simpleTypeName(field.getMapValueTypeReference());
            w.line(
                "if (__value != null) { sb.append(\"!2m\").append((__value as %s).countPbtkFields()); (__value as %s).appendPbtkFields(sb) }",
                msgType, msgType);
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
            String enumType = simpleTypeName(field.getMapValueTypeReference());
            w.line(
                "sb.append(\"!2e\").append(if (__value != null) (__value as %s).getNumber() else 0)",
                enumType);
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line(
                "sb.append(\"!2s\").append(java.net.URLEncoder.encode(__value as String, Charsets.UTF_8))");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
            w.line(
                "sb.append(\"!2z\").append(java.util.Base64.getEncoder().encodeToString(__value as ByteArray))");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("sb.append(\"!2b\").append(if (__value as Boolean) \"1\" else \"0\")");
          } else {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.line("sb.append(\"!2%s\").append(__value)", valTypeChar);
          }
        });
  }

  private void emitFieldCount(CodeWriter w, ProtoField field) {
    String ktField = "this." + nameResolver.fieldName(field.getName());

    if (field.isOneofMember()) {
      String caseName = nameResolver.fieldName(field.getOneofName()) + "Case_";
      String enumConst = field.getName().toUpperCase() + "Case_";
      w.line("if (%s == %s) count++", caseName, enumConst);
      return;
    }

    if (field.isMap()) {
      w.line("count += %s.size", ktField);
    } else if (field.isRepeated()) {
      if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
        w.line("count += %s.count { it != null }", ktField);
      } else {
        w.line("count += %s.size", ktField);
      }
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      w.line("if (%s != null) count++", ktField);
    } else if (field.hasExplicitPresence() && !field.isRequired()) {
      w.line("if (presentFields_.get(%d)) count++", field.getArrayPosition());
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_DOUBLE) {
      w.line("if (!(%s).isNaN() && !(%s).isInfinite()) count++", ktField, ktField);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_FLOAT) {
      w.line("if (!(%s).isNaN() && !(%s).isInfinite()) count++", ktField, ktField);
    } else {
      w.line("count++");
    }
  }

  // ---------------------------------------------------------------------------
  // Deserializer (fromPbtkUrl) -- emitted inside companion object
  // ---------------------------------------------------------------------------

  private void emitDeserializer(CodeWriter w, ProtoMessage message, String className) {
    // parsePbtkTokens
    w.blankLine();
    w.block(
        "internal fun parsePbtkTokens(tokens: List<String>, fieldCount: Int, offset: IntArray): "
            + className,
        () -> {
          w.line("val builder = %s.newBuilder()", className);
          w.line("var consumed = 0");
          w.block(
              "while (consumed < fieldCount && offset[0] < tokens.size)",
              () -> {
                w.line("val token = tokens[offset[0]]");
                w.line("var numEnd = 0");
                w.line("while (numEnd < token.length && token[numEnd].isDigit()) numEnd++");
                w.line(
                    "if (numEnd == 0 || numEnd >= token.length) { offset[0]++; consumed++; continue }");
                w.line("val fieldNum = token.substring(0, numEnd).toInt()");
                w.line("val typeChar = token[numEnd]");
                w.line("val value = token.substring(numEnd + 1)");

                w.block(
                    "when (fieldNum)",
                    () -> {
                      for (ProtoField field : message.getFields()) {
                        emitFieldCase(w, field, className);
                      }
                      w.line("else -> { offset[0]++; consumed++ }");
                    });
              });
          w.line("return builder.build()");
        });

    // fromPbtkUrl
    w.blankLine();
    w.line("@JvmStatic");
    w.block(
        "fun fromPbtkUrl(input: String): " + className,
        () -> {
          w.line("if (input.isEmpty()) return %s.getDefaultInstance()", className);
          w.line("val tokens = tokenizePbtk(input)");
          w.line("val offset = intArrayOf(0)");
          w.line("return parsePbtkTokens(tokens, tokens.size, offset)");
        });

    // tokenizePbtk
    w.blankLine();
    w.block(
        "private fun tokenizePbtk(input: String): List<String>",
        () -> {
          w.line("val tokens = mutableListOf<String>()");
          w.line("var i = if (input[0] == '!') 1 else 0");
          w.block(
              "while (i < input.length)",
              () -> {
                w.line("val next = input.indexOf('!', i)");
                w.block(
                    "if (next < 0)",
                    () -> {
                      w.line("tokens.add(input.substring(i))");
                      w.line("break");
                    });
                w.line("tokens.add(input.substring(i, next))");
                w.line("i = next + 1");
              });
          w.line("return tokens");
        });
  }

  private void emitFieldCase(CodeWriter w, ProtoField field, String className) {
    int fieldNum = field.getFieldNumber();
    String setterCall = "builder." + nameResolver.setterName(field.getName());

    w.block(
        fieldNum + " ->",
        () -> {
          if (field.isMap()) {
            emitMapDeserialize(w, field);
          } else if (field.isRepeated()) {
            emitRepeatedDeserialize(w, field);
          } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
            emitMessageDeserialize(w, field, setterCall);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            emitEnumDeserialize(w, field, setterCall);
          } else {
            emitScalarDeserialize(w, field, setterCall);
          }
          w.line("offset[0]++");
          w.line("consumed++");
        });
  }

  private void emitScalarDeserialize(CodeWriter w, ProtoField field, String setterCall) {
    String readExpr = scalarReadExpr(field.getProtoType(), "value");
    w.line("%s(%s)", setterCall, readExpr);
  }

  private void emitEnumDeserialize(CodeWriter w, ProtoField field, String setterCall) {
    String enumType = simpleTypeName(field.getTypeReference());
    w.line("%s(%s.forNumber(value.toInt()))", setterCall, enumType);
  }

  private void emitMessageDeserialize(CodeWriter w, ProtoField field, String setterCall) {
    String msgType = simpleTypeName(field.getTypeReference());
    w.line("val subCount = value.toInt()");
    w.line("offset[0]++");
    w.line("%s(%s.parsePbtkTokens(tokens, subCount, offset))", setterCall, msgType);
    w.line("offset[0]--"); // compensate for outer offset[0]++
  }

  private void emitRepeatedDeserialize(CodeWriter w, ProtoField field) {
    String addCall = "builder.add" + KotlinNameResolver.snakeToPascal(field.getName());
    if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      String msgType = simpleTypeName(field.getTypeReference());
      w.line("val subCount = value.toInt()");
      w.line("offset[0]++");
      w.line("%s(%s.parsePbtkTokens(tokens, subCount, offset))", addCall, msgType);
      w.line("offset[0]--");
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      String enumType = simpleTypeName(field.getTypeReference());
      w.line("%s(%s.forNumber(value.toInt()))", addCall, enumType);
    } else {
      String readExpr = scalarReadExpr(field.getProtoType(), "value");
      w.line("%s(%s)", addCall, readExpr);
    }
  }

  private void emitMapDeserialize(CodeWriter w, ProtoField field) {
    String putCall = "builder.put" + KotlinNameResolver.snakeToPascal(field.getName());
    w.line("val entryCount = value.toInt()");
    w.line("offset[0]++");
    w.line("var entryKey: Any? = null");
    w.line("var entryVal: Any? = null");
    w.block(
        "for (__mi in 0 until entryCount)",
        () -> {
          w.line("if (offset[0] >= tokens.size) break");
          w.line("val mapToken = tokens[offset[0]]");
          w.line("var mne = 0");
          w.line("while (mne < mapToken.length && mapToken[mne].isDigit()) mne++");
          w.line("if (mne == 0 || mne >= mapToken.length) { offset[0]++; continue }");
          w.line("val mfn = mapToken.substring(0, mne).toInt()");
          w.line("val mval = mapToken.substring(mne + 1)");
          w.block(
              "if (mfn == 1)",
              () -> {
                String keyRead = scalarReadExpr(field.getMapKeyType(), "mval");
                w.line("entryKey = %s", keyRead);
              });
          w.block(
              "if (mfn == 2)",
              () -> {
                emitMapValueRead(w, field);
              });
          w.line("offset[0]++");
        });
    w.line("offset[0]--"); // compensate for outer offset[0]++
    emitMapPut(w, field, putCall);
  }

  private void emitMapValueRead(CodeWriter w, ProtoField field) {
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
      String msgType = simpleTypeName(field.getMapValueTypeReference());
      w.line("val valSubCount = mval.toInt()");
      w.line("offset[0]++");
      w.line("entryVal = %s.parsePbtkTokens(tokens, valSubCount, offset)", msgType);
      w.line("offset[0]--");
    } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
      String enumType = simpleTypeName(field.getMapValueTypeReference());
      w.line("entryVal = %s.forNumber(mval.toInt())", enumType);
    } else {
      String valRead = scalarReadExpr(field.getMapValueType(), "mval");
      w.line("entryVal = %s", valRead);
    }
  }

  private void emitMapPut(CodeWriter w, ProtoField field, String putCall) {
    String keyCast = mapKeyCast(field.getMapKeyType());
    String valCast = mapValueCast(field);
    w.line("if (entryKey != null) %s(%s, %s)", putCall, keyCast, valCast);
  }

  private String mapKeyCast(FieldDescriptorProto.Type keyType) {
    return switch (keyType) {
      case TYPE_STRING -> "entryKey as String";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32, TYPE_UINT32, TYPE_FIXED32 -> "entryKey as Int";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64, TYPE_UINT64, TYPE_FIXED64 -> "entryKey as Long";
      case TYPE_BOOL -> "entryKey as Boolean";
      default -> "entryKey";
    };
  }

  private String mapValueCast(ProtoField field) {
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
      String msgType = simpleTypeName(field.getMapValueTypeReference());
      return "entryVal as " + msgType;
    }
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
      String enumType = simpleTypeName(field.getMapValueTypeReference());
      return "entryVal as " + enumType;
    }
    return switch (field.getMapValueType()) {
      case TYPE_STRING -> "entryVal as String";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32, TYPE_UINT32, TYPE_FIXED32 -> "entryVal as Int";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64, TYPE_UINT64, TYPE_FIXED64 -> "entryVal as Long";
      case TYPE_DOUBLE -> "entryVal as Double";
      case TYPE_FLOAT -> "entryVal as Float";
      case TYPE_BOOL -> "entryVal as Boolean";
      case TYPE_BYTES -> "entryVal as ByteArray";
      default -> "entryVal!!";
    };
  }

  private String scalarReadExpr(FieldDescriptorProto.Type type, String valueVar) {
    return switch (type) {
      case TYPE_DOUBLE -> valueVar + ".toDouble()";
      case TYPE_FLOAT -> valueVar + ".toFloat()";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64 -> valueVar + ".toLong()";
      case TYPE_UINT64, TYPE_FIXED64 -> "java.lang.Long.parseUnsignedLong(" + valueVar + ")";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32 -> valueVar + ".toInt()";
      case TYPE_UINT32, TYPE_FIXED32 -> "Integer.parseUnsignedInt(" + valueVar + ")";
      case TYPE_BOOL -> valueVar + " == \"1\"";
      case TYPE_STRING -> "java.net.URLDecoder.decode(" + valueVar + ", Charsets.UTF_8)";
      case TYPE_BYTES -> "java.util.Base64.getDecoder().decode(" + valueVar + ")";
      default -> valueVar;
    };
  }

  // ---------------------------------------------------------------------------
  // toString, equals, hashCode
  // ---------------------------------------------------------------------------

  private void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "override fun toString(): String",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return \"%s{}\"", className);
            return;
          }
          w.line("return \"%s{\" +", className);
          w.indent();
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String ktName = nameResolver.fieldName(field.getName());
            String prefix = i == 0 ? "\"" : "\", ";
            boolean isLast = i == message.getFields().size() - 1;
            if (isLast) {
              w.line("%s%s=\" + %s + \"}\"", prefix, field.getName(), ktName);
            } else {
              w.line("%s%s=\" + %s +", prefix, field.getName(), ktName);
            }
          }
          w.dedent();
        });
  }

  private void emitEquals(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "override fun equals(other: Any?): Boolean",
        () -> {
          w.line("if (this === other) return true");
          w.line("if (other !is %s) return false", className);
          if (message.getFields().isEmpty()) {
            w.line("return true");
            return;
          }
          StringBuilder sb = new StringBuilder("return ");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String ktName = nameResolver.fieldName(field.getName());
            if (i > 0) sb.append(" && ");
            if (isByteArrayField(field)) {
              sb.append(String.format("this.%s.contentEquals(other.%s)", ktName, ktName));
            } else if (isFloatField(field)) {
              sb.append(String.format("this.%s.compareTo(other.%s) == 0", ktName, ktName));
            } else if (isDoubleField(field)) {
              sb.append(String.format("this.%s.compareTo(other.%s) == 0", ktName, ktName));
            } else {
              sb.append(String.format("this.%s == other.%s", ktName, ktName));
            }
          }
          w.line(sb.toString());
        });
  }

  private void emitHashCode(CodeWriter w, ProtoMessage message) {
    w.blankLine();
    w.block(
        "override fun hashCode(): Int",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return 0");
            return;
          }
          w.line("var result = 0");
          for (ProtoField field : message.getFields()) {
            String ktName = nameResolver.fieldName(field.getName());
            if (isByteArrayField(field)) {
              w.line("result = 31 * result + %s.contentHashCode()", ktName);
            } else if (isDoubleField(field)) {
              w.line("result = 31 * result + %s.toBits().hashCode()", ktName);
            } else if (isFloatField(field)) {
              w.line("result = 31 * result + %s.toBits().hashCode()", ktName);
            } else {
              w.line("result = 31 * result + %s.hashCode()", ktName);
            }
          }
          w.line("return result");
        });
  }

  // ---------------------------------------------------------------------------
  // Builder
  // ---------------------------------------------------------------------------

  private void emitBuilder(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "class Builder",
        () -> {
          for (ProtoField field : message.getFields()) {
            String ktType = typeMapper.languageType(field);
            String ktName = nameResolver.fieldName(field.getName());
            String defaultVal = typeMapper.defaultValue(field);
            w.line("internal var %s: %s = %s", ktName, ktType, defaultVal);
          }

          if (hasPresenceTrackedFields(message)) {
            w.blankLine();
            w.line("internal val presentFields_ = java.util.BitSet()");
          }

          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            w.blankLine();
            String caseName = nameResolver.fieldName(group.name()) + "Case_";
            w.line("internal var %s: Int = 0", caseName);
          }

          // Setters
          for (ProtoField field : message.getFields()) {
            String ktType = typeMapper.languageType(field);
            String ktName = nameResolver.fieldName(field.getName());
            String pascalName = KotlinNameResolver.snakeToPascal(field.getName());

            // set
            w.blankLine();
            w.block(
                "fun set" + pascalName + "(value: " + ktType + "): Builder",
                () -> {
                  w.line("this.%s = value", ktName);
                  if (field.hasExplicitPresence()) {
                    w.line("this.presentFields_.set(%d)", field.getArrayPosition());
                  }
                  if (field.isOneofMember()) {
                    w.line(
                        "this.%sCase_ = %sCase_",
                        nameResolver.fieldName(field.getOneofName()),
                        field.getName().toUpperCase());
                  }
                  w.line("return this");
                });

            // clear
            w.blankLine();
            String defaultVal = typeMapper.defaultValue(field);
            w.block(
                "fun clear" + pascalName + "(): Builder",
                () -> {
                  w.line("this.%s = %s", ktName, defaultVal);
                  if (field.hasExplicitPresence()) {
                    w.line("this.presentFields_.clear(%d)", field.getArrayPosition());
                  }
                  if (field.isOneofMember()) {
                    String caseName = nameResolver.fieldName(field.getOneofName()) + "Case_";
                    w.block(
                        "if (this." + caseName + " == " + field.getName().toUpperCase() + "Case_)",
                        () -> w.line("this.%s = 0", caseName));
                  }
                  w.line("return this");
                });

            // repeated: add / addAll
            if (field.isRepeated()) {
              String elemType = elementType(field);
              w.blankLine();
              w.block(
                  "fun add" + pascalName + "(value: " + elemType + "): Builder",
                  () -> {
                    w.line("this.%s.add(value)", ktName);
                    w.line("return this");
                  });
              w.blankLine();
              w.block(
                  "fun addAll" + pascalName + "(values: Iterable<" + elemType + ">): Builder",
                  () -> {
                    w.block("for (v in values)", () -> w.line("this.%s.add(v)", ktName));
                    w.line("return this");
                  });
            }

            // map: put / putAll / remove
            if (field.isMap()) {
              String keyType = typeMapper.scalarType(field.getMapKeyType());
              String valueType = mapValueType(field);
              w.blankLine();
              w.block(
                  "fun put"
                      + pascalName
                      + "(key: "
                      + keyType
                      + ", value: "
                      + valueType
                      + "): Builder",
                  () -> {
                    w.line("this.%s[key] = value", ktName);
                    w.line("return this");
                  });
              w.blankLine();
              w.block(
                  "fun putAll"
                      + pascalName
                      + "(values: Map<"
                      + keyType
                      + ", "
                      + valueType
                      + ">): Builder",
                  () -> {
                    w.line("this.%s.putAll(values)", ktName);
                    w.line("return this");
                  });
              w.blankLine();
              w.block(
                  "fun remove" + pascalName + "(key: " + keyType + "): Builder",
                  () -> {
                    w.line("this.%s.remove(key)", ktName);
                    w.line("return this");
                  });
            }
          }

          // clear()
          w.blankLine();
          w.block(
              "fun clear(): Builder",
              () -> {
                for (ProtoField field : message.getFields()) {
                  String ktName = nameResolver.fieldName(field.getName());
                  String defaultVal = typeMapper.defaultValue(field);
                  w.line("this.%s = %s", ktName, defaultVal);
                }
                if (hasPresenceTrackedFields(message)) {
                  w.line("this.presentFields_.clear()");
                }
                for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
                  String caseName = nameResolver.fieldName(group.name()) + "Case_";
                  w.line("this.%s = 0", caseName);
                }
                w.line("return this");
              });

          // build()
          w.blankLine();
          w.block("fun build(): " + className, () -> w.line("return %s(this)", className));
        });
  }

  // ---------------------------------------------------------------------------
  // Companion object
  // ---------------------------------------------------------------------------

  private void emitCompanionObject(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "companion object",
        () -> {
          // Field number constants
          for (ProtoField field : message.getFields()) {
            String constName = snakeToUpperSnake(field.getName()) + "_FIELD_NUMBER";
            w.line("const val %s: Int = %d", constName, field.getFieldNumber());
          }

          // Oneof case constants
          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            for (ProtoField member : group.members()) {
              w.line(
                  "private const val %sCase_: Int = %d",
                  member.getName().toUpperCase(), member.getFieldNumber());
            }
          }

          // DEFAULT_INSTANCE
          w.blankLine();
          w.line("private val DEFAULT_INSTANCE: %s = Builder().build()", className);

          // getDefaultInstance()
          w.blankLine();
          w.line("@JvmStatic");
          w.block(
              "fun getDefaultInstance(): " + className, () -> w.line("return DEFAULT_INSTANCE"));

          // newBuilder()
          w.blankLine();
          w.line("@JvmStatic");
          w.block("fun newBuilder(): Builder", () -> w.line("return Builder()"));

          // newBuilder(prototype)
          w.blankLine();
          w.line("@JvmStatic");
          w.block(
              "fun newBuilder(prototype: " + className + "): Builder",
              () -> {
                w.line("val builder = Builder()");
                for (ProtoField field : message.getFields()) {
                  String ktName = nameResolver.fieldName(field.getName());
                  if (field.isRepeated()) {
                    w.line("builder.%s.addAll(prototype.%s)", ktName, ktName);
                  } else if (field.isMap()) {
                    w.line("builder.%s.putAll(prototype.%s)", ktName, ktName);
                  } else {
                    w.line("builder.%s = prototype.%s", ktName, ktName);
                  }
                }
                if (hasPresenceTrackedFields(message)) {
                  w.line("builder.presentFields_.or(prototype.presentFields_)");
                }
                for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
                  String caseName = nameResolver.fieldName(group.name()) + "Case_";
                  w.line("builder.%s = prototype.%s", caseName, caseName);
                }
                w.line("return builder");
              });

          // Deserializer
          emitDeserializer(w, message, className);
        });
  }

  // ---------------------------------------------------------------------------
  // Enum
  // ---------------------------------------------------------------------------

  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    w.blankLine();
    w.block(
        "enum class " + protoEnum.getName() + "(val number: Int)",
        () -> {
          for (int i = 0; i < protoEnum.getValues().size(); i++) {
            ProtoEnum.EnumValue val = protoEnum.getValues().get(i);
            String suffix = i < protoEnum.getValues().size() - 1 ? "," : ";";
            w.line("%s(%d)%s", val.name(), val.number(), suffix);
          }

          w.blankLine();
          w.block("fun getNumber(): Int", () -> w.line("return number"));
          w.blankLine();
          w.block(
              "companion object",
              () -> {
                w.line("@JvmStatic");
                w.block(
                    "fun forNumber(number: Int): " + protoEnum.getName() + "?",
                    () -> {
                      w.block(
                          "for (v in entries)",
                          () -> w.block("if (v.number == number)", () -> w.line("return v")));
                      w.line("return null");
                    });
              });
        });
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  private void emitDocComment(CodeWriter w, String comment) {
    if (comment == null || comment.isEmpty()) return;
    String safeComment = comment.replace("*/", "* /");
    String[] lines = safeComment.split("\n");
    if (lines.length == 1) {
      w.line("/** %s */", lines[0].strip());
    } else {
      w.line("/**");
      for (String line : lines) {
        String trimmed = line.strip();
        if (trimmed.isEmpty()) {
          w.line(" *");
        } else {
          w.line(" * %s", trimmed);
        }
      }
      w.line(" */");
    }
  }

  private String elementType(ProtoField field) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      return simpleTypeName(field.getTypeReference());
    }
    if (field.getKind() == ProtoField.FieldKind.ENUM) {
      return simpleTypeName(field.getTypeReference());
    }
    return typeMapper.scalarType(field.getProtoType());
  }

  private String mapValueType(ProtoField field) {
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE
        || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
      return simpleTypeName(field.getMapValueTypeReference());
    }
    return typeMapper.scalarType(field.getMapValueType());
  }

  private String simpleTypeName(String protoFullName) {
    if (protoFullName == null) return "Any";
    int lastDot = protoFullName.lastIndexOf('.');
    return lastDot >= 0 ? protoFullName.substring(lastDot + 1) : protoFullName;
  }

  private static String snakeToUpperSnake(String name) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < name.length(); i++) {
      char c = name.charAt(i);
      if (Character.isUpperCase(c) && i > 0 && name.charAt(i - 1) != '_') {
        sb.append('_');
      }
      sb.append(Character.toUpperCase(c));
    }
    return sb.toString();
  }

  static String pbtkTypeChar(FieldDescriptorProto.Type type) {
    return switch (type) {
      case TYPE_BOOL -> "b";
      case TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64 ->
          "i";
      case TYPE_FLOAT -> "f";
      case TYPE_DOUBLE -> "d";
      case TYPE_STRING -> "s";
      case TYPE_ENUM -> "e";
      case TYPE_MESSAGE -> "m";
      case TYPE_BYTES -> "z";
      default -> "s";
    };
  }

  private boolean isByteArrayField(ProtoField field) {
    return field.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES && field.isSingular();
  }

  private boolean isFloatField(ProtoField field) {
    return field.isSingular()
        && field.getKind() == ProtoField.FieldKind.SCALAR
        && field.getProtoType() == FieldDescriptorProto.Type.TYPE_FLOAT;
  }

  private boolean isDoubleField(ProtoField field) {
    return field.isSingular()
        && field.getKind() == ProtoField.FieldKind.SCALAR
        && field.getProtoType() == FieldDescriptorProto.Type.TYPE_DOUBLE;
  }

  private boolean hasPresenceTrackedFields(ProtoMessage message) {
    return message.getFields().stream().anyMatch(ProtoField::hasExplicitPresence);
  }
}
