// Generated by protoc-gen-pbtkurl. DO NOT EDIT.
// Source: address.proto

class Address {
  constructor() {
    /** @type {string} */
    this.street = "";
    /** @type {string} */
    this.city = "";
    /** @type {string} */
    this.state = "";
    /** @type {number} */
    this.zip = 0;
  }

  /** @returns {string} */
  getStreet() {
    return this.street;
  }

  /** @param {string} value */
  setStreet(value) {
    this.street = value;
  }

  /** @returns {string} */
  getCity() {
    return this.city;
  }

  /** @param {string} value */
  setCity(value) {
    this.city = value;
  }

  /** @returns {string} */
  getState() {
    return this.state;
  }

  /** @param {string} value */
  setState(value) {
    this.state = value;
  }

  /** @returns {number} */
  getZip() {
    return this.zip;
  }

  /** @param {number} value */
  setZip(value) {
    this.zip = value;
  }

  /** @private @returns {number} */
  _countPbtkFields() {
    let count = 0;
    count++;
    count++;
    count++;
    count++;
    return count;
  }

  /** @private @param {string[]} parts */
  _appendPbtkFields(parts) {
    parts.push('!1s' + encodeURIComponent(this.street));
    parts.push('!2s' + encodeURIComponent(this.city));
    parts.push('!3s' + encodeURIComponent(this.state));
    parts.push('!4i' + this.zip);
  }

  /**
   * Encode this message to a Uint8Array.
   * @returns {Uint8Array}
   */
  encode() {
    const parts = [];
    this._appendPbtkFields(parts);
    return new TextEncoder().encode(parts.join(''));
  }

  /**
   * @private
   * @param {string[]} tokens
   * @param {number} fieldCount
   * @param {{v:number}} offset
   * @returns {Address}
   */
  static _parsePbtkTokens(tokens, fieldCount, offset) {
    const obj = new Address();
    let consumed = 0;
    while (consumed < fieldCount && offset.v < tokens.length) {
      const token = tokens[offset.v];
      let numEnd = 0;
      while (numEnd < token.length && token.charCodeAt(numEnd) >= 48 && token.charCodeAt(numEnd) <= 57) numEnd++;
      if (numEnd === 0 || numEnd >= token.length) { offset.v++; consumed++; continue; }
      const fieldNum = parseInt(token.substring(0, numEnd), 10);
      const value = token.substring(numEnd + 1);

      switch (fieldNum) {
        case 1: {
          obj.setStreet(decodeURIComponent(value));
          offset.v++;
          consumed++;
          break;
        }
        case 2: {
          obj.setCity(decodeURIComponent(value));
          offset.v++;
          consumed++;
          break;
        }
        case 3: {
          obj.setState(decodeURIComponent(value));
          offset.v++;
          consumed++;
          break;
        }
        case 4: {
          obj.setZip(parseInt(value, 10));
          offset.v++;
          consumed++;
          break;
        }
        default: offset.v++; consumed++; break;
      }
    }
    return obj;
  }

  /**
   * Decode from a Uint8Array or string.
   * @param {Uint8Array|string} data
   * @returns {Address}
   */
  static decode(data) {
    const input = typeof data === 'string' ? data : new TextDecoder().decode(data);
    if (input == null || input.length === 0) return new Address();
    const tokens = Address._tokenizePbtk(input);
    const offset = {v: 0};
    return Address._parsePbtkTokens(tokens, tokens.length, offset);
  }

  /** @private @param {string} input @returns {string[]} */
  static _tokenizePbtk(input) {
    const tokens = [];
    let i = input.charAt(0) === '!' ? 1 : 0;
    while (i < input.length) {
      const next = input.indexOf('!', i);
      if (next < 0) {
        tokens.push(input.substring(i));
        break;
      }
      tokens.push(input.substring(i, next));
      i = next + 1;
    }
    return tokens;
  }

  /** @returns {string} */
  toString() {
    return `Address{street=${this.street}, city=${this.city}, state=${this.state}, zip=${this.zip}}`;
  }
}

export { Address };
