// Generated by protoc-gen-pbtkurl. DO NOT EDIT.
// Source: address.proto

import 'dart:convert';

class Address {
  String street = '';
  String city = '';
  String state = '';
  int zip = 0;

  /// Creates a new [Address] instance.
  Address();

  /// Returns the value of [street].
  String getStreet() {
    return street;
  }

  /// Sets the value of [street].
  void setStreet(String value) {
    street = value;
  }

  /// Returns the value of [city].
  String getCity() {
    return city;
  }

  /// Sets the value of [city].
  void setCity(String value) {
    city = value;
  }

  /// Returns the value of [state].
  String getState() {
    return state;
  }

  /// Sets the value of [state].
  void setState(String value) {
    state = value;
  }

  /// Returns the value of [zip].
  int getZip() {
    return zip;
  }

  /// Sets the value of [zip].
  void setZip(int value) {
    zip = value;
  }

  /// @private Counts how many top-level tokens this message produces.
  int _countPbtkFields() {
    int count = 0;
    count++;
    count++;
    count++;
    count++;
    return count;
  }

  /// @private Appends pbtk tokens to the given list.
  void _appendPbtkFields(List<String> parts) {
    parts.add('!1s${Uri.encodeComponent(street)}');
    parts.add('!2s${Uri.encodeComponent(city)}');
    parts.add('!3s${Uri.encodeComponent(state)}');
    parts.add('!4i$zip');
  }

  /// Serialize this message to a Uint8List.
  Uint8List writeToBuffer() {
    final parts = <String>[];
    _appendPbtkFields(parts);
    return Uint8List.fromList(utf8.encode(parts.join('')));
  }

  /// @private Parses pbtk tokens into this message type.
  static Address _parsePbtkTokens(List<String> tokens, int fieldCount, List<int> offset) {
    final obj = Address();
    int consumed = 0;
    while (consumed < fieldCount && offset[0] < tokens.length) {
      final token = tokens[offset[0]];
      int numEnd = 0;
      while (numEnd < token.length && token.codeUnitAt(numEnd) >= 48 && token.codeUnitAt(numEnd) <= 57) { numEnd++; }
      if (numEnd == 0 || numEnd >= token.length) { offset[0]++; consumed++; continue; }
      final fieldNum = int.parse(token.substring(0, numEnd));
      final value = token.substring(numEnd + 1);

      switch (fieldNum) {
        case 1: {
          obj.setStreet(Uri.decodeComponent(value));
          offset[0]++;
          consumed++;
          break;
        }
        case 2: {
          obj.setCity(Uri.decodeComponent(value));
          offset[0]++;
          consumed++;
          break;
        }
        case 3: {
          obj.setState(Uri.decodeComponent(value));
          offset[0]++;
          consumed++;
          break;
        }
        case 4: {
          obj.setZip(int.parse(value));
          offset[0]++;
          consumed++;
          break;
        }
        default: offset[0]++; consumed++; break;
      }
    }
    return obj;
  }

  /// Deserialize from a Uint8List.
  static Address fromBuffer(Uint8List buffer) {
    final input = utf8.decode(buffer);
    if (input.isEmpty) return Address();
    final tokens = Address._tokenizePbtk(input);
    final offset = [0];
    return Address._parsePbtkTokens(tokens, tokens.length, offset);
  }

  /// @private Tokenizes a pbtk URL string into individual tokens.
  static List<String> _tokenizePbtk(String input) {
    final tokens = <String>[];
    int i = input.isNotEmpty && input[0] == '!' ? 1 : 0;
    while (i < input.length) {
      final next = input.indexOf('!', i);
      if (next < 0) {
        tokens.add(input.substring(i));
        break;
      }
      tokens.add(input.substring(i, next));
      i = next + 1;
    }
    return tokens;
  }

  @override
  String toString() {
    return 'Address{street=$street, city=$city, state=$state, zip=$zip}';
  }
}
