// @generated by protoc-gen-pbtkurl -- do not edit.

#include "example/address.h"

static char* pbtk_url_encode(const char* input) {
  if (!input) return NULL;
  size_t len = strlen(input);
  char* out = (char*)malloc(len * 3 + 1);
  if (!out) return NULL;
  size_t j = 0;
  for (size_t i = 0; i < len; i++) {
    unsigned char c = (unsigned char)input[i];
    if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' || c == '~') {
      out[j++] = c;
    }
    else {
      snprintf(out + j, 4, "%%25%%02X", c);
      j += 3;
    }
  }
  out[j] = '\0';
  return out;
}

static int pbtk_hex_val(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  return -1;
}

static char* pbtk_url_decode(const char* input) {
  if (!input) return NULL;
  size_t len = strlen(input);
  char* out = (char*)malloc(len + 1);
  if (!out) return NULL;
  size_t j = 0;
  for (size_t i = 0; i < len; i++) {
    if (input[i] == '%%' && i + 2 < len) {
      int hi = pbtk_hex_val(input[i + 1]);
      int lo = pbtk_hex_val(input[i + 2]);
      if (hi >= 0 && lo >= 0) {
        out[j++] = (char)((hi << 4) | lo);
        i += 2;
        continue;
      }
    }
    out[j++] = input[i];
  }
  out[j] = '\0';
  return out;
}

static const char pbtk_b64_table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

static char* pbtk_base64_encode(const uint8_t* data, size_t len) {
  if (!data || len == 0) { char* e = (char*)malloc(1); if (e) e[0] = '\0'; return e; }
  size_t out_len = 4 * ((len + 2) / 3);
  char* out = (char*)malloc(out_len + 1);
  if (!out) return NULL;
  size_t j = 0;
  for (size_t i = 0; i < len; i += 3) {
    uint32_t a = data[i];
    uint32_t b = (i + 1 < len) ? data[i + 1] : 0;
    uint32_t c = (i + 2 < len) ? data[i + 2] : 0;
    uint32_t triple = (a << 16) | (b << 8) | c;
    out[j++] = pbtk_b64_table[(triple >> 18) & 0x3F];
    out[j++] = pbtk_b64_table[(triple >> 12) & 0x3F];
    out[j++] = (i + 1 < len) ? pbtk_b64_table[(triple >> 6) & 0x3F] : '=';
    out[j++] = (i + 2 < len) ? pbtk_b64_table[triple & 0x3F] : '=';
  }
  out[j] = '\0';
  return out;
}

static int pbtk_b64_val(char c) {
  if (c >= 'A' && c <= 'Z') return c - 'A';
  if (c >= 'a' && c <= 'z') return c - 'a' + 26;
  if (c >= '0' && c <= '9') return c - '0' + 52;
  if (c == '+') return 62;
  if (c == '/') return 63;
  return -1;
}

static uint8_t* pbtk_base64_decode(const char* input, size_t* out_len) {
  if (!input || !out_len) return NULL;
  size_t len = strlen(input);
  if (len == 0) { *out_len = 0; return (uint8_t*)malloc(1); }
  size_t padding = 0;
  if (len > 0 && input[len - 1] == '=') padding++;
  if (len > 1 && input[len - 2] == '=') padding++;
  *out_len = (len / 4) * 3 - padding;
  uint8_t* out = (uint8_t*)malloc(*out_len);
  if (!out) return NULL;
  size_t j = 0;
  for (size_t i = 0; i < len; i += 4) {
    int a = pbtk_b64_val(input[i]);
    int b = (i + 1 < len) ? pbtk_b64_val(input[i + 1]) : 0;
    int c = (i + 2 < len) ? pbtk_b64_val(input[i + 2]) : 0;
    int d = (i + 3 < len) ? pbtk_b64_val(input[i + 3]) : 0;
    if (a < 0) a = 0; if (b < 0) b = 0; if (c < 0) c = 0; if (d < 0) d = 0;
    uint32_t triple = ((uint32_t)a << 18) | ((uint32_t)b << 12) | ((uint32_t)c << 6) | (uint32_t)d;
    if (j < *out_len) out[j++] = (triple >> 16) & 0xFF;
    if (j < *out_len) out[j++] = (triple >> 8) & 0xFF;
    if (j < *out_len) out[j++] = triple & 0xFF;
  }
  return out;
}

#define PBTK_BUF_INITIAL_CAP 256

typedef struct { char* data; size_t len; size_t cap; } pbtk_buf_t;

static void pbtk_buf_init(pbtk_buf_t* buf) {
  buf->cap = PBTK_BUF_INITIAL_CAP;
  buf->data = (char*)malloc(buf->cap);
  buf->len = 0;
  if (buf->data) buf->data[0] = '\0';
}

static void pbtk_buf_append(pbtk_buf_t* buf, const char* str) {
  if (!buf->data || !str) return;
  size_t slen = strlen(str);
  if (buf->len + slen + 1 > buf->cap) {
    buf->cap = (buf->len + slen + 1) * 2;
    char* newdata = (char*)realloc(buf->data, buf->cap);
    if (!newdata) return;
    buf->data = newdata;
  }
  memcpy(buf->data + buf->len, str, slen);
  buf->len += slen;
  buf->data[buf->len] = '\0';
}

static void pbtk_buf_append_int(pbtk_buf_t* buf, int64_t val) {
  char tmp[32];
  snprintf(tmp, sizeof(tmp), "%%" PRId64, val);
  pbtk_buf_append(buf, tmp);
}

static void pbtk_buf_append_uint(pbtk_buf_t* buf, uint64_t val) {
  char tmp[32];
  snprintf(tmp, sizeof(tmp), "%%" PRIu64, val);
  pbtk_buf_append(buf, tmp);
}

static void pbtk_buf_append_double(pbtk_buf_t* buf, double val) {
  char tmp[64];
  snprintf(tmp, sizeof(tmp), "%%.17g", val);
  pbtk_buf_append(buf, tmp);
}

static void pbtk_buf_append_float(pbtk_buf_t* buf, float val) {
  char tmp[64];
  snprintf(tmp, sizeof(tmp), "%%.9g", (double)val);
  pbtk_buf_append(buf, tmp);
}

static int example_address_count_pbtk_fields(const example_Address* msg) {
  int count = 0;
  count++;
  count++;
  count++;
  count++;
  return count;
}

static void example_address_append_pbtk_fields(pbtk_buf_t* buf, const example_Address* msg) {
  if (msg->street) {
    char* enc = pbtk_url_encode(msg->street);
    pbtk_buf_append(buf, "!1s");
    if (enc) { pbtk_buf_append(buf, enc); free(enc); }
  }
  if (msg->city) {
    char* enc = pbtk_url_encode(msg->city);
    pbtk_buf_append(buf, "!2s");
    if (enc) { pbtk_buf_append(buf, enc); free(enc); }
  }
  if (msg->state) {
    char* enc = pbtk_url_encode(msg->state);
    pbtk_buf_append(buf, "!3s");
    if (enc) { pbtk_buf_append(buf, enc); free(enc); }
  }
  pbtk_buf_append(buf, "!4i");
  pbtk_buf_append_int(buf, (int64_t)msg->zip);
}

static example_Address* example_address_parse_pbtk_tokens(const char** tokens, int field_count, int* offset) {
  example_Address* obj = (example_Address*)calloc(1, sizeof(example_Address));
  if (!obj) return NULL;
  int consumed = 0;
  while (consumed < field_count && tokens[*offset]) {
    const char* token = tokens[*offset];
    int num_end = 0;
    while (token[num_end] >= '0' && token[num_end] <= '9') num_end++;
    if (num_end == 0 || token[num_end] == '\0') { (*offset)++; consumed++; continue; }
    char field_num_str[16];
    if (num_end > 15) num_end = 15;
    memcpy(field_num_str, token, num_end);
    field_num_str[num_end] = '\0';
    int field_num = (int)strtol(field_num_str, NULL, 10);
    const char* value = token + num_end + 1;

    switch (field_num) {
      case 1: {
        obj->street = pbtk_url_decode(value);
        (*offset)++;
        consumed++;
        break;
      }
      case 2: {
        obj->city = pbtk_url_decode(value);
        (*offset)++;
        consumed++;
        break;
      }
      case 3: {
        obj->state = pbtk_url_decode(value);
        (*offset)++;
        consumed++;
        break;
      }
      case 4: {
        obj->zip = (int32_t)strtol(value, NULL, 10);
        (*offset)++;
        consumed++;
        break;
      }
      default: (*offset)++; consumed++; break;
    }
  }
  return obj;
}

char* example_address_pack(const example_Address* msg) {
  if (!msg) return NULL;
  pbtk_buf_t buf;
  pbtk_buf_init(&buf);
  example_address_append_pbtk_fields(&buf, msg);
  return buf.data;
}

example_Address* example_address_unpack(const char* input) {
  if (!input || input[0] == '\0') return NULL;

  /* Tokenize: split on '!' */
  size_t input_len = strlen(input);
  size_t max_tokens = input_len / 2 + 2;
  const char** tokens = (const char**)malloc(sizeof(const char*) * (max_tokens + 1));
  if (!tokens) return NULL;
  size_t token_count = 0;
  const char* p = input;
  if (*p == '!') p++;
  while (*p) {
    tokens[token_count++] = p;
    const char* next = strchr(p, '!');
    if (!next) {
      break;
    }
    p = next + 1;
  }
  tokens[token_count] = NULL;

  /* Create a mutable copy for null-termination of tokens */
  char* mutable_input = strdup(input);
  if (!mutable_input) { free(tokens); return NULL; }
  /* Re-tokenize using mutable copy */
  token_count = 0;
  p = mutable_input;
  if (*p == '!') p++;
  while (*p) {
    tokens[token_count++] = p;
    char* next = strchr(p, '!');
    if (!next) {
      break;
    }
    *next = '\0';
    p = next + 1;
  }
  tokens[token_count] = NULL;

  int offset = 0;
  example_Address* result = example_address_parse_pbtk_tokens(tokens, (int)token_count, &offset);
  free(mutable_input);
  free(tokens);
  return result;
}

void example_address_free(example_Address* msg) {
  if (!msg) return;
  free(msg->street);
  free(msg->city);
  free(msg->state);
  free(msg);
}

