/*
 * Copyright 2024 protobuf-text-codecs contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.jsonarray.codegen.csharp;

import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.ProtoTypeUtil;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;

/**
 * Generates complete C# source files for proto messages and enums. Produces immutable sealed
 * classes with nested Builder, JSON array serialization via System.Text.Json.
 */
public class CSharpCodeEmitter {

  private static final String GENERATED_MARKER =
      "// @generated by protoc-gen-jsonarray \u2014 do not edit.";

  private final CSharpTypeMapper typeMapper;
  private final CSharpNameResolver nameResolver;
  private final CSharpSerializerGenerator serializerGen;
  private final CSharpDeserializerGenerator deserializerGen;

  public CSharpCodeEmitter(CSharpTypeMapper typeMapper, CSharpNameResolver nameResolver) {
    this.typeMapper = typeMapper;
    this.nameResolver = nameResolver;
    this.serializerGen = new CSharpSerializerGenerator(typeMapper, nameResolver);
    this.deserializerGen = new CSharpDeserializerGenerator(typeMapper, nameResolver);
  }

  /** Generate a complete C# source file for a message. */
  public String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String ns = nameResolver.resolvePackage(file);
    String className = nameResolver.messageClassName(message.getName());

    // Generated file marker
    w.line(GENERATED_MARKER);
    w.blankLine();

    // Using declarations
    emitUsings(w);

    // Namespace declaration
    if (!ns.isEmpty()) {
      w.blankLine();
      w.block(
          "namespace " + ns,
          () -> {
            emitDocComment(w, message.getComment());
            w.block(
                "public sealed class " + className,
                () -> {
                  emitMessageBody(w, message, className, false);
                });
          });
    } else {
      w.blankLine();
      emitDocComment(w, message.getComment());
      w.block(
          "public sealed class " + className,
          () -> {
            emitMessageBody(w, message, className, false);
          });
    }

    return w.toString();
  }

  /** Generate a complete C# source file for a top-level enum. */
  public String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String ns = nameResolver.resolvePackage(file);

    w.line(GENERATED_MARKER);
    w.blankLine();

    if (!ns.isEmpty()) {
      w.block(
          "namespace " + ns,
          () -> {
            emitEnum(w, protoEnum);
          });
    } else {
      emitEnum(w, protoEnum);
    }
    return w.toString();
  }

  // ---------------------------------------------------------------------------
  // Using declarations
  // ---------------------------------------------------------------------------

  private void emitUsings(CodeWriter w) {
    w.line("using System;");
    w.line("using System.Collections.Generic;");
    w.line("using System.Linq;");
    w.line("using System.Text;");
    w.line("using System.Text.Json;");
  }

  // ---------------------------------------------------------------------------
  // Message body (shared between top-level and nested messages)
  // ---------------------------------------------------------------------------

  private void emitMessageBody(
      CodeWriter w, ProtoMessage message, String className, boolean isNested) {
    // Field number constants
    emitFieldNumberConstants(w, message);

    // Private readonly fields
    emitFields(w, message);

    // Presence tracking bitset for fields with explicit presence (proto2 all fields,
    // proto3 optional)
    if (hasPresenceTrackedFields(message)) {
      w.blankLine();
      w.line("private readonly bool[] presentFields_;");
    }

    // Oneof case tracking fields
    emitOneofCaseFields(w, message);

    // Private constructor from Builder
    emitPrivateConstructor(w, message, className);

    // Properties on the message class (readonly -- no setters)
    emitMessageProperties(w, message);

    // Default instance
    w.blankLine();
    w.line(
        "private static readonly %s DefaultInstance_ = new %s(new Builder());",
        className, className);
    w.blankLine();
    w.block(
        "public static " + className + " GetDefaultInstance()",
        () -> {
          w.line("return DefaultInstance_;");
        });

    // Builder factory methods
    w.blankLine();
    w.block(
        "public static Builder NewBuilder()",
        () -> {
          w.line("return new Builder();");
        });
    w.blankLine();
    w.block(
        "public static Builder NewBuilder(" + className + " prototype)",
        () -> {
          w.line("return new Builder(prototype);");
        });
    w.blankLine();
    w.block(
        "public Builder ToBuilder()",
        () -> {
          w.line("return new Builder(this);");
        });

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
    }

    // Oneof case enums
    emitOneofCaseEnums(w, message);

    // Nested message classes
    for (ProtoMessage nested : message.getNestedMessages()) {
      w.blankLine();
      emitNestedMessage(w, nested);
    }

    // Serialize method
    serializerGen.generate(w, message);

    // Deserialize method
    deserializerGen.generate(w, message, className);

    // ToString
    emitToString(w, message, className);

    // Equals and GetHashCode
    emitEquals(w, message, className);
    emitHashCode(w, message);

    // Builder inner class
    emitBuilder(w, message, className);
  }

  // ---------------------------------------------------------------------------
  // Field number constants
  // ---------------------------------------------------------------------------

  private void emitFieldNumberConstants(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String constName = snakeToUpperSnake(field.getName()) + "_FIELD_NUMBER";
      w.line("public const int %s = %d;", constName, field.getFieldNumber());
    }
  }

  // ---------------------------------------------------------------------------
  // Private readonly fields on the message class
  // ---------------------------------------------------------------------------

  private void emitFields(CodeWriter w, ProtoMessage message) {
    if (!message.getFields().isEmpty()) {
      w.blankLine();
    }
    for (ProtoField field : message.getFields()) {
      String csType = typeMapper.languageType(field);
      String csName = nameResolver.fieldName(field.getName());
      w.line("private readonly %s %s;", csType, csName);
    }
  }

  // ---------------------------------------------------------------------------
  // Oneof case tracking fields
  // ---------------------------------------------------------------------------

  private void emitOneofCaseFields(CodeWriter w, ProtoMessage message) {
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      w.blankLine();
      String caseName = nameResolver.fieldName(group.name()) + "Case_";
      w.line("private readonly int %s;", caseName);
      // Static constants for each oneof member
      for (ProtoField member : group.members()) {
        w.line(
            "private const int %sCase_ = %d;",
            member.getName().toUpperCase(), member.getFieldNumber());
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Oneof case enums
  // ---------------------------------------------------------------------------

  private void emitOneofCaseEnums(CodeWriter w, ProtoMessage message) {
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      w.blankLine();
      String enumName = CSharpNameResolver.snakeToPascal(group.name()) + "Case";
      w.block(
          "public enum " + enumName,
          () -> {
            // NOT_SET = 0 first
            w.line("%sNotSet = 0,", CSharpNameResolver.snakeToPascal(group.name()));
            for (int i = 0; i < group.members().size(); i++) {
              ProtoField member = group.members().get(i);
              String suffix = i < group.members().size() - 1 ? "," : "";
              w.line(
                  "%s = %d%s",
                  CSharpNameResolver.snakeToPascal(member.getName()),
                  member.getFieldNumber(),
                  suffix);
            }
          });
    }
  }

  // ---------------------------------------------------------------------------
  // Private constructor (from Builder)
  // ---------------------------------------------------------------------------

  private void emitPrivateConstructor(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "private " + className + "(Builder builder)",
        () -> {
          for (ProtoField field : message.getFields()) {
            String csName = nameResolver.fieldName(field.getName());
            if (field.isRepeated()) {
              w.line(
                  "this.%s = new List<%s>(builder.%s).AsReadOnly();",
                  csName, repeatedElementType(field), csName);
            } else if (field.isMap()) {
              w.line(
                  "this.%s = new Dictionary<%s>(builder.%s);",
                  csName, mapGenericArgs(field), csName);
            } else {
              w.line("this.%s = builder.%s;", csName, csName);
            }
          }
          if (hasPresenceTrackedFields(message)) {
            w.line("this.presentFields_ = (bool[])builder.presentFields_.Clone();");
          }
          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            String caseName = nameResolver.fieldName(group.name()) + "Case_";
            w.line("this.%s = builder.%s;", caseName, caseName);
          }
        });
  }

  // ---------------------------------------------------------------------------
  // Properties on the message class (readonly)
  // ---------------------------------------------------------------------------

  private void emitMessageProperties(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String csType = typeMapper.languageType(field);
      String csName = nameResolver.fieldName(field.getName());
      String pascalName = CSharpNameResolver.snakeToPascal(field.getName());

      if (field.isRepeated()) {
        emitRepeatedProperties(w, field, csType, csName, pascalName);
      } else if (field.isMap()) {
        emitMapProperties(w, field, csType, csName, pascalName);
      } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
          || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
        emitMessageFieldProperties(w, field, csType, csName, pascalName);
      } else {
        emitScalarProperty(w, field, csType, csName, pascalName);
      }
    }

    // Oneof GetXxxCase() methods
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String pascalOneof = CSharpNameResolver.snakeToPascal(group.name());
      String enumName = pascalOneof + "Case";
      String caseName = nameResolver.fieldName(group.name()) + "Case_";
      w.blankLine();
      w.block(
          "public " + enumName + " Get" + pascalOneof + "Case()",
          () -> {
            w.line("return (%s)%s;", enumName, caseName);
          });
    }
  }

  private void emitScalarProperty(
      CodeWriter w, ProtoField field, String csType, String csName, String pascalName) {
    w.blankLine();
    emitDocComment(w, field.getComment());
    w.line("public %s %s => this.%s;", csType, pascalName, csName);

    // Has method for fields with explicit presence
    if (field.hasExplicitPresence()) {
      w.blankLine();
      w.line("public bool Has%s => this.presentFields_[%d];", pascalName, field.getArrayPosition());
    }
  }

  private void emitRepeatedProperties(
      CodeWriter w, ProtoField field, String csType, String csName, String pascalName) {
    // Property returning the list
    w.blankLine();
    emitDocComment(w, field.getComment());
    w.line("public %s %sList => this.%s;", csType, pascalName, csName);

    // Count
    w.blankLine();
    w.line("public int %sCount => this.%s.Count;", pascalName, csName);
  }

  private void emitMapProperties(
      CodeWriter w, ProtoField field, String csType, String csName, String pascalName) {
    // Map property
    w.blankLine();
    emitDocComment(w, field.getComment());
    w.line("public %s %sMap => this.%s;", csType, pascalName, csName);

    // Count
    w.blankLine();
    w.line("public int %sCount => this.%s.Count;", pascalName, csName);
  }

  private void emitMessageFieldProperties(
      CodeWriter w, ProtoField field, String csType, String csName, String pascalName) {
    // Has
    w.blankLine();
    if (field.hasExplicitPresence()) {
      w.line("public bool Has%s => this.presentFields_[%d];", pascalName, field.getArrayPosition());
    } else {
      w.line("public bool Has%s => this.%s != null;", pascalName, csName);
    }

    // Get -- returns default instance if null
    w.blankLine();
    emitDocComment(w, field.getComment());
    w.line(
        "public %s %s => this.%s ?? %s.GetDefaultInstance();", csType, pascalName, csName, csType);
  }

  // ---------------------------------------------------------------------------
  // Builder inner class
  // ---------------------------------------------------------------------------

  private void emitBuilder(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "public sealed class Builder",
        () -> {
          // Builder fields (mutable, with defaults)
          for (ProtoField field : message.getFields()) {
            String csType = typeMapper.languageType(field);
            String csName = nameResolver.fieldName(field.getName());
            String defaultVal = typeMapper.defaultValue(field);
            w.line("internal %s %s = %s;", csType, csName, defaultVal);
          }

          // Presence tracking for builder
          if (hasPresenceTrackedFields(message)) {
            w.blankLine();
            int maxBit = maxPresenceBit(message);
            w.line("internal bool[] presentFields_ = new bool[%d];", maxBit + 1);
          }

          // Oneof case tracking in builder
          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            w.blankLine();
            String caseName = nameResolver.fieldName(group.name()) + "Case_";
            w.line("internal int %s = 0;", caseName);
          }

          // Internal no-arg constructor
          w.blankLine();
          w.block("internal Builder()", () -> {});

          // Internal copy constructor from message
          w.blankLine();
          w.block(
              "internal Builder(" + className + " from)",
              () -> {
                for (ProtoField field : message.getFields()) {
                  String csName = nameResolver.fieldName(field.getName());
                  if (field.isRepeated()) {
                    w.line(
                        "this.%s = new List<%s>(from.%s);",
                        csName, repeatedElementType(field), csName);
                  } else if (field.isMap()) {
                    w.line(
                        "this.%s = new Dictionary<%s>(from.%s);",
                        csName, mapGenericArgs(field), csName);
                  } else {
                    w.line("this.%s = from.%s;", csName, csName);
                  }
                }
                if (hasPresenceTrackedFields(message)) {
                  w.line("this.presentFields_ = (bool[])from.presentFields_.Clone();");
                }
                for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
                  String caseName = nameResolver.fieldName(group.name()) + "Case_";
                  w.line("this.%s = from.%s;", caseName, caseName);
                }
              });

          // Builder setters and clearers for each field
          for (ProtoField field : message.getFields()) {
            String csType = typeMapper.languageType(field);
            String csName = nameResolver.fieldName(field.getName());
            String pascalName = CSharpNameResolver.snakeToPascal(field.getName());

            if (field.isRepeated()) {
              emitBuilderRepeatedMethods(w, field, csType, csName, pascalName);
            } else if (field.isMap()) {
              emitBuilderMapMethods(w, field, csType, csName, pascalName);
            } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
                || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
              emitBuilderMessageMethods(w, field, csType, csName, pascalName);
            } else {
              emitBuilderScalarMethods(w, field, csType, csName, pascalName);
            }
          }

          // Oneof GetXxxCase() on builder
          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            String pascalOneof = CSharpNameResolver.snakeToPascal(group.name());
            String enumName = pascalOneof + "Case";
            String caseName = nameResolver.fieldName(group.name()) + "Case_";
            w.blankLine();
            w.block(
                "public " + enumName + " Get" + pascalOneof + "Case()",
                () -> {
                  w.line("return (%s)%s;", enumName, caseName);
                });
          }

          // Build()
          w.blankLine();
          w.block(
              "public " + className + " Build()",
              () -> {
                w.line("return new %s(this);", className);
              });

          // Clear() -- resets all fields to defaults
          w.blankLine();
          w.block(
              "public Builder Clear()",
              () -> {
                for (ProtoField field : message.getFields()) {
                  String csName = nameResolver.fieldName(field.getName());
                  String defaultVal = typeMapper.defaultValue(field);
                  w.line("this.%s = %s;", csName, defaultVal);
                }
                if (hasPresenceTrackedFields(message)) {
                  w.line("Array.Clear(this.presentFields_, 0, this.presentFields_.Length);");
                }
                for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
                  String caseName = nameResolver.fieldName(group.name()) + "Case_";
                  w.line("this.%s = 0;", caseName);
                }
                w.line("return this;");
              });
        });
  }

  // ---------------------------------------------------------------------------
  // Builder: scalar field methods
  // ---------------------------------------------------------------------------

  private void emitBuilderScalarMethods(
      CodeWriter w, ProtoField field, String csType, String csName, String pascalName) {
    // Getter
    w.blankLine();
    w.block(
        "public " + csType + " Get" + pascalName + "()",
        () -> {
          w.line("return this.%s;", csName);
        });

    // Setter
    w.blankLine();
    w.block(
        "public Builder Set" + pascalName + "(" + csType + " value)",
        () -> {
          w.line("this.%s = value;", csName);
          if (field.hasExplicitPresence()) {
            w.line("this.presentFields_[%d] = true;", field.getArrayPosition());
          }
          emitOneofCaseSet(w, field);
          w.line("return this;");
        });

    // Clear
    w.blankLine();
    String defaultVal = typeMapper.defaultValue(field);
    w.block(
        "public Builder Clear" + pascalName + "()",
        () -> {
          w.line("this.%s = %s;", csName, defaultVal);
          if (field.hasExplicitPresence()) {
            w.line("this.presentFields_[%d] = false;", field.getArrayPosition());
          }
          emitOneofCaseClear(w, field);
          w.line("return this;");
        });

    // Has for presence-tracked fields
    if (field.hasExplicitPresence()) {
      w.blankLine();
      w.block(
          "public bool Has" + pascalName + "()",
          () -> {
            w.line("return this.presentFields_[%d];", field.getArrayPosition());
          });
    }
  }

  // ---------------------------------------------------------------------------
  // Builder: repeated field methods
  // ---------------------------------------------------------------------------

  private void emitBuilderRepeatedMethods(
      CodeWriter w, ProtoField field, String csType, String csName, String pascalName) {
    String elementType = repeatedElementType(field);

    // GetXxxList()
    w.blankLine();
    w.block(
        "public " + csType + " Get" + pascalName + "List()",
        () -> {
          w.line("return this.%s;", csName);
        });

    // GetXxxCount()
    w.blankLine();
    w.block(
        "public int Get" + pascalName + "Count()",
        () -> {
          w.line("return this.%s.Count;", csName);
        });

    // AddXxx(value)
    w.blankLine();
    w.block(
        "public Builder Add" + pascalName + "(" + elementType + " value)",
        () -> {
          w.line("this.%s.Add(value);", csName);
          w.line("return this;");
        });

    // AddAllXxx(IEnumerable)
    w.blankLine();
    w.block(
        "public Builder AddAll" + pascalName + "(IEnumerable<" + elementType + "> values)",
        () -> {
          w.block(
              "foreach (var v in values)",
              () -> {
                w.line("this.%s.Add(v);", csName);
              });
          w.line("return this;");
        });

    // SetXxx(list)
    w.blankLine();
    w.block(
        "public Builder Set" + pascalName + "(" + csType + " value)",
        () -> {
          w.line("this.%s = new List<%s>(value);", csName, elementType);
          w.line("return this;");
        });

    // ClearXxx()
    w.blankLine();
    w.block(
        "public Builder Clear" + pascalName + "()",
        () -> {
          w.line("this.%s.Clear();", csName);
          w.line("return this;");
        });
  }

  // ---------------------------------------------------------------------------
  // Builder: map field methods
  // ---------------------------------------------------------------------------

  private void emitBuilderMapMethods(
      CodeWriter w, ProtoField field, String csType, String csName, String pascalName) {
    String keyType = typeMapper.boxedScalarType(field.getMapKeyType());
    String valueType = mapValueType(field);

    // GetXxxMap()
    w.blankLine();
    w.block(
        "public " + csType + " Get" + pascalName + "Map()",
        () -> {
          w.line("return this.%s;", csName);
        });

    // GetXxxCount()
    w.blankLine();
    w.block(
        "public int Get" + pascalName + "Count()",
        () -> {
          w.line("return this.%s.Count;", csName);
        });

    // ContainsXxx(key)
    w.blankLine();
    w.block(
        "public bool Contains" + pascalName + "(" + keyType + " key)",
        () -> {
          w.line("return this.%s.ContainsKey(key);", csName);
        });

    // PutXxx(key, value)
    w.blankLine();
    w.block(
        "public Builder Put" + pascalName + "(" + keyType + " key, " + valueType + " value)",
        () -> {
          w.line("this.%s[key] = value;", csName);
          w.line("return this;");
        });

    // PutAllXxx(Dictionary)
    w.blankLine();
    w.block(
        "public Builder PutAll" + pascalName + "(" + csType + " values)",
        () -> {
          w.block(
              "foreach (var kvp in values)",
              () -> {
                w.line("this.%s[kvp.Key] = kvp.Value;", csName);
              });
          w.line("return this;");
        });

    // RemoveXxx(key)
    w.blankLine();
    w.block(
        "public Builder Remove" + pascalName + "(" + keyType + " key)",
        () -> {
          w.line("this.%s.Remove(key);", csName);
          w.line("return this;");
        });

    // SetXxx(map)
    w.blankLine();
    w.block(
        "public Builder Set" + pascalName + "(" + csType + " value)",
        () -> {
          w.line("this.%s = new Dictionary<%s>(value);", csName, mapGenericArgs(field));
          w.line("return this;");
        });

    // ClearXxx()
    w.blankLine();
    w.block(
        "public Builder Clear" + pascalName + "()",
        () -> {
          w.line("this.%s.Clear();", csName);
          w.line("return this;");
        });
  }

  // ---------------------------------------------------------------------------
  // Builder: message field methods
  // ---------------------------------------------------------------------------

  private void emitBuilderMessageMethods(
      CodeWriter w, ProtoField field, String csType, String csName, String pascalName) {
    // Getter
    w.blankLine();
    w.block(
        "public " + csType + " Get" + pascalName + "()",
        () -> {
          w.line("return this.%s ?? %s.GetDefaultInstance();", csName, csType);
        });

    // Has
    w.blankLine();
    w.block(
        "public bool Has" + pascalName + "()",
        () -> {
          if (field.hasExplicitPresence()) {
            w.line("return this.presentFields_[%d];", field.getArrayPosition());
          } else {
            w.line("return this.%s != null;", csName);
          }
        });

    // Setter
    w.blankLine();
    w.block(
        "public Builder Set" + pascalName + "(" + csType + " value)",
        () -> {
          w.line("this.%s = value;", csName);
          if (field.hasExplicitPresence()) {
            w.line("this.presentFields_[%d] = true;", field.getArrayPosition());
          }
          emitOneofCaseSet(w, field);
          w.line("return this;");
        });

    // Clear
    w.blankLine();
    w.block(
        "public Builder Clear" + pascalName + "()",
        () -> {
          w.line("this.%s = null;", csName);
          if (field.hasExplicitPresence()) {
            w.line("this.presentFields_[%d] = false;", field.getArrayPosition());
          }
          emitOneofCaseClear(w, field);
          w.line("return this;");
        });
  }

  // ---------------------------------------------------------------------------
  // Oneof helpers for Builder setters
  // ---------------------------------------------------------------------------

  private void emitOneofCaseSet(CodeWriter w, ProtoField field) {
    if (field.isOneofMember()) {
      String caseName = nameResolver.fieldName(field.getOneofName()) + "Case_";
      w.line("this.%s = %d;", caseName, field.getFieldNumber());
    }
  }

  private void emitOneofCaseClear(CodeWriter w, ProtoField field) {
    if (field.isOneofMember()) {
      String caseName = nameResolver.fieldName(field.getOneofName()) + "Case_";
      w.line("this.%s = 0;", caseName);
    }
  }

  // ---------------------------------------------------------------------------
  // Nested messages
  // ---------------------------------------------------------------------------

  private void emitNestedMessage(CodeWriter w, ProtoMessage nested) {
    String className = nameResolver.messageClassName(nested.getName());

    emitDocComment(w, nested.getComment());

    w.block(
        "public sealed class " + className,
        () -> {
          emitMessageBody(w, nested, className, true);
        });
  }

  // ---------------------------------------------------------------------------
  // ToString, Equals, GetHashCode
  // ---------------------------------------------------------------------------

  private void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "public override string ToString()",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return \"%s{}\";", className);
            return;
          }
          w.line("return \"%s{\" +", className);
          w.indent();
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String csName = nameResolver.fieldName(field.getName());
            String prefix = i == 0 ? "\"" : "\", ";
            boolean isLast = i == message.getFields().size() - 1;
            if (isLast) {
              w.line("%s%s=\" + %s + \"}\";", prefix, field.getName(), csName);
            } else {
              w.line("%s%s=\" + %s +", prefix, field.getName(), csName);
            }
          }
          w.dedent();
        });
  }

  private void emitEquals(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "public override bool Equals(object o)",
        () -> {
          w.line("if (ReferenceEquals(this, o)) return true;");
          w.line("if (!(o is %s)) return false;", className);
          w.line("var that = (%s)o;", className);
          if (message.getFields().isEmpty()) {
            w.line("return true;");
            return;
          }
          StringBuilder sb = new StringBuilder("return ");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String csName = nameResolver.fieldName(field.getName());
            if (i > 0) {
              sb.append(" && ");
            }
            if (isByteArrayField(field)) {
              sb.append(String.format("this.%s.SequenceEqual(that.%s)", csName, csName));
            } else if (isFloatField(field) || isDoubleField(field)) {
              sb.append(String.format("this.%s.Equals(that.%s)", csName, csName));
            } else if (isPrimitiveField(field)) {
              sb.append(String.format("this.%s == that.%s", csName, csName));
            } else {
              sb.append(String.format("object.Equals(this.%s, that.%s)", csName, csName));
            }
          }
          sb.append(";");
          w.line(sb.toString());
        });
  }

  private void emitHashCode(CodeWriter w, ProtoMessage message) {
    w.blankLine();
    w.block(
        "public override int GetHashCode()",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return 0;");
            return;
          }
          w.line("unchecked {");
          w.indent();
          w.line("int hash = 17;");
          for (ProtoField field : message.getFields()) {
            String csName = nameResolver.fieldName(field.getName());
            if (isByteArrayField(field)) {
              w.line(
                  "hash = hash * 31 + (%s != null ? %s.Aggregate(0, (a, b) => a * 31 + b) : 0);",
                  csName, csName);
            } else if (isPrimitiveField(field)) {
              w.line("hash = hash * 31 + %s.GetHashCode();", csName);
            } else {
              w.line("hash = hash * 31 + (%s != null ? %s.GetHashCode() : 0);", csName, csName);
            }
          }
          w.line("return hash;");
          w.dedent();
          w.line("}");
        });
  }

  // ---------------------------------------------------------------------------
  // Enum generation
  // ---------------------------------------------------------------------------

  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    w.blankLine();
    w.block(
        "public enum " + protoEnum.getName(),
        () -> {
          for (int i = 0; i < protoEnum.getValues().size(); i++) {
            ProtoEnum.EnumValue val = protoEnum.getValues().get(i);
            String suffix = i < protoEnum.getValues().size() - 1 ? "," : "";
            w.line("%s = %d%s", val.name(), val.number(), suffix);
          }
        });

    // Static ForNumber helper method (as an extension-like static class pattern)
    w.blankLine();
    w.block(
        "public static class " + protoEnum.getName() + "Extensions",
        () -> {
          w.block(
              "public static " + protoEnum.getName() + " ForNumber(int number)",
              () -> {
                w.block(
                    "foreach (var v in Enum.GetValues<" + protoEnum.getName() + ">())",
                    () -> {
                      w.block(
                          "if ((int)v == number)",
                          () -> {
                            w.line("return v;");
                          });
                    });
                w.line("return (%s)0;", protoEnum.getName());
              });
        });
  }

  // ---------------------------------------------------------------------------
  // Doc comments
  // ---------------------------------------------------------------------------

  /** Emit an XML documentation comment if the comment text is non-null and non-empty. */
  private void emitDocComment(CodeWriter w, String comment) {
    if (comment == null || comment.isEmpty()) {
      return;
    }
    // Escape XML special characters
    String safeComment = comment.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    String[] lines = safeComment.split("\n");
    w.line("/// <summary>");
    for (String line : lines) {
      String trimmed = line.strip();
      if (trimmed.isEmpty()) {
        w.line("///");
      } else {
        w.line("/// %s", trimmed);
      }
    }
    w.line("/// </summary>");
  }

  // ---------------------------------------------------------------------------
  // Utility methods
  // ---------------------------------------------------------------------------

  private boolean isByteArrayField(ProtoField field) {
    return field.getProtoType()
            == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_BYTES
        && field.isSingular();
  }

  private boolean isFloatField(ProtoField field) {
    return field.isSingular()
        && field.getKind() == ProtoField.FieldKind.SCALAR
        && field.getProtoType()
            == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_FLOAT;
  }

  private boolean isDoubleField(ProtoField field) {
    return field.isSingular()
        && field.getKind() == ProtoField.FieldKind.SCALAR
        && field.getProtoType()
            == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_DOUBLE;
  }

  private boolean isPrimitiveField(ProtoField field) {
    if (!field.isSingular()) return false;
    if (field.getKind() != ProtoField.FieldKind.SCALAR) return false;
    return switch (field.getProtoType()) {
      case TYPE_DOUBLE,
          TYPE_FLOAT,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64,
          TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_BOOL ->
          true;
      default -> false;
    };
  }

  private boolean hasPresenceTrackedFields(ProtoMessage message) {
    return message.getFields().stream().anyMatch(ProtoField::hasExplicitPresence);
  }

  private int maxPresenceBit(ProtoMessage message) {
    return message.getFields().stream()
        .filter(ProtoField::hasExplicitPresence)
        .mapToInt(ProtoField::getArrayPosition)
        .max()
        .orElse(0);
  }

  /** Convert snake_case proto field name to UPPER_SNAKE_CASE for constants. */
  private String snakeToUpperSnake(String name) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < name.length(); i++) {
      char c = name.charAt(i);
      if (Character.isUpperCase(c) && i > 0 && name.charAt(i - 1) != '_') {
        sb.append('_');
      }
      sb.append(Character.toUpperCase(c));
    }
    return sb.toString();
  }

  /** Get the element type for a repeated field. */
  private String repeatedElementType(ProtoField field) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      return simpleTypeName(field.getTypeReference());
    }
    if (field.getKind() == ProtoField.FieldKind.ENUM) {
      return simpleTypeName(field.getTypeReference());
    }
    return typeMapper.boxedScalarType(field.getProtoType());
  }

  /** Get the generic type arguments string for a map field. */
  private String mapGenericArgs(ProtoField field) {
    String keyType = typeMapper.boxedScalarType(field.getMapKeyType());
    String valueType =
        field.getMapValueType()
                    == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_MESSAGE
                || field.getMapValueType()
                    == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_ENUM
            ? simpleTypeName(field.getMapValueTypeReference())
            : typeMapper.boxedScalarType(field.getMapValueType());
    return keyType + ", " + valueType;
  }

  /** Get the value type for a map field. */
  private String mapValueType(ProtoField field) {
    if (field.getMapValueType()
            == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_MESSAGE
        || field.getMapValueType()
            == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_ENUM) {
      return simpleTypeName(field.getMapValueTypeReference());
    }
    return typeMapper.boxedScalarType(field.getMapValueType());
  }

  private String simpleTypeName(String protoFullName) {
    String simple = ProtoTypeUtil.simpleTypeName(protoFullName);
    return simple != null ? simple : "object";
  }
}
