// @generated by protoc-gen-pbtkurl — do not edit.

package com.example;

/** A physical mailing address. */
public final class Address {
    public static final int STREET_FIELD_NUMBER = 1;
    public static final int CITY_FIELD_NUMBER = 2;
    public static final int STATE_FIELD_NUMBER = 3;
    public static final int ZIP_FIELD_NUMBER = 4;

    private final String street;
    private final String city;
    private final String state;
    private final int zip;

    private Address(Builder builder) {
        this.street = builder.street;
        this.city = builder.city;
        this.state = builder.state;
        this.zip = builder.zip;
    }

    private static final Address DEFAULT_INSTANCE = new Builder().build();

    public static Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    /** The street address line. */
    public String getStreet() {
        return this.street;
    }

    /** The city name. */
    public String getCity() {
        return this.city;
    }

    /** The state or province code. */
    public String getState() {
        return this.state;
    }

    /** The postal/ZIP code. */
    public int getZip() {
        return this.zip;
    }

    public static Builder newBuilder() {
        return new Builder();
    }

    public static Builder newBuilder(Address prototype) {
        return new Builder(prototype);
    }

    public Builder toBuilder() {
        return new Builder(this);
    }

    public static final class Builder {
        private String street = "";
        private String city = "";
        private String state = "";
        private int zip = 0;

        private Builder() {
        }

        private Builder(Address prototype) {
            this.street = prototype.street;
            this.city = prototype.city;
            this.state = prototype.state;
            this.zip = prototype.zip;
        }

        public Builder setStreet(String street) {
            this.street = street;
            return this;
        }

        public Builder clearStreet() {
            this.street = "";
            return this;
        }

        public Builder setCity(String city) {
            this.city = city;
            return this;
        }

        public Builder clearCity() {
            this.city = "";
            return this;
        }

        public Builder setState(String state) {
            this.state = state;
            return this;
        }

        public Builder clearState() {
            this.state = "";
            return this;
        }

        public Builder setZip(int zip) {
            this.zip = zip;
            return this;
        }

        public Builder clearZip() {
            this.zip = 0;
            return this;
        }

        public Builder clear() {
            this.street = "";
            this.city = "";
            this.state = "";
            this.zip = 0;
            return this;
        }

        public Address build() {
            return new Address(this);
        }
    }

    void appendPbtkFields(StringBuilder sb) {
        sb.append("!1s").append(java.net.URLEncoder.encode(this.street, java.nio.charset.StandardCharsets.UTF_8));
        sb.append("!2s").append(java.net.URLEncoder.encode(this.city, java.nio.charset.StandardCharsets.UTF_8));
        sb.append("!3s").append(java.net.URLEncoder.encode(this.state, java.nio.charset.StandardCharsets.UTF_8));
        sb.append("!4i").append(this.zip);
    }

    int countPbtkFields() {
        int count = 0;
        count++;
        count++;
        count++;
        count++;
        return count;
    }

    public byte[] toByteArray() {
        StringBuilder sb = new StringBuilder();
        appendPbtkFields(sb);
        return sb.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
    }

    public void writeTo(java.io.OutputStream output) throws java.io.IOException {
        output.write(toByteArray());
    }

    static Address parsePbtkTokens(java.util.List<String> tokens, int fieldCount, int[] offset) {
        Address.Builder builder = Address.newBuilder();
        int consumed = 0;
        while (consumed < fieldCount && offset[0] < tokens.size()) {
            String token = tokens.get(offset[0]);
            int numEnd = 0;
            while (numEnd < token.length() && Character.isDigit(token.charAt(numEnd))) numEnd++;
            if (numEnd == 0 || numEnd >= token.length()) { offset[0]++; consumed++; continue; }
            int fieldNum = Integer.parseInt(token.substring(0, numEnd));
            char typeChar = token.charAt(numEnd);
            String value = token.substring(numEnd + 1);
            switch (fieldNum) {
                case 1: {
                    builder.setStreet(java.net.URLDecoder.decode(value, java.nio.charset.StandardCharsets.UTF_8));
                    offset[0]++;
                    consumed++;
                    break;
                }
                case 2: {
                    builder.setCity(java.net.URLDecoder.decode(value, java.nio.charset.StandardCharsets.UTF_8));
                    offset[0]++;
                    consumed++;
                    break;
                }
                case 3: {
                    builder.setState(java.net.URLDecoder.decode(value, java.nio.charset.StandardCharsets.UTF_8));
                    offset[0]++;
                    consumed++;
                    break;
                }
                case 4: {
                    builder.setZip(Integer.parseInt(value));
                    offset[0]++;
                    consumed++;
                    break;
                }
                default: offset[0]++; consumed++; break;
            }
        }
        return builder.build();
    }

    public static Address parseFrom(byte[] data) {
        String input = new String(data, java.nio.charset.StandardCharsets.UTF_8);
        if (input.isEmpty()) return Address.getDefaultInstance();
        java.util.List<String> tokens = tokenizePbtk(input);
        int[] offset = {0};
        return parsePbtkTokens(tokens, tokens.size(), offset);
    }

    public static Address parseFrom(java.io.InputStream input) throws java.io.IOException {
        return parseFrom(input.readAllBytes());
    }

    private static java.util.List<String> tokenizePbtk(String input) {
        java.util.List<String> tokens = new java.util.ArrayList<>();
        int i = 0;
        if (input.charAt(0) == '!') i = 1;
        while (i < input.length()) {
            int next = input.indexOf('!', i);
            if (next < 0) {
                tokens.add(input.substring(i));
                break;
            }
            tokens.add(input.substring(i, next));
            i = next + 1;
        }
        return tokens;
    }

    @Override
    public String toString() {
        return "Address{" +
            "street=" + street +
            ", city=" + city +
            ", state=" + state +
            ", zip=" + zip + "}";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Address)) return false;
        Address that = (Address) o;
        return java.util.Objects.equals(this.street, that.street) && java.util.Objects.equals(this.city, that.city) && java.util.Objects.equals(this.state, that.state) && this.zip == that.zip;
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(street, city, state, zip);
    }
}
