// @generated by protoc-gen-jsonarray -- do not edit.

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface EXAddress : NSObject

@property (nonatomic, copy, nullable) NSString *street;
@property (nonatomic, copy, nullable) NSString *city;
@property (nonatomic, copy, nullable) NSString *state;
@property (nonatomic, assign) int32_t zip;

- (NSArray *)toJsonArray;
- (NSData *)data;

+ (instancetype)fromJsonArray:(NSArray *)array;
+ (instancetype)parseFromData:(NSData *)data error:(NSError **)errorPtr;

@end

NS_ASSUME_NONNULL_END
