// @generated by protoc-gen-jsonarray -- do not edit.

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface EXAddress : NSObject

@property (nonatomic, strong, nullable) NSString *street;
@property (nonatomic, strong, nullable) NSString *city;
@property (nonatomic, strong, nullable) NSString *state;
@property (nonatomic, assign) int32_t zip;

- (NSArray *)toJsonArray;
- (NSString *)toJsonString;

+ (instancetype)fromJsonArray:(NSArray *)array;
+ (instancetype)fromJsonString:(NSString *)jsonString;

@end

NS_ASSUME_NONNULL_END
