// @generated by protoc-gen-jsonarray -- do not edit.

#import "EXAddress.h"
#import <math.h>

@implementation EXAddress

- (NSArray *)toJsonArray {
    NSMutableArray *array = [NSMutableArray array];
    [array addObject:(self.street != nil) ? self.street : @""];
    [array addObject:(self.city != nil) ? self.city : @""];
    [array addObject:(self.state != nil) ? self.state : @""];
    [array addObject:@(self.zip)];
    return [array copy];
}

- (NSString *)toJsonString {
    NSArray *array = [self toJsonArray];
    NSData *data = [NSJSONSerialization dataWithJSONObject:array options:0 error:nil];
    if (!data) return nil;
    return [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
}

+ (instancetype)fromJsonArray:(NSArray *)array {
    if (!array || ![array isKindOfClass:[NSArray class]]) return nil;
    EXAddress *msg = [[EXAddress alloc] init];
    NSUInteger count = array.count;
    if (count > 0) {
        id item = array[0];
        if (item && item != (id)[NSNull null]) {
            if ([item isKindOfClass:[NSString class]]) {
                msg.street = (NSString *)item;
            }
        }
    }
    if (count > 1) {
        id item = array[1];
        if (item && item != (id)[NSNull null]) {
            if ([item isKindOfClass:[NSString class]]) {
                msg.city = (NSString *)item;
            }
        }
    }
    if (count > 2) {
        id item = array[2];
        if (item && item != (id)[NSNull null]) {
            if ([item isKindOfClass:[NSString class]]) {
                msg.state = (NSString *)item;
            }
        }
    }
    if (count > 3) {
        id item = array[3];
        if (item && item != (id)[NSNull null]) {
            msg.zip = [(NSNumber *)item intValue];
        }
    }
    return msg;
}

+ (instancetype)fromJsonString:(NSString *)jsonString {
    if (!jsonString) return nil;
    NSData *data = [jsonString dataUsingEncoding:NSUTF8StringEncoding];
    if (!data) return nil;
    NSArray *array = [NSJSONSerialization JSONObjectWithData:data options:0 error:nil];
    if (![array isKindOfClass:[NSArray class]]) return nil;
    return [EXAddress fromJsonArray:array];
}

@end
