// @generated by protoc-gen-pbtkurl -- do not edit.


fn pbtk_url_encode(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for &byte in input.as_bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => out.push(byte as char),
            _ => {
                out.push('%');
                out.push_str(&format!("{:02X}", byte));
            }
        }
    }
    out
}

fn pbtk_url_decode(input: &str) -> String {
    fn hex_val(c: u8) -> Option<u8> {
        match c {
            b'0'..=b'9' => Some(c - b'0'),
            b'A'..=b'F' => Some(c - b'A' + 10),
            b'a'..=b'f' => Some(c - b'a' + 10),
            _ => None,
        }
    }
    let bytes = input.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let (Some(h), Some(l)) = (hex_val(bytes[i + 1]), hex_val(bytes[i + 2])) {
                out.push((h << 4) | l);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

#[derive(Debug, Clone, Default)]
pub struct Address {
    pub street: String,
    pub city: String,
    pub state: String,
    pub zip: i32,
}

impl Address {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn street(&self) -> &str {
        &self.street
    }

    pub fn set_street(&mut self, value: String) {
        self.street = value;
    }

    pub fn city(&self) -> &str {
        &self.city
    }

    pub fn set_city(&mut self, value: String) {
        self.city = value;
    }

    pub fn state(&self) -> &str {
        &self.state
    }

    pub fn set_state(&mut self, value: String) {
        self.state = value;
    }

    pub fn zip(&self) -> i32 {
        self.zip
    }

    pub fn set_zip(&mut self, value: i32) {
        self.zip = value;
    }

    pub fn append_pbtk_fields(&self, s: &mut String) {
        s.push_str("!1s"); s.push_str(&pbtk_url_encode(&self.street));
        s.push_str("!2s"); s.push_str(&pbtk_url_encode(&self.city));
        s.push_str("!3s"); s.push_str(&pbtk_url_encode(&self.state));
        s.push_str("!4i"); s.push_str(&self.zip.to_string());
    }

    pub fn count_pbtk_fields(&self) -> usize {
        let mut count: usize = 0;
        count += 1;
        count += 1;
        count += 1;
        count += 1;
        count
    }

    pub fn encode_to_vec(&self) -> Vec<u8> {
        let mut s = String::new();
        self.append_pbtk_fields(&mut s);
        s.into_bytes()
    }

    pub fn parse_pbtk_tokens(tokens: &[&str], field_count: usize, offset: &mut usize) -> Self {
        let mut obj = Address::default();
        let mut consumed: usize = 0;
        while consumed < field_count && *offset < tokens.len() {
            let token = tokens[*offset];
            let num_end = token.find(|c: char| !c.is_ascii_digit()).unwrap_or(token.len());
            if num_end == 0 || num_end >= token.len() { *offset += 1; consumed += 1; continue; }
            let field_num: i32 = token[..num_end].parse().unwrap_or(0);
            let type_char = token.as_bytes()[num_end] as char;
            let value = &token[num_end + 1..];
            match field_num {
                1 => {
                    obj.street = pbtk_url_decode(value);
                    *offset += 1;
                    consumed += 1;
                }
                2 => {
                    obj.city = pbtk_url_decode(value);
                    *offset += 1;
                    consumed += 1;
                }
                3 => {
                    obj.state = pbtk_url_decode(value);
                    *offset += 1;
                    consumed += 1;
                }
                4 => {
                    obj.zip = value.parse::<i32>().unwrap_or(0);
                    *offset += 1;
                    consumed += 1;
                }
                _ => { *offset += 1; consumed += 1; }
            }
        }
        obj
    }

    pub fn decode(data: &[u8]) -> Result<Self, String> {
        let input = std::str::from_utf8(data).map_err(|e| e.to_string())?;
        if input.is_empty() { return Ok(Self::default()); }
        let trimmed = if input.starts_with('!') { &input[1..] } else { input };
        let tokens: Vec<&str> = trimmed.split('!').collect();
        let mut offset: usize = 0;
        Ok(Self::parse_pbtk_tokens(&tokens, tokens.len(), &mut offset))
    }
}

impl std::fmt::Display for Address {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Address{{street: {:?}, city: {:?}, state: {:?}, zip: {:?}}}", self.street, self.city, self.state, self.zip)
    }
}
