/*
 * Copyright 2024 protobuf-text-codecs contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.jsonarray.codegen.dart;

import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Generates complete Dart source files for proto messages and enums. Produces Dart classes with
 * factory constructors, getters/setters, serialize, and deserialize.
 */
public class DartCodeEmitter {

  private final DartTypeMapper typeMapper;
  private final DartNameResolver nameResolver;
  private final DartSerializerGenerator serializerGen;
  private final DartDeserializerGenerator deserializerGen;

  public DartCodeEmitter(DartTypeMapper typeMapper, DartNameResolver nameResolver) {
    this.typeMapper = typeMapper;
    this.nameResolver = nameResolver;
    this.serializerGen = new DartSerializerGenerator(typeMapper, nameResolver);
    this.deserializerGen = new DartDeserializerGenerator(typeMapper, nameResolver);
  }

  /** Generate a complete Dart source file for a message. */
  public String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter("  "); // 2-space indent for Dart
    String className = nameResolver.messageClassName(message.getName());

    emitFileHeader(w, file);

    // Collect referenced type imports
    Set<String> importNames = new LinkedHashSet<>();
    collectReferencedTypeNames(message, file, importNames);
    emitImports(w, importNames);

    // Emit nested enums as abstract classes before the main class
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
      w.blankLine();
    }

    // Emit nested message classes before the main class
    for (ProtoMessage nested : message.getNestedMessages()) {
      emitMessageClass(w, nested, file);
      w.blankLine();
    }

    // Main class
    emitMessageClass(w, message, file);

    return w.toString();
  }

  /** Generate a complete Dart source file for a top-level enum. */
  public String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    emitFileHeader(w, file);
    emitEnum(w, protoEnum);
    return w.toString();
  }

  private void emitFileHeader(CodeWriter w, ProtoFile file) {
    w.line("// Generated by protoc-gen-jsonarray. DO NOT EDIT.");
    w.line("// Source: %s", file.getFileName());
    w.blankLine();
    w.line("import 'dart:convert';");
    w.blankLine();
  }

  private void emitImports(CodeWriter w, Set<String> importNames) {
    for (String name : importNames) {
      String fileName = DartNameResolver.pascalToSnake(name);
      w.line("import '%s.dart';", fileName);
    }
    if (!importNames.isEmpty()) {
      w.blankLine();
    }
  }

  /**
   * Collect the simple names of types referenced from other files. These will be emitted as import
   * statements.
   */
  private void collectReferencedTypeNames(ProtoMessage message, ProtoFile file, Set<String> names) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      String typeRef = field.getTypeReference();
      if (typeRef == null) continue;
      if (field.isWellKnownType()) continue;

      // Check if the type is defined in the current message (nested type)
      boolean isNested = false;
      for (ProtoMessage nested : message.getNestedMessages()) {
        if (typeRef.equals(message.getFullName() + "." + nested.getName())) {
          isNested = true;
          break;
        }
      }
      if (isNested) continue;

      // Extract the simple name
      String simpleName = typeRef.substring(typeRef.lastIndexOf('.') + 1);

      // Check if this is a type in the same package but different file
      if (typeRef.startsWith(currentPrefix)) {
        names.add(simpleName);
      }

      // For map value types
      if (field.isMap() && field.getMapValueTypeReference() != null) {
        String valRef = field.getMapValueTypeReference();
        String valName = valRef.substring(valRef.lastIndexOf('.') + 1);
        if (valRef.startsWith(currentPrefix)) {
          names.add(valName);
        }
      }
    }

    // Also check nested messages for their references
    for (ProtoMessage nested : message.getNestedMessages()) {
      collectReferencedTypeNames(nested, file, names);
    }
  }

  /** Emit a complete Dart class for a message. */
  private void emitMessageClass(CodeWriter w, ProtoMessage message, ProtoFile file) {
    String className = nameResolver.messageClassName(message.getName());

    w.block(
        "class " + className,
        () -> {
          // Fields
          emitFields(w, message);

          // Constructor
          emitConstructor(w, message, className);

          // Getters and setters
          emitGettersSetters(w, message);

          // Presence checks for optional fields
          emitHasMethods(w, message);

          // Serialize
          serializerGen.generate(w, message);

          // Deserialize
          deserializerGen.generate(w, message, className);

          // toString
          emitToString(w, message, className);
        });
  }

  private void emitFields(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String dartName = nameResolver.fieldName(field.getName());
      String dartType = typeMapper.dartType(field);
      String defaultVal = typeMapper.defaultValue(field);

      if (field.getKind() == ProtoField.FieldKind.MESSAGE
          || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE
          || field.isProto3Optional()) {
        w.line("%s %s;", dartType, dartName);
      } else if (field.isMap() || field.isRepeated()) {
        w.line("%s %s = %s;", dartType, dartName, defaultVal);
      } else {
        w.line("%s %s = %s;", dartType, dartName, defaultVal);
      }
    }

    // Presence tracking for proto3 optional fields
    if (hasOptionalFields(message)) {
      w.blankLine();
      w.line("final Map<int, bool> _presentFields = {};");
    }

    // Oneof case tracking
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String caseProp = "_" + nameResolver.fieldName(group.name()) + "Case";
      w.line("int %s = 0; // 0 = not set", caseProp);
    }
  }

  private void emitConstructor(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.line("/// Creates a new [%s] instance.", className);
    w.line("%s();", className);
  }

  private void emitGettersSetters(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String dartName = nameResolver.fieldName(field.getName());
      String getterName = nameResolver.getterName(field.getName());
      String setterName = nameResolver.setterName(field.getName());
      String dartType = typeMapper.dartType(field);

      // Getter
      w.blankLine();
      w.line("/// Returns the value of [%s].", field.getName());
      w.block(
          dartType + " " + getterName + "()",
          () -> {
            w.line("return %s;", dartName);
          });

      // Setter
      w.blankLine();
      w.line("/// Sets the value of [%s].", field.getName());
      w.block(
          "void " + setterName + "(" + dartType + " value)",
          () -> {
            w.line("%s = value;", dartName);
            if (field.isProto3Optional()) {
              w.line("_presentFields[%d] = true;", field.getArrayPosition());
            }
            if (field.isOneofMember()) {
              String caseProp = "_" + nameResolver.fieldName(field.getOneofName()) + "Case";
              w.line("%s = %d;", caseProp, field.getFieldNumber());
            }
          });
    }
  }

  private void emitHasMethods(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.isProto3Optional() || field.getKind() == ProtoField.FieldKind.MESSAGE) {
        String hasName = "has" + DartNameResolver.snakeToPascal(field.getName());
        w.blankLine();
        w.line("/// Returns whether the [%s] field is present.", field.getName());
        w.block(
            "bool " + hasName + "()",
            () -> {
              if (field.isProto3Optional()) {
                w.line("return _presentFields[%d] == true;", field.getArrayPosition());
              } else {
                w.line("return %s != null;", nameResolver.fieldName(field.getName()));
              }
            });
      }
    }
  }

  /** Emit a Dart enum as an abstract class with static const int fields. */
  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    String enumName = protoEnum.getName();
    w.line("/// Enum values for %s.", enumName);
    w.block(
        "abstract class " + enumName,
        () -> {
          for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
            w.line(
                "static const int %s = %d;",
                nameResolver.enumConstantName(val.name()), val.number());
          }
        });
  }

  private void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.line("@override");
    w.block(
        "String toString()",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return '%s{}';", className);
            return;
          }
          StringBuilder sb = new StringBuilder();
          sb.append("return '").append(className).append("{");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String dartName = nameResolver.fieldName(field.getName());
            if (i > 0) sb.append(", ");
            sb.append(field.getName()).append("=$").append(dartName);
          }
          sb.append("}';");
          w.line(sb.toString());
        });
  }

  private boolean hasOptionalFields(ProtoMessage message) {
    return message.getFields().stream().anyMatch(ProtoField::isProto3Optional);
  }
}
