/*
 * Copyright 2026 coffeeandwork
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.jsonarray.codegen.dart;

import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Generates complete Dart source files for proto messages and enums. Produces Dart classes with
 * factory constructors, getters/setters, serialize, and deserialize.
 */
public class DartCodeEmitter {

  private final DartTypeMapper typeMapper;
  private final DartNameResolver nameResolver;
  private final DartSerializerGenerator serializerGen;
  private final DartDeserializerGenerator deserializerGen;

  public DartCodeEmitter(DartTypeMapper typeMapper, DartNameResolver nameResolver) {
    this.typeMapper = typeMapper;
    this.nameResolver = nameResolver;
    this.serializerGen = new DartSerializerGenerator(typeMapper, nameResolver);
    this.deserializerGen = new DartDeserializerGenerator(typeMapper, nameResolver);
  }

  /** Generate a complete Dart source file for a message. */
  public String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter("  "); // 2-space indent for Dart

    emitFileHeader(w, file);

    // Collect referenced type imports
    Set<String> importNames = new LinkedHashSet<>();
    collectReferencedTypeNames(message, file, importNames);
    emitImports(w, importNames);

    // Emit nested enums as abstract classes before the main class
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
      w.blankLine();
    }

    // Emit nested message classes (any depth, deepest first) before the main class
    emitNestedTypes(w, message, file);

    // Main class
    emitMessageClass(w, message, file);

    return w.toString();
  }

  /** Generate a complete Dart source file for a top-level enum. */
  public String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    emitFileHeader(w, file);
    emitEnum(w, protoEnum);
    return w.toString();
  }

  private void emitFileHeader(CodeWriter w, ProtoFile file) {
    w.line("// Generated by protoc-gen-jsonarray. DO NOT EDIT.");
    w.line("// Source: %s", file.getFileName());
    w.blankLine();
    w.line("import 'dart:convert';");
    w.line("import 'dart:typed_data';");
    w.blankLine();
  }

  /** Emit all nested enums and message classes of a container, deepest first. */
  private void emitNestedTypes(CodeWriter w, ProtoMessage container, ProtoFile file) {
    for (ProtoMessage nested : container.getNestedMessages()) {
      emitNestedTypes(w, nested, file);
      for (ProtoEnum protoEnum : nested.getEnums()) {
        emitEnum(w, protoEnum);
        w.blankLine();
      }
      emitMessageClass(w, nested, file);
      w.blankLine();
    }
  }

  private void emitImports(CodeWriter w, Set<String> importPaths) {
    for (String path : importPaths) {
      w.line("import '%s.dart';", path);
    }
    if (!importPaths.isEmpty()) {
      w.blankLine();
    }
  }

  /**
   * Collect the simple names of types referenced from other files. These will be emitted as import
   * statements.
   */
  private void collectReferencedTypeNames(ProtoMessage message, ProtoFile file, Set<String> names) {
    names.addAll(collectImportPaths(message, file));
  }

  /** Collect relative import paths for a top-level message's file. Shared with pbtk. */
  public static Set<String> collectImportPaths(ProtoMessage topLevelMessage, ProtoFile file) {
    Set<String> names = new LinkedHashSet<>();
    collectImportPaths(topLevelMessage, topLevelMessage, file, names);
    return names;
  }

  /**
   * Collect relative import paths (extensionless, snake_case) for types referenced from other
   * files, including other proto packages. Nested types are imported via their top-level
   * container's file. {@code topLevel} is the message whose file is being emitted; everything
   * nested under it lives in the same file and needs no import.
   */
  private static void collectImportPaths(
      ProtoMessage message, ProtoMessage topLevel, ProtoFile file, Set<String> names) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      // A map field's own type reference is the synthetic *MapEntry message, which is
      // never generated as a file; only the value type may need an import.
      if (field.isMap()) {
        addImportPath(field.getMapValueTypeReference(), topLevel, file, currentPrefix, names);
        continue;
      }
      if (field.isWellKnownType()) continue;
      addImportPath(field.getTypeReference(), topLevel, file, currentPrefix, names);
    }

    for (ProtoMessage nested : message.getNestedMessages()) {
      collectImportPaths(nested, topLevel, file, names);
    }
  }

  private static void addImportPath(
      String typeRef,
      ProtoMessage topLevel,
      ProtoFile file,
      String currentPrefix,
      Set<String> names) {
    if (typeRef == null || typeRef.startsWith(".google.protobuf.")) return;

    // Anything in this file's own type tree needs no import (and a Dart file must
    // not import itself)
    if (typeRef.equals(topLevel.getFullName())
        || typeRef.startsWith(topLevel.getFullName() + ".")) {
      return;
    }

    // Split into package segments (lowercase by proto convention) and type segments;
    // the first type segment is the top-level container whose file we import.
    String withoutDot = typeRef.startsWith(".") ? typeRef.substring(1) : typeRef;
    String[] segments = withoutDot.split("\\.");
    int firstType = 0;
    while (firstType < segments.length
        && !segments[firstType].isEmpty()
        && Character.isLowerCase(segments[firstType].charAt(0))) {
      firstType++;
    }
    if (firstType >= segments.length) return;
    String fileBase = DartNameResolver.pascalToSnake(segments[firstType]);

    if (typeRef.startsWith(currentPrefix)) {
      // Same package: sibling file
      names.add(fileBase);
      return;
    }

    // Cross-package: path relative to this file's package directory
    int currentDepth =
        file.getProtoPackage().isEmpty() ? 0 : file.getProtoPackage().split("\\.").length;
    StringBuilder path = new StringBuilder();
    for (int i = 0; i < currentDepth; i++) {
      path.append("../");
    }
    for (int i = 0; i < firstType; i++) {
      path.append(segments[i]).append('/');
    }
    path.append(fileBase);
    names.add(path.toString());
  }

  /** Emit a complete Dart class for a message. */
  private void emitMessageClass(CodeWriter w, ProtoMessage message, ProtoFile file) {
    String className = nameResolver.messageClassName(message.getName());

    w.block(
        "class " + className,
        () -> {
          // Fields
          emitFields(w, message);

          // Constructor
          emitConstructor(w, message, className);

          // Getters and setters
          emitGettersSetters(w, message);

          // Presence checks for optional fields
          emitHasMethods(w, message);

          // Serialize
          serializerGen.generate(w, message);

          // Deserialize
          deserializerGen.generate(w, message, className);

          // toString
          emitToString(w, message, className);
        });
  }

  private void emitFields(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String dartName = nameResolver.fieldName(field.getName());
      String dartType = typeMapper.dartType(field);
      String defaultVal = typeMapper.defaultValue(field);

      if (!field.isMap()
          && !field.isRepeated()
          && (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE
              || field.isProto3Optional())) {
        w.line("%s %s;", dartType, dartName);
      } else {
        w.line("%s %s = %s;", dartType, dartName, defaultVal);
      }
    }

    // Presence tracking for proto3 optional fields
    if (hasOptionalFields(message)) {
      w.blankLine();
      w.line("final Map<int, bool> _presentFields = {};");
    }

    // Oneof case tracking
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String caseProp = "_" + nameResolver.fieldName(group.name()) + "Case";
      w.line("int %s = 0; // 0 = not set", caseProp);
    }
  }

  private void emitConstructor(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.line("/// Creates a new [%s] instance.", className);
    w.line("%s();", className);
  }

  private void emitGettersSetters(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String dartName = nameResolver.fieldName(field.getName());
      String getterName = nameResolver.getterName(field.getName());
      String setterName = nameResolver.setterName(field.getName());
      String dartType = typeMapper.dartType(field);

      // Getter
      w.blankLine();
      w.line("/// Returns the value of [%s].", field.getName());
      w.block(
          dartType + " " + getterName + "()",
          () -> {
            w.line("return %s;", dartName);
          });

      // Setter
      w.blankLine();
      w.line("/// Sets the value of [%s].", field.getName());
      w.block(
          "void " + setterName + "(" + dartType + " value)",
          () -> {
            w.line("%s = value;", dartName);
            if (field.isProto3Optional()) {
              w.line("_presentFields[%d] = true;", field.getArrayPosition());
            }
            if (field.isOneofMember()) {
              String caseProp = "_" + nameResolver.fieldName(field.getOneofName()) + "Case";
              w.line("%s = %d;", caseProp, field.getFieldNumber());
            }
          });
    }
  }

  private void emitHasMethods(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.isProto3Optional() || field.getKind() == ProtoField.FieldKind.MESSAGE) {
        String hasName = "has" + DartNameResolver.snakeToPascal(field.getName());
        w.blankLine();
        w.line("/// Returns whether the [%s] field is present.", field.getName());
        w.block(
            "bool " + hasName + "()",
            () -> {
              if (field.isProto3Optional()) {
                w.line("return _presentFields[%d] == true;", field.getArrayPosition());
              } else {
                w.line("return %s != null;", nameResolver.fieldName(field.getName()));
              }
            });
      }
    }
  }

  /** Emit a Dart enum as an abstract class with static const int fields. */
  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    String enumName = protoEnum.getName();
    w.line("/// Enum values for %s.", enumName);
    w.block(
        "abstract class " + enumName,
        () -> {
          for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
            w.line(
                "static const int %s = %d;",
                nameResolver.enumConstantName(val.name()), val.number());
          }
        });
  }

  private void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.line("@override");
    w.block(
        "String toString()",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return '%s{}';", className);
            return;
          }
          StringBuilder sb = new StringBuilder();
          sb.append("return \"").append(className).append("{");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String dartName = nameResolver.fieldName(field.getName());
            if (i > 0) sb.append(", ");
            sb.append(field.getName()).append("=$").append(dartName);
          }
          sb.append("}\";");
          w.line(sb.toString());
        });
  }

  private boolean hasOptionalFields(ProtoMessage message) {
    return message.getFields().stream().anyMatch(ProtoField::isProto3Optional);
  }
}
