/*
 * Copyright 2026 coffeeandwork
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.jsonarray.codegen.javascript;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.ProtoTypeUtil;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Generates complete JavaScript source files for proto messages and enums. Produces ES6 classes
 * with constructor, getters/setters, serialize, and deserialize.
 */
public class JavaScriptCodeEmitter {

  protected final JavaScriptTypeMapper typeMapper;
  protected final JavaScriptNameResolver nameResolver;
  protected final JavaScriptSerializerGenerator serializerGen;
  protected final JavaScriptDeserializerGenerator deserializerGen;

  public JavaScriptCodeEmitter(
      JavaScriptTypeMapper typeMapper, JavaScriptNameResolver nameResolver) {
    this.typeMapper = typeMapper;
    this.nameResolver = nameResolver;
    this.serializerGen = new JavaScriptSerializerGenerator(typeMapper, nameResolver);
    this.deserializerGen = new JavaScriptDeserializerGenerator(typeMapper, nameResolver);
  }

  /** Generate a complete JavaScript source file for a message. */
  public String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter("  "); // 2-space indent for JS
    String className = nameResolver.messageClassName(message.getName());

    emitFileHeader(w, file);

    // Collect referenced types — emitted as top-level ES module imports
    Set<String> importNames = new LinkedHashSet<>();
    collectReferencedTypeNames(message, file, importNames);
    List<String> importNameList = List.copyOf(importNames);

    // Emit top-level imports
    for (String name : importNameList) {
      w.line(formatImport(name));
    }
    if (!importNameList.isEmpty()) {
      w.blankLine();
    }

    // Emit base64 helpers if needed
    if (messageHasBytesFields(message)) {
      emitBase64Helpers(w);
      w.blankLine();
    }

    // Emit nested enums as const objects before the class
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
      w.blankLine();
    }

    // Emit nested message classes before the main class
    for (ProtoMessage nested : message.getNestedMessages()) {
      emitMessageClass(w, nested, file);
      w.blankLine();
    }

    // Main class — no lazy imports needed, imports are at top level
    emitMessageClass(w, message, file, List.of());

    // Export
    w.blankLine();
    emitExports(w, message, className);

    return w.toString();
  }

  /** Generate a complete JavaScript source file for a top-level enum. */
  public String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    emitFileHeader(w, file);
    emitEnum(w, protoEnum);
    w.blankLine();
    w.line("export { %s };", protoEnum.getName());
    return w.toString();
  }

  /** Override point for subclasses (TypeScript) to add file-level header content. */
  protected void emitFileHeader(CodeWriter w, ProtoFile file) {
    w.line("// Generated by protoc-gen-jsonarray. DO NOT EDIT.");
    w.line("// Source: %s", file.getFileName());
    w.blankLine();
  }

  /** Emit require statements for message/enum types referenced from other proto files. */
  protected void emitTypeImports(CodeWriter w, ProtoMessage message, ProtoFile file) {
    // No-op: imports are now emitted lazily inside deserialize() to avoid circular requires.
  }

  /**
   * Collect the simple names of types referenced from other files. These will be emitted as lazy
   * imports inside the deserialize() method body to avoid circular require issues.
   */
  protected void collectReferencedTypeNames(
      ProtoMessage message, ProtoFile file, Set<String> names) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      String typeRef = field.getTypeReference();
      if (typeRef == null) continue;
      if (field.isWellKnownType()) continue;

      // Check if the type is defined in the current message (nested type)
      boolean isNested = false;
      for (ProtoMessage nested : message.getNestedMessages()) {
        if (typeRef.equals(message.getFullName() + "." + nested.getName())) {
          isNested = true;
          break;
        }
      }
      if (isNested) continue;

      // Extract the simple name
      String simpleName = ProtoTypeUtil.simpleTypeName(typeRef);

      // Check if this is a type in the same package but different file
      if (typeRef.startsWith(currentPrefix)) {
        names.add(simpleName);
      }

      // For map value types
      if (field.isMap() && field.getMapValueTypeReference() != null) {
        String valRef = field.getMapValueTypeReference();
        String valName = ProtoTypeUtil.simpleTypeName(valRef);
        if (valRef.startsWith(currentPrefix)) {
          names.add(valName);
        }
      }
    }

    // Also check nested messages for their references
    for (ProtoMessage nested : message.getNestedMessages()) {
      collectReferencedTypeNames(nested, file, names);
    }
  }

  /**
   * Format a single import statement for a referenced type. ES modules handle circular dependencies
   * via live bindings, so lazy imports are no longer needed. Override in subclasses for different
   * import syntax (e.g. TypeScript).
   */
  public String formatLazyImport(String simpleName) {
    return formatImport(simpleName);
  }

  /**
   * Format a single import statement for a referenced type. Override in subclasses for different
   * import syntax (e.g. TypeScript).
   */
  protected String formatImport(String simpleName) {
    return String.format("import { %s } from './%s.js';", simpleName, simpleName);
  }

  /** Emit a complete ES6 class for a message (without lazy imports). */
  protected void emitMessageClass(CodeWriter w, ProtoMessage message, ProtoFile file) {
    emitMessageClass(w, message, file, List.of());
  }

  /** Emit a complete ES6 class for a message, with lazy imports inside deserialize(). */
  protected void emitMessageClass(
      CodeWriter w, ProtoMessage message, ProtoFile file, List<String> lazyImportNames) {
    String className = nameResolver.messageClassName(message.getName());

    w.block(
        "class " + className,
        () -> {
          // Constructor
          emitConstructor(w, message);

          // Getters and setters
          emitGettersSetters(w, message);

          // Presence checks for optional fields
          emitHasMethods(w, message);

          // Serialize
          serializerGen.generate(w, message);

          // Deserialize (with lazy imports to avoid circular requires)
          deserializerGen.generate(w, message, className, lazyImportNames, this);

          // toString
          emitToString(w, message, className);
        });
  }

  protected void emitConstructor(CodeWriter w, ProtoMessage message) {
    w.line("/**");
    w.line(" * @constructor");
    w.line(" */");
    w.block(
        "constructor()",
        () -> {
          // Fields with defaults
          for (ProtoField field : message.getFields()) {
            String jsName = nameResolver.fieldName(field.getName());
            String defaultVal = typeMapper.defaultValue(field);
            w.line("/** @type {%s} */", typeMapper.jsDocType(field));
            w.line("this.%s = %s;", jsName, defaultVal);
          }

          // Presence tracking for proto3 optional fields
          if (hasOptionalFields(message)) {
            w.blankLine();
            w.line("/** @private */");
            w.line("this._presentFields = {};");
          }

          // Oneof case tracking
          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            w.blankLine();
            String caseProp = "_" + nameResolver.fieldName(group.name()) + "Case";
            w.line("/** @private */");
            w.line("this.%s = 0; // 0 = not set", caseProp);
          }
        });
  }

  protected void emitGettersSetters(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String jsName = nameResolver.fieldName(field.getName());
      String getterName = nameResolver.getterName(field.getName());
      String setterName = nameResolver.setterName(field.getName());

      // Getter
      w.blankLine();
      w.line("/**");
      w.line(" * @returns {%s}", typeMapper.jsDocType(field));
      w.line(" */");
      w.block(
          getterName + "()",
          () -> {
            w.line("return this.%s;", jsName);
          });

      // Setter
      w.blankLine();
      w.line("/**");
      w.line(" * @param {%s} value", typeMapper.jsDocType(field));
      w.line(" */");
      w.block(
          setterName + "(value)",
          () -> {
            w.line("this.%s = value;", jsName);
            if (field.isProto3Optional()) {
              w.line("this._presentFields[%d] = true;", field.getArrayPosition());
            }
            if (field.isOneofMember()) {
              String caseProp = "_" + nameResolver.fieldName(field.getOneofName()) + "Case";
              w.line("this.%s = %d;", caseProp, field.getFieldNumber());
            }
          });
    }
  }

  protected void emitHasMethods(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.isProto3Optional() || field.getKind() == ProtoField.FieldKind.MESSAGE) {
        String hasName = "has" + JavaScriptNameResolver.snakeToPascal(field.getName());
        w.blankLine();
        w.line("/**");
        w.line(" * @returns {boolean}");
        w.line(" */");
        w.block(
            hasName + "()",
            () -> {
              if (field.isProto3Optional()) {
                w.line("return !!this._presentFields[%d];", field.getArrayPosition());
              } else {
                w.line("return this.%s != null;", nameResolver.fieldName(field.getName()));
              }
            });
      }
    }
  }

  /** Emit a JavaScript enum as a frozen const object with forward and reverse mapping. */
  protected void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    String enumName = protoEnum.getName();
    w.line("/**");
    w.line(" * @enum {number}");
    w.line(" */");
    w.line("const %s = Object.freeze({", enumName);
    w.indent();
    // Forward mapping: NAME -> number
    for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
      w.line("%s: %d,", nameResolver.enumConstantName(val.name()), val.number());
    }
    // Reverse mapping: number -> NAME (for lookup by value)
    for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
      w.line("%d: '%s',", val.number(), nameResolver.enumConstantName(val.name()));
    }
    w.dedent();
    w.line("});");
  }

  protected void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.line("/**");
    w.line(" * @returns {string}");
    w.line(" */");
    w.block(
        "toString()",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return '%s{}';", className);
            return;
          }
          StringBuilder sb = new StringBuilder();
          sb.append("return `").append(className).append("{");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String jsName = nameResolver.fieldName(field.getName());
            if (i > 0) sb.append(", ");
            sb.append(field.getName()).append("=${this.").append(jsName).append("}");
          }
          sb.append("}`;");
          w.line(sb.toString());
        });
  }

  /** Emit ES module export with the class and any nested types. */
  protected void emitExports(CodeWriter w, ProtoMessage message, String className) {
    StringBuilder exports = new StringBuilder();
    exports.append(className);

    for (ProtoEnum protoEnum : message.getEnums()) {
      exports.append(", ").append(protoEnum.getName());
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      exports.append(", ").append(nameResolver.messageClassName(nested.getName()));
    }

    w.line("export { %s };", exports.toString());
  }

  protected boolean hasOptionalFields(ProtoMessage message) {
    return message.getFields().stream().anyMatch(ProtoField::isProto3Optional);
  }

  /** Check if any field in the message (or nested messages) uses bytes type. */
  protected boolean messageHasBytesFields(ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES) {
        return true;
      }
      if (field.isMap() && field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
        return true;
      }
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      if (messageHasBytesFields(nested)) {
        return true;
      }
    }
    return false;
  }

  /** Emit file-level base64 encode/decode helper functions. */
  protected void emitBase64Helpers(CodeWriter w) {
    w.block(
        "function _base64Encode(bytes)",
        () -> {
          w.line("let binary = '';");
          w.line("for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);");
          w.line("if (typeof btoa === 'function') return btoa(binary);");
          w.line("if (typeof Buffer === 'function') return Buffer.from(bytes).toString('base64');");
          w.line("throw new Error('No base64 encoder available');");
        });
    w.blankLine();
    w.block(
        "function _base64Decode(str)",
        () -> {
          w.block(
              "if (typeof atob === 'function')",
              () -> {
                w.line("const binary = atob(str);");
                w.line("const bytes = new Uint8Array(binary.length);");
                w.line("for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);");
                w.line("return bytes;");
              });
          w.line(
              "if (typeof Buffer === 'function') return new Uint8Array(Buffer.from(str, 'base64'));");
          w.line("throw new Error('No base64 decoder available');");
        });
  }
}
