/*
 * Copyright 2024 protobuf-text-codecs contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.jsonarray.codegen;

import java.util.Set;

/**
 * Utility for escaping identifiers that collide with target-language keywords. Each language has a
 * set of reserved words; when a proto name (message, field, enum constant) maps to one of those
 * words, the escape function appends a suffix or wraps the name so the generated code compiles.
 */
public final class KeywordUtil {

  private KeywordUtil() {}

  private static final Set<String> JAVA_KEYWORDS =
      Set.of(
          "abstract",
          "assert",
          "boolean",
          "break",
          "byte",
          "case",
          "catch",
          "char",
          "class",
          "const",
          "continue",
          "default",
          "do",
          "double",
          "else",
          "enum",
          "extends",
          "final",
          "finally",
          "float",
          "for",
          "goto",
          "if",
          "implements",
          "import",
          "instanceof",
          "int",
          "interface",
          "long",
          "native",
          "new",
          "package",
          "private",
          "protected",
          "public",
          "return",
          "short",
          "static",
          "strictfp",
          "super",
          "switch",
          "synchronized",
          "this",
          "throw",
          "throws",
          "transient",
          "try",
          "void",
          "volatile",
          "while",
          "var",
          "yield",
          "record",
          "sealed",
          "permits");

  private static final Set<String> PYTHON_KEYWORDS =
      Set.of(
          "False",
          "None",
          "True",
          "and",
          "as",
          "assert",
          "async",
          "await",
          "break",
          "class",
          "continue",
          "def",
          "del",
          "elif",
          "else",
          "except",
          "finally",
          "for",
          "from",
          "global",
          "if",
          "import",
          "in",
          "is",
          "lambda",
          "nonlocal",
          "not",
          "or",
          "pass",
          "raise",
          "return",
          "try",
          "while",
          "with",
          "yield");

  private static final Set<String> JS_KEYWORDS =
      Set.of(
          "break",
          "case",
          "catch",
          "class",
          "const",
          "continue",
          "debugger",
          "default",
          "delete",
          "do",
          "else",
          "export",
          "extends",
          "finally",
          "for",
          "function",
          "if",
          "import",
          "in",
          "instanceof",
          "let",
          "new",
          "return",
          "super",
          "switch",
          "this",
          "throw",
          "try",
          "typeof",
          "var",
          "void",
          "while",
          "with",
          "yield",
          "enum",
          "await",
          "implements",
          "interface",
          "package",
          "private",
          "protected",
          "public",
          "static");

  private static final Set<String> C_KEYWORDS =
      Set.of(
          "auto",
          "break",
          "case",
          "char",
          "const",
          "continue",
          "default",
          "do",
          "double",
          "else",
          "enum",
          "extern",
          "float",
          "for",
          "goto",
          "if",
          "inline",
          "int",
          "long",
          "register",
          "restrict",
          "return",
          "short",
          "signed",
          "sizeof",
          "static",
          "struct",
          "switch",
          "typedef",
          "union",
          "unsigned",
          "void",
          "volatile",
          "while",
          "_Bool",
          "_Complex",
          "_Imaginary");

  private static final Set<String> CPP_KEYWORDS =
      Set.of(
          // C++ specific keywords
          "alignas",
          "alignof",
          "and",
          "and_eq",
          "asm",
          "bitand",
          "bitor",
          "bool",
          "catch",
          "char8_t",
          "char16_t",
          "char32_t",
          "class",
          "compl",
          "concept",
          "consteval",
          "constexpr",
          "constinit",
          "const_cast",
          "co_await",
          "co_return",
          "co_yield",
          "decltype",
          "delete",
          "dynamic_cast",
          "explicit",
          "export",
          "false",
          "friend",
          "mutable",
          "namespace",
          "new",
          "noexcept",
          "not",
          "not_eq",
          "nullptr",
          "operator",
          "or",
          "or_eq",
          "private",
          "protected",
          "public",
          "reinterpret_cast",
          "requires",
          "static_assert",
          "static_cast",
          "template",
          "this",
          "thread_local",
          "throw",
          "true",
          "try",
          "typeid",
          "typename",
          "using",
          "virtual",
          "wchar_t",
          "xor",
          "xor_eq",
          // C keywords (shared with C++)
          "auto",
          "break",
          "case",
          "char",
          "const",
          "continue",
          "default",
          "do",
          "double",
          "else",
          "enum",
          "extern",
          "float",
          "for",
          "goto",
          "if",
          "inline",
          "int",
          "long",
          "register",
          "return",
          "short",
          "signed",
          "sizeof",
          "static",
          "struct",
          "switch",
          "typedef",
          "union",
          "unsigned",
          "void",
          "volatile",
          "while");

  private static final Set<String> RUST_KEYWORDS =
      Set.of(
          "as",
          "break",
          "const",
          "continue",
          "crate",
          "else",
          "enum",
          "extern",
          "false",
          "fn",
          "for",
          "if",
          "impl",
          "in",
          "let",
          "loop",
          "match",
          "mod",
          "move",
          "mut",
          "pub",
          "ref",
          "return",
          "self",
          "Self",
          "static",
          "struct",
          "super",
          "trait",
          "true",
          "type",
          "unsafe",
          "use",
          "where",
          "while",
          "async",
          "await",
          "dyn",
          "abstract",
          "become",
          "box",
          "do",
          "final",
          "macro",
          "override",
          "priv",
          "typeof",
          "unsized",
          "virtual",
          "yield");

  private static final Set<String> GO_KEYWORDS =
      Set.of(
          "break",
          "case",
          "chan",
          "const",
          "continue",
          "default",
          "defer",
          "else",
          "fallthrough",
          "for",
          "func",
          "go",
          "goto",
          "if",
          "import",
          "interface",
          "map",
          "package",
          "range",
          "return",
          "select",
          "struct",
          "switch",
          "type",
          "var");

  private static final Set<String> PERL_KEYWORDS =
      Set.of(
          "__DATA__",
          "__END__",
          "__FILE__",
          "__LINE__",
          "__PACKAGE__",
          "and",
          "cmp",
          "continue",
          "CORE",
          "do",
          "else",
          "elsif",
          "eq",
          "exp",
          "for",
          "foreach",
          "ge",
          "goto",
          "gt",
          "if",
          "last",
          "le",
          "local",
          "lt",
          "my",
          "ne",
          "next",
          "no",
          "not",
          "or",
          "our",
          "package",
          "print",
          "redo",
          "require",
          "return",
          "say",
          "sub",
          "tr",
          "unless",
          "until",
          "use",
          "when",
          "while",
          "xor");

  private static final Set<String> ZIG_KEYWORDS =
      Set.of(
          "addrspace",
          "align",
          "allowzero",
          "and",
          "anyframe",
          "anytype",
          "asm",
          "async",
          "await",
          "break",
          "callconv",
          "catch",
          "comptime",
          "const",
          "continue",
          "defer",
          "else",
          "enum",
          "errdefer",
          "error",
          "export",
          "extern",
          "fn",
          "for",
          "if",
          "inline",
          "linksection",
          "noalias",
          "nosuspend",
          "null",
          "opaque",
          "or",
          "orelse",
          "packed",
          "pub",
          "resume",
          "return",
          "struct",
          "suspend",
          "switch",
          "test",
          "threadlocal",
          "try",
          "undefined",
          "union",
          "unreachable",
          "var",
          "volatile",
          "while");

  private static final Set<String> CSHARP_KEYWORDS =
      Set.of(
          "abstract",
          "as",
          "base",
          "bool",
          "break",
          "byte",
          "case",
          "catch",
          "char",
          "checked",
          "class",
          "const",
          "continue",
          "decimal",
          "default",
          "delegate",
          "do",
          "double",
          "else",
          "enum",
          "event",
          "explicit",
          "extern",
          "false",
          "finally",
          "fixed",
          "float",
          "for",
          "foreach",
          "goto",
          "if",
          "implicit",
          "in",
          "int",
          "interface",
          "internal",
          "is",
          "lock",
          "long",
          "namespace",
          "new",
          "null",
          "object",
          "operator",
          "out",
          "override",
          "params",
          "private",
          "protected",
          "public",
          "readonly",
          "ref",
          "return",
          "sbyte",
          "sealed",
          "short",
          "sizeof",
          "stackalloc",
          "static",
          "string",
          "struct",
          "switch",
          "this",
          "throw",
          "true",
          "try",
          "typeof",
          "uint",
          "ulong",
          "unchecked",
          "unsafe",
          "ushort",
          "using",
          "virtual",
          "void",
          "volatile",
          "while",
          "yield");

  private static final Set<String> DART_KEYWORDS =
      Set.of(
          "abstract",
          "as",
          "assert",
          "async",
          "await",
          "break",
          "case",
          "catch",
          "class",
          "const",
          "continue",
          "default",
          "deferred",
          "do",
          "dynamic",
          "else",
          "enum",
          "export",
          "extends",
          "extension",
          "external",
          "factory",
          "false",
          "final",
          "finally",
          "for",
          "function",
          "get",
          "hide",
          "if",
          "implements",
          "import",
          "in",
          "interface",
          "is",
          "late",
          "library",
          "mixin",
          "new",
          "null",
          "of",
          "on",
          "operator",
          "part",
          "required",
          "rethrow",
          "return",
          "sealed",
          "set",
          "show",
          "static",
          "super",
          "switch",
          "sync",
          "this",
          "throw",
          "true",
          "try",
          "typedef",
          "var",
          "void",
          "when",
          "while",
          "with",
          "yield");

  private static final Set<String> PHP_KEYWORDS =
      Set.of(
          "abstract",
          "and",
          "array",
          "as",
          "break",
          "callable",
          "case",
          "catch",
          "class",
          "clone",
          "const",
          "continue",
          "declare",
          "default",
          "die",
          "do",
          "echo",
          "else",
          "elseif",
          "empty",
          "enddeclare",
          "endfor",
          "endforeach",
          "endif",
          "endswitch",
          "endwhile",
          "eval",
          "exit",
          "extends",
          "final",
          "finally",
          "fn",
          "for",
          "foreach",
          "function",
          "global",
          "goto",
          "if",
          "implements",
          "include",
          "instanceof",
          "insteadof",
          "interface",
          "isset",
          "list",
          "match",
          "namespace",
          "new",
          "or",
          "print",
          "private",
          "protected",
          "public",
          "readonly",
          "require",
          "return",
          "static",
          "switch",
          "throw",
          "trait",
          "try",
          "unset",
          "use",
          "var",
          "while",
          "xor",
          "yield");

  private static final Set<String> RUBY_KEYWORDS =
      Set.of(
          "alias", "and", "begin", "break", "case", "class", "def", "do", "else", "elsif", "end",
          "ensure", "false", "for", "if", "in", "module", "next", "nil", "not", "or", "redo",
          "rescue", "retry", "return", "self", "super", "then", "true", "undef", "unless", "until",
          "when", "while", "yield");

  private static final Set<String> SWIFT_KEYWORDS =
      Set.of(
          "Any",
          "Protocol",
          "Self",
          "Type",
          "as",
          "associatedtype",
          "break",
          "case",
          "catch",
          "class",
          "continue",
          "default",
          "defer",
          "deinit",
          "do",
          "else",
          "enum",
          "extension",
          "fallthrough",
          "false",
          "fileprivate",
          "for",
          "func",
          "guard",
          "if",
          "import",
          "in",
          "init",
          "inout",
          "internal",
          "is",
          "let",
          "nil",
          "open",
          "operator",
          "private",
          "protocol",
          "public",
          "repeat",
          "rethrows",
          "return",
          "self",
          "static",
          "struct",
          "subscript",
          "super",
          "switch",
          "throw",
          "throws",
          "true",
          "try",
          "typealias",
          "var",
          "where",
          "while");

  /** Escape a Java identifier by appending underscore if it collides with a Java keyword. */
  public static String escapeJava(String name) {
    return JAVA_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a Python identifier by appending underscore if it collides with a Python keyword. */
  public static String escapePython(String name) {
    return PYTHON_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a JS/TS identifier by appending underscore if it collides with a JS keyword. */
  public static String escapeJs(String name) {
    return JS_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a C identifier by appending _pb if it collides with a C keyword. */
  public static String escapeC(String name) {
    return C_KEYWORDS.contains(name) ? name + "_pb" : name;
  }

  /** Escape a C++ identifier by appending _pb if it collides with a C++ keyword. */
  public static String escapeCpp(String name) {
    return CPP_KEYWORDS.contains(name) ? name + "_pb" : name;
  }

  /** Escape a Rust identifier using raw identifier syntax (r#keyword) if it is a keyword. */
  public static String escapeRust(String name) {
    return RUST_KEYWORDS.contains(name) ? "r#" + name : name;
  }

  /** Escape a Go identifier by appending underscore if it collides with a Go keyword. */
  public static String escapeGo(String name) {
    return GO_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a Perl identifier by appending underscore if it collides with a Perl keyword. */
  public static String escapePerl(String name) {
    return PERL_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a Zig identifier using quoted syntax (@"keyword") if it is a keyword. */
  public static String escapeZig(String name) {
    return ZIG_KEYWORDS.contains(name) ? "@\"" + name + "\"" : name;
  }

  /** Escape a C# identifier by prefixing with @ if it collides with a C# keyword. */
  public static String escapeCSharp(String name) {
    return CSHARP_KEYWORDS.contains(name) ? "@" + name : name;
  }

  /** Escape a Dart identifier by appending underscore if it collides with a Dart keyword. */
  public static String escapeDart(String name) {
    return DART_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a PHP identifier by appending underscore if it collides with a PHP keyword. */
  public static String escapePhp(String name) {
    return PHP_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a Ruby identifier by appending underscore if it collides with a Ruby keyword. */
  public static String escapeRuby(String name) {
    return RUBY_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a Swift identifier by backtick-quoting if it collides with a Swift keyword. */
  public static String escapeSwift(String name) {
    return SWIFT_KEYWORDS.contains(name) ? "`" + name + "`" : name;
  }

  private static final Set<String> KOTLIN_KEYWORDS =
      Set.of(
          "as",
          "break",
          "class",
          "continue",
          "do",
          "else",
          "false",
          "for",
          "fun",
          "if",
          "in",
          "interface",
          "is",
          "null",
          "object",
          "package",
          "return",
          "super",
          "this",
          "throw",
          "true",
          "try",
          "typealias",
          "typeof",
          "val",
          "var",
          "when",
          "while");

  /** Escape a Kotlin identifier using backtick syntax if it collides with a hard keyword. */
  public static String escapeKotlin(String name) {
    return KOTLIN_KEYWORDS.contains(name) ? "`" + name + "`" : name;
  }

  private static final Set<String> OBJC_KEYWORDS =
      Set.of(
          "auto",
          "break",
          "case",
          "char",
          "const",
          "continue",
          "default",
          "do",
          "double",
          "else",
          "enum",
          "extern",
          "float",
          "for",
          "goto",
          "if",
          "int",
          "long",
          "register",
          "return",
          "short",
          "signed",
          "sizeof",
          "static",
          "struct",
          "switch",
          "typedef",
          "union",
          "unsigned",
          "void",
          "volatile",
          "while",
          "id",
          "self",
          "super",
          "nil",
          "Nil",
          "YES",
          "NO",
          "TRUE",
          "FALSE",
          "BOOL",
          "Class",
          "SEL",
          "IMP",
          "Protocol",
          "NSObject",
          "NSString",
          "NSArray",
          "NSDictionary",
          "NSNumber",
          "NSData",
          "NSNull",
          "NSError",
          "description",
          "hash",
          "init",
          "new",
          "copy",
          "mutableCopy",
          "dealloc",
          "class",
          "retain",
          "release",
          "autorelease");

  /** Escape an Objective-C identifier by appending _pb if it collides with a keyword. */
  public static String escapeObjC(String name) {
    return OBJC_KEYWORDS.contains(name) ? name + "_pb" : name;
  }
}
