package dev.protocgen.textcodecs.jsonarray.codegen;

import java.util.Set;

/**
 * Utility for escaping identifiers that collide with target-language keywords. Each language has a
 * set of reserved words; when a proto name (message, field, enum constant) maps to one of those
 * words, the escape function appends a suffix or wraps the name so the generated code compiles.
 */
public final class KeywordUtil {

  private KeywordUtil() {}

  private static final Set<String> JAVA_KEYWORDS =
      Set.of(
          "abstract",
          "assert",
          "boolean",
          "break",
          "byte",
          "case",
          "catch",
          "char",
          "class",
          "const",
          "continue",
          "default",
          "do",
          "double",
          "else",
          "enum",
          "extends",
          "final",
          "finally",
          "float",
          "for",
          "goto",
          "if",
          "implements",
          "import",
          "instanceof",
          "int",
          "interface",
          "long",
          "native",
          "new",
          "package",
          "private",
          "protected",
          "public",
          "return",
          "short",
          "static",
          "strictfp",
          "super",
          "switch",
          "synchronized",
          "this",
          "throw",
          "throws",
          "transient",
          "try",
          "void",
          "volatile",
          "while",
          "var",
          "yield",
          "record",
          "sealed",
          "permits");

  private static final Set<String> PYTHON_KEYWORDS =
      Set.of(
          "False",
          "None",
          "True",
          "and",
          "as",
          "assert",
          "async",
          "await",
          "break",
          "class",
          "continue",
          "def",
          "del",
          "elif",
          "else",
          "except",
          "finally",
          "for",
          "from",
          "global",
          "if",
          "import",
          "in",
          "is",
          "lambda",
          "nonlocal",
          "not",
          "or",
          "pass",
          "raise",
          "return",
          "try",
          "while",
          "with",
          "yield");

  private static final Set<String> JS_KEYWORDS =
      Set.of(
          "break",
          "case",
          "catch",
          "class",
          "const",
          "continue",
          "debugger",
          "default",
          "delete",
          "do",
          "else",
          "export",
          "extends",
          "finally",
          "for",
          "function",
          "if",
          "import",
          "in",
          "instanceof",
          "let",
          "new",
          "return",
          "super",
          "switch",
          "this",
          "throw",
          "try",
          "typeof",
          "var",
          "void",
          "while",
          "with",
          "yield",
          "enum",
          "await",
          "implements",
          "interface",
          "package",
          "private",
          "protected",
          "public",
          "static");

  private static final Set<String> C_KEYWORDS =
      Set.of(
          "auto",
          "break",
          "case",
          "char",
          "const",
          "continue",
          "default",
          "do",
          "double",
          "else",
          "enum",
          "extern",
          "float",
          "for",
          "goto",
          "if",
          "inline",
          "int",
          "long",
          "register",
          "restrict",
          "return",
          "short",
          "signed",
          "sizeof",
          "static",
          "struct",
          "switch",
          "typedef",
          "union",
          "unsigned",
          "void",
          "volatile",
          "while",
          "_Bool",
          "_Complex",
          "_Imaginary");

  private static final Set<String> CPP_KEYWORDS =
      Set.of(
          // C++ specific keywords
          "alignas",
          "alignof",
          "and",
          "and_eq",
          "asm",
          "bitand",
          "bitor",
          "bool",
          "catch",
          "char8_t",
          "char16_t",
          "char32_t",
          "class",
          "compl",
          "concept",
          "consteval",
          "constexpr",
          "constinit",
          "const_cast",
          "co_await",
          "co_return",
          "co_yield",
          "decltype",
          "delete",
          "dynamic_cast",
          "explicit",
          "export",
          "false",
          "friend",
          "mutable",
          "namespace",
          "new",
          "noexcept",
          "not",
          "not_eq",
          "nullptr",
          "operator",
          "or",
          "or_eq",
          "private",
          "protected",
          "public",
          "reinterpret_cast",
          "requires",
          "static_assert",
          "static_cast",
          "template",
          "this",
          "thread_local",
          "throw",
          "true",
          "try",
          "typeid",
          "typename",
          "using",
          "virtual",
          "wchar_t",
          "xor",
          "xor_eq",
          // C keywords (shared with C++)
          "auto",
          "break",
          "case",
          "char",
          "const",
          "continue",
          "default",
          "do",
          "double",
          "else",
          "enum",
          "extern",
          "float",
          "for",
          "goto",
          "if",
          "inline",
          "int",
          "long",
          "register",
          "return",
          "short",
          "signed",
          "sizeof",
          "static",
          "struct",
          "switch",
          "typedef",
          "union",
          "unsigned",
          "void",
          "volatile",
          "while");

  private static final Set<String> RUST_KEYWORDS =
      Set.of(
          "as",
          "break",
          "const",
          "continue",
          "crate",
          "else",
          "enum",
          "extern",
          "false",
          "fn",
          "for",
          "if",
          "impl",
          "in",
          "let",
          "loop",
          "match",
          "mod",
          "move",
          "mut",
          "pub",
          "ref",
          "return",
          "self",
          "Self",
          "static",
          "struct",
          "super",
          "trait",
          "true",
          "type",
          "unsafe",
          "use",
          "where",
          "while",
          "async",
          "await",
          "dyn",
          "abstract",
          "become",
          "box",
          "do",
          "final",
          "macro",
          "override",
          "priv",
          "typeof",
          "unsized",
          "virtual",
          "yield");

  private static final Set<String> GO_KEYWORDS =
      Set.of(
          "break",
          "case",
          "chan",
          "const",
          "continue",
          "default",
          "defer",
          "else",
          "fallthrough",
          "for",
          "func",
          "go",
          "goto",
          "if",
          "import",
          "interface",
          "map",
          "package",
          "range",
          "return",
          "select",
          "struct",
          "switch",
          "type",
          "var");

  private static final Set<String> ZIG_KEYWORDS =
      Set.of(
          "addrspace",
          "align",
          "allowzero",
          "and",
          "anyframe",
          "anytype",
          "asm",
          "async",
          "await",
          "break",
          "callconv",
          "catch",
          "comptime",
          "const",
          "continue",
          "defer",
          "else",
          "enum",
          "errdefer",
          "error",
          "export",
          "extern",
          "fn",
          "for",
          "if",
          "inline",
          "linksection",
          "noalias",
          "nosuspend",
          "null",
          "opaque",
          "or",
          "orelse",
          "packed",
          "pub",
          "resume",
          "return",
          "struct",
          "suspend",
          "switch",
          "test",
          "threadlocal",
          "try",
          "undefined",
          "union",
          "unreachable",
          "var",
          "volatile",
          "while");

  /** Escape a Java identifier by appending underscore if it collides with a Java keyword. */
  public static String escapeJava(String name) {
    return JAVA_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a Python identifier by appending underscore if it collides with a Python keyword. */
  public static String escapePython(String name) {
    return PYTHON_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a JS/TS identifier by appending underscore if it collides with a JS keyword. */
  public static String escapeJs(String name) {
    return JS_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a C identifier by appending _pb if it collides with a C keyword. */
  public static String escapeC(String name) {
    return C_KEYWORDS.contains(name) ? name + "_pb" : name;
  }

  /** Escape a C++ identifier by appending _pb if it collides with a C++ keyword. */
  public static String escapeCpp(String name) {
    return CPP_KEYWORDS.contains(name) ? name + "_pb" : name;
  }

  /** Escape a Rust identifier using raw identifier syntax (r#keyword) if it is a keyword. */
  public static String escapeRust(String name) {
    return RUST_KEYWORDS.contains(name) ? "r#" + name : name;
  }

  /** Escape a Go identifier by appending underscore if it collides with a Go keyword. */
  public static String escapeGo(String name) {
    return GO_KEYWORDS.contains(name) ? name + "_" : name;
  }

  /** Escape a Zig identifier using quoted syntax (@"keyword") if it is a keyword. */
  public static String escapeZig(String name) {
    return ZIG_KEYWORDS.contains(name) ? "@\"" + name + "\"" : name;
  }
}
