// Generated by protoc-gen-pbtkurl. DO NOT EDIT.
// Source: address.proto

class Address {
  street: string;
  city: string;
  state: string;
  zip: number;

  constructor() {
    this.street = "";
    this.city = "";
    this.state = "";
    this.zip = 0;
  }

  getStreet(): string {
    return this.street;
  }

  setStreet(value: string): void {
    this.street = value;
  }

  getCity(): string {
    return this.city;
  }

  setCity(value: string): void {
    this.city = value;
  }

  getState(): string {
    return this.state;
  }

  setState(value: string): void {
    this.state = value;
  }

  getZip(): number {
    return this.zip;
  }

  setZip(value: number): void {
    this.zip = value;
  }

  private _countPbtkFields(): number {
    let count: number = 0;
    count++;
    count++;
    count++;
    count++;
    return count;
  }

  private _appendPbtkFields(parts: string[]): void {
    parts.push('!1s' + encodeURIComponent(this.street));
    parts.push('!2s' + encodeURIComponent(this.city));
    parts.push('!3s' + encodeURIComponent(this.state));
    parts.push('!4i' + this.zip);
  }

  encode(): Uint8Array {
    const parts: string[] = [];
    this._appendPbtkFields(parts);
    return new TextEncoder().encode(parts.join(''));
  }

  private static _parsePbtkTokens(tokens: string[], fieldCount: number, offset: {v: number}): Address {
    const obj = new Address();
    let consumed: number = 0;
    while (consumed < fieldCount && offset.v < tokens.length) {
      const token: string = tokens[offset.v];
      let numEnd: number = 0;
      while (numEnd < token.length && token.charCodeAt(numEnd) >= 48 && token.charCodeAt(numEnd) <= 57) numEnd++;
      if (numEnd === 0 || numEnd >= token.length) { offset.v++; consumed++; continue; }
      const fieldNum: number = parseInt(token.substring(0, numEnd), 10);
      const value: string = token.substring(numEnd + 1);

      switch (fieldNum) {
        case 1: {
          obj.setStreet(decodeURIComponent(value));
          offset.v++;
          consumed++;
          break;
        }
        case 2: {
          obj.setCity(decodeURIComponent(value));
          offset.v++;
          consumed++;
          break;
        }
        case 3: {
          obj.setState(decodeURIComponent(value));
          offset.v++;
          consumed++;
          break;
        }
        case 4: {
          obj.setZip(parseInt(value, 10));
          offset.v++;
          consumed++;
          break;
        }
        default: offset.v++; consumed++; break;
      }
    }
    return obj;
  }

  static decode(data: Uint8Array): Address {
    const input: string = new TextDecoder().decode(data);
    if (input == null || input.length === 0) return new Address();
    const tokens: string[] = Address._tokenizePbtk(input);
    const offset: {v: number} = {v: 0};
    return Address._parsePbtkTokens(tokens, tokens.length, offset);
  }

  private static _tokenizePbtk(input: string): string[] {
    const tokens: string[] = [];
    let i: number = input.charAt(0) === '!' ? 1 : 0;
    while (i < input.length) {
      const next: number = input.indexOf('!', i);
      if (next < 0) {
        tokens.push(input.substring(i));
        break;
      }
      tokens.push(input.substring(i, next));
      i = next + 1;
    }
    return tokens;
  }

  toString(): string {
    return `Address{street=${this.street}, city=${this.city}, state=${this.state}, zip=${this.zip}}`;
  }
}

export { Address };
