/*
 * Copyright 2026 protobuf-text-codecs contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.jsonarray.codegen.objc;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Generates complete Objective-C source files (.h and .m) for proto messages and enums. Each
 * message produces two files: a header with @interface and a source with @implementation.
 *
 * <p>Uses Foundation framework (NSJSONSerialization, NSArray, NSDictionary) for JSON handling. Uses
 * ARC (Automatic Reference Counting) -- no manual retain/release.
 */
public class ObjCCodeEmitter {

  private final ObjCTypeMapper typeMapper;
  private final ObjCNameResolver nameResolver;
  private final ObjCSerializerGenerator serializerGen;
  private final ObjCDeserializerGenerator deserializerGen;

  public ObjCCodeEmitter(ObjCTypeMapper typeMapper, ObjCNameResolver nameResolver) {
    this.typeMapper = typeMapper;
    this.nameResolver = nameResolver;
    this.serializerGen = new ObjCSerializerGenerator(typeMapper, nameResolver);
    this.deserializerGen = new ObjCDeserializerGenerator(typeMapper, nameResolver);
  }

  // ========================================================================
  // Header file (.h) generation
  // ========================================================================

  /** Generate the .h header file for a message. */
  public String emitHeader(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String className = nameResolver.qualifiedClassName(file, message.getName());

    w.line("// @generated by protoc-gen-jsonarray -- do not edit.");
    w.blankLine();
    w.line("#import <Foundation/Foundation.h>");
    w.blankLine();

    // Import headers for cross-file referenced types
    emitCrossFileImports(w, message, file);

    // Forward declarations for message types
    emitForwardDeclarations(w, message, file);

    w.line("NS_ASSUME_NONNULL_BEGIN");
    w.blankLine();

    // Nested enums (as C enums with typedef)
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnumDef(w, protoEnum, file, message.getName() + "_");
    }

    // Nested message forward declarations
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedClass =
          nameResolver.qualifiedClassName(file, message.getName() + "_" + nested.getName());
      w.line("@class %s;", nestedClass);
    }
    if (!message.getNestedMessages().isEmpty()) {
      w.blankLine();
    }

    // Main @interface
    w.line("@interface %s : NSObject", className);
    w.blankLine();

    // Properties
    for (ProtoField field : message.getFields()) {
      if (field.isOneofMember()) {
        continue; // handled as part of oneof group
      }
      emitPropertyDecl(w, field);
    }

    // Oneof properties
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      emitOneofPropertyDecls(w, group, file);
    }

    // Proto3 optional presence tracking
    for (ProtoField field : message.getFields()) {
      if (field.isProto3Optional() && !field.isOneofMember()) {
        String propName = nameResolver.fieldName(field.getName());
        w.line("@property (nonatomic, assign) BOOL has%s;", capitalize(propName));
      }
    }

    w.blankLine();

    // Serialization methods
    serializerGen.generateDeclarations(w, className);
    w.blankLine();

    // Deserialization methods
    deserializerGen.generateDeclarations(w, className);

    w.blankLine();
    w.line("@end");
    w.blankLine();

    // Nested message interfaces
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedClassName =
          nameResolver.qualifiedClassName(file, message.getName() + "_" + nested.getName());
      emitNestedMessageHeader(w, nested, file, nestedClassName, message.getName() + "_");
    }

    w.line("NS_ASSUME_NONNULL_END");

    return w.toString();
  }

  /** Generate the .h header file for a top-level enum. */
  public String emitTopLevelEnumHeader(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter();

    w.line("// @generated by protoc-gen-jsonarray -- do not edit.");
    w.blankLine();
    w.line("#import <Foundation/Foundation.h>");
    w.blankLine();
    w.line("NS_ASSUME_NONNULL_BEGIN");
    w.blankLine();

    emitEnumDef(w, protoEnum, file, "");

    w.line("NS_ASSUME_NONNULL_END");

    return w.toString();
  }

  // ========================================================================
  // Source file (.m) generation
  // ========================================================================

  /** Generate the .m implementation file for a message. */
  public String emitSource(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String className = nameResolver.qualifiedClassName(file, message.getName());

    w.line("// @generated by protoc-gen-jsonarray -- do not edit.");
    w.blankLine();

    // Import own header
    w.line("#import \"%s.h\"", className);
    w.line("#import <math.h>");
    w.blankLine();

    // Nested message implementations first
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedClassName =
          nameResolver.qualifiedClassName(file, message.getName() + "_" + nested.getName());
      emitNestedMessageSource(w, nested, file, nestedClassName, message.getName() + "_");
    }

    // Main @implementation
    w.line("@implementation %s", className);

    // Serialize
    serializerGen.generate(w, message, className);

    // Deserialize
    deserializerGen.generate(w, message, className);

    w.blankLine();
    w.line("@end");

    return w.toString();
  }

  // ========================================================================
  // Private helpers
  // ========================================================================

  private void emitForwardDeclarations(CodeWriter w, ProtoMessage message, ProtoFile file) {
    Set<String> forwardDecls = new LinkedHashSet<>();
    collectForwardDeclarations(message, file, forwardDecls);
    for (String decl : forwardDecls) {
      w.line(decl);
    }
    if (!forwardDecls.isEmpty()) {
      w.blankLine();
    }
  }

  private void collectForwardDeclarations(
      ProtoMessage message, ProtoFile file, Set<String> forwardDecls) {
    for (ProtoField field : message.getFields()) {
      collectTypeForwardDecl(field.getTypeReference(), field, message, file, forwardDecls);
      if (field.isMap() && field.getMapValueTypeReference() != null) {
        collectMapValueForwardDecl(field.getMapValueTypeReference(), field, file, forwardDecls);
      }
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      collectForwardDeclarations(nested, file, forwardDecls);
    }
  }

  private void collectTypeForwardDecl(
      String typeRef,
      ProtoField field,
      ProtoMessage message,
      ProtoFile file,
      Set<String> forwardDecls) {
    if (typeRef == null) return;
    if (field != null && field.isWellKnownType()) return;
    if (field != null
        && field.getKind() != ProtoField.FieldKind.MESSAGE
        && field.getKind() != ProtoField.FieldKind.WELL_KNOWN_TYPE) return;

    // Check if nested
    for (ProtoMessage nested : message.getNestedMessages()) {
      if (typeRef.equals(message.getFullName() + "." + nested.getName())) {
        return;
      }
    }

    String objcType = nameResolver.resolveTypeReference(typeRef, file);
    forwardDecls.add("@class " + objcType + ";");
  }

  private void collectMapValueForwardDecl(
      String typeRef, ProtoField field, ProtoFile file, Set<String> forwardDecls) {
    if (typeRef == null) return;
    if (field.getMapValueType() != FieldDescriptorProto.Type.TYPE_MESSAGE) return;

    String objcType = nameResolver.resolveTypeReference(typeRef, file);
    forwardDecls.add("@class " + objcType + ";");
  }

  private void emitCrossFileImports(CodeWriter w, ProtoMessage message, ProtoFile file) {
    Set<String> imports = new LinkedHashSet<>();
    collectCrossFileImports(message, file, imports);
    for (String imp : imports) {
      w.line(imp);
    }
    if (!imports.isEmpty()) {
      w.blankLine();
    }
  }

  private void collectCrossFileImports(ProtoMessage message, ProtoFile file, Set<String> imports) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      collectTypeImport(field.getTypeReference(), field, message, file, currentPrefix, imports);
      if (field.isMap() && field.getMapValueTypeReference() != null) {
        collectTypeImport(
            field.getMapValueTypeReference(), null, message, file, currentPrefix, imports);
      }
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      collectCrossFileImports(nested, file, imports);
    }
  }

  private void collectTypeImport(
      String typeRef,
      ProtoField field,
      ProtoMessage message,
      ProtoFile file,
      String currentPrefix,
      Set<String> imports) {
    if (typeRef == null) return;
    if (field != null && field.isWellKnownType()) return;

    // Check if nested
    for (ProtoMessage nested : message.getNestedMessages()) {
      if (typeRef.equals(message.getFullName() + "." + nested.getName())) {
        return;
      }
    }

    if (typeRef.startsWith(currentPrefix)) {
      String simpleName = typeRef.substring(typeRef.lastIndexOf('.') + 1);
      if (simpleName.equals(message.getName())) return;

      String className = nameResolver.resolveTypeReference(typeRef, file);
      imports.add("#import \"" + className + ".h\"");
    }
  }

  private void emitEnumDef(CodeWriter w, ProtoEnum protoEnum, ProtoFile file, String parentPrefix) {
    String prefix = nameResolver.classPrefix(file);
    String enumTypeName = prefix + parentPrefix + protoEnum.getName();

    w.line("typedef NS_ENUM(NSInteger, %s) {", enumTypeName);
    w.indent();
    for (int i = 0; i < protoEnum.getValues().size(); i++) {
      ProtoEnum.EnumValue val = protoEnum.getValues().get(i);
      String constName = enumTypeName + val.name();
      String suffix = i < protoEnum.getValues().size() - 1 ? "," : "";
      w.line("%s = %d%s", constName, val.number(), suffix);
    }
    w.dedent();
    w.line("};");
    w.blankLine();
  }

  private void emitPropertyDecl(CodeWriter w, ProtoField field) {
    String propName = nameResolver.fieldName(field.getName());
    String attrs = typeMapper.propertyAttributes(field);
    boolean isObj = typeMapper.isObjectType(field);

    if (field.isMap()) {
      String keyType = typeMapper.mapKeyObjCType(field.getMapKeyType());
      String valType = typeMapper.mapValueObjCType(field);
      if (isObj && (field.isProto3Optional() || !field.isRequired())) {
        w.line(
            "@property (%s, nullable) NSMutableDictionary<%s, %s> *%s;",
            attrs, keyType, valType, propName);
      } else {
        w.line(
            "@property (%s) NSMutableDictionary<%s, %s> *%s;", attrs, keyType, valType, propName);
      }
    } else if (field.isRepeated()) {
      String elemType = typeMapper.elementType(field);
      if (isObj && (field.isProto3Optional() || !field.isRequired())) {
        w.line("@property (%s, nullable) NSMutableArray<%s> *%s;", attrs, elemType, propName);
      } else {
        w.line("@property (%s) NSMutableArray<%s> *%s;", attrs, elemType, propName);
      }
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      String refType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
      w.line("@property (%s, nullable) %s *%s;", attrs, refType, propName);
    } else if (isObj && (field.isProto3Optional() || !field.isRequired())) {
      w.line(
          "@property (%s, nullable) %s%s;",
          attrs, typeMapper.scalarType(field.getProtoType()), propName);
    } else {
      String type = typeMapper.scalarType(field.getProtoType());
      if (type.endsWith("*")) {
        w.line("@property (%s) %s%s;", attrs, type, propName);
      } else {
        w.line("@property (%s) %s %s;", attrs, type, propName);
      }
    }
  }

  private void emitOneofPropertyDecls(CodeWriter w, ProtoMessage.OneofGroup group, ProtoFile file) {
    // For Objective-C, we generate individual properties for each oneof member
    // plus a case tracking property
    for (ProtoField member : group.members()) {
      emitPropertyDecl(w, member);
    }
  }

  private void emitNestedMessageHeader(
      CodeWriter w, ProtoMessage nested, ProtoFile file, String className, String parentPrefix) {
    // Nested enums
    for (ProtoEnum protoEnum : nested.getEnums()) {
      emitEnumDef(w, protoEnum, file, parentPrefix + nested.getName() + "_");
    }

    w.line("@interface %s : NSObject", className);
    w.blankLine();

    // Properties
    for (ProtoField field : nested.getFields()) {
      if (field.isOneofMember()) continue;
      emitPropertyDecl(w, field);
    }

    for (ProtoMessage.OneofGroup group : nested.getOneofGroups()) {
      emitOneofPropertyDecls(w, group, file);
    }

    for (ProtoField field : nested.getFields()) {
      if (field.isProto3Optional() && !field.isOneofMember()) {
        String propName = nameResolver.fieldName(field.getName());
        w.line("@property (nonatomic, assign) BOOL has%s;", capitalize(propName));
      }
    }

    w.blankLine();

    // Serialization/deserialization declarations
    serializerGen.generateDeclarations(w, className);
    w.blankLine();
    deserializerGen.generateDeclarations(w, className);

    w.blankLine();
    w.line("@end");
    w.blankLine();

    // Recursively handle deeper nesting
    for (ProtoMessage deepNested : nested.getNestedMessages()) {
      String deepClassName =
          nameResolver.qualifiedClassName(
              file, parentPrefix + nested.getName() + "_" + deepNested.getName());
      emitNestedMessageHeader(
          w, deepNested, file, deepClassName, parentPrefix + nested.getName() + "_");
    }
  }

  private void emitNestedMessageSource(
      CodeWriter w, ProtoMessage nested, ProtoFile file, String className, String parentPrefix) {
    // Recursively emit deeper nested messages first
    for (ProtoMessage deepNested : nested.getNestedMessages()) {
      String deepClassName =
          nameResolver.qualifiedClassName(
              file, parentPrefix + nested.getName() + "_" + deepNested.getName());
      emitNestedMessageSource(
          w, deepNested, file, deepClassName, parentPrefix + nested.getName() + "_");
    }

    w.line("@implementation %s", className);

    serializerGen.generate(w, nested, className);
    deserializerGen.generate(w, nested, className);

    w.blankLine();
    w.line("@end");
    w.blankLine();
  }

  private static String capitalize(String s) {
    if (s == null || s.isEmpty()) return s;
    return Character.toUpperCase(s.charAt(0)) + s.substring(1);
  }
}
