/*
 * Copyright 2026 coffeeandwork
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.pbtkurl.codegen.typescript;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.LanguageGenerator;
import dev.protocgen.textcodecs.jsonarray.codegen.ProtoTypeUtil;
import dev.protocgen.textcodecs.jsonarray.codegen.javascript.JavaScriptNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.typescript.TypeScriptNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.typescript.TypeScriptTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import dev.protocgen.textcodecs.jsonarray.model.TypeRegistry;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * TypeScript language code generator for pbtk URL encoding. Produces TypeScript source files with
 * typed toPbtkUrl()/fromPbtkUrl() serialization using the {@code !<fieldNumber><typeChar><value>}
 * format.
 */
public class PbtkTypeScriptGenerator implements LanguageGenerator {

  private final TypeScriptNameResolver nameResolver = new TypeScriptNameResolver();
  private final TypeScriptTypeMapper typeMapper = new TypeScriptTypeMapper();

  @Override
  public List<CodeGeneratorResponse.File> generate(ProtoFile file, TypeRegistry registry) {
    List<CodeGeneratorResponse.File> result = new ArrayList<>();

    for (ProtoMessage message : file.getMessages()) {
      nameResolver.validateFieldNames(message.getFields());
      String sourceCode = emitMessage(message, file);
      String outputPath = nameResolver.outputFilePath(file, message.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    for (ProtoEnum protoEnum : file.getEnums()) {
      String sourceCode = emitTopLevelEnum(protoEnum, file);
      String outputPath = nameResolver.outputFilePath(file, protoEnum.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    return result;
  }

  // ---------------------------------------------------------------------------
  // File-level emission
  // ---------------------------------------------------------------------------

  private String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    String className = nameResolver.messageClassName(message.getName());

    emitFileHeader(w, file);

    Set<String> importNames = new LinkedHashSet<>();
    collectReferencedTypeNames(message, file, importNames);
    List<String> lazyImportNames = List.copyOf(importNames);

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
      w.blankLine();
    }

    // Nested messages
    for (ProtoMessage nested : message.getNestedMessages()) {
      emitMessageClass(w, nested, file, List.of());
      w.blankLine();
    }

    // Main class
    emitMessageClass(w, message, file, lazyImportNames);

    // Exports
    w.blankLine();
    emitExports(w, message, className);

    return w.toString();
  }

  private String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    emitFileHeader(w, file);
    emitEnum(w, protoEnum);
    w.blankLine();
    w.line("export { %s };", protoEnum.getName());
    return w.toString();
  }

  private void emitFileHeader(CodeWriter w, ProtoFile file) {
    w.line("// Generated by protoc-gen-pbtkurl. DO NOT EDIT.");
    w.line("// Source: %s", file.getFileName());
    w.blankLine();
  }

  // ---------------------------------------------------------------------------
  // Class emission
  // ---------------------------------------------------------------------------

  private void emitMessageClass(
      CodeWriter w, ProtoMessage message, ProtoFile file, List<String> lazyImportNames) {
    String className = nameResolver.messageClassName(message.getName());

    w.block(
        "class " + className,
        () -> {
          // Typed field declarations
          emitFieldDeclarations(w, message);

          emitConstructor(w, message);
          emitGettersSetters(w, message);
          emitHasMethods(w, message);
          emitToPbtkUrl(w, message);
          emitFromPbtkUrl(w, message, className, lazyImportNames);
          emitToString(w, message, className);
        });
  }

  // ---------------------------------------------------------------------------
  // Field declarations (TypeScript-specific)
  // ---------------------------------------------------------------------------

  private void emitFieldDeclarations(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String jsName = nameResolver.fieldName(field.getName());
      String tsType = typeMapper.nullableType(field);
      w.line("%s: %s;", jsName, tsType);
    }

    if (hasOptionalFields(message)) {
      w.line("private _presentFields: Record<number, boolean>;");
    }

    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String caseProp = "_" + nameResolver.fieldName(group.name()) + "Case";
      w.line("private %s: number;", caseProp);
    }

    w.blankLine();
  }

  // ---------------------------------------------------------------------------
  // Constructor
  // ---------------------------------------------------------------------------

  private void emitConstructor(CodeWriter w, ProtoMessage message) {
    w.block(
        "constructor()",
        () -> {
          for (ProtoField field : message.getFields()) {
            String jsName = nameResolver.fieldName(field.getName());
            String defaultVal = typeMapper.defaultValue(field);
            w.line("this.%s = %s;", jsName, defaultVal);
          }

          if (hasOptionalFields(message)) {
            w.line("this._presentFields = {};");
          }

          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            String caseProp = "_" + nameResolver.fieldName(group.name()) + "Case";
            w.line("this.%s = 0;", caseProp);
          }
        });
  }

  // ---------------------------------------------------------------------------
  // Getters / Setters / Has
  // ---------------------------------------------------------------------------

  private void emitGettersSetters(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String jsName = nameResolver.fieldName(field.getName());
      String getterName = nameResolver.getterName(field.getName());
      String setterName = nameResolver.setterName(field.getName());
      String tsType = typeMapper.nullableType(field);

      w.blankLine();
      w.block(getterName + "(): " + tsType, () -> w.line("return this.%s;", jsName));

      w.blankLine();
      w.block(
          setterName + "(value: " + tsType + "): void",
          () -> {
            w.line("this.%s = value;", jsName);
            if (field.isProto3Optional()) {
              w.line("this._presentFields[%d] = true;", field.getArrayPosition());
            }
            if (field.isOneofMember()) {
              String caseProp = "_" + nameResolver.fieldName(field.getOneofName()) + "Case";
              w.line("this.%s = %d;", caseProp, field.getFieldNumber());
            }
          });
    }
  }

  private void emitHasMethods(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.isProto3Optional() || field.getKind() == ProtoField.FieldKind.MESSAGE) {
        String hasName = "has" + JavaScriptNameResolver.snakeToPascal(field.getName());
        w.blankLine();
        w.block(
            hasName + "(): boolean",
            () -> {
              if (field.isProto3Optional()) {
                w.line("return !!this._presentFields[%d];", field.getArrayPosition());
              } else {
                w.line("return this.%s != null;", nameResolver.fieldName(field.getName()));
              }
            });
      }
    }
  }

  // ---------------------------------------------------------------------------
  // toPbtkUrl() — serialization
  // ---------------------------------------------------------------------------

  private void emitToPbtkUrl(CodeWriter w, ProtoMessage message) {
    // _countPbtkFields()
    w.blankLine();
    w.block(
        "private _countPbtkFields(): number",
        () -> {
          w.line("let count: number = 0;");
          for (ProtoField field : message.getFields()) {
            emitFieldCount(w, field);
          }
          w.line("return count;");
        });

    // _appendPbtkFields(parts)
    w.blankLine();
    w.block(
        "private _appendPbtkFields(parts: string[]): void",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldSerialize(w, field);
          }
        });

    // toPbtkUrl() — public method
    w.blankLine();
    w.block(
        "toPbtkUrl(): string",
        () -> {
          w.line("const parts: string[] = [];");
          w.line("this._appendPbtkFields(parts);");
          w.line("return parts.join('');");
        });
  }

  private void emitFieldCount(CodeWriter w, ProtoField field) {
    String jsField = "this." + nameResolver.fieldName(field.getName());

    if (field.isOneofMember()) {
      String caseProp = "this._" + nameResolver.fieldName(field.getOneofName()) + "Case";
      w.line("if (%s === %d) count++;", caseProp, field.getFieldNumber());
      return;
    }

    if (field.isMap()) {
      w.line("count += Object.keys(%s).length;", jsField);
    } else if (field.isRepeated()) {
      w.line("count += %s.length;", jsField);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      w.line("if (%s != null) count++;", jsField);
    } else if (field.isProto3Optional()) {
      w.line("if (this._presentFields[%d]) count++;", field.getArrayPosition());
    } else {
      w.line("count++;");
    }
  }

  private void emitFieldSerialize(CodeWriter w, ProtoField field) {
    String jsField = "this." + nameResolver.fieldName(field.getName());
    int fieldNum = field.getFieldNumber();

    if (field.isOneofMember()) {
      String caseProp = "this._" + nameResolver.fieldName(field.getOneofName()) + "Case";
      w.block(
          "if (" + caseProp + " === " + field.getFieldNumber() + ")",
          () -> emitSingleFieldSerialize(w, field, jsField, fieldNum));
      return;
    }

    if (field.isMap()) {
      emitMapSerialize(w, field, jsField, fieldNum);
    } else if (field.isRepeated()) {
      emitRepeatedSerialize(w, field, jsField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      emitMessageSerialize(w, field, jsField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, jsField, fieldNum);
    } else {
      emitScalarSerialize(w, field, jsField, fieldNum);
    }
  }

  private void emitSingleFieldSerialize(
      CodeWriter w, ProtoField field, String jsField, int fieldNum) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      emitMessageSerialize(w, field, jsField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, jsField, fieldNum);
    } else {
      emitScalarSerialize(w, field, jsField, fieldNum);
    }
  }

  private void emitScalarSerialize(CodeWriter w, ProtoField field, String jsField, int fieldNum) {
    if (field.isProto3Optional()) {
      w.block(
          "if (this._presentFields[" + field.getArrayPosition() + "])",
          () -> emitScalarAppend(w, field, jsField, fieldNum));
      return;
    }
    emitScalarAppend(w, field, jsField, fieldNum);
  }

  private void emitScalarAppend(CodeWriter w, ProtoField field, String jsField, int fieldNum) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    switch (type) {
      case TYPE_BOOL:
        w.line("parts.push('!%d%s' + (%s ? '1' : '0'));", fieldNum, typeChar, jsField);
        break;
      case TYPE_BYTES:
        w.line(
            "parts.push('!%d%s' + (typeof Buffer !== 'undefined' ? Buffer.from(%s).toString('base64') : btoa(String.fromCharCode.apply(null, %s as unknown as number[]))));",
            fieldNum, typeChar, jsField, jsField);
        break;
      case TYPE_STRING:
        w.line("parts.push('!%d%s' + encodeURIComponent(%s));", fieldNum, typeChar, jsField);
        break;
      default:
        w.line("parts.push('!%d%s' + %s);", fieldNum, typeChar, jsField);
        break;
    }
  }

  private void emitEnumSerialize(CodeWriter w, ProtoField field, String jsField, int fieldNum) {
    if (field.isProto3Optional()) {
      w.block(
          "if (this._presentFields[" + field.getArrayPosition() + "])",
          () -> w.line("parts.push('!%de' + (%s != null ? %s : 0));", fieldNum, jsField, jsField));
    } else {
      w.line("parts.push('!%de' + (%s != null ? %s : 0));", fieldNum, jsField, jsField);
    }
  }

  private void emitMessageSerialize(CodeWriter w, ProtoField field, String jsField, int fieldNum) {
    w.block(
        "if (" + jsField + " != null)",
        () -> {
          w.line("parts.push('!%dm' + (%s as any)._countPbtkFields());", fieldNum, jsField);
          w.line("(%s as any)._appendPbtkFields(parts);", jsField);
        });
  }

  private void emitRepeatedSerialize(CodeWriter w, ProtoField field, String jsField, int fieldNum) {
    String elemVar = "__" + nameResolver.fieldName(field.getName()) + "Item";
    w.block(
        "for (const " + elemVar + " of " + jsField + ")",
        () -> {
          if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
            w.block(
                "if (" + elemVar + " != null)",
                () -> {
                  w.line("parts.push('!%dm' + (%s as any)._countPbtkFields());", fieldNum, elemVar);
                  w.line("(%s as any)._appendPbtkFields(parts);", elemVar);
                });
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            w.line("parts.push('!%de' + (%s != null ? %s : 0));", fieldNum, elemVar, elemVar);
          } else {
            emitScalarAppend(w, field, elemVar, fieldNum);
          }
        });
  }

  private void emitMapSerialize(CodeWriter w, ProtoField field, String jsField, int fieldNum) {
    w.block(
        "for (const [__key, __val] of Object.entries(" + jsField + "))",
        () -> {
          w.line("parts.push('!%dm2');", fieldNum);

          // Key (field 1)
          String keyTypeChar = pbtkTypeChar(field.getMapKeyType());
          if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("parts.push('!1%s' + encodeURIComponent(__key));", keyTypeChar);
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("parts.push('!1%s' + (__key === 'true' ? '1' : '0'));", keyTypeChar);
          } else {
            w.line("parts.push('!1%s' + __key);", keyTypeChar);
          }

          // Value (field 2)
          if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
            w.block(
                "if (__val != null)",
                () -> {
                  w.line("parts.push('!2m' + (__val as any)._countPbtkFields());");
                  w.line("(__val as any)._appendPbtkFields(parts);");
                });
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
            w.line("parts.push('!2e' + (__val != null ? __val : 0));");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("parts.push('!2s' + encodeURIComponent(String(__val)));");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
            w.line(
                "parts.push('!2z' + (typeof Buffer !== 'undefined' ? Buffer.from(__val as Uint8Array).toString('base64') : btoa(String.fromCharCode.apply(null, __val as unknown as number[]))));");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("parts.push('!2b' + (__val ? '1' : '0'));");
          } else {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.line("parts.push('!2%s' + __val);", valTypeChar);
          }
        });
  }

  // ---------------------------------------------------------------------------
  // fromPbtkUrl() — deserialization
  // ---------------------------------------------------------------------------

  private void emitFromPbtkUrl(
      CodeWriter w, ProtoMessage message, String className, List<String> lazyImportNames) {
    // _parsePbtkTokens — internal parser
    w.blankLine();
    w.block(
        "private static _parsePbtkTokens(tokens: string[], fieldCount: number, offset: {v: number}): "
            + className,
        () -> {
          // Lazy imports
          for (String name : lazyImportNames) {
            w.line("const { %s } = require('./%s');", name, name);
          }

          w.line("const obj = new %s();", className);
          w.line("let consumed: number = 0;");
          w.block(
              "while (consumed < fieldCount && offset.v < tokens.length)",
              () -> {
                w.line("const token: string = tokens[offset.v];");
                w.line("let numEnd: number = 0;");
                w.line(
                    "while (numEnd < token.length && token.charCodeAt(numEnd) >= 48 && token.charCodeAt(numEnd) <= 57) numEnd++;");
                w.line(
                    "if (numEnd === 0 || numEnd >= token.length) { offset.v++; consumed++; continue; }");
                w.line("const fieldNum: number = parseInt(token.substring(0, numEnd), 10);");
                w.line("const value: string = token.substring(numEnd + 1);");
                w.blankLine();

                w.block(
                    "switch (fieldNum)",
                    () -> {
                      for (ProtoField field : message.getFields()) {
                        emitFieldCase(w, field);
                      }
                      w.line("default: offset.v++; consumed++; break;");
                    });
              });
          w.line("return obj;");
        });

    // fromPbtkUrl — public static method
    w.blankLine();
    w.block(
        "static fromPbtkUrl(input: string): " + className,
        () -> {
          w.line("if (input == null || input.length === 0) return new %s();", className);
          w.line("const tokens: string[] = %s._tokenizePbtk(input);", className);
          w.line("const offset: {v: number} = {v: 0};");
          w.line("return %s._parsePbtkTokens(tokens, tokens.length, offset);", className);
        });

    // _tokenizePbtk — split on '!'
    w.blankLine();
    w.block(
        "private static _tokenizePbtk(input: string): string[]",
        () -> {
          w.line("const tokens: string[] = [];");
          w.line("let i: number = input.charAt(0) === '!' ? 1 : 0;");
          w.block(
              "while (i < input.length)",
              () -> {
                w.line("const next: number = input.indexOf('!', i);");
                w.block(
                    "if (next < 0)",
                    () -> {
                      w.line("tokens.push(input.substring(i));");
                      w.line("break;");
                    });
                w.line("tokens.push(input.substring(i, next));");
                w.line("i = next + 1;");
              });
          w.line("return tokens;");
        });
  }

  private void emitFieldCase(CodeWriter w, ProtoField field) {
    int fieldNum = field.getFieldNumber();
    String setter = "obj." + nameResolver.setterName(field.getName());
    String getter = "obj." + nameResolver.getterName(field.getName()) + "()";

    w.block(
        "case " + fieldNum + ":",
        () -> {
          if (field.isMap()) {
            emitMapDeserialize(w, field);
          } else if (field.isRepeated()) {
            emitRepeatedDeserialize(w, field, getter);
          } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
            emitMessageDeserialize(w, field, setter);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            emitEnumDeserialize(w, field, setter);
          } else {
            emitScalarDeserialize(w, field, setter);
          }
          w.line("offset.v++;");
          w.line("consumed++;");
          w.line("break;");
        });
  }

  private void emitScalarDeserialize(CodeWriter w, ProtoField field, String setter) {
    String readExpr = tsScalarReadExpr(field.getProtoType(), "value");
    w.line("%s(%s);", setter, readExpr);
    if (field.isProto3Optional()) {
      w.line("(obj as any)._presentFields[%d] = true;", field.getArrayPosition());
    }
  }

  private void emitEnumDeserialize(CodeWriter w, ProtoField field, String setter) {
    w.line("%s(parseInt(value, 10));", setter);
    if (field.isProto3Optional()) {
      w.line("(obj as any)._presentFields[%d] = true;", field.getArrayPosition());
    }
  }

  private void emitMessageDeserialize(CodeWriter w, ProtoField field, String setter) {
    String msgType = typeMapper.simpleTypeName(field.getTypeReference());
    w.line("const subCount: number = parseInt(value, 10);");
    w.line("offset.v++;");
    w.line("%s((%s as any)._parsePbtkTokens(tokens, subCount, offset));", setter, msgType);
    w.line("offset.v--;"); // compensate for outer offset.v++
  }

  private void emitRepeatedDeserialize(CodeWriter w, ProtoField field, String getter) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      String msgType = typeMapper.simpleTypeName(field.getTypeReference());
      w.line("const subCount: number = parseInt(value, 10);");
      w.line("offset.v++;");
      w.line("%s.push((%s as any)._parsePbtkTokens(tokens, subCount, offset));", getter, msgType);
      w.line("offset.v--;");
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      w.line("%s.push(parseInt(value, 10));", getter);
    } else {
      String readExpr = tsScalarReadExpr(field.getProtoType(), "value");
      w.line("%s.push(%s);", getter, readExpr);
    }
  }

  private void emitMapDeserialize(CodeWriter w, ProtoField field) {
    String jsFieldExpr = "obj." + nameResolver.fieldName(field.getName());
    w.line("const entryCount: number = parseInt(value, 10);");
    w.line("offset.v++;");
    w.line("let entryKey: string | null = null;");
    w.line("let entryVal: any = null;");
    w.block(
        "for (let __mi: number = 0; __mi < entryCount && offset.v < tokens.length; __mi++)",
        () -> {
          w.line("const mapToken: string = tokens[offset.v];");
          w.line("let mne: number = 0;");
          w.line(
              "while (mne < mapToken.length && mapToken.charCodeAt(mne) >= 48 && mapToken.charCodeAt(mne) <= 57) mne++;");
          w.line("if (mne === 0 || mne >= mapToken.length) { offset.v++; continue; }");
          w.line("const mfn: number = parseInt(mapToken.substring(0, mne), 10);");
          w.line("const mval: string = mapToken.substring(mne + 1);");

          // Key (field 1)
          w.block(
              "if (mfn === 1)",
              () -> {
                String keyRead = tsScalarReadExpr(field.getMapKeyType(), "mval");
                w.line("entryKey = String(%s);", keyRead);
              });

          // Value (field 2)
          w.block(
              "if (mfn === 2)",
              () -> {
                if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
                  String msgType = typeMapper.simpleTypeName(field.getMapValueTypeReference());
                  w.line("const valSubCount: number = parseInt(mval, 10);");
                  w.line("offset.v++;");
                  w.line(
                      "entryVal = (%s as any)._parsePbtkTokens(tokens, valSubCount, offset);",
                      msgType);
                  w.line("offset.v--;");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
                  w.line("entryVal = parseInt(mval, 10);");
                } else {
                  String valRead = tsScalarReadExpr(field.getMapValueType(), "mval");
                  w.line("entryVal = %s;", valRead);
                }
              });
          w.line("offset.v++;");
        });
    w.line("offset.v--;"); // compensate for outer offset.v++
    w.line("if (entryKey != null) (%s as any)[entryKey] = entryVal;", jsFieldExpr);
  }

  // ---------------------------------------------------------------------------
  // Shared helpers
  // ---------------------------------------------------------------------------

  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    String enumName = protoEnum.getName();
    w.line("const %s = Object.freeze({", enumName);
    w.indent();
    for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
      w.line("%s: %d as const,", nameResolver.enumConstantName(val.name()), val.number());
    }
    for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
      w.line("%d: '%s' as const,", val.number(), nameResolver.enumConstantName(val.name()));
    }
    w.dedent();
    w.line("});");

    // Type alias as numeric literal union
    StringBuilder unionType = new StringBuilder();
    for (int i = 0; i < protoEnum.getValues().size(); i++) {
      if (i > 0) unionType.append(" | ");
      unionType.append(protoEnum.getValues().get(i).number());
    }
    w.line("type %s = %s;", enumName, unionType.toString());
  }

  private void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "toString(): string",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return '%s{}';", className);
            return;
          }
          StringBuilder sb = new StringBuilder();
          sb.append("return `").append(className).append("{");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String jsName = nameResolver.fieldName(field.getName());
            if (i > 0) sb.append(", ");
            sb.append(field.getName()).append("=${this.").append(jsName).append("}");
          }
          sb.append("}`;");
          w.line(sb.toString());
        });
  }

  private void emitExports(CodeWriter w, ProtoMessage message, String className) {
    StringBuilder exports = new StringBuilder();
    exports.append(className);
    for (ProtoEnum protoEnum : message.getEnums()) {
      exports.append(", ").append(protoEnum.getName());
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      exports.append(", ").append(nameResolver.messageClassName(nested.getName()));
    }
    w.line("export { %s };", exports.toString());
  }

  private void collectReferencedTypeNames(ProtoMessage message, ProtoFile file, Set<String> names) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      String typeRef = field.getTypeReference();
      if (typeRef == null) continue;
      if (field.isWellKnownType()) continue;

      boolean isNested = false;
      for (ProtoMessage nested : message.getNestedMessages()) {
        if (typeRef.equals(message.getFullName() + "." + nested.getName())) {
          isNested = true;
          break;
        }
      }
      if (isNested) continue;

      String simpleName = ProtoTypeUtil.simpleTypeName(typeRef);
      if (typeRef.startsWith(currentPrefix)) {
        names.add(simpleName);
      }

      if (field.isMap() && field.getMapValueTypeReference() != null) {
        String valRef = field.getMapValueTypeReference();
        String valName = ProtoTypeUtil.simpleTypeName(valRef);
        if (valRef.startsWith(currentPrefix)) {
          names.add(valName);
        }
      }
    }

    for (ProtoMessage nested : message.getNestedMessages()) {
      collectReferencedTypeNames(nested, file, names);
    }
  }

  private boolean hasOptionalFields(ProtoMessage message) {
    return message.getFields().stream().anyMatch(ProtoField::isProto3Optional);
  }

  private String tsScalarReadExpr(FieldDescriptorProto.Type type, String valueVar) {
    return switch (type) {
      case TYPE_DOUBLE, TYPE_FLOAT -> "Number(" + valueVar + ")";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64, TYPE_UINT64, TYPE_FIXED64 ->
          "String(" + valueVar + ")";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32, TYPE_UINT32, TYPE_FIXED32 ->
          "parseInt(" + valueVar + ", 10)";
      case TYPE_BOOL -> valueVar + " === '1'";
      case TYPE_STRING -> "decodeURIComponent(" + valueVar + ")";
      case TYPE_BYTES ->
          "(typeof Buffer !== 'undefined' ? new Uint8Array(Buffer.from("
              + valueVar
              + ", 'base64')) : new Uint8Array(atob("
              + valueVar
              + ").split('').map((c: string) => c.charCodeAt(0))))";
      default -> valueVar;
    };
  }

  static String pbtkTypeChar(FieldDescriptorProto.Type type) {
    return switch (type) {
      case TYPE_BOOL -> "b";
      case TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64 ->
          "i";
      case TYPE_FLOAT -> "f";
      case TYPE_DOUBLE -> "d";
      case TYPE_STRING -> "s";
      case TYPE_ENUM -> "e";
      case TYPE_MESSAGE -> "m";
      case TYPE_BYTES -> "z";
      default -> "s";
    };
  }
}
