/*
 * Copyright 2026 coffeeandwork
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.jsonarray.codegen.typescript;

import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.javascript.JavaScriptCodeEmitter;
import dev.protocgen.textcodecs.jsonarray.codegen.javascript.JavaScriptNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.javascript.JavaScriptTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Generates TypeScript source files for proto messages and enums. Extends the JavaScript emitter to
 * add type annotations on fields, parameters, and return types.
 */
public class TypeScriptCodeEmitter extends JavaScriptCodeEmitter {

  private final TypeScriptTypeMapper tsTypeMapper;
  private final TypeScriptSerializerGenerator tsSerializerGen;
  private final TypeScriptDeserializerGenerator tsDeserializerGen;

  public TypeScriptCodeEmitter(
      TypeScriptTypeMapper tsTypeMapper, JavaScriptNameResolver nameResolver) {
    super(new JavaScriptTypeMapper(), nameResolver);
    this.tsTypeMapper = tsTypeMapper;
    this.tsSerializerGen = new TypeScriptSerializerGenerator(tsTypeMapper, nameResolver);
    this.tsDeserializerGen = new TypeScriptDeserializerGenerator(tsTypeMapper, nameResolver);
  }

  @Override
  public String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    String className = nameResolver.messageClassName(message.getName());

    emitFileHeader(w, file);

    // Collect referenced types — these will be emitted as lazy imports inside methods
    Set<String> importNames = new LinkedHashSet<>();
    collectReferencedTypeNames(message, file, importNames);
    List<String> lazyImportNames = List.copyOf(importNames);

    // Emit nested enums as const objects before the class
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
      w.blankLine();
    }

    // Emit nested message classes before the main class
    for (ProtoMessage nested : message.getNestedMessages()) {
      emitMessageClass(w, nested, file);
      w.blankLine();
    }

    // Main class
    emitMessageClass(w, message, file, lazyImportNames);

    // Export
    w.blankLine();
    emitExports(w, message, className);

    return w.toString();
  }

  @Override
  public String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    emitFileHeader(w, file);
    emitEnum(w, protoEnum);
    w.blankLine();
    w.line("export { %s };", protoEnum.getName());
    return w.toString();
  }

  @Override
  protected void emitFileHeader(CodeWriter w, ProtoFile file) {
    w.line("// Generated by protoc-gen-jsonarray. DO NOT EDIT.");
    w.line("// Source: %s", file.getFileName());
    w.blankLine();
  }

  @Override
  protected String formatImport(String simpleName) {
    return String.format("import { %s } from './%s';", simpleName, simpleName);
  }

  @Override
  public String formatLazyImport(String simpleName) {
    // Use require() inside method body for both JS and TS to avoid circular import issues
    return String.format("const { %s } = require('./%s');", simpleName, simpleName);
  }

  @Override
  protected void emitMessageClass(CodeWriter w, ProtoMessage message, ProtoFile file) {
    emitMessageClass(w, message, file, List.of());
  }

  @Override
  protected void emitMessageClass(
      CodeWriter w, ProtoMessage message, ProtoFile file, List<String> lazyImportNames) {
    String className = nameResolver.messageClassName(message.getName());

    w.block(
        "class " + className,
        () -> {
          // Typed field declarations
          emitFieldDeclarations(w, message);

          // Constructor
          emitConstructor(w, message);

          // Getters and setters with type annotations
          emitGettersSetters(w, message);

          // Presence checks
          emitHasMethods(w, message);

          // Serialize with return type
          tsSerializerGen.generate(w, message);

          // Deserialize with parameter and return types (with lazy imports)
          tsDeserializerGen.generate(w, message, className, lazyImportNames, this);

          // toString
          emitToString(w, message, className);
        });
  }

  /** Emit typed field declarations at the top of the class. */
  private void emitFieldDeclarations(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String jsName = nameResolver.fieldName(field.getName());
      String tsType = tsTypeMapper.nullableType(field);
      w.line("%s: %s;", jsName, tsType);
    }

    if (hasOptionalFields(message)) {
      w.line("private _presentFields: Record<number, boolean>;");
    }

    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String caseProp = "_" + nameResolver.fieldName(group.name()) + "Case";
      w.line("private %s: number;", caseProp);
    }

    w.blankLine();
  }

  @Override
  protected void emitConstructor(CodeWriter w, ProtoMessage message) {
    w.block(
        "constructor()",
        () -> {
          for (ProtoField field : message.getFields()) {
            String jsName = nameResolver.fieldName(field.getName());
            String defaultVal = tsTypeMapper.defaultValue(field);
            w.line("this.%s = %s;", jsName, defaultVal);
          }

          if (hasOptionalFields(message)) {
            w.line("this._presentFields = {};");
          }

          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            String caseProp = "_" + nameResolver.fieldName(group.name()) + "Case";
            w.line("this.%s = 0;", caseProp);
          }
        });
  }

  @Override
  protected void emitGettersSetters(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String jsName = nameResolver.fieldName(field.getName());
      String getterName = nameResolver.getterName(field.getName());
      String setterName = nameResolver.setterName(field.getName());
      String tsType = tsTypeMapper.nullableType(field);

      // Getter with return type
      w.blankLine();
      w.block(
          getterName + "(): " + tsType,
          () -> {
            w.line("return this.%s;", jsName);
          });

      // Setter with parameter type
      w.blankLine();
      w.block(
          setterName + "(value: " + tsType + "): void",
          () -> {
            w.line("this.%s = value;", jsName);
            if (field.isProto3Optional()) {
              w.line("this._presentFields[%d] = true;", field.getArrayPosition());
            }
            if (field.isOneofMember()) {
              String caseProp = "_" + nameResolver.fieldName(field.getOneofName()) + "Case";
              w.line("this.%s = %d;", caseProp, field.getFieldNumber());
            }
          });
    }
  }

  @Override
  protected void emitHasMethods(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.isProto3Optional() || field.getKind() == ProtoField.FieldKind.MESSAGE) {
        String hasName = "has" + JavaScriptNameResolver.snakeToPascal(field.getName());
        w.blankLine();
        w.block(
            hasName + "(): boolean",
            () -> {
              if (field.isProto3Optional()) {
                w.line("return !!this._presentFields[%d];", field.getArrayPosition());
              } else {
                w.line("return this.%s != null;", nameResolver.fieldName(field.getName()));
              }
            });
      }
    }
  }

  @Override
  protected void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    String enumName = protoEnum.getName();

    // Emit as a const object with an 'as const' assertion for strong typing
    w.line("const %s = Object.freeze({", enumName);
    w.indent();
    // Forward mapping: NAME -> number
    for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
      w.line("%s: %d as const,", nameResolver.enumConstantName(val.name()), val.number());
    }
    // Reverse mapping: number -> NAME
    for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
      w.line("%d: '%s' as const,", val.number(), nameResolver.enumConstantName(val.name()));
    }
    w.dedent();
    w.line("});");

    // Type alias as a numeric literal union (e.g. type Status = 0 | 1 | 2)
    StringBuilder unionType = new StringBuilder();
    for (int i = 0; i < protoEnum.getValues().size(); i++) {
      if (i > 0) unionType.append(" | ");
      unionType.append(protoEnum.getValues().get(i).number());
    }
    w.line("type %s = %s;", enumName, unionType.toString());
  }

  @Override
  protected void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "toString(): string",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return '%s{}';", className);
            return;
          }
          StringBuilder sb = new StringBuilder();
          sb.append("return `").append(className).append("{");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String jsName = nameResolver.fieldName(field.getName());
            if (i > 0) sb.append(", ");
            sb.append(field.getName()).append("=${this.").append(jsName).append("}");
          }
          sb.append("}`;");
          w.line(sb.toString());
        });
  }

  @Override
  protected void emitExports(CodeWriter w, ProtoMessage message, String className) {
    StringBuilder exports = new StringBuilder();
    exports.append(className);

    for (ProtoEnum protoEnum : message.getEnums()) {
      exports.append(", ").append(protoEnum.getName());
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      exports.append(", ").append(nameResolver.messageClassName(nested.getName()));
    }

    w.line("export { %s };", exports.toString());
  }
}
