// @generated by protoc-gen-pbtkurl -- do not edit.

const std = @import("std");

pub const Address = struct {
    street: []const u8 = "",
    city: []const u8 = "",
    state: []const u8 = "",
    zip: i32 = 0,

    fn appendPbtkFields(self: *const Address, buf: *std.ArrayList(u8)) void {
        buf.writer().print("!1s", .{}) catch {};
        const pct = std.Uri.percentEncode(self.street, std.Uri.Component.query) catch return;
        buf.writer().writeAll(pct) catch {};
        buf.writer().print("!2s", .{}) catch {};
        const pct = std.Uri.percentEncode(self.city, std.Uri.Component.query) catch return;
        buf.writer().writeAll(pct) catch {};
        buf.writer().print("!3s", .{}) catch {};
        const pct = std.Uri.percentEncode(self.state, std.Uri.Component.query) catch return;
        buf.writer().writeAll(pct) catch {};
        buf.writer().print("!4i{d}", .{self.zip}) catch {};
    }

    fn countPbtkFields(self: *const Address) usize {
        var count: usize = 0;
        count += 1;
        count += 1;
        count += 1;
        count += 1;
        return count;
    }

    pub fn serialize(self: *const Address, allocator: std.mem.Allocator) ![]u8 {
        var buf = std.ArrayList(u8).init(allocator);
        self.appendPbtkFields(&buf);
        return buf.toOwnedSlice();
    }

    fn parsePbtkTokens(tokens: []const []const u8, field_count: usize, offset: *usize) Address {
        var obj = Address{};
        var consumed: usize = 0;
        while (consumed < field_count and offset.* < tokens.len) {
            const token = tokens[offset.*];
            var num_end: usize = 0;
            while (num_end < token.len and token[num_end] >= '0' and token[num_end] <= '9') {
                num_end += 1;
            }
            if (num_end == 0 or num_end >= token.len) {
                offset.* += 1;
                consumed += 1;
                continue;
            }
            const field_num = std.fmt.parseInt(i32, token[0..num_end], 10) catch 0;
            const value = token[num_end + 1 ..];
            switch (field_num) {
                1 => {
                    obj.street = std.Uri.percentDecode(value) catch value;
                    offset.* += 1;
                    consumed += 1;
                }
                2 => {
                    obj.city = std.Uri.percentDecode(value) catch value;
                    offset.* += 1;
                    consumed += 1;
                }
                3 => {
                    obj.state = std.Uri.percentDecode(value) catch value;
                    offset.* += 1;
                    consumed += 1;
                }
                4 => {
                    obj.zip = std.fmt.parseInt(i32, value, 10) catch 0;
                    offset.* += 1;
                    consumed += 1;
                }
                else => {
                    offset.* += 1;
                    consumed += 1;
                }
            }
        }
        return obj;
    }

    pub fn deserialize(data: []const u8, allocator: std.mem.Allocator) !Address {
        if (data.len == 0) return Address{};
        const trimmed = if (data[0] == '!') data[1..] else data;
        var token_list = std.ArrayList([]const u8).init(allocator);
        defer token_list.deinit();
        var start: usize = 0;
        for (trimmed, 0..) |ch, idx| {
            if (ch == '!') {
                try token_list.append(trimmed[start..idx]);
                start = idx + 1;
            }
        }
        if (start <= trimmed.len) try token_list.append(trimmed[start..]);
        const tokens = token_list.items;
        var offset: usize = 0;
        return parsePbtkTokens(tokens, tokens.len, &offset);
    }

    pub fn deinit(self: *Address, allocator: std.mem.Allocator) void {
        if (self.street.len > 0) {
            allocator.free(self.street);
        }
        if (self.city.len > 0) {
            allocator.free(self.city);
        }
        if (self.state.len > 0) {
            allocator.free(self.state);
        }
    }
};
