/*
 * Copyright 2026 coffeeandwork
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.pbtkurl.codegen.c;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.LanguageGenerator;
import dev.protocgen.textcodecs.jsonarray.codegen.ProtoTypeUtil;
import dev.protocgen.textcodecs.jsonarray.codegen.c.CNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.c.CTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import dev.protocgen.textcodecs.jsonarray.model.TypeRegistry;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * C language code generator for pbtk URL encoding. Produces .h header and .c source file pairs with
 * pbtk URL serialization/deserialization using the {@code !<fieldNumber><typeChar><value>} format.
 *
 * <p>For each message, two CodeGeneratorResponse.File entries are produced:
 *
 * <ol>
 *   <li>message_name.h - struct definition and function declarations
 *   <li>message_name.c - function implementations (pack, unpack, free)
 * </ol>
 *
 * <p>For top-level enums, only a .h file is produced (enums need no implementation).
 */
public class PbtkCGenerator implements LanguageGenerator {

  private static final String GENERATED_MARKER =
      "// @generated by protoc-gen-pbtkurl -- do not edit.";

  private final CNameResolver nameResolver = new CNameResolver();
  private final CTypeMapper typeMapper = new CTypeMapper(nameResolver);

  @Override
  public List<CodeGeneratorResponse.File> generate(ProtoFile file, TypeRegistry registry) {
    List<CodeGeneratorResponse.File> result = new ArrayList<>();

    for (ProtoMessage message : file.getMessages()) {
      nameResolver.validateFieldNames(message.getFields());

      // Header file (.h)
      String headerCode = emitHeader(message, file);
      String headerPath = nameResolver.outputFilePath(file, message.getName());
      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(headerPath)
              .setContent(headerCode)
              .build());

      // Source file (.c)
      String sourceCode = emitSource(message, file);
      String sourcePath = nameResolver.outputSourcePath(file, message.getName());
      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(sourcePath)
              .setContent(sourceCode)
              .build());
    }

    // Generate .h for each top-level enum (no .c needed)
    for (ProtoEnum protoEnum : file.getEnums()) {
      String headerCode = emitTopLevelEnumHeader(protoEnum, file);
      String headerPath = nameResolver.outputFilePath(file, protoEnum.getName());
      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(headerPath)
              .setContent(headerCode)
              .build());
    }

    return result;
  }

  // ========================================================================
  // Header file (.h) generation
  // ========================================================================

  private String emitHeader(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    String pkg = nameResolver.resolvePackage(file);
    String typeName = nameResolver.qualifiedTypeName(pkg, message.getName());
    String funcPrefix = nameResolver.functionPrefix(pkg, message.getName());
    String guard = nameResolver.includeGuard(file, message.getName()) + "_PBTK";

    w.line(GENERATED_MARKER);
    w.blankLine();
    w.line("#ifndef %s", guard);
    w.line("#define %s", guard);
    w.blankLine();

    // Standard includes
    w.line("#include <stdint.h>");
    w.line("#include <stdbool.h>");
    w.line("#include <stdlib.h>");
    w.line("#include <string.h>");
    w.line("#include <stdio.h>");
    w.line("#include <inttypes.h>");
    w.line("#include <math.h>");
    w.blankLine();

    // Cross-file includes for referenced message/enum types
    emitCrossFileIncludes(w, message, file);

    // C++ guard
    w.line("#ifdef __cplusplus");
    w.line("extern \"C\" {");
    w.line("#endif");
    w.blankLine();

    // Forward declarations for nested messages
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedType =
          nameResolver.qualifiedTypeName(pkg, message.getName() + "_" + nested.getName());
      w.line("typedef struct %s %s;", nestedType, nestedType);
    }
    if (!message.getNestedMessages().isEmpty()) {
      w.blankLine();
    }

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnumDef(w, protoEnum, pkg, message.getName() + "_");
    }

    // Map entry typedefs
    emitMapEntryTypedefs(w, message, funcPrefix);

    // Oneof case enums and union types
    emitOneofTypes(w, message, funcPrefix, pkg);

    // Struct definition
    emitStructDef(w, message, typeName, funcPrefix, pkg);

    // Function declarations
    w.blankLine();
    w.line("/* pbtk URL serialization */");
    w.line("char* %s_pack(const %s* msg);", funcPrefix, typeName);
    w.blankLine();
    w.line("/* pbtk URL deserialization */");
    w.line("%s* %s_unpack(const char* input);", typeName, funcPrefix);
    w.blankLine();
    w.line("/* Memory management */");
    w.line("void %s_free(%s* msg);", funcPrefix, typeName);

    // Nested message declarations
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedTypeName =
          nameResolver.qualifiedTypeName(pkg, message.getName() + "_" + nested.getName());
      String nestedFuncPrefix =
          nameResolver.functionPrefix(pkg, message.getName() + "_" + nested.getName());
      w.blankLine();
      w.line("/* Nested message: %s */", nested.getName());
      emitNestedMessageHeader(
          w, nested, file, nestedTypeName, nestedFuncPrefix, pkg, message.getName() + "_");
    }

    w.blankLine();
    w.line("#ifdef __cplusplus");
    w.line("}");
    w.line("#endif");
    w.blankLine();
    w.line("#endif /* %s */", guard);

    return w.toString();
  }

  private String emitTopLevelEnumHeader(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    String pkg = nameResolver.resolvePackage(file);
    String guard = nameResolver.includeGuard(file, protoEnum.getName()) + "_PBTK";

    w.line(GENERATED_MARKER);
    w.blankLine();
    w.line("#ifndef %s", guard);
    w.line("#define %s", guard);
    w.blankLine();
    w.line("#ifdef __cplusplus");
    w.line("extern \"C\" {");
    w.line("#endif");
    w.blankLine();

    emitEnumDef(w, protoEnum, pkg, "");

    w.line("#ifdef __cplusplus");
    w.line("}");
    w.line("#endif");
    w.blankLine();
    w.line("#endif /* %s */", guard);

    return w.toString();
  }

  // ========================================================================
  // Source file (.c) generation
  // ========================================================================

  private String emitSource(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    String pkg = nameResolver.resolvePackage(file);
    String typeName = nameResolver.qualifiedTypeName(pkg, message.getName());
    String funcPrefix = nameResolver.functionPrefix(pkg, message.getName());
    String snakeName = pascalToSnake(message.getName());

    w.line(GENERATED_MARKER);
    w.blankLine();

    // Include our own header
    String headerFile =
        pkg.isEmpty() ? snakeName + ".h" : pkg.replace('.', '/') + "/" + snakeName + ".h";
    w.line("#include \"%s\"", headerFile);
    w.blankLine();

    // Helper: URL percent-encode a string
    emitUrlEncodeHelper(w);

    // Helper: URL percent-decode a string
    emitUrlDecodeHelper(w);

    // Helper: base64 encode
    emitBase64EncodeHelper(w);

    // Helper: base64 decode
    emitBase64DecodeHelper(w);

    // Helper: append to dynamic string buffer
    emitStringBufferHelper(w);

    // Nested message implementations first
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedTypeName =
          nameResolver.qualifiedTypeName(pkg, message.getName() + "_" + nested.getName());
      String nestedFuncPrefix =
          nameResolver.functionPrefix(pkg, message.getName() + "_" + nested.getName());
      emitNestedMessageSource(
          w, nested, file, nestedTypeName, nestedFuncPrefix, pkg, message.getName() + "_");
    }

    // Internal field-count function
    emitCountFunction(w, message, funcPrefix, typeName);

    // Internal append-fields function
    emitAppendFieldsFunction(w, message, funcPrefix, typeName);

    // Internal parse-tokens function
    emitParseTokensFunction(w, message, funcPrefix, typeName);

    // Public serialize
    emitSerializeFunction(w, message, funcPrefix, typeName);

    // Public deserialize
    emitDeserializeFunction(w, message, funcPrefix, typeName);

    // Free
    emitFreeFunction(w, message, funcPrefix, typeName, pkg);

    return w.toString();
  }

  // ========================================================================
  // Static C helpers (emitted once per .c file)
  // ========================================================================

  private void emitUrlEncodeHelper(CodeWriter w) {
    w.line("static char* pbtk_url_encode(const char* input) {");
    w.indent();
    w.line("if (!input) return NULL;");
    w.line("size_t len = strlen(input);");
    w.line("char* out = (char*)malloc(len * 3 + 1);");
    w.line("if (!out) return NULL;");
    w.line("size_t j = 0;");
    w.block(
        "for (size_t i = 0; i < len; i++)",
        () -> {
          w.line("unsigned char c = (unsigned char)input[i];");
          w.block(
              "if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || "
                  + "(c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.' || c == '~')",
              () -> {
                w.line("out[j++] = c;");
              });
          w.block(
              "else",
              () -> {
                w.line("snprintf(out + j, 4, \"%%25%%02X\", c);");
                w.line("j += 3;");
              });
        });
    w.line("out[j] = '\\0';");
    w.line("return out;");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  private void emitUrlDecodeHelper(CodeWriter w) {
    w.line("static int pbtk_hex_val(char c) {");
    w.indent();
    w.line("if (c >= '0' && c <= '9') return c - '0';");
    w.line("if (c >= 'A' && c <= 'F') return c - 'A' + 10;");
    w.line("if (c >= 'a' && c <= 'f') return c - 'a' + 10;");
    w.line("return -1;");
    w.dedent();
    w.line("}");
    w.blankLine();

    w.line("static char* pbtk_url_decode(const char* input) {");
    w.indent();
    w.line("if (!input) return NULL;");
    w.line("size_t len = strlen(input);");
    w.line("char* out = (char*)malloc(len + 1);");
    w.line("if (!out) return NULL;");
    w.line("size_t j = 0;");
    w.block(
        "for (size_t i = 0; i < len; i++)",
        () -> {
          w.block(
              "if (input[i] == '%%' && i + 2 < len)",
              () -> {
                w.line("int hi = pbtk_hex_val(input[i + 1]);");
                w.line("int lo = pbtk_hex_val(input[i + 2]);");
                w.block(
                    "if (hi >= 0 && lo >= 0)",
                    () -> {
                      w.line("out[j++] = (char)((hi << 4) | lo);");
                      w.line("i += 2;");
                      w.line("continue;");
                    });
              });
          w.line("out[j++] = input[i];");
        });
    w.line("out[j] = '\\0';");
    w.line("return out;");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  private void emitBase64EncodeHelper(CodeWriter w) {
    w.line(
        "static const char pbtk_b64_table[] = "
            + "\"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\";");
    w.blankLine();
    w.line("static char* pbtk_base64_encode(const uint8_t* data, size_t len) {");
    w.indent();
    w.line("if (!data || len == 0) { char* e = (char*)malloc(1); if (e) e[0] = '\\0'; return e; }");
    w.line("size_t out_len = 4 * ((len + 2) / 3);");
    w.line("char* out = (char*)malloc(out_len + 1);");
    w.line("if (!out) return NULL;");
    w.line("size_t j = 0;");
    w.block(
        "for (size_t i = 0; i < len; i += 3)",
        () -> {
          w.line("uint32_t a = data[i];");
          w.line("uint32_t b = (i + 1 < len) ? data[i + 1] : 0;");
          w.line("uint32_t c = (i + 2 < len) ? data[i + 2] : 0;");
          w.line("uint32_t triple = (a << 16) | (b << 8) | c;");
          w.line("out[j++] = pbtk_b64_table[(triple >> 18) & 0x3F];");
          w.line("out[j++] = pbtk_b64_table[(triple >> 12) & 0x3F];");
          w.line("out[j++] = (i + 1 < len) ? pbtk_b64_table[(triple >> 6) & 0x3F] : '=';");
          w.line("out[j++] = (i + 2 < len) ? pbtk_b64_table[triple & 0x3F] : '=';");
        });
    w.line("out[j] = '\\0';");
    w.line("return out;");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  private void emitBase64DecodeHelper(CodeWriter w) {
    w.line("static int pbtk_b64_val(char c) {");
    w.indent();
    w.line("if (c >= 'A' && c <= 'Z') return c - 'A';");
    w.line("if (c >= 'a' && c <= 'z') return c - 'a' + 26;");
    w.line("if (c >= '0' && c <= '9') return c - '0' + 52;");
    w.line("if (c == '+') return 62;");
    w.line("if (c == '/') return 63;");
    w.line("return -1;");
    w.dedent();
    w.line("}");
    w.blankLine();

    w.line("static uint8_t* pbtk_base64_decode(const char* input, size_t* out_len) {");
    w.indent();
    w.line("if (!input || !out_len) return NULL;");
    w.line("size_t len = strlen(input);");
    w.line("if (len == 0) { *out_len = 0; return (uint8_t*)malloc(1); }");
    w.line("size_t padding = 0;");
    w.line("if (len > 0 && input[len - 1] == '=') padding++;");
    w.line("if (len > 1 && input[len - 2] == '=') padding++;");
    w.line("*out_len = (len / 4) * 3 - padding;");
    w.line("uint8_t* out = (uint8_t*)malloc(*out_len);");
    w.line("if (!out) return NULL;");
    w.line("size_t j = 0;");
    w.block(
        "for (size_t i = 0; i < len; i += 4)",
        () -> {
          w.line("int a = pbtk_b64_val(input[i]);");
          w.line("int b = (i + 1 < len) ? pbtk_b64_val(input[i + 1]) : 0;");
          w.line("int c = (i + 2 < len) ? pbtk_b64_val(input[i + 2]) : 0;");
          w.line("int d = (i + 3 < len) ? pbtk_b64_val(input[i + 3]) : 0;");
          w.line("if (a < 0) a = 0; if (b < 0) b = 0; if (c < 0) c = 0; if (d < 0) d = 0;");
          w.line(
              "uint32_t triple = ((uint32_t)a << 18) | ((uint32_t)b << 12) | ((uint32_t)c << 6) | (uint32_t)d;");
          w.line("if (j < *out_len) out[j++] = (triple >> 16) & 0xFF;");
          w.line("if (j < *out_len) out[j++] = (triple >> 8) & 0xFF;");
          w.line("if (j < *out_len) out[j++] = triple & 0xFF;");
        });
    w.line("return out;");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  private void emitStringBufferHelper(CodeWriter w) {
    w.line("#define PBTK_BUF_INITIAL_CAP 256");
    w.blankLine();
    w.line("typedef struct { char* data; size_t len; size_t cap; } pbtk_buf_t;");
    w.blankLine();
    w.line("static void pbtk_buf_init(pbtk_buf_t* buf) {");
    w.indent();
    w.line("buf->cap = PBTK_BUF_INITIAL_CAP;");
    w.line("buf->data = (char*)malloc(buf->cap);");
    w.line("buf->len = 0;");
    w.line("if (buf->data) buf->data[0] = '\\0';");
    w.dedent();
    w.line("}");
    w.blankLine();

    w.line("static void pbtk_buf_append(pbtk_buf_t* buf, const char* str) {");
    w.indent();
    w.line("if (!buf->data || !str) return;");
    w.line("size_t slen = strlen(str);");
    w.block(
        "if (buf->len + slen + 1 > buf->cap)",
        () -> {
          w.line("buf->cap = (buf->len + slen + 1) * 2;");
          w.line("char* newdata = (char*)realloc(buf->data, buf->cap);");
          w.line("if (!newdata) return;");
          w.line("buf->data = newdata;");
        });
    w.line("memcpy(buf->data + buf->len, str, slen);");
    w.line("buf->len += slen;");
    w.line("buf->data[buf->len] = '\\0';");
    w.dedent();
    w.line("}");
    w.blankLine();

    w.line("static void pbtk_buf_append_int(pbtk_buf_t* buf, int64_t val) {");
    w.indent();
    w.line("char tmp[32];");
    w.line("snprintf(tmp, sizeof(tmp), \"%%\" PRId64, val);");
    w.line("pbtk_buf_append(buf, tmp);");
    w.dedent();
    w.line("}");
    w.blankLine();

    w.line("static void pbtk_buf_append_uint(pbtk_buf_t* buf, uint64_t val) {");
    w.indent();
    w.line("char tmp[32];");
    w.line("snprintf(tmp, sizeof(tmp), \"%%\" PRIu64, val);");
    w.line("pbtk_buf_append(buf, tmp);");
    w.dedent();
    w.line("}");
    w.blankLine();

    w.line("static void pbtk_buf_append_double(pbtk_buf_t* buf, double val) {");
    w.indent();
    w.line("char tmp[64];");
    w.line("snprintf(tmp, sizeof(tmp), \"%%.17g\", val);");
    w.line("pbtk_buf_append(buf, tmp);");
    w.dedent();
    w.line("}");
    w.blankLine();

    w.line("static void pbtk_buf_append_float(pbtk_buf_t* buf, float val) {");
    w.indent();
    w.line("char tmp[64];");
    w.line("snprintf(tmp, sizeof(tmp), \"%%.9g\", (double)val);");
    w.line("pbtk_buf_append(buf, tmp);");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  // ========================================================================
  // Tokenizer (emitted in .c)
  // ========================================================================

  private void emitTokenizer(CodeWriter w) {
    // Already part of the parse function -- tokenize inline
  }

  // ========================================================================
  // Serialize implementation
  // ========================================================================

  private void emitCountFunction(
      CodeWriter w, ProtoMessage message, String funcPrefix, String typeName) {
    w.block(
        "static int " + funcPrefix + "_count_pbtk_fields(const " + typeName + "* msg)",
        () -> {
          w.line("int count = 0;");
          for (ProtoField field : message.getFields()) {
            emitFieldCount(w, field, funcPrefix);
          }
          w.line("return count;");
        });
    w.blankLine();
  }

  private void emitFieldCount(CodeWriter w, ProtoField field, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());
    String accessor = "msg->" + fieldName;

    if (field.isOneofMember()) {
      String caseConst =
          funcPrefix.toUpperCase()
              + "_"
              + field.getOneofName().toUpperCase()
              + "_"
              + field.getName().toUpperCase();
      w.line(
          "if (msg->%s_case == %s) count++;",
          nameResolver.fieldName(field.getOneofName()), caseConst);
      return;
    }

    if (field.isMap()) {
      w.line("count += (int)msg->%s_count;", fieldName);
    } else if (field.isRepeated()) {
      w.line("count += (int)msg->%s_count;", fieldName);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      w.line("if (%s) count++;", accessor);
    } else if (field.isProto3Optional()) {
      w.line("if (msg->has_%s) count++;", fieldName);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_DOUBLE
        || field.getProtoType() == FieldDescriptorProto.Type.TYPE_FLOAT) {
      w.line("if (!isnan(%s) && !isinf(%s)) count++;", accessor, accessor);
    } else {
      w.line("count++;");
    }
  }

  private void emitAppendFieldsFunction(
      CodeWriter w, ProtoMessage message, String funcPrefix, String typeName) {
    w.block(
        "static void "
            + funcPrefix
            + "_append_pbtk_fields(pbtk_buf_t* buf, const "
            + typeName
            + "* msg)",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldSerialize(w, field, funcPrefix);
          }
        });
    w.blankLine();
  }

  private void emitFieldSerialize(CodeWriter w, ProtoField field, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());
    String accessor = "msg->" + fieldName;
    int fieldNum = field.getFieldNumber();

    if (field.isOneofMember()) {
      String caseConst =
          funcPrefix.toUpperCase()
              + "_"
              + field.getOneofName().toUpperCase()
              + "_"
              + field.getName().toUpperCase();
      String unionAccess = "msg->" + nameResolver.fieldName(field.getOneofName()) + "." + fieldName;
      w.block(
          "if (msg->"
              + nameResolver.fieldName(field.getOneofName())
              + "_case == "
              + caseConst
              + ")",
          () -> {
            emitSingleFieldAppend(w, field, unionAccess, fieldNum, funcPrefix);
          });
      return;
    }

    if (field.isMap()) {
      emitMapSerialize(w, field, accessor, fieldNum, funcPrefix);
    } else if (field.isRepeated()) {
      emitRepeatedSerialize(w, field, accessor, fieldNum, funcPrefix);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      emitMessageSerialize(w, field, accessor, fieldNum, funcPrefix);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, accessor, fieldNum);
    } else {
      emitScalarSerialize(w, field, accessor, fieldNum);
    }
  }

  private void emitSingleFieldAppend(
      CodeWriter w, ProtoField field, String accessor, int fieldNum, String funcPrefix) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      emitMessageSerialize(w, field, accessor, fieldNum, funcPrefix);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, accessor, fieldNum);
    } else {
      emitScalarSerialize(w, field, accessor, fieldNum);
    }
  }

  private void emitScalarSerialize(CodeWriter w, ProtoField field, String accessor, int fieldNum) {
    String fieldName = nameResolver.fieldName(field.getName());
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    Runnable appendCode =
        () -> {
          switch (type) {
            case TYPE_BOOL:
              w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
              w.line("pbtk_buf_append(buf, %s ? \"1\" : \"0\");", accessor);
              break;
            case TYPE_BYTES:
              w.block(
                  "",
                  () -> {
                    w.line("char* b64 = pbtk_base64_encode(%s, msg->%s_len);", accessor, fieldName);
                    w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
                    w.line("if (b64) { pbtk_buf_append(buf, b64); free(b64); }");
                  });
              break;
            case TYPE_STRING:
              w.block(
                  "if (" + accessor + ")",
                  () -> {
                    w.line("char* enc = pbtk_url_encode(%s);", accessor);
                    w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
                    w.line("if (enc) { pbtk_buf_append(buf, enc); free(enc); }");
                  });
              break;
            case TYPE_DOUBLE:
              w.block(
                  "if (!isnan(" + accessor + ") && !isinf(" + accessor + "))",
                  () -> {
                    w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
                    w.line("pbtk_buf_append_double(buf, %s);", accessor);
                  });
              break;
            case TYPE_FLOAT:
              w.block(
                  "if (!isnan(" + accessor + ") && !isinf(" + accessor + "))",
                  () -> {
                    w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
                    w.line("pbtk_buf_append_float(buf, %s);", accessor);
                  });
              break;
            case TYPE_UINT32:
            case TYPE_FIXED32:
              w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
              w.line("pbtk_buf_append_uint(buf, (uint64_t)%s);", accessor);
              break;
            case TYPE_UINT64:
            case TYPE_FIXED64:
              w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
              w.line("pbtk_buf_append_uint(buf, %s);", accessor);
              break;
            case TYPE_INT64:
            case TYPE_SINT64:
            case TYPE_SFIXED64:
              w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
              w.line("pbtk_buf_append_int(buf, %s);", accessor);
              break;
            default:
              // int32 and similar
              w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
              w.line("pbtk_buf_append_int(buf, (int64_t)%s);", accessor);
              break;
          }
        };

    if (field.isProto3Optional()) {
      w.block("if (msg->has_" + fieldName + ")", appendCode);
    } else {
      appendCode.run();
    }
  }

  private void emitEnumSerialize(CodeWriter w, ProtoField field, String accessor, int fieldNum) {
    String fieldName = nameResolver.fieldName(field.getName());
    if (field.isProto3Optional()) {
      w.block(
          "if (msg->has_" + fieldName + ")",
          () -> {
            w.line("pbtk_buf_append(buf, \"!%de\");", fieldNum);
            w.line("pbtk_buf_append_int(buf, (int64_t)%s);", accessor);
          });
    } else {
      w.line("pbtk_buf_append(buf, \"!%de\");", fieldNum);
      w.line("pbtk_buf_append_int(buf, (int64_t)%s);", accessor);
    }
  }

  private void emitMessageSerialize(
      CodeWriter w, ProtoField field, String accessor, int fieldNum, String funcPrefix) {
    String refPrefix = nameResolver.resolveTypeFunctionPrefix(field.getTypeReference());
    w.block(
        "if (" + accessor + ")",
        () -> {
          w.line("pbtk_buf_append(buf, \"!%dm\");", fieldNum);
          w.line("pbtk_buf_append_int(buf, %s_count_pbtk_fields(%s));", refPrefix, accessor);
          w.line("%s_append_pbtk_fields(buf, %s);", refPrefix, accessor);
        });
  }

  private void emitRepeatedSerialize(
      CodeWriter w, ProtoField field, String accessor, int fieldNum, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());
    w.block(
        "for (size_t pb_i = 0; pb_i < msg->" + fieldName + "_count; pb_i++)",
        () -> {
          if (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
            String refPrefix = nameResolver.resolveTypeFunctionPrefix(field.getTypeReference());
            w.block(
                "if (" + accessor + "[pb_i])",
                () -> {
                  w.line("pbtk_buf_append(buf, \"!%dm\");", fieldNum);
                  w.line(
                      "pbtk_buf_append_int(buf, %s_count_pbtk_fields(%s[pb_i]));",
                      refPrefix, accessor);
                  w.line("%s_append_pbtk_fields(buf, %s[pb_i]);", refPrefix, accessor);
                });
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            w.line("pbtk_buf_append(buf, \"!%de\");", fieldNum);
            w.line("pbtk_buf_append_int(buf, (int64_t)%s[pb_i]);", accessor);
          } else {
            emitScalarElementAppend(w, field, accessor + "[pb_i]", fieldNum, fieldName);
          }
        });
  }

  private void emitScalarElementAppend(
      CodeWriter w, ProtoField field, String elemAccessor, int fieldNum, String fieldName) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    switch (type) {
      case TYPE_BOOL:
        w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
        w.line("pbtk_buf_append(buf, %s ? \"1\" : \"0\");", elemAccessor);
        break;
      case TYPE_STRING:
        w.block(
            "if (" + elemAccessor + ")",
            () -> {
              w.line("char* enc = pbtk_url_encode(%s);", elemAccessor);
              w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
              w.line("if (enc) { pbtk_buf_append(buf, enc); free(enc); }");
            });
        break;
      case TYPE_BYTES:
        w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
        w.line(
            "char* b64_%s = pbtk_base64_encode(%s, msg->%s_lengths[pb_i]);",
            fieldName, elemAccessor, fieldName);
        w.line(
            "if (b64_%s) { pbtk_buf_append(buf, b64_%s); free(b64_%s); }",
            fieldName, fieldName, fieldName);
        break;
      case TYPE_DOUBLE:
        w.block(
            "if (!isnan(" + elemAccessor + ") && !isinf(" + elemAccessor + "))",
            () -> {
              w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
              w.line("pbtk_buf_append_double(buf, %s);", elemAccessor);
            });
        break;
      case TYPE_FLOAT:
        w.block(
            "if (!isnan(" + elemAccessor + ") && !isinf(" + elemAccessor + "))",
            () -> {
              w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
              w.line("pbtk_buf_append_float(buf, %s);", elemAccessor);
            });
        break;
      case TYPE_UINT32:
      case TYPE_FIXED32:
      case TYPE_UINT64:
      case TYPE_FIXED64:
        w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
        w.line("pbtk_buf_append_uint(buf, (uint64_t)%s);", elemAccessor);
        break;
      default:
        w.line("pbtk_buf_append(buf, \"!%d%s\");", fieldNum, typeChar);
        w.line("pbtk_buf_append_int(buf, (int64_t)%s);", elemAccessor);
        break;
    }
  }

  private void emitMapSerialize(
      CodeWriter w, ProtoField field, String accessor, int fieldNum, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());
    w.block(
        "for (size_t pb_i = 0; pb_i < msg->" + fieldName + "_count; pb_i++)",
        () -> {
          w.line("pbtk_buf_append(buf, \"!%dm2\");", fieldNum);
          // Key (field 1)
          String keyTypeChar = pbtkTypeChar(field.getMapKeyType());
          String keyAccessor = accessor + "[pb_i].key";
          if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("char* kenc = pbtk_url_encode(%s);", keyAccessor);
            w.line("pbtk_buf_append(buf, \"!1%s\");", keyTypeChar);
            w.line("if (kenc) { pbtk_buf_append(buf, kenc); free(kenc); }");
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("pbtk_buf_append(buf, \"!1%s\");", keyTypeChar);
            w.line("pbtk_buf_append(buf, %s ? \"1\" : \"0\");", keyAccessor);
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_UINT32
              || field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_FIXED32
              || field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_UINT64
              || field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_FIXED64) {
            w.line("pbtk_buf_append(buf, \"!1%s\");", keyTypeChar);
            w.line("pbtk_buf_append_uint(buf, (uint64_t)%s);", keyAccessor);
          } else {
            w.line("pbtk_buf_append(buf, \"!1%s\");", keyTypeChar);
            w.line("pbtk_buf_append_int(buf, (int64_t)%s);", keyAccessor);
          }
          // Value (field 2)
          String valAccessor = accessor + "[pb_i].value";
          if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
            String refPrefix =
                nameResolver.resolveTypeFunctionPrefix(field.getMapValueTypeReference());
            w.block(
                "if (" + valAccessor + ")",
                () -> {
                  w.line("pbtk_buf_append(buf, \"!2m\");");
                  w.line(
                      "pbtk_buf_append_int(buf, %s_count_pbtk_fields(%s));",
                      refPrefix, valAccessor);
                  w.line("%s_append_pbtk_fields(buf, %s);", refPrefix, valAccessor);
                });
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
            w.line("pbtk_buf_append(buf, \"!2e\");");
            w.line("pbtk_buf_append_int(buf, (int64_t)%s);", valAccessor);
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("char* venc = pbtk_url_encode(%s);", valAccessor);
            w.line("pbtk_buf_append(buf, \"!2s\");");
            w.line("if (venc) { pbtk_buf_append(buf, venc); free(venc); }");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
            w.line("char* b64_val = pbtk_base64_encode(%s, %s_len);", valAccessor, valAccessor);
            w.line("pbtk_buf_append(buf, \"!2z\");");
            w.line("if (b64_val) { pbtk_buf_append(buf, b64_val); free(b64_val); }");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("pbtk_buf_append(buf, \"!2b\");");
            w.line("pbtk_buf_append(buf, %s ? \"1\" : \"0\");", valAccessor);
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_DOUBLE) {
            w.block(
                "if (!isnan(" + valAccessor + ") && !isinf(" + valAccessor + "))",
                () -> {
                  w.line("pbtk_buf_append(buf, \"!2d\");");
                  w.line("pbtk_buf_append_double(buf, %s);", valAccessor);
                });
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_FLOAT) {
            w.block(
                "if (!isnan(" + valAccessor + ") && !isinf(" + valAccessor + "))",
                () -> {
                  w.line("pbtk_buf_append(buf, \"!2f\");");
                  w.line("pbtk_buf_append_float(buf, %s);", valAccessor);
                });
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_UINT32
              || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_FIXED32
              || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_UINT64
              || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_FIXED64) {
            w.line("pbtk_buf_append(buf, \"!2i\");");
            w.line("pbtk_buf_append_uint(buf, (uint64_t)%s);", valAccessor);
          } else {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.line("pbtk_buf_append(buf, \"!2%s\");", valTypeChar);
            w.line("pbtk_buf_append_int(buf, (int64_t)%s);", valAccessor);
          }
        });
  }

  private void emitSerializeFunction(
      CodeWriter w, ProtoMessage message, String funcPrefix, String typeName) {
    w.block(
        "char* " + funcPrefix + "_pack(const " + typeName + "* msg)",
        () -> {
          w.line("if (!msg) return NULL;");
          w.line("pbtk_buf_t buf;");
          w.line("pbtk_buf_init(&buf);");
          w.line("%s_append_pbtk_fields(&buf, msg);", funcPrefix);
          w.line("return buf.data;");
        });
    w.blankLine();
  }

  // ========================================================================
  // Deserialize implementation
  // ========================================================================

  private void emitParseTokensFunction(
      CodeWriter w, ProtoMessage message, String funcPrefix, String typeName) {
    w.block(
        "static "
            + typeName
            + "* "
            + funcPrefix
            + "_parse_pbtk_tokens(const char** tokens, int field_count, int* offset)",
        () -> {
          w.line("%s* obj = (%s*)calloc(1, sizeof(%s));", typeName, typeName, typeName);
          w.line("if (!obj) return NULL;");
          w.line("int consumed = 0;");
          w.block(
              "while (consumed < field_count && tokens[*offset])",
              () -> {
                w.line("const char* token = tokens[*offset];");
                w.line("int num_end = 0;");
                w.line("while (token[num_end] >= '0' && token[num_end] <= '9') num_end++;");
                w.line(
                    "if (num_end == 0 || token[num_end] == '\\0') { (*offset)++; consumed++; continue; }");
                w.line("char field_num_str[16];");
                w.line("if (num_end > 15) num_end = 15;");
                w.line("memcpy(field_num_str, token, num_end);");
                w.line("field_num_str[num_end] = '\\0';");
                w.line("int field_num = (int)strtol(field_num_str, NULL, 10);");
                w.line("const char* value = token + num_end + 1;");
                w.blankLine();
                w.block(
                    "switch (field_num)",
                    () -> {
                      for (ProtoField field : message.getFields()) {
                        emitFieldCase(w, field, funcPrefix);
                      }
                      w.line("default: (*offset)++; consumed++; break;");
                    });
              });
          w.line("return obj;");
        });
    w.blankLine();
  }

  private void emitFieldCase(CodeWriter w, ProtoField field, String funcPrefix) {
    int fieldNum = field.getFieldNumber();
    String fieldName = nameResolver.fieldName(field.getName());

    w.block(
        "case " + fieldNum + ":",
        () -> {
          if (field.isMap()) {
            emitMapDeserialize(w, field, funcPrefix);
          } else if (field.isRepeated()) {
            emitRepeatedDeserialize(w, field, funcPrefix);
          } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
            emitMessageDeserialize(w, field, funcPrefix);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            emitEnumDeserialize(w, field, funcPrefix);
          } else {
            emitScalarDeserialize(w, field, funcPrefix);
          }
          w.line("(*offset)++;");
          w.line("consumed++;");
          w.line("break;");
        });
  }

  private void emitScalarDeserialize(CodeWriter w, ProtoField field, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());
    String target;
    if (field.isOneofMember()) {
      target = "obj->" + nameResolver.fieldName(field.getOneofName()) + "." + fieldName;
    } else {
      target = "obj->" + fieldName;
    }
    String readExpr = scalarReadExpr(field.getProtoType(), "value", fieldName);
    w.line("%s = %s;", target, readExpr);
    if (field.isProto3Optional()) {
      w.line("obj->has_%s = true;", fieldName);
    }
    if (field.isOneofMember()) {
      String caseConst =
          funcPrefix.toUpperCase()
              + "_"
              + field.getOneofName().toUpperCase()
              + "_"
              + field.getName().toUpperCase();
      w.line("obj->%s_case = %s;", nameResolver.fieldName(field.getOneofName()), caseConst);
    }
  }

  private void emitEnumDeserialize(CodeWriter w, ProtoField field, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());
    String target;
    if (field.isOneofMember()) {
      target = "obj->" + nameResolver.fieldName(field.getOneofName()) + "." + fieldName;
    } else {
      target = "obj->" + fieldName;
    }
    w.line("%s = (int)strtol(value, NULL, 10);", target);
    if (field.isProto3Optional()) {
      w.line("obj->has_%s = true;", fieldName);
    }
    if (field.isOneofMember()) {
      String caseConst =
          funcPrefix.toUpperCase()
              + "_"
              + field.getOneofName().toUpperCase()
              + "_"
              + field.getName().toUpperCase();
      w.line("obj->%s_case = %s;", nameResolver.fieldName(field.getOneofName()), caseConst);
    }
  }

  private void emitMessageDeserialize(CodeWriter w, ProtoField field, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());
    String refPrefix = nameResolver.resolveTypeFunctionPrefix(field.getTypeReference());
    String target;
    if (field.isOneofMember()) {
      target = "obj->" + nameResolver.fieldName(field.getOneofName()) + "." + fieldName;
    } else {
      target = "obj->" + fieldName;
    }
    w.line("int sub_count = (int)strtol(value, NULL, 10);");
    w.line("(*offset)++;");
    w.line("%s = %s_parse_pbtk_tokens(tokens, sub_count, offset);", target, refPrefix);
    w.line("(*offset)--;"); // compensate for outer offset++
    if (field.isOneofMember()) {
      String caseConst =
          funcPrefix.toUpperCase()
              + "_"
              + field.getOneofName().toUpperCase()
              + "_"
              + field.getName().toUpperCase();
      w.line("obj->%s_case = %s;", nameResolver.fieldName(field.getOneofName()), caseConst);
    }
  }

  private void emitRepeatedDeserialize(CodeWriter w, ProtoField field, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());

    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      String refType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
      String refPrefix = nameResolver.resolveTypeFunctionPrefix(field.getTypeReference());
      w.line("int sub_count = (int)strtol(value, NULL, 10);");
      w.line("(*offset)++;");
      w.line("%s* pb_elem = %s_parse_pbtk_tokens(tokens, sub_count, offset);", refType, refPrefix);
      w.line("(*offset)--;");
      w.line(
          "obj->%s = (%s**)realloc(obj->%s, sizeof(%s*) * (obj->%s_count + 1));",
          fieldName, refType, fieldName, refType, fieldName);
      w.line("obj->%s[obj->%s_count++] = pb_elem;", fieldName, fieldName);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      String enumType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
      w.line(
          "obj->%s = (%s*)realloc(obj->%s, sizeof(%s) * (obj->%s_count + 1));",
          fieldName, enumType, fieldName, enumType, fieldName);
      w.line("obj->%s[obj->%s_count++] = (int)strtol(value, NULL, 10);", fieldName, fieldName);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_STRING) {
      w.line(
          "obj->%s = (char**)realloc(obj->%s, sizeof(char*) * (obj->%s_count + 1));",
          fieldName, fieldName, fieldName);
      w.line("obj->%s[obj->%s_count++] = pbtk_url_decode(value);", fieldName, fieldName);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES) {
      w.line("size_t dec_len = 0;");
      w.line("uint8_t* dec_data = pbtk_base64_decode(value, &dec_len);");
      w.line(
          "obj->%s = (uint8_t**)realloc(obj->%s, sizeof(uint8_t*) * (obj->%s_count + 1));",
          fieldName, fieldName, fieldName);
      w.line(
          "obj->%s_lengths = (size_t*)realloc(obj->%s_lengths, sizeof(size_t) * (obj->%s_count + 1));",
          fieldName, fieldName, fieldName);
      w.line("obj->%s[obj->%s_count] = dec_data;", fieldName, fieldName);
      w.line("obj->%s_lengths[obj->%s_count] = dec_len;", fieldName, fieldName);
      w.line("obj->%s_count++;", fieldName);
    } else {
      String cType = typeMapper.scalarType(field.getProtoType());
      w.line(
          "obj->%s = (%s*)realloc(obj->%s, sizeof(%s) * (obj->%s_count + 1));",
          fieldName, cType, fieldName, cType, fieldName);
      String readExpr = scalarReadExpr(field.getProtoType(), "value", fieldName);
      w.line("obj->%s[obj->%s_count++] = %s;", fieldName, fieldName, readExpr);
    }
  }

  private void emitMapDeserialize(CodeWriter w, ProtoField field, String funcPrefix) {
    String fieldName = nameResolver.fieldName(field.getName());
    String entryType = typeMapper.qualifiedMapEntryTypeName(funcPrefix, field);

    w.line("int entry_count = (int)strtol(value, NULL, 10);");
    w.line("(*offset)++;");
    // Parse key and value from the next entry_count tokens
    w.line("%s entry;", entryType);
    w.line("memset(&entry, 0, sizeof(entry));");
    w.block(
        "for (int pb_mi = 0; pb_mi < entry_count && tokens[*offset]; pb_mi++)",
        () -> {
          w.line("const char* map_token = tokens[*offset];");
          w.line("int mne = 0;");
          w.line("while (map_token[mne] >= '0' && map_token[mne] <= '9') mne++;");
          w.line("if (mne == 0 || map_token[mne] == '\\0') { (*offset)++; continue; }");
          w.line("int mfn = (int)strtol(map_token, NULL, 10);");
          w.line("const char* mval = map_token + mne + 1;");
          w.block(
              "if (mfn == 1)",
              () -> {
                // Key
                if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
                  w.line("entry.key = pbtk_url_decode(mval);");
                } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
                  w.line("entry.key = (mval[0] == '1');");
                } else {
                  w.line("entry.key = strtoll(mval, NULL, 10);");
                }
              });
          w.block(
              "if (mfn == 2)",
              () -> {
                // Value
                if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
                  String refPrefix =
                      nameResolver.resolveTypeFunctionPrefix(field.getMapValueTypeReference());
                  w.line("int val_sub_count = (int)strtol(mval, NULL, 10);");
                  w.line("(*offset)++;");
                  w.line(
                      "entry.value = %s_parse_pbtk_tokens(tokens, val_sub_count, offset);",
                      refPrefix);
                  w.line("(*offset)--;");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
                  w.line("entry.value = (int)strtol(mval, NULL, 10);");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
                  w.line("entry.value = pbtk_url_decode(mval);");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
                  w.line("entry.value = (mval[0] == '1');");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
                  w.line("entry.value = pbtk_base64_decode(mval, &entry.value_len);");
                } else {
                  w.line("entry.value = strtoll(mval, NULL, 10);");
                }
              });
          w.line("(*offset)++;");
        });
    w.line("(*offset)--;"); // compensate for outer offset++
    // Add entry to the array
    w.line(
        "obj->%s = (%s*)realloc(obj->%s, sizeof(%s) * (obj->%s_count + 1));",
        fieldName, entryType, fieldName, entryType, fieldName);
    w.line("obj->%s[obj->%s_count++] = entry;", fieldName, fieldName);
  }

  private void emitDeserializeFunction(
      CodeWriter w, ProtoMessage message, String funcPrefix, String typeName) {
    w.block(
        typeName + "* " + funcPrefix + "_unpack(const char* input)",
        () -> {
          w.line("if (!input || input[0] == '\\0') return NULL;");
          w.blankLine();
          w.line("/* Tokenize: split on '!' */");
          w.line("size_t input_len = strlen(input);");
          w.line("size_t max_tokens = input_len / 2 + 2;");
          w.line(
              "const char** tokens = (const char**)malloc(sizeof(const char*) * (max_tokens + 1));");
          w.line("if (!tokens) return NULL;");
          w.line("size_t token_count = 0;");
          w.line("const char* p = input;");
          w.line("if (*p == '!') p++;");
          w.block(
              "while (*p)",
              () -> {
                w.line("tokens[token_count++] = p;");
                w.line("const char* next = strchr(p, '!');");
                w.block(
                    "if (!next)",
                    () -> {
                      w.line("break;");
                    });
                // We need a mutable copy for null-termination -- create one
                w.line("p = next + 1;");
              });
          w.line("tokens[token_count] = NULL;");
          w.blankLine();
          w.line("/* Create a mutable copy for null-termination of tokens */");
          w.line("char* mutable_input = strdup(input);");
          w.line("if (!mutable_input) { free(tokens); return NULL; }");
          w.line("/* Re-tokenize using mutable copy */");
          w.line("token_count = 0;");
          w.line("p = mutable_input;");
          w.line("if (*p == '!') p++;");
          w.block(
              "while (*p)",
              () -> {
                w.line("tokens[token_count++] = p;");
                w.line("char* next = strchr(p, '!');");
                w.block(
                    "if (!next)",
                    () -> {
                      w.line("break;");
                    });
                w.line("*next = '\\0';");
                w.line("p = next + 1;");
              });
          w.line("tokens[token_count] = NULL;");
          w.blankLine();
          w.line("int offset = 0;");
          w.line(
              "%s* result = %s_parse_pbtk_tokens(tokens, (int)token_count, &offset);",
              typeName, funcPrefix);
          w.line("free(mutable_input);");
          w.line("free(tokens);");
          w.line("return result;");
        });
    w.blankLine();
  }

  // ========================================================================
  // Free function
  // ========================================================================

  private void emitFreeFunction(
      CodeWriter w, ProtoMessage message, String funcPrefix, String typeName, String pkg) {
    w.block(
        "void " + funcPrefix + "_free(" + typeName + "* msg)",
        () -> {
          w.line("if (!msg) return;");

          for (ProtoField field : message.getFields()) {
            if (field.isOneofMember()) continue;
            emitFieldFree(w, field, funcPrefix, pkg);
          }

          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            emitOneofFree(w, group, funcPrefix);
          }

          w.line("free(msg);");
        });
    w.blankLine();
  }

  private void emitFieldFree(CodeWriter w, ProtoField field, String funcPrefix, String pkg) {
    String fieldName = nameResolver.fieldName(field.getName());
    String accessor = "msg->" + fieldName;

    if (field.isMap()) {
      w.block(
          "if (" + accessor + ")",
          () -> {
            w.block(
                "for (size_t i = 0; i < msg->" + fieldName + "_count; i++)",
                () -> {
                  if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
                    w.line("free(%s[i].key);", accessor);
                  }
                  if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
                    w.line("free(%s[i].value);", accessor);
                  } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
                    w.line("free(%s[i].value);", accessor);
                  } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
                    String refPrefix =
                        nameResolver.resolveTypeFunctionPrefix(field.getMapValueTypeReference());
                    w.line("%s_free(%s[i].value);", refPrefix, accessor);
                  }
                });
            w.line("free(%s);", accessor);
          });
    } else if (field.isRepeated()) {
      w.block(
          "if (" + accessor + ")",
          () -> {
            if (field.getKind() == ProtoField.FieldKind.MESSAGE
                || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
              String refPrefix = nameResolver.resolveTypeFunctionPrefix(field.getTypeReference());
              w.block(
                  "for (size_t i = 0; i < msg->" + fieldName + "_count; i++)",
                  () -> {
                    w.line("%s_free(%s[i]);", refPrefix, accessor);
                  });
            } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_STRING) {
              w.block(
                  "for (size_t i = 0; i < msg->" + fieldName + "_count; i++)",
                  () -> {
                    w.line("free(%s[i]);", accessor);
                  });
            } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES) {
              w.block(
                  "for (size_t i = 0; i < msg->" + fieldName + "_count; i++)",
                  () -> {
                    w.line("free(%s[i]);", accessor);
                  });
              w.line("free(msg->%s_lengths);", fieldName);
            }
            w.line("free(%s);", accessor);
          });
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      String refPrefix = nameResolver.resolveTypeFunctionPrefix(field.getTypeReference());
      w.line("%s_free(%s);", refPrefix, accessor);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_STRING) {
      w.line("free(%s);", accessor);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES) {
      w.line("free(%s);", accessor);
    }
  }

  private void emitOneofFree(CodeWriter w, ProtoMessage.OneofGroup group, String funcPrefix) {
    String oneofField = nameResolver.fieldName(group.name());
    String caseField = "msg->" + oneofField + "_case";

    boolean hasFreeable =
        group.members().stream()
            .anyMatch(
                m ->
                    m.getKind() == ProtoField.FieldKind.MESSAGE
                        || m.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE
                        || m.getProtoType() == FieldDescriptorProto.Type.TYPE_STRING
                        || m.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES);

    if (!hasFreeable) return;

    w.block(
        "switch (" + caseField + ")",
        () -> {
          for (ProtoField member : group.members()) {
            String memberName = nameResolver.fieldName(member.getName());
            String caseConst =
                funcPrefix.toUpperCase()
                    + "_"
                    + group.name().toUpperCase()
                    + "_"
                    + member.getName().toUpperCase();
            String unionAccess = "msg->" + oneofField + "." + memberName;

            if (member.getKind() == ProtoField.FieldKind.MESSAGE
                || member.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
              String refPrefix = nameResolver.resolveTypeFunctionPrefix(member.getTypeReference());
              w.line("case %s: %s_free(%s); break;", caseConst, refPrefix, unionAccess);
            } else if (member.getProtoType() == FieldDescriptorProto.Type.TYPE_STRING) {
              w.line("case %s: free(%s); break;", caseConst, unionAccess);
            } else if (member.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES) {
              w.line("case %s: free(%s); break;", caseConst, unionAccess);
            }
          }
          w.line("default: break;");
        });
  }

  // ========================================================================
  // Nested message helpers
  // ========================================================================

  private void emitNestedMessageHeader(
      CodeWriter w,
      ProtoMessage nested,
      ProtoFile file,
      String typeName,
      String funcPrefix,
      String pkg,
      String parentPrefix) {
    for (ProtoEnum protoEnum : nested.getEnums()) {
      emitEnumDef(w, protoEnum, pkg, parentPrefix + nested.getName() + "_");
    }

    emitMapEntryTypedefs(w, nested, funcPrefix);
    emitOneofTypes(w, nested, funcPrefix, pkg);
    emitStructDef(w, nested, typeName, funcPrefix, pkg);

    w.blankLine();
    w.line("char* %s_pack(const %s* msg);", funcPrefix, typeName);
    w.line("%s* %s_unpack(const char* input);", typeName, funcPrefix);
    w.line("void %s_free(%s* msg);", funcPrefix, typeName);

    for (ProtoMessage deepNested : nested.getNestedMessages()) {
      String deepTypeName =
          nameResolver.qualifiedTypeName(
              pkg, parentPrefix + nested.getName() + "_" + deepNested.getName());
      String deepFuncPrefix =
          nameResolver.functionPrefix(
              pkg, parentPrefix + nested.getName() + "_" + deepNested.getName());
      w.blankLine();
      emitNestedMessageHeader(
          w,
          deepNested,
          file,
          deepTypeName,
          deepFuncPrefix,
          pkg,
          parentPrefix + nested.getName() + "_");
    }
  }

  private void emitNestedMessageSource(
      CodeWriter w,
      ProtoMessage nested,
      ProtoFile file,
      String typeName,
      String funcPrefix,
      String pkg,
      String parentPrefix) {
    for (ProtoMessage deepNested : nested.getNestedMessages()) {
      String deepTypeName =
          nameResolver.qualifiedTypeName(
              pkg, parentPrefix + nested.getName() + "_" + deepNested.getName());
      String deepFuncPrefix =
          nameResolver.functionPrefix(
              pkg, parentPrefix + nested.getName() + "_" + deepNested.getName());
      emitNestedMessageSource(
          w,
          deepNested,
          file,
          deepTypeName,
          deepFuncPrefix,
          pkg,
          parentPrefix + nested.getName() + "_");
    }

    emitCountFunction(w, nested, funcPrefix, typeName);
    emitAppendFieldsFunction(w, nested, funcPrefix, typeName);
    emitParseTokensFunction(w, nested, funcPrefix, typeName);
    emitSerializeFunction(w, nested, funcPrefix, typeName);
    emitDeserializeFunction(w, nested, funcPrefix, typeName);
    emitFreeFunction(w, nested, funcPrefix, typeName, pkg);
  }

  // ========================================================================
  // Shared helpers
  // ========================================================================

  private void emitEnumDef(CodeWriter w, ProtoEnum protoEnum, String pkg, String parentPrefix) {
    String enumTypeName = nameResolver.qualifiedTypeName(pkg, parentPrefix + protoEnum.getName());

    w.line("typedef enum {");
    w.indent();
    for (int i = 0; i < protoEnum.getValues().size(); i++) {
      ProtoEnum.EnumValue val = protoEnum.getValues().get(i);
      String constName = enumTypeName.toUpperCase() + "_" + val.name();
      String suffix = i < protoEnum.getValues().size() - 1 ? "," : "";
      w.line("%s = %d%s", constName, val.number(), suffix);
    }
    w.dedent();
    w.line("} %s;", enumTypeName);
    w.blankLine();
  }

  private void emitMapEntryTypedefs(CodeWriter w, ProtoMessage message, String funcPrefix) {
    for (ProtoField field : message.getFields()) {
      if (field.isMap()) {
        String entryType = typeMapper.qualifiedMapEntryTypeName(funcPrefix, field);
        String keyType = typeMapper.mapKeyType(field);
        String valType = typeMapper.mapValueType(field);

        w.line("typedef struct {");
        w.indent();
        w.line("%s key;", keyType);
        w.line("%s value;", valType);
        w.dedent();
        w.line("} %s;", entryType);
        w.blankLine();
      }
    }
  }

  private void emitOneofTypes(CodeWriter w, ProtoMessage message, String funcPrefix, String pkg) {
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String enumName = funcPrefix.toUpperCase() + "_" + group.name().toUpperCase() + "_CASE";
      w.line("typedef enum {");
      w.indent();
      w.line("%s_NOT_SET = 0,", funcPrefix.toUpperCase() + "_" + group.name().toUpperCase());
      for (ProtoField member : group.members()) {
        String constName =
            funcPrefix.toUpperCase()
                + "_"
                + group.name().toUpperCase()
                + "_"
                + member.getName().toUpperCase();
        w.line("%s = %d,", constName, member.getFieldNumber());
      }
      w.dedent();
      w.line("} %s;", enumName);
      w.blankLine();

      String unionName = funcPrefix + "_" + group.name() + "_union";
      w.line("typedef union {");
      w.indent();
      for (ProtoField member : group.members()) {
        String memberField = nameResolver.fieldName(member.getName());
        String memberType = resolveFieldType(member);
        w.line("%s %s;", memberType, memberField);
      }
      w.dedent();
      w.line("} %s;", unionName);
      w.blankLine();
    }
  }

  private void emitStructDef(
      CodeWriter w, ProtoMessage message, String typeName, String funcPrefix, String pkg) {
    w.line("typedef struct {");
    w.indent();

    for (ProtoField field : message.getFields()) {
      if (field.isOneofMember()) continue;
      String fieldName = nameResolver.fieldName(field.getName());

      if (field.isMap()) {
        String entryType = typeMapper.qualifiedMapEntryTypeName(funcPrefix, field);
        w.line("%s* %s;", entryType, fieldName);
        w.line("size_t %s_count;", fieldName);
      } else if (field.isRepeated()) {
        String elemType = resolveFieldType(field);
        if (field.getKind() == ProtoField.FieldKind.MESSAGE
            || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
          w.line("%s* %s;", elemType, fieldName);
        } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_STRING) {
          w.line("char** %s;", fieldName);
        } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES) {
          w.line("uint8_t** %s;", fieldName);
          w.line("size_t* %s_lengths;", fieldName);
        } else {
          w.line("%s* %s;", typeMapper.scalarType(field.getProtoType()), fieldName);
        }
        w.line("size_t %s_count;", fieldName);
      } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
          || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
        String refType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
        w.line("%s* %s;", refType, fieldName);
      } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
        String enumType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
        w.line("%s %s;", enumType, fieldName);
      } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES) {
        w.line("uint8_t* %s;", fieldName);
        w.line("size_t %s_len;", fieldName);
      } else {
        w.line("%s %s;", typeMapper.scalarType(field.getProtoType()), fieldName);
      }

      if (field.isProto3Optional()) {
        w.line("bool has_%s;", fieldName);
      }
    }

    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String oneofField = nameResolver.fieldName(group.name());
      String unionType = funcPrefix + "_" + group.name() + "_union";
      String caseEnumType = funcPrefix.toUpperCase() + "_" + group.name().toUpperCase() + "_CASE";
      w.line("%s %s;", unionType, oneofField);
      w.line("%s %s_case;", caseEnumType, oneofField);
    }

    w.dedent();
    w.line("} %s;", typeName);
  }

  private void emitCrossFileIncludes(CodeWriter w, ProtoMessage message, ProtoFile file) {
    Set<String> includes = new LinkedHashSet<>();
    collectCrossFileIncludes(message, file, includes);
    for (String inc : includes) {
      w.line(inc);
    }
  }

  private void collectCrossFileIncludes(
      ProtoMessage message, ProtoFile file, Set<String> includes) {
    String pkg = nameResolver.resolvePackage(file);
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      collectTypeInclude(
          field.getTypeReference(), field, message, file, currentPrefix, pkg, includes);
      if (field.isMap() && field.getMapValueTypeReference() != null) {
        collectTypeInclude(
            field.getMapValueTypeReference(), null, message, file, currentPrefix, pkg, includes);
      }
    }

    for (ProtoMessage nested : message.getNestedMessages()) {
      collectCrossFileIncludes(nested, file, includes);
    }
  }

  private void collectTypeInclude(
      String typeRef,
      ProtoField field,
      ProtoMessage message,
      ProtoFile file,
      String currentPrefix,
      String pkg,
      Set<String> includes) {
    if (typeRef == null) return;
    if (field != null && field.isWellKnownType()) return;

    for (ProtoMessage nested : message.getNestedMessages()) {
      if (typeRef.equals(message.getFullName() + "." + nested.getName())) return;
    }

    if (typeRef.startsWith(currentPrefix)) {
      String simpleName = ProtoTypeUtil.simpleTypeName(typeRef);
      if (simpleName.equals(message.getName())) return;
      String snakeName = pascalToSnake(simpleName);
      String dir = pkg.isEmpty() ? "" : pkg.replace('.', '/') + "/";
      includes.add("#include \"" + dir + snakeName + ".h\"");
    }
  }

  private String resolveFieldType(ProtoField field) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      return nameResolver.resolveTypeReference(field.getTypeReference(), null) + "*";
    }
    if (field.getKind() == ProtoField.FieldKind.ENUM) {
      return nameResolver.resolveTypeReference(field.getTypeReference(), null);
    }
    return typeMapper.scalarType(field.getProtoType());
  }

  private String scalarReadExpr(FieldDescriptorProto.Type type, String valueVar, String fieldName) {
    return switch (type) {
      case TYPE_DOUBLE -> "strtod(" + valueVar + ", NULL)";
      case TYPE_FLOAT -> "(float)strtod(" + valueVar + ", NULL)";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64 -> "strtoll(" + valueVar + ", NULL, 10)";
      case TYPE_UINT64, TYPE_FIXED64 -> "strtoull(" + valueVar + ", NULL, 10)";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32 -> "(int32_t)strtol(" + valueVar + ", NULL, 10)";
      case TYPE_UINT32, TYPE_FIXED32 -> "(uint32_t)strtoul(" + valueVar + ", NULL, 10)";
      case TYPE_BOOL -> "(" + valueVar + "[0] == '1')";
      case TYPE_STRING -> "pbtk_url_decode(" + valueVar + ")";
      case TYPE_BYTES -> "pbtk_base64_decode(" + valueVar + ", &obj->" + fieldName + "_len)";
      default -> valueVar;
    };
  }

  /** Convert PascalCase to snake_case. Local copy to avoid package-private access. */
  private static String pascalToSnake(String pascal) {
    if (pascal == null || pascal.isEmpty()) return pascal;
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < pascal.length(); i++) {
      char c = pascal.charAt(i);
      if (Character.isUpperCase(c)) {
        if (i > 0) {
          char prev = pascal.charAt(i - 1);
          if (!Character.isUpperCase(prev)) {
            sb.append('_');
          } else if (i + 1 < pascal.length() && !Character.isUpperCase(pascal.charAt(i + 1))) {
            sb.append('_');
          }
        }
        sb.append(Character.toLowerCase(c));
      } else {
        sb.append(c);
      }
    }
    return sb.toString();
  }

  static String pbtkTypeChar(FieldDescriptorProto.Type type) {
    return switch (type) {
      case TYPE_BOOL -> "b";
      case TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64 ->
          "i";
      case TYPE_FLOAT -> "f";
      case TYPE_DOUBLE -> "d";
      case TYPE_STRING -> "s";
      case TYPE_ENUM -> "e";
      case TYPE_MESSAGE -> "m";
      case TYPE_BYTES -> "z";
      default -> "s";
    };
  }
}
