/*
 * Copyright 2024 protobuf-text-codecs contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.pbtkurl.codegen.csharp;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.LanguageGenerator;
import dev.protocgen.textcodecs.jsonarray.codegen.csharp.CSharpNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.csharp.CSharpTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import dev.protocgen.textcodecs.jsonarray.model.TypeRegistry;
import java.util.ArrayList;
import java.util.List;

/**
 * C# language code generator for pbtk URL encoding. Produces C# source files with
 * ToPbtkUrl()/FromPbtkUrl() serialization methods using pure string manipulation (StringBuilder,
 * Uri.EscapeDataString).
 */
public class PbtkCSharpGenerator implements LanguageGenerator {

  private static final String GENERATED_MARKER =
      "// @generated by protoc-gen-pbtkurl \u2014 do not edit.";

  private final CSharpNameResolver nameResolver = new CSharpNameResolver();
  private final CSharpTypeMapper typeMapper = new CSharpTypeMapper();

  @Override
  public List<CodeGeneratorResponse.File> generate(ProtoFile file, TypeRegistry registry) {
    List<CodeGeneratorResponse.File> result = new ArrayList<>();

    for (ProtoMessage message : file.getMessages()) {
      nameResolver.validateFieldNames(message.getFields());
      String sourceCode = emitMessage(message, file);
      String outputPath = nameResolver.outputFilePath(file, message.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    for (ProtoEnum protoEnum : file.getEnums()) {
      String sourceCode = emitTopLevelEnum(protoEnum, file);
      String outputPath = nameResolver.outputFilePath(file, protoEnum.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    return result;
  }

  // ---------------------------------------------------------------------------
  // Top-level message emission
  // ---------------------------------------------------------------------------

  private String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String ns = nameResolver.resolvePackage(file);
    String className = nameResolver.messageClassName(message.getName());

    w.line(GENERATED_MARKER);
    w.blankLine();
    // Using declarations
    w.line("using System;");
    w.line("using System.Collections.Generic;");
    w.line("using System.Linq;");
    w.line("using System.Text;");

    if (!ns.isEmpty()) {
      w.blankLine();
      w.block(
          "namespace " + ns,
          () -> {
            emitDocComment(w, message.getComment());
            w.block(
                "public sealed class " + className,
                () -> {
                  emitMessageBody(w, message, className, file);
                });
          });
    } else {
      w.blankLine();
      emitDocComment(w, message.getComment());
      w.block(
          "public sealed class " + className,
          () -> {
            emitMessageBody(w, message, className, file);
          });
    }

    return w.toString();
  }

  private String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String ns = nameResolver.resolvePackage(file);

    w.line(GENERATED_MARKER);
    w.blankLine();

    if (!ns.isEmpty()) {
      w.block("namespace " + ns, () -> emitEnum(w, protoEnum));
    } else {
      emitEnum(w, protoEnum);
    }
    return w.toString();
  }

  // ---------------------------------------------------------------------------
  // Message body
  // ---------------------------------------------------------------------------

  private void emitMessageBody(
      CodeWriter w, ProtoMessage message, String className, ProtoFile file) {
    // Field number constants
    for (ProtoField field : message.getFields()) {
      String constName = snakeToUpperSnake(field.getName()) + "_FIELD_NUMBER";
      w.line("public const int %s = %d;", constName, field.getFieldNumber());
    }

    // Private readonly fields
    w.blankLine();
    for (ProtoField field : message.getFields()) {
      String csType = typeMapper.languageType(field);
      String csName = nameResolver.fieldName(field.getName());
      w.line("private readonly %s %s;", csType, csName);
    }

    // Presence tracking
    if (hasPresenceTrackedFields(message)) {
      w.blankLine();
      w.line("private readonly bool[] presentFields_;");
    }

    // Oneof case tracking
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      w.blankLine();
      String caseName = nameResolver.fieldName(group.name()) + "Case_";
      w.line("private readonly int %s;", caseName);
      for (ProtoField member : group.members()) {
        w.line(
            "private const int %sCase_ = %d;",
            member.getName().toUpperCase(), member.getFieldNumber());
      }
    }

    // Private constructor
    emitPrivateConstructor(w, message, className);

    // Default instance
    w.blankLine();
    w.line("private static readonly %s DefaultInstance_ = new Builder().Build();", className);
    w.blankLine();
    w.block(
        "public static " + className + " GetDefaultInstance()",
        () -> w.line("return DefaultInstance_;"));

    // Properties
    emitProperties(w, message);

    // Oneof case enums
    emitOneofCaseEnums(w, message);

    // Builder factory methods
    w.blankLine();
    w.block("public static Builder NewBuilder()", () -> w.line("return new Builder();"));
    w.blankLine();
    w.block(
        "public static Builder NewBuilder(" + className + " prototype)",
        () -> w.line("return new Builder(prototype);"));
    w.blankLine();
    w.block("public Builder ToBuilder()", () -> w.line("return new Builder(this);"));

    // Builder class
    emitBuilderClass(w, message, className);

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
    }

    // Nested messages
    for (ProtoMessage nested : message.getNestedMessages()) {
      w.blankLine();
      emitNestedMessage(w, nested, file);
    }

    // Serialize (pbtk URL)
    emitSerializer(w, message);

    // Deserialize (pbtk URL)
    emitDeserializer(w, message, className);

    // ToString
    emitToString(w, message, className);

    // Equals and GetHashCode
    emitEquals(w, message, className);
    emitHashCode(w, message);
  }

  // ---------------------------------------------------------------------------
  // Serializer
  // ---------------------------------------------------------------------------

  private void emitSerializer(CodeWriter w, ProtoMessage message) {
    // AppendPbtkFields
    w.blankLine();
    w.block(
        "internal void AppendPbtkFields(StringBuilder sb)",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldSerialize(w, field);
          }
        });

    // CountPbtkFields
    w.blankLine();
    w.block(
        "internal int CountPbtkFields()",
        () -> {
          w.line("int count = 0;");
          for (ProtoField field : message.getFields()) {
            emitFieldCount(w, field);
          }
          w.line("return count;");
        });

    // Public ToPbtkUrl
    w.blankLine();
    w.block(
        "public string ToPbtkUrl()",
        () -> {
          w.line("var sb = new StringBuilder();");
          w.line("AppendPbtkFields(sb);");
          w.line("return sb.ToString();");
        });
  }

  private void emitFieldSerialize(CodeWriter w, ProtoField field) {
    String csField = "this." + nameResolver.fieldName(field.getName());
    int fieldNum = field.getFieldNumber();

    if (field.isOneofMember()) {
      String caseName = nameResolver.fieldName(field.getOneofName()) + "Case_";
      String enumConst = field.getName().toUpperCase() + "Case_";
      w.block(
          "if (" + caseName + " == " + enumConst + ")",
          () -> emitSingleFieldSerialize(w, field, csField, fieldNum));
      return;
    }

    if (field.isMap()) {
      emitMapSerialize(w, field, csField, fieldNum);
    } else if (field.isRepeated()) {
      emitRepeatedSerialize(w, field, csField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      emitMessageSerialize(w, field, csField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, csField, fieldNum);
    } else {
      emitScalarSerialize(w, field, csField, fieldNum);
    }
  }

  private void emitSingleFieldSerialize(
      CodeWriter w, ProtoField field, String csField, int fieldNum) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      emitMessageSerialize(w, field, csField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, csField, fieldNum);
    } else {
      emitScalarSerialize(w, field, csField, fieldNum);
    }
  }

  private void emitScalarSerialize(CodeWriter w, ProtoField field, String csField, int fieldNum) {
    if (field.hasExplicitPresence() && !field.isRequired()) {
      String bitCheck = "presentFields_[" + field.getArrayPosition() + "]";
      w.block("if (" + bitCheck + ")", () -> emitScalarAppend(w, field, csField, fieldNum));
      return;
    }
    emitScalarAppend(w, field, csField, fieldNum);
  }

  private void emitScalarAppend(CodeWriter w, ProtoField field, String csField, int fieldNum) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    switch (type) {
      case TYPE_BOOL:
        w.line("sb.Append(\"!%d%s\").Append(%s ? \"1\" : \"0\");", fieldNum, typeChar, csField);
        break;
      case TYPE_BYTES:
        w.line(
            "sb.Append(\"!%d%s\").Append(Convert.ToBase64String(%s));",
            fieldNum, typeChar, csField);
        break;
      case TYPE_STRING:
        w.line(
            "sb.Append(\"!%d%s\").Append(Uri.EscapeDataString(%s));", fieldNum, typeChar, csField);
        break;
      case TYPE_DOUBLE:
        w.block(
            "if (!double.IsNaN(" + csField + ") && !double.IsInfinity(" + csField + "))",
            () -> w.line("sb.Append(\"!%d%s\").Append(%s);", fieldNum, typeChar, csField));
        break;
      case TYPE_FLOAT:
        w.block(
            "if (!float.IsNaN(" + csField + ") && !float.IsInfinity(" + csField + "))",
            () -> w.line("sb.Append(\"!%d%s\").Append(%s);", fieldNum, typeChar, csField));
        break;
      default:
        w.line("sb.Append(\"!%d%s\").Append(%s);", fieldNum, typeChar, csField);
        break;
    }
  }

  private void emitEnumSerialize(CodeWriter w, ProtoField field, String csField, int fieldNum) {
    if (field.hasExplicitPresence() && !field.isRequired()) {
      String bitCheck = "presentFields_[" + field.getArrayPosition() + "]";
      w.block(
          "if (" + bitCheck + ")",
          () -> w.line("sb.Append(\"!%de\").Append((int)%s);", fieldNum, csField));
    } else {
      w.line("sb.Append(\"!%de\").Append((int)%s);", fieldNum, csField);
    }
  }

  private void emitMessageSerialize(CodeWriter w, ProtoField field, String csField, int fieldNum) {
    w.block(
        "if (" + csField + " != null)",
        () -> {
          w.line("sb.Append(\"!%dm\").Append(%s.CountPbtkFields());", fieldNum, csField);
          w.line("%s.AppendPbtkFields(sb);", csField);
        });
  }

  private void emitRepeatedSerialize(CodeWriter w, ProtoField field, String csField, int fieldNum) {
    String elementVar = "__" + nameResolver.fieldName(field.getName()) + "Item";
    String boxedType = elementType(field);
    w.block(
        "foreach (" + boxedType + " " + elementVar + " in " + csField + ")",
        () -> {
          if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
            w.block(
                "if (" + elementVar + " != null)",
                () -> {
                  w.line("sb.Append(\"!%dm\").Append(%s.CountPbtkFields());", fieldNum, elementVar);
                  w.line("%s.AppendPbtkFields(sb);", elementVar);
                });
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            w.line("sb.Append(\"!%de\").Append((int)%s);", fieldNum, elementVar);
          } else {
            emitScalarAppend(w, field, elementVar, fieldNum);
          }
        });
  }

  private void emitMapSerialize(CodeWriter w, ProtoField field, String csField, int fieldNum) {
    String entryVar = "__" + nameResolver.fieldName(field.getName()) + "Entry";
    w.block(
        "foreach (var " + entryVar + " in " + csField + ")",
        () -> {
          w.line("sb.Append(\"!%dm2\");", fieldNum);

          // Key (field 1)
          String keyTypeChar = pbtkTypeChar(field.getMapKeyType());
          if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line(
                "sb.Append(\"!1%s\").Append(Uri.EscapeDataString(%s.Key));", keyTypeChar, entryVar);
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("sb.Append(\"!1%s\").Append(%s.Key ? \"1\" : \"0\");", keyTypeChar, entryVar);
          } else {
            w.line("sb.Append(\"!1%s\").Append(%s.Key);", keyTypeChar, entryVar);
          }

          // Value (field 2)
          if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
            String msgType = simpleTypeName(field.getMapValueTypeReference());
            w.line(
                "if (%s.Value != null) { sb.Append(\"!2m\").Append(%s.Value.CountPbtkFields()); %s.Value.AppendPbtkFields(sb); }",
                entryVar, entryVar, entryVar);
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
            w.line("sb.Append(\"!2e\").Append((int)%s.Value);", entryVar);
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("sb.Append(\"!2s\").Append(Uri.EscapeDataString(%s.Value));", entryVar);
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
            w.line("sb.Append(\"!2z\").Append(Convert.ToBase64String(%s.Value));", entryVar);
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("sb.Append(\"!2b\").Append(%s.Value ? \"1\" : \"0\");", entryVar);
          } else {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.line("sb.Append(\"!2%s\").Append(%s.Value);", valTypeChar, entryVar);
          }
        });
  }

  private void emitFieldCount(CodeWriter w, ProtoField field) {
    String csField = "this." + nameResolver.fieldName(field.getName());

    if (field.isOneofMember()) {
      String caseName = nameResolver.fieldName(field.getOneofName()) + "Case_";
      String enumConst = field.getName().toUpperCase() + "Case_";
      w.line("if (%s == %s) count++;", caseName, enumConst);
      return;
    }

    if (field.isMap()) {
      w.line("count += %s.Count;", csField);
    } else if (field.isRepeated()) {
      if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
        w.line("count += %s.Count(x => x != null);", csField);
      } else {
        w.line("count += %s.Count;", csField);
      }
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      w.line("if (%s != null) count++;", csField);
    } else if (field.hasExplicitPresence() && !field.isRequired()) {
      w.line("if (presentFields_[%d]) count++;", field.getArrayPosition());
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_DOUBLE) {
      w.line("if (!double.IsNaN(%s) && !double.IsInfinity(%s)) count++;", csField, csField);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_FLOAT) {
      w.line("if (!float.IsNaN(%s) && !float.IsInfinity(%s)) count++;", csField, csField);
    } else {
      w.line("count++;");
    }
  }

  // ---------------------------------------------------------------------------
  // Deserializer
  // ---------------------------------------------------------------------------

  private void emitDeserializer(CodeWriter w, ProtoMessage message, String className) {
    // Internal parser that takes a token list and offset
    emitParseFromTokens(w, message, className);

    // Public FromPbtkUrl
    w.blankLine();
    w.block(
        "public static " + className + " FromPbtkUrl(string input)",
        () -> {
          w.line("if (string.IsNullOrEmpty(input)) return %s.GetDefaultInstance();", className);
          w.line("var tokens = TokenizePbtk(input);");
          w.line("int[] offset = {0};");
          w.line("return ParsePbtkTokens(tokens, tokens.Count, offset);");
        });

    // Tokenizer
    w.blankLine();
    w.block(
        "private static List<string> TokenizePbtk(string input)",
        () -> {
          w.line("var tokens = new List<string>();");
          w.line("int i = 0;");
          w.line("if (input[0] == '!') i = 1;");
          w.block(
              "while (i < input.Length)",
              () -> {
                w.line("int next = input.IndexOf('!', i);");
                w.block(
                    "if (next < 0)",
                    () -> {
                      w.line("tokens.Add(input.Substring(i));");
                      w.line("break;");
                    });
                w.line("tokens.Add(input.Substring(i, next - i));");
                w.line("i = next + 1;");
              });
          w.line("return tokens;");
        });
  }

  private void emitParseFromTokens(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "internal static "
            + className
            + " ParsePbtkTokens(List<string> tokens, int fieldCount, int[] offset)",
        () -> {
          w.line("var builder = %s.NewBuilder();", className);
          w.line("int consumed = 0;");
          w.block(
              "while (consumed < fieldCount && offset[0] < tokens.Count)",
              () -> {
                w.line("string token = tokens[offset[0]];");
                w.line("int numEnd = 0;");
                w.line("while (numEnd < token.Length && char.IsDigit(token[numEnd])) numEnd++;");
                w.line(
                    "if (numEnd == 0 || numEnd >= token.Length) { offset[0]++; consumed++; continue; }");
                w.line("int fieldNum = int.Parse(token.Substring(0, numEnd));");
                w.line("char typeChar = token[numEnd];");
                w.line("string value = token.Substring(numEnd + 1);");

                w.block(
                    "switch (fieldNum)",
                    () -> {
                      for (ProtoField field : message.getFields()) {
                        emitFieldCase(w, field);
                      }
                      w.line("default: offset[0]++; consumed++; break;");
                    });
              });
          w.line("return builder.Build();");
        });
  }

  private void emitFieldCase(CodeWriter w, ProtoField field) {
    int fieldNum = field.getFieldNumber();
    String setterCall = "builder.Set" + CSharpNameResolver.snakeToPascal(field.getName());

    w.block(
        "case " + fieldNum + ":",
        () -> {
          if (field.isMap()) {
            emitMapDeserialize(w, field);
          } else if (field.isRepeated()) {
            emitRepeatedDeserialize(w, field);
          } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
            emitMsgDeserialize(w, field, setterCall);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            emitEnumDeserialize(w, field, setterCall);
          } else {
            emitScalarDeserialize(w, field, setterCall);
          }
          w.line("offset[0]++;");
          w.line("consumed++;");
          w.line("break;");
        });
  }

  private void emitScalarDeserialize(CodeWriter w, ProtoField field, String setterCall) {
    String readExpr = scalarReadExpr(field.getProtoType(), "value");
    w.line("%s(%s);", setterCall, readExpr);
  }

  private void emitEnumDeserialize(CodeWriter w, ProtoField field, String setterCall) {
    String enumType = simpleTypeName(field.getTypeReference());
    w.line("%s((%s)int.Parse(value));", setterCall, enumType);
  }

  private void emitMsgDeserialize(CodeWriter w, ProtoField field, String setterCall) {
    String msgType = simpleTypeName(field.getTypeReference());
    w.line("int subCount = int.Parse(value);");
    w.line("offset[0]++;");
    w.line("%s(%s.ParsePbtkTokens(tokens, subCount, offset));", setterCall, msgType);
    w.line("offset[0]--;");
  }

  private void emitRepeatedDeserialize(CodeWriter w, ProtoField field) {
    String addCall = "builder.Add" + CSharpNameResolver.snakeToPascal(field.getName());
    if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      String msgType = simpleTypeName(field.getTypeReference());
      w.line("int subCount = int.Parse(value);");
      w.line("offset[0]++;");
      w.line("%s(%s.ParsePbtkTokens(tokens, subCount, offset));", addCall, msgType);
      w.line("offset[0]--;");
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      String enumType = simpleTypeName(field.getTypeReference());
      w.line("%s((%s)int.Parse(value));", addCall, enumType);
    } else {
      String readExpr = scalarReadExpr(field.getProtoType(), "value");
      w.line("%s(%s);", addCall, readExpr);
    }
  }

  private void emitMapDeserialize(CodeWriter w, ProtoField field) {
    String putCall = "builder.Put" + CSharpNameResolver.snakeToPascal(field.getName());
    w.line("int entryCount = int.Parse(value);");
    w.line("offset[0]++;");
    w.line("object entryKey = null;");
    w.line("object entryVal = null;");
    w.block(
        "for (int __mi = 0; __mi < entryCount && offset[0] < tokens.Count; __mi++)",
        () -> {
          w.line("string mapToken = tokens[offset[0]];");
          w.line("int mne = 0;");
          w.line("while (mne < mapToken.Length && char.IsDigit(mapToken[mne])) mne++;");
          w.line("if (mne == 0 || mne >= mapToken.Length) { offset[0]++; continue; }");
          w.line("int mfn = int.Parse(mapToken.Substring(0, mne));");
          w.line("string mval = mapToken.Substring(mne + 1);");
          w.block(
              "if (mfn == 1)",
              () -> {
                String keyRead = scalarReadExpr(field.getMapKeyType(), "mval");
                w.line("entryKey = %s;", keyRead);
              });
          w.block(
              "if (mfn == 2)",
              () -> {
                if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
                  String msgType = simpleTypeName(field.getMapValueTypeReference());
                  w.line("int valSubCount = int.Parse(mval);");
                  w.line("offset[0]++;");
                  w.line("entryVal = %s.ParsePbtkTokens(tokens, valSubCount, offset);", msgType);
                  w.line("offset[0]--;");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
                  String enumType = simpleTypeName(field.getMapValueTypeReference());
                  w.line("entryVal = (%s)int.Parse(mval);", enumType);
                } else {
                  String valRead = scalarReadExpr(field.getMapValueType(), "mval");
                  w.line("entryVal = %s;", valRead);
                }
              });
          w.line("offset[0]++;");
        });
    w.line("offset[0]--;");
    // Put the entry
    String keyCast = mapKeyCast(field.getMapKeyType());
    String valCast = mapValueCast(field);
    w.line("if (entryKey != null) %s(%s, %s);", putCall, keyCast, valCast);
  }

  // ---------------------------------------------------------------------------
  // Shared structure emission
  // ---------------------------------------------------------------------------

  private void emitPrivateConstructor(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "private " + className + "(Builder builder)",
        () -> {
          for (ProtoField field : message.getFields()) {
            String csName = nameResolver.fieldName(field.getName());
            if (field.isRepeated()) {
              w.line(
                  "this.%s = new List<%s>(builder.%s).AsReadOnly();",
                  csName, elementType(field), csName);
            } else if (field.isMap()) {
              w.line(
                  "this.%s = new Dictionary<%s>(builder.%s);",
                  csName, mapGenericArgs(field), csName);
            } else {
              w.line("this.%s = builder.%s;", csName, csName);
            }
          }
          if (hasPresenceTrackedFields(message)) {
            w.line("this.presentFields_ = (bool[])builder.presentFields_.Clone();");
          }
          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            String caseName = nameResolver.fieldName(group.name()) + "Case_";
            w.line("this.%s = builder.%s;", caseName, caseName);
          }
        });
  }

  private void emitProperties(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String csType = typeMapper.languageType(field);
      String csName = nameResolver.fieldName(field.getName());
      String pascalName = CSharpNameResolver.snakeToPascal(field.getName());

      w.blankLine();
      emitDocComment(w, field.getComment());
      if (field.getKind() == ProtoField.FieldKind.MESSAGE
          && !field.isRepeated()
          && !field.isMap()) {
        String msgType = simpleTypeName(field.getTypeReference());
        w.line(
            "public %s %s => this.%s ?? %s.GetDefaultInstance();",
            csType, pascalName, csName, msgType);
      } else {
        w.line("public %s %s => this.%s;", csType, pascalName, csName);
      }

      // Has method for message fields and presence-tracked fields
      if (field.hasExplicitPresence() || field.getKind() == ProtoField.FieldKind.MESSAGE) {
        w.blankLine();
        if (field.hasExplicitPresence()) {
          w.line(
              "public bool Has%s => this.presentFields_[%d];",
              pascalName, field.getArrayPosition());
        } else {
          w.line("public bool Has%s => this.%s != null;", pascalName, csName);
        }
      }
    }

    // Oneof case getters
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String pascalOneof = CSharpNameResolver.snakeToPascal(group.name());
      String enumName = pascalOneof + "Case";
      String caseName = nameResolver.fieldName(group.name()) + "Case_";
      w.blankLine();
      w.block(
          "public " + enumName + " Get" + pascalOneof + "Case()",
          () -> w.line("return (%s)%s;", enumName, caseName));
    }
  }

  private void emitOneofCaseEnums(CodeWriter w, ProtoMessage message) {
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      w.blankLine();
      String enumName = CSharpNameResolver.snakeToPascal(group.name()) + "Case";
      w.block(
          "public enum " + enumName,
          () -> {
            w.line("%sNotSet = 0,", CSharpNameResolver.snakeToPascal(group.name()));
            for (int i = 0; i < group.members().size(); i++) {
              ProtoField member = group.members().get(i);
              String suffix = i < group.members().size() - 1 ? "," : "";
              w.line(
                  "%s = %d%s",
                  CSharpNameResolver.snakeToPascal(member.getName()),
                  member.getFieldNumber(),
                  suffix);
            }
          });
    }
  }

  private void emitBuilderClass(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "public sealed class Builder",
        () -> {
          for (ProtoField field : message.getFields()) {
            String csType = typeMapper.languageType(field);
            String csName = nameResolver.fieldName(field.getName());
            String defaultVal = typeMapper.defaultValue(field);
            w.line("internal %s %s = %s;", csType, csName, defaultVal);
          }

          if (hasPresenceTrackedFields(message)) {
            w.blankLine();
            int maxBit = maxPresenceBit(message);
            w.line("internal bool[] presentFields_ = new bool[%d];", maxBit + 1);
          }

          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            w.blankLine();
            String caseName = nameResolver.fieldName(group.name()) + "Case_";
            w.line("internal int %s = 0;", caseName);
          }

          w.blankLine();
          w.block("internal Builder()", () -> {});

          w.blankLine();
          w.block(
              "internal Builder(" + className + " prototype)",
              () -> {
                for (ProtoField field : message.getFields()) {
                  String csName = nameResolver.fieldName(field.getName());
                  if (field.isRepeated()) {
                    w.line(
                        "this.%s = new List<%s>(prototype.%s);",
                        csName, elementType(field), csName);
                  } else if (field.isMap()) {
                    w.line(
                        "this.%s = new Dictionary<%s>(prototype.%s);",
                        csName, mapGenericArgs(field), csName);
                  } else {
                    w.line("this.%s = prototype.%s;", csName, csName);
                  }
                }
                if (hasPresenceTrackedFields(message)) {
                  w.line("this.presentFields_ = (bool[])prototype.presentFields_.Clone();");
                }
                for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
                  String caseName = nameResolver.fieldName(group.name()) + "Case_";
                  w.line("this.%s = prototype.%s;", caseName, caseName);
                }
              });

          // Setters, clearers, add/put methods
          for (ProtoField field : message.getFields()) {
            String csType = typeMapper.languageType(field);
            String csName = nameResolver.fieldName(field.getName());
            String pascalName = CSharpNameResolver.snakeToPascal(field.getName());

            // Set method
            w.blankLine();
            w.block(
                "public Builder Set" + pascalName + "(" + csType + " " + csName + ")",
                () -> {
                  w.line("this.%s = %s;", csName, csName);
                  if (field.hasExplicitPresence()) {
                    w.line("this.presentFields_[%d] = true;", field.getArrayPosition());
                  }
                  if (field.isOneofMember()) {
                    w.line(
                        "this.%sCase_ = %sCase_;",
                        nameResolver.fieldName(field.getOneofName()),
                        field.getName().toUpperCase());
                  }
                  w.line("return this;");
                });

            // Clear method
            w.blankLine();
            w.block(
                "public Builder Clear" + pascalName + "()",
                () -> {
                  String defaultVal = typeMapper.defaultValue(field);
                  w.line("this.%s = %s;", csName, defaultVal);
                  if (field.hasExplicitPresence()) {
                    w.line("this.presentFields_[%d] = false;", field.getArrayPosition());
                  }
                  if (field.isOneofMember()) {
                    String caseN = nameResolver.fieldName(field.getOneofName()) + "Case_";
                    w.block(
                        "if (this." + caseN + " == " + field.getName().toUpperCase() + "Case_)",
                        () -> w.line("this.%s = 0;", caseN));
                  }
                  w.line("return this;");
                });

            // Repeated: add / addAll
            if (field.isRepeated()) {
              String elemType = elementType(field);
              w.blankLine();
              w.block(
                  "public Builder Add" + pascalName + "(" + elemType + " value)",
                  () -> {
                    w.line("this.%s.Add(value);", csName);
                    w.line("return this;");
                  });
              w.blankLine();
              w.block(
                  "public Builder AddAll" + pascalName + "(IEnumerable<" + elemType + "> values)",
                  () -> {
                    w.block("foreach (var v in values)", () -> w.line("this.%s.Add(v);", csName));
                    w.line("return this;");
                  });
            }

            // Map: put / putAll / remove
            if (field.isMap()) {
              String keyType = typeMapper.boxedScalarType(field.getMapKeyType());
              String valueType = mapValueType(field);
              w.blankLine();
              w.block(
                  "public Builder Put"
                      + pascalName
                      + "("
                      + keyType
                      + " key, "
                      + valueType
                      + " value)",
                  () -> {
                    w.line("this.%s[key] = value;", csName);
                    w.line("return this;");
                  });
              w.blankLine();
              w.block(
                  "public Builder PutAll"
                      + pascalName
                      + "(Dictionary<"
                      + keyType
                      + ", "
                      + valueType
                      + "> values)",
                  () -> {
                    w.block(
                        "foreach (var kvp in values)",
                        () -> w.line("this.%s[kvp.Key] = kvp.Value;", csName));
                    w.line("return this;");
                  });
              w.blankLine();
              w.block(
                  "public Builder Remove" + pascalName + "(" + keyType + " key)",
                  () -> {
                    w.line("this.%s.Remove(key);", csName);
                    w.line("return this;");
                  });
            }
          }

          // Clear all
          w.blankLine();
          w.block(
              "public Builder Clear()",
              () -> {
                for (ProtoField field : message.getFields()) {
                  String csName = nameResolver.fieldName(field.getName());
                  String defaultVal = typeMapper.defaultValue(field);
                  w.line("this.%s = %s;", csName, defaultVal);
                }
                if (hasPresenceTrackedFields(message)) {
                  w.line("Array.Clear(this.presentFields_, 0, this.presentFields_.Length);");
                }
                for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
                  String caseName = nameResolver.fieldName(group.name()) + "Case_";
                  w.line("this.%s = 0;", caseName);
                }
                w.line("return this;");
              });

          // Build
          w.blankLine();
          w.block(
              "public " + className + " Build()", () -> w.line("return new %s(this);", className));
        });
  }

  private void emitNestedMessage(CodeWriter w, ProtoMessage nested, ProtoFile file) {
    String className = nameResolver.messageClassName(nested.getName());
    emitDocComment(w, nested.getComment());
    w.block("public sealed class " + className, () -> emitMessageBody(w, nested, className, file));
  }

  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    w.blankLine();
    w.block(
        "public enum " + protoEnum.getName(),
        () -> {
          for (int i = 0; i < protoEnum.getValues().size(); i++) {
            ProtoEnum.EnumValue val = protoEnum.getValues().get(i);
            String suffix = i < protoEnum.getValues().size() - 1 ? "," : "";
            w.line("%s = %d%s", val.name(), val.number(), suffix);
          }
        });
  }

  private void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "public override string ToString()",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return \"%s{}\";", className);
            return;
          }
          w.line("return \"%s{\" +", className);
          w.indent();
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String csName = nameResolver.fieldName(field.getName());
            String prefix = i == 0 ? "\"" : "\", ";
            boolean isLast = i == message.getFields().size() - 1;
            if (isLast) {
              w.line("%s%s=\" + %s + \"}\";", prefix, field.getName(), csName);
            } else {
              w.line("%s%s=\" + %s +", prefix, field.getName(), csName);
            }
          }
          w.dedent();
        });
  }

  private void emitEquals(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "public override bool Equals(object o)",
        () -> {
          w.line("if (ReferenceEquals(this, o)) return true;");
          w.line("if (!(o is %s)) return false;", className);
          w.line("var that = (%s)o;", className);
          if (message.getFields().isEmpty()) {
            w.line("return true;");
            return;
          }
          StringBuilder sb = new StringBuilder("return ");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String csName = nameResolver.fieldName(field.getName());
            if (i > 0) sb.append(" && ");
            if (isByteArrayField(field)) {
              sb.append(String.format("this.%s.SequenceEqual(that.%s)", csName, csName));
            } else if (isPrimitiveField(field)) {
              sb.append(String.format("this.%s == that.%s", csName, csName));
            } else {
              sb.append(String.format("object.Equals(this.%s, that.%s)", csName, csName));
            }
          }
          sb.append(";");
          w.line(sb.toString());
        });
  }

  private void emitHashCode(CodeWriter w, ProtoMessage message) {
    w.blankLine();
    w.block(
        "public override int GetHashCode()",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return 0;");
            return;
          }
          w.line("unchecked {");
          w.indent();
          w.line("int hash = 17;");
          for (ProtoField field : message.getFields()) {
            String csName = nameResolver.fieldName(field.getName());
            if (isPrimitiveField(field)) {
              w.line("hash = hash * 31 + %s.GetHashCode();", csName);
            } else {
              w.line("hash = hash * 31 + (%s != null ? %s.GetHashCode() : 0);", csName, csName);
            }
          }
          w.line("return hash;");
          w.dedent();
          w.line("}");
        });
  }

  private void emitDocComment(CodeWriter w, String comment) {
    if (comment == null || comment.isEmpty()) return;
    String safeComment = comment.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    String[] lines = safeComment.split("\n");
    w.line("/// <summary>");
    for (String line : lines) {
      String trimmed = line.strip();
      if (trimmed.isEmpty()) {
        w.line("///");
      } else {
        w.line("/// %s", trimmed);
      }
    }
    w.line("/// </summary>");
  }

  // ---------------------------------------------------------------------------
  // Utility methods
  // ---------------------------------------------------------------------------

  private String elementType(ProtoField field) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      return simpleTypeName(field.getTypeReference());
    }
    if (field.getKind() == ProtoField.FieldKind.ENUM) {
      return simpleTypeName(field.getTypeReference());
    }
    return typeMapper.boxedScalarType(field.getProtoType());
  }

  private String mapValueType(ProtoField field) {
    if (field.getMapValueType()
            == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_MESSAGE
        || field.getMapValueType()
            == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_ENUM) {
      return simpleTypeName(field.getMapValueTypeReference());
    }
    return typeMapper.boxedScalarType(field.getMapValueType());
  }

  private String mapGenericArgs(ProtoField field) {
    String keyType = typeMapper.boxedScalarType(field.getMapKeyType());
    String valueType =
        field.getMapValueType()
                    == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_MESSAGE
                || field.getMapValueType()
                    == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_ENUM
            ? simpleTypeName(field.getMapValueTypeReference())
            : typeMapper.boxedScalarType(field.getMapValueType());
    return keyType + ", " + valueType;
  }

  static String pbtkTypeChar(FieldDescriptorProto.Type type) {
    return switch (type) {
      case TYPE_BOOL -> "b";
      case TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64 ->
          "i";
      case TYPE_FLOAT -> "f";
      case TYPE_DOUBLE -> "d";
      case TYPE_STRING -> "s";
      case TYPE_ENUM -> "e";
      case TYPE_MESSAGE -> "m";
      case TYPE_BYTES -> "z";
      default -> "s";
    };
  }

  private String scalarReadExpr(FieldDescriptorProto.Type type, String valueVar) {
    return switch (type) {
      case TYPE_DOUBLE -> "double.Parse(" + valueVar + ")";
      case TYPE_FLOAT -> "float.Parse(" + valueVar + ")";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64 -> "long.Parse(" + valueVar + ")";
      case TYPE_UINT64, TYPE_FIXED64 -> "ulong.Parse(" + valueVar + ")";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32 -> "int.Parse(" + valueVar + ")";
      case TYPE_UINT32, TYPE_FIXED32 -> "uint.Parse(" + valueVar + ")";
      case TYPE_BOOL -> "\"1\".Equals(" + valueVar + ")";
      case TYPE_STRING -> "Uri.UnescapeDataString(" + valueVar + ")";
      case TYPE_BYTES -> "Convert.FromBase64String(" + valueVar + ")";
      default -> valueVar;
    };
  }

  private String mapKeyCast(FieldDescriptorProto.Type keyType) {
    return switch (keyType) {
      case TYPE_STRING -> "(string)entryKey";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32 -> "(int)entryKey";
      case TYPE_UINT32, TYPE_FIXED32 -> "(uint)entryKey";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64 -> "(long)entryKey";
      case TYPE_UINT64, TYPE_FIXED64 -> "(ulong)entryKey";
      case TYPE_BOOL -> "(bool)entryKey";
      default -> "entryKey";
    };
  }

  private String mapValueCast(ProtoField field) {
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
      return "(" + simpleTypeName(field.getMapValueTypeReference()) + ")entryVal";
    }
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
      return "(" + simpleTypeName(field.getMapValueTypeReference()) + ")entryVal";
    }
    return switch (field.getMapValueType()) {
      case TYPE_STRING -> "(string)entryVal";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32 -> "(int)entryVal";
      case TYPE_UINT32, TYPE_FIXED32 -> "(uint)entryVal";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64 -> "(long)entryVal";
      case TYPE_UINT64, TYPE_FIXED64 -> "(ulong)entryVal";
      case TYPE_DOUBLE -> "(double)entryVal";
      case TYPE_FLOAT -> "(float)entryVal";
      case TYPE_BOOL -> "(bool)entryVal";
      case TYPE_BYTES -> "(byte[])entryVal";
      default -> "entryVal";
    };
  }

  private boolean isByteArrayField(ProtoField field) {
    return field.getProtoType()
            == com.google.protobuf.DescriptorProtos.FieldDescriptorProto.Type.TYPE_BYTES
        && field.isSingular();
  }

  private boolean isPrimitiveField(ProtoField field) {
    if (!field.isSingular()) return false;
    if (field.getKind() != ProtoField.FieldKind.SCALAR) return false;
    return switch (field.getProtoType()) {
      case TYPE_DOUBLE,
          TYPE_FLOAT,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64,
          TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_BOOL ->
          true;
      default -> false;
    };
  }

  private boolean hasPresenceTrackedFields(ProtoMessage message) {
    return message.getFields().stream().anyMatch(ProtoField::hasExplicitPresence);
  }

  private int maxPresenceBit(ProtoMessage message) {
    return message.getFields().stream()
        .filter(ProtoField::hasExplicitPresence)
        .mapToInt(ProtoField::getArrayPosition)
        .max()
        .orElse(0);
  }

  private static String snakeToUpperSnake(String name) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < name.length(); i++) {
      char c = name.charAt(i);
      if (Character.isUpperCase(c) && i > 0 && name.charAt(i - 1) != '_') {
        sb.append('_');
      }
      sb.append(Character.toUpperCase(c));
    }
    return sb.toString();
  }

  private String simpleTypeName(String protoFullName) {
    if (protoFullName == null) return "object";
    int lastDot = protoFullName.lastIndexOf('.');
    return lastDot >= 0 ? protoFullName.substring(lastDot + 1) : protoFullName;
  }
}
