// @generated by protoc-gen-pbtkurl — do not edit.

package com.example

/** A physical mailing address. */
class Address private constructor(builder: Builder) {

    val street: String
    val city: String
    val state: String
    val zip: Int

    init {
        this.street = builder.street
        this.city = builder.city
        this.state = builder.state
        this.zip = builder.zip
    }

    internal fun appendPbtkFields(sb: StringBuilder) {
        sb.append("!1s").append(java.net.URLEncoder.encode(this.street, Charsets.UTF_8))
        sb.append("!2s").append(java.net.URLEncoder.encode(this.city, Charsets.UTF_8))
        sb.append("!3s").append(java.net.URLEncoder.encode(this.state, Charsets.UTF_8))
        sb.append("!4i").append(this.zip)
    }

    internal fun countPbtkFields(): Int {
        var count = 0
        count++
        count++
        count++
        count++
        return count
    }

    fun toByteArray(): ByteArray {
        val sb = StringBuilder()
        appendPbtkFields(sb)
        return sb.toString().toByteArray(Charsets.UTF_8)
    }

    override fun toString(): String {
        return "Address{" +
            "street=" + street +
            ", city=" + city +
            ", state=" + state +
            ", zip=" + zip + "}"
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Address) return false
        return this.street == other.street && this.city == other.city && this.state == other.state && this.zip == other.zip
    }

    override fun hashCode(): Int {
        var result = 0
        result = 31 * result + street.hashCode()
        result = 31 * result + city.hashCode()
        result = 31 * result + state.hashCode()
        result = 31 * result + zip.hashCode()
        return result
    }

    class Builder {
        internal var street: String = ""
        internal var city: String = ""
        internal var state: String = ""
        internal var zip: Int = 0

        fun setStreet(value: String): Builder {
            this.street = value
            return this
        }

        fun clearStreet(): Builder {
            this.street = ""
            return this
        }

        fun setCity(value: String): Builder {
            this.city = value
            return this
        }

        fun clearCity(): Builder {
            this.city = ""
            return this
        }

        fun setState(value: String): Builder {
            this.state = value
            return this
        }

        fun clearState(): Builder {
            this.state = ""
            return this
        }

        fun setZip(value: Int): Builder {
            this.zip = value
            return this
        }

        fun clearZip(): Builder {
            this.zip = 0
            return this
        }

        fun clear(): Builder {
            this.street = ""
            this.city = ""
            this.state = ""
            this.zip = 0
            return this
        }

        fun build(): Address {
            return Address(this)
        }
    }

    companion object {
        const val STREET_FIELD_NUMBER: Int = 1
        const val CITY_FIELD_NUMBER: Int = 2
        const val STATE_FIELD_NUMBER: Int = 3
        const val ZIP_FIELD_NUMBER: Int = 4

        private val DEFAULT_INSTANCE: Address = Builder().build()

        @JvmStatic
        fun getDefaultInstance(): Address {
            return DEFAULT_INSTANCE
        }

        @JvmStatic
        fun newBuilder(): Builder {
            return Builder()
        }

        @JvmStatic
        fun newBuilder(prototype: Address): Builder {
            val builder = Builder()
            builder.street = prototype.street
            builder.city = prototype.city
            builder.state = prototype.state
            builder.zip = prototype.zip
            return builder
        }

        internal fun parsePbtkTokens(tokens: List<String>, fieldCount: Int, offset: IntArray): Address {
            val builder = Address.newBuilder()
            var consumed = 0
            while (consumed < fieldCount && offset[0] < tokens.size) {
                val token = tokens[offset[0]]
                var numEnd = 0
                while (numEnd < token.length && token[numEnd].isDigit()) numEnd++
                if (numEnd == 0 || numEnd >= token.length) { offset[0]++; consumed++; continue }
                val fieldNum = token.substring(0, numEnd).toInt()
                val typeChar = token[numEnd]
                val value = token.substring(numEnd + 1)
                when (fieldNum) {
                    1 -> {
                        builder.setStreet(java.net.URLDecoder.decode(value, Charsets.UTF_8))
                        offset[0]++
                        consumed++
                    }
                    2 -> {
                        builder.setCity(java.net.URLDecoder.decode(value, Charsets.UTF_8))
                        offset[0]++
                        consumed++
                    }
                    3 -> {
                        builder.setState(java.net.URLDecoder.decode(value, Charsets.UTF_8))
                        offset[0]++
                        consumed++
                    }
                    4 -> {
                        builder.setZip(value.toInt())
                        offset[0]++
                        consumed++
                    }
                    else -> { offset[0]++; consumed++ }
                }
            }
            return builder.build()
        }

        @JvmStatic
        fun parseFrom(bytes: ByteArray): Address {
            val input = String(bytes, Charsets.UTF_8)
            if (input.isEmpty()) return Address.getDefaultInstance()
            val tokens = tokenizePbtk(input)
            val offset = intArrayOf(0)
            return parsePbtkTokens(tokens, tokens.size, offset)
        }

        private fun tokenizePbtk(input: String): List<String> {
            val tokens = mutableListOf<String>()
            var i = if (input[0] == '!') 1 else 0
            while (i < input.length) {
                val next = input.indexOf('!', i)
                if (next < 0) {
                    tokens.add(input.substring(i))
                    break
                }
                tokens.add(input.substring(i, next))
                i = next + 1
            }
            return tokens
        }
    }
}
