// @generated by protoc-gen-jsonarray — do not edit.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace Example {
    /// <summary>
    /// A physical mailing address.
    /// </summary>
    public sealed class Address {
        public const int StreetFieldNumber = 1;
        public const int CityFieldNumber = 2;
        public const int StateFieldNumber = 3;
        public const int ZipFieldNumber = 4;

        private readonly string _street;
        private readonly string _city;
        private readonly string _state;
        private readonly int _zip;

        private Address(Builder builder) {
            this._street = builder.street;
            this._city = builder.city;
            this._state = builder.state;
            this._zip = builder.zip;
        }

        /// <summary>
        /// The street address line.
        /// </summary>
        public string Street => this._street;

        /// <summary>
        /// The city name.
        /// </summary>
        public string City => this._city;

        /// <summary>
        /// The state or province code.
        /// </summary>
        public string State => this._state;

        /// <summary>
        /// The postal/ZIP code.
        /// </summary>
        public int Zip => this._zip;

        private static readonly Address DefaultInstance_ = new Address(new Builder());

        public static Address GetDefaultInstance() {
            return DefaultInstance_;
        }

        public static Builder NewBuilder() {
            return new Builder();
        }

        public static Builder NewBuilder(Address prototype) {
            return new Builder(prototype);
        }

        public Builder ToBuilder() {
            return new Builder(this);
        }

        internal void AppendJsonArray(StringBuilder sb) {
            sb.Append('[');
            sb.Append('"');
            sb.Append(JsonEncodedText.Encode(this._street).ToString());
            sb.Append('"');
            sb.Append(',');
            sb.Append('"');
            sb.Append(JsonEncodedText.Encode(this._city).ToString());
            sb.Append('"');
            sb.Append(',');
            sb.Append('"');
            sb.Append(JsonEncodedText.Encode(this._state).ToString());
            sb.Append('"');
            sb.Append(',');
            sb.Append(this._zip);
            sb.Append(']');
        }

        public string ToJsonString() {
            var sb = new StringBuilder(128);
            AppendJsonArray(sb);
            return sb.ToString();
        }

        public byte[] ToJsonBytes() {
            return System.Text.Encoding.UTF8.GetBytes(ToJsonString());
        }

        internal static Address FromJsonArray(JsonElement array) {
            var builder = Address.NewBuilder();
            int size = array.GetArrayLength();
            if (size > 0 && array[0].ValueKind != JsonValueKind.Null) {
                builder.SetStreet(array[0].GetString());
            }
            if (size > 1 && array[1].ValueKind != JsonValueKind.Null) {
                builder.SetCity(array[1].GetString());
            }
            if (size > 2 && array[2].ValueKind != JsonValueKind.Null) {
                builder.SetState(array[2].GetString());
            }
            if (size > 3 && array[3].ValueKind != JsonValueKind.Null) {
                builder.SetZip(array[3].GetInt32());
            }
            return builder.Build();
        }

        public static Address FromJsonString(string json) {
            using var doc = JsonDocument.Parse(json);
            return FromJsonArray(doc.RootElement);
        }

        public static Address FromJsonBytes(byte[] bytes) {
            return FromJsonString(System.Text.Encoding.UTF8.GetString(bytes));
        }

        public override string ToString() {
            return "Address{" +
                "street=" + _street +
                ", city=" + _city +
                ", state=" + _state +
                ", zip=" + _zip + "}";
        }

        public override bool Equals(object o) {
            if (ReferenceEquals(this, o)) return true;
            if (!(o is Address)) return false;
            var that = (Address)o;
            return object.Equals(this._street, that._street) && object.Equals(this._city, that._city) && object.Equals(this._state, that._state) && this._zip == that._zip;
        }

        public override int GetHashCode() {
            unchecked {
                int hash = 17;
                hash = hash * 31 + (_street != null ? _street.GetHashCode() : 0);
                hash = hash * 31 + (_city != null ? _city.GetHashCode() : 0);
                hash = hash * 31 + (_state != null ? _state.GetHashCode() : 0);
                hash = hash * 31 + _zip.GetHashCode();
                return hash;
            }
        }

        public sealed class Builder {
            internal string street = "";
            internal string city = "";
            internal string state = "";
            internal int zip = 0;

            internal Builder() {
            }

            internal Builder(Address from) {
                this.street = from._street;
                this.city = from._city;
                this.state = from._state;
                this.zip = from._zip;
            }

            public string GetStreet() {
                return this.street;
            }

            public Builder SetStreet(string value) {
                this.street = value;
                return this;
            }

            public Builder ClearStreet() {
                this.street = "";
                return this;
            }

            public string GetCity() {
                return this.city;
            }

            public Builder SetCity(string value) {
                this.city = value;
                return this;
            }

            public Builder ClearCity() {
                this.city = "";
                return this;
            }

            public string GetState() {
                return this.state;
            }

            public Builder SetState(string value) {
                this.state = value;
                return this;
            }

            public Builder ClearState() {
                this.state = "";
                return this;
            }

            public int GetZip() {
                return this.zip;
            }

            public Builder SetZip(int value) {
                this.zip = value;
                return this;
            }

            public Builder ClearZip() {
                this.zip = 0;
                return this;
            }

            public Address Build() {
                return new Address(this);
            }

            public Builder Clear() {
                this.street = "";
                this.city = "";
                this.state = "";
                this.zip = 0;
                return this;
            }
        }
    }
}
