// @generated by protoc-gen-jsonarray — do not edit.

package com.example;

/** A physical mailing address. */
public class Address {
    private String street = "";
    private String city = "";
    private String state = "";
    private int zip = 0;

    public Address() {
    }

    /** The street address line. */
    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    /** The city name. */
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    /** The state or province code. */
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    /** The postal/ZIP code. */
    public int getZip() {
        return this.zip;
    }

    public void setZip(int zip) {
        this.zip = zip;
    }

    void appendJsonArray(StringBuilder sb) {
        sb.append('[');
        dev.protocgen.textcodecs.jsonarray.runtime.JsonArrayWriter.appendQuotedString(sb, this.street);
        sb.append(',');
        dev.protocgen.textcodecs.jsonarray.runtime.JsonArrayWriter.appendQuotedString(sb, this.city);
        sb.append(',');
        dev.protocgen.textcodecs.jsonarray.runtime.JsonArrayWriter.appendQuotedString(sb, this.state);
        sb.append(',');
        sb.append(this.zip);
        sb.append(']');
    }

    public String toJsonString() {
        StringBuilder sb = new StringBuilder(128);
        appendJsonArray(sb);
        return sb.toString();
    }

    public byte[] toJsonBytes() {
        return toJsonString().getBytes(java.nio.charset.StandardCharsets.UTF_8);
    }

    @SuppressWarnings("unchecked")
    static Address fromJsonArray(java.util.List<Object> array) {
        Address obj = new Address();
        int size = array.size();
        if (size > 0 && array.get(0) != null) {
            obj.setStreet((String) array.get(0));
        }
        if (size > 1 && array.get(1) != null) {
            obj.setCity((String) array.get(1));
        }
        if (size > 2 && array.get(2) != null) {
            obj.setState((String) array.get(2));
        }
        if (size > 3 && array.get(3) != null) {
            obj.setZip(((Number) array.get(3)).intValue());
        }
        return obj;
    }

    public static Address fromJsonString(String json) {
        java.util.List<Object> array = dev.protocgen.textcodecs.jsonarray.runtime.JsonArrayReader.parseArray(json);
        return fromJsonArray(array);
    }

    public static Address fromJsonBytes(byte[] bytes) {
        return fromJsonString(new String(bytes, java.nio.charset.StandardCharsets.UTF_8));
    }

    @Override
    public String toString() {
        return "Address{" +
            "street='" + street + "'" +
            ", city='" + city + "'" +
            ", state='" + state + "'" +
            ", zip=" + zip + "}";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Address)) return false;
        Address that = (Address) o;
        return java.util.Objects.equals(this.street, that.street) && java.util.Objects.equals(this.city, that.city) && java.util.Objects.equals(this.state, that.state) && this.zip == that.zip;
    }

    @Override
    public int hashCode() {
        return java.util.Objects.hash(street, city, state, zip);
    }
}
