package dev.protocgen.textcodecs.jsonarray;

import com.google.protobuf.DescriptorProtos.DescriptorProto;
import com.google.protobuf.DescriptorProtos.EnumDescriptorProto;
import com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto;
import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.DescriptorProtos.FileDescriptorProto;
import com.google.protobuf.DescriptorProtos.MessageOptions;
import com.google.protobuf.DescriptorProtos.OneofDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorRequest;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.pbtkurl.PbtkPluginRunner;
import java.lang.management.ManagementFactory;
import java.lang.management.MemoryMXBean;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Memory consumption benchmark tests for the protoc-gen-jsonarray and protoc-gen-pbtkurl code
 * generators.
 *
 * <p>Measures heap memory before/after code generation, retained memory after generation, and
 * provides object count estimates. Uses forced GC with stabilization to get reliable measurements.
 *
 * <p>Run separately with: {@code ./gradlew :plugin:test --tests "*.MemoryBenchmarkTest"}
 */
@Tag("benchmark")
class MemoryBenchmarkTest {

  private static final int MEASUREMENT_ITERATIONS = 10;
  private static final int GC_SETTLE_ATTEMPTS = 5;

  private static FileDescriptorProto complexProto;
  private static CodeGeneratorRequest jsonArrayJavaRequest;
  private static CodeGeneratorRequest pbtkUrlJavaRequest;

  @BeforeAll
  static void buildDescriptors() {
    complexProto = buildComplexProto();
    jsonArrayJavaRequest = buildRequest(complexProto, "lang=java");
    pbtkUrlJavaRequest = buildRequest(complexProto, "lang=java");
  }

  // ======================================================================
  // 1. JSON array format -- memory during code generation
  // ======================================================================

  @Test
  void measureJsonArrayGenerationMemory() {
    PluginRunner runner = new PluginRunner();

    // Warm up to stabilize JIT and class loading
    for (int i = 0; i < 5; i++) {
      runner.run(jsonArrayJavaRequest);
    }

    long[] heapBefore = new long[MEASUREMENT_ITERATIONS];
    long[] heapAfter = new long[MEASUREMENT_ITERATIONS];
    long[] peakHeap = new long[MEASUREMENT_ITERATIONS];
    long[] retainedAfterGc = new long[MEASUREMENT_ITERATIONS];
    int[] generatedFileCount = new int[MEASUREMENT_ITERATIONS];
    int[] totalGeneratedBytes = new int[MEASUREMENT_ITERATIONS];

    MemoryMXBean memBean = ManagementFactory.getMemoryMXBean();

    for (int i = 0; i < MEASUREMENT_ITERATIONS; i++) {
      // Force GC and measure baseline
      forceGc();
      heapBefore[i] = getUsedHeap();

      // Run code generation
      CodeGeneratorResponse response = runner.run(jsonArrayJavaRequest);
      heapAfter[i] = getUsedHeap();

      // Capture output stats
      generatedFileCount[i] = response.getFileCount();
      int totalBytes = 0;
      for (int f = 0; f < response.getFileCount(); f++) {
        totalBytes += response.getFile(f).getContent().length();
      }
      totalGeneratedBytes[i] = totalBytes;

      // Record peak (approximate -- heap after generation, before GC)
      peakHeap[i] = heapAfter[i];

      // Force GC and measure retained
      forceGc();
      retainedAfterGc[i] = getUsedHeap();
    }

    // Report results
    System.err.println();
    System.err.println("=== JSON Array Format: Memory Benchmark (complex KitchenSink message) ===");
    reportMemoryStats("Heap before generation", heapBefore);
    reportMemoryStats("Heap after generation (peak)", heapAfter);
    reportMemoryStats("Retained after GC", retainedAfterGc);

    long[] allocatedDuringGen = new long[MEASUREMENT_ITERATIONS];
    long[] retainedDelta = new long[MEASUREMENT_ITERATIONS];
    for (int i = 0; i < MEASUREMENT_ITERATIONS; i++) {
      allocatedDuringGen[i] = heapAfter[i] - heapBefore[i];
      retainedDelta[i] = retainedAfterGc[i] - heapBefore[i];
    }
    reportMemoryStats("Allocated during generation", allocatedDuringGen);
    reportMemoryStats("Retained delta (leak indicator)", retainedDelta);

    System.err.printf("  Generated files: %d%n", generatedFileCount[0]);
    System.err.printf("  Total generated bytes: %,d%n", totalGeneratedBytes[0]);

    // Estimate object count: ~(bytes allocated / avg object size of 64 bytes)
    long medianAllocated = median(allocatedDuringGen);
    long estimatedObjects = medianAllocated / 64;
    System.err.printf("  Estimated object count (median alloc / 64B): ~%,d objects%n",
        estimatedObjects);
    System.err.println();

    // Assertion: generation should not allocate more than 10MB for a single complex message
    assertTrue(medianAllocated < 10_000_000L,
        "JSON array generation allocated too much memory: " + medianAllocated + " bytes");
  }

  // ======================================================================
  // 2. pbtk URL format -- memory during code generation
  // ======================================================================

  @Test
  void measurePbtkUrlGenerationMemory() {
    PbtkPluginRunner runner = new PbtkPluginRunner();

    // Warm up
    for (int i = 0; i < 5; i++) {
      runner.run(pbtkUrlJavaRequest);
    }

    long[] heapBefore = new long[MEASUREMENT_ITERATIONS];
    long[] heapAfter = new long[MEASUREMENT_ITERATIONS];
    long[] retainedAfterGc = new long[MEASUREMENT_ITERATIONS];
    int[] generatedFileCount = new int[MEASUREMENT_ITERATIONS];
    int[] totalGeneratedBytes = new int[MEASUREMENT_ITERATIONS];

    for (int i = 0; i < MEASUREMENT_ITERATIONS; i++) {
      forceGc();
      heapBefore[i] = getUsedHeap();

      CodeGeneratorResponse response = runner.run(pbtkUrlJavaRequest);
      heapAfter[i] = getUsedHeap();

      generatedFileCount[i] = response.getFileCount();
      int totalBytes = 0;
      for (int f = 0; f < response.getFileCount(); f++) {
        totalBytes += response.getFile(f).getContent().length();
      }
      totalGeneratedBytes[i] = totalBytes;

      forceGc();
      retainedAfterGc[i] = getUsedHeap();
    }

    System.err.println();
    System.err.println("=== pbtk URL Format: Memory Benchmark (complex KitchenSink message) ===");
    reportMemoryStats("Heap before generation", heapBefore);
    reportMemoryStats("Heap after generation (peak)", heapAfter);
    reportMemoryStats("Retained after GC", retainedAfterGc);

    long[] allocatedDuringGen = new long[MEASUREMENT_ITERATIONS];
    long[] retainedDelta = new long[MEASUREMENT_ITERATIONS];
    for (int i = 0; i < MEASUREMENT_ITERATIONS; i++) {
      allocatedDuringGen[i] = heapAfter[i] - heapBefore[i];
      retainedDelta[i] = retainedAfterGc[i] - heapBefore[i];
    }
    reportMemoryStats("Allocated during generation", allocatedDuringGen);
    reportMemoryStats("Retained delta (leak indicator)", retainedDelta);

    System.err.printf("  Generated files: %d%n", generatedFileCount[0]);
    System.err.printf("  Total generated bytes: %,d%n", totalGeneratedBytes[0]);

    long medianAllocated = median(allocatedDuringGen);
    long estimatedObjects = medianAllocated / 64;
    System.err.printf("  Estimated object count (median alloc / 64B): ~%,d objects%n",
        estimatedObjects);
    System.err.println();

    assertTrue(medianAllocated < 10_000_000L,
        "pbtk URL generation allocated too much memory: " + medianAllocated + " bytes");
  }

  // ======================================================================
  // 3. Comparison: JSON array vs pbtk URL memory
  // ======================================================================

  @Test
  void compareJsonArrayVsPbtkUrlMemory() {
    PluginRunner jsonRunner = new PluginRunner();
    PbtkPluginRunner pbtkRunner = new PbtkPluginRunner();

    // Warm up both
    for (int i = 0; i < 5; i++) {
      jsonRunner.run(jsonArrayJavaRequest);
      pbtkRunner.run(pbtkUrlJavaRequest);
    }

    long[] jsonAllocated = new long[MEASUREMENT_ITERATIONS];
    long[] pbtkAllocated = new long[MEASUREMENT_ITERATIONS];

    for (int i = 0; i < MEASUREMENT_ITERATIONS; i++) {
      forceGc();
      long before = getUsedHeap();
      jsonRunner.run(jsonArrayJavaRequest);
      jsonAllocated[i] = getUsedHeap() - before;

      forceGc();
      before = getUsedHeap();
      pbtkRunner.run(pbtkUrlJavaRequest);
      pbtkAllocated[i] = getUsedHeap() - before;
    }

    System.err.println();
    System.err.println("=== Memory Comparison: JSON Array vs pbtk URL ===");
    reportMemoryStats("JSON array allocated", jsonAllocated);
    reportMemoryStats("pbtk URL allocated", pbtkAllocated);

    long jsonMedian = median(jsonAllocated);
    long pbtkMedian = median(pbtkAllocated);
    if (pbtkMedian > 0 && jsonMedian > 0) {
      double ratio = (double) pbtkMedian / jsonMedian;
      System.err.printf("  pbtk/jsonarray ratio: %.2fx%n", ratio);
    }
    System.err.println();

    // Both should be reasonable
    assertTrue(median(jsonAllocated) < 10_000_000L, "JSON array generation memory too high");
    assertTrue(median(pbtkAllocated) < 10_000_000L, "pbtk URL generation memory too high");
  }

  // ======================================================================
  // 4. Model object memory -- ProtoField, ProtoMessage object sizes
  // ======================================================================

  @Test
  void measureModelObjectMemory() {
    dev.protocgen.textcodecs.jsonarray.model.TypeRegistry registry =
        new dev.protocgen.textcodecs.jsonarray.model.TypeRegistry();
    registry.registerFile(complexProto);
    MessageAnalyzer analyzer = new MessageAnalyzer(registry);

    // Warm up
    for (int i = 0; i < 5; i++) {
      analyzer.analyze(complexProto.getMessageType(0), ".bench.");
    }

    long[] analyzerAllocated = new long[MEASUREMENT_ITERATIONS];

    for (int i = 0; i < MEASUREMENT_ITERATIONS; i++) {
      forceGc();
      long before = getUsedHeap();
      var msg = analyzer.analyze(complexProto.getMessageType(0), ".bench.");
      analyzerAllocated[i] = getUsedHeap() - before;
      // Prevent dead-code elimination
      if (msg.getFields().isEmpty()) throw new AssertionError("no fields");
    }

    System.err.println();
    System.err.println("=== Model Object Memory (MessageAnalyzer.analyze) ===");
    reportMemoryStats("Memory per analyze() call", analyzerAllocated);

    // Estimate per-field overhead
    long medianAlloc = median(analyzerAllocated);
    int fieldCount = 16; // KitchenSink has 16 fields
    long perFieldEstimate = medianAlloc / fieldCount;
    System.err.printf("  Fields in KitchenSink: %d%n", fieldCount);
    System.err.printf("  Estimated bytes per field: ~%,d bytes%n", perFieldEstimate);
    System.err.printf(
        "    (includes ProtoField object + Builder + String allocations + list overhead)%n");
    System.err.println();

    // ProtoField should be under 32KB per field including all transient objects
    // (heap-diff measurements have significant noise due to GC timing)
    assertTrue(perFieldEstimate < 32_768,
        "Per-field memory too high: " + perFieldEstimate + " bytes");
  }

  // ======================================================================
  // Utility methods
  // ======================================================================

  /** Force garbage collection with stabilization. */
  private static void forceGc() {
    for (int i = 0; i < GC_SETTLE_ATTEMPTS; i++) {
      System.gc();
      try {
        Thread.sleep(10);
      } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        break;
      }
    }
  }

  /** Get current used heap memory. */
  private static long getUsedHeap() {
    Runtime rt = Runtime.getRuntime();
    return rt.totalMemory() - rt.freeMemory();
  }

  /** Compute median of a long array. */
  private static long median(long[] values) {
    long[] sorted = values.clone();
    java.util.Arrays.sort(sorted);
    int mid = sorted.length / 2;
    if (sorted.length % 2 == 0) {
      return (sorted[mid - 1] + sorted[mid]) / 2;
    }
    return sorted[mid];
  }

  /** Report min/median/max/mean for a set of memory measurements. */
  private static void reportMemoryStats(String label, long[] values) {
    long[] sorted = values.clone();
    java.util.Arrays.sort(sorted);
    long min = sorted[0];
    long max = sorted[sorted.length - 1];
    long med = sorted[sorted.length / 2];
    double mean = 0;
    for (long v : sorted) mean += v;
    mean /= sorted.length;
    System.err.printf("  %-40s  min=%,12d  median=%,12d  max=%,12d  mean=%,.0f bytes%n",
        label, min, med, max, mean);
  }

  // ======================================================================
  // Proto descriptor builders (same complex proto as PerformanceBenchmarkTest)
  // ======================================================================

  private static FileDescriptorProto buildComplexProto() {
    EnumDescriptorProto statusEnum =
        EnumDescriptorProto.newBuilder()
            .setName("Status")
            .addValue(
                EnumValueDescriptorProto.newBuilder().setName("STATUS_UNKNOWN").setNumber(0))
            .addValue(
                EnumValueDescriptorProto.newBuilder().setName("STATUS_ACTIVE").setNumber(1))
            .addValue(
                EnumValueDescriptorProto.newBuilder().setName("STATUS_INACTIVE").setNumber(2))
            .build();

    DescriptorProto innerMsg =
        DescriptorProto.newBuilder()
            .setName("Inner")
            .addField(
                FieldDescriptorProto.newBuilder()
                    .setName("value")
                    .setNumber(1)
                    .setType(FieldDescriptorProto.Type.TYPE_STRING)
                    .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL))
            .addField(
                FieldDescriptorProto.newBuilder()
                    .setName("score")
                    .setNumber(2)
                    .setType(FieldDescriptorProto.Type.TYPE_INT32)
                    .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL))
            .build();

    DescriptorProto stringMapEntry =
        DescriptorProto.newBuilder()
            .setName("MetadataEntry")
            .setOptions(MessageOptions.newBuilder().setMapEntry(true))
            .addField(
                FieldDescriptorProto.newBuilder()
                    .setName("key")
                    .setNumber(1)
                    .setType(FieldDescriptorProto.Type.TYPE_STRING)
                    .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL))
            .addField(
                FieldDescriptorProto.newBuilder()
                    .setName("value")
                    .setNumber(2)
                    .setType(FieldDescriptorProto.Type.TYPE_STRING)
                    .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL))
            .build();

    DescriptorProto intMapEntry =
        DescriptorProto.newBuilder()
            .setName("LookupEntry")
            .setOptions(MessageOptions.newBuilder().setMapEntry(true))
            .addField(
                FieldDescriptorProto.newBuilder()
                    .setName("key")
                    .setNumber(1)
                    .setType(FieldDescriptorProto.Type.TYPE_INT32)
                    .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL))
            .addField(
                FieldDescriptorProto.newBuilder()
                    .setName("value")
                    .setNumber(2)
                    .setType(FieldDescriptorProto.Type.TYPE_STRING)
                    .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL))
            .build();

    DescriptorProto.Builder kitchenSink =
        DescriptorProto.newBuilder()
            .setName("KitchenSink")
            .addEnumType(statusEnum)
            .addNestedType(innerMsg)
            .addNestedType(stringMapEntry)
            .addNestedType(intMapEntry);

    kitchenSink.addOneofDecl(OneofDescriptorProto.newBuilder().setName("result"));
    kitchenSink.addOneofDecl(OneofDescriptorProto.newBuilder().setName("_opt_tag"));

    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("str_field").setNumber(1)
            .setType(FieldDescriptorProto.Type.TYPE_STRING)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("int_field").setNumber(2)
            .setType(FieldDescriptorProto.Type.TYPE_INT32)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("long_field").setNumber(3)
            .setType(FieldDescriptorProto.Type.TYPE_INT64)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("double_field").setNumber(4)
            .setType(FieldDescriptorProto.Type.TYPE_DOUBLE)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("float_field").setNumber(5)
            .setType(FieldDescriptorProto.Type.TYPE_FLOAT)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("bool_field").setNumber(6)
            .setType(FieldDescriptorProto.Type.TYPE_BOOL)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("bytes_field").setNumber(7)
            .setType(FieldDescriptorProto.Type.TYPE_BYTES)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("status").setNumber(8)
            .setType(FieldDescriptorProto.Type.TYPE_ENUM)
            .setTypeName(".bench.KitchenSink.Status")
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("inner").setNumber(9)
            .setType(FieldDescriptorProto.Type.TYPE_MESSAGE)
            .setTypeName(".bench.KitchenSink.Inner")
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("tags").setNumber(10)
            .setType(FieldDescriptorProto.Type.TYPE_STRING)
            .setLabel(FieldDescriptorProto.Label.LABEL_REPEATED));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("items").setNumber(11)
            .setType(FieldDescriptorProto.Type.TYPE_MESSAGE)
            .setTypeName(".bench.KitchenSink.Inner")
            .setLabel(FieldDescriptorProto.Label.LABEL_REPEATED));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("metadata").setNumber(12)
            .setType(FieldDescriptorProto.Type.TYPE_MESSAGE)
            .setTypeName(".bench.KitchenSink.MetadataEntry")
            .setLabel(FieldDescriptorProto.Label.LABEL_REPEATED));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("lookup").setNumber(13)
            .setType(FieldDescriptorProto.Type.TYPE_MESSAGE)
            .setTypeName(".bench.KitchenSink.LookupEntry")
            .setLabel(FieldDescriptorProto.Label.LABEL_REPEATED));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("success_msg").setNumber(14)
            .setType(FieldDescriptorProto.Type.TYPE_STRING)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
            .setOneofIndex(0));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("error_code").setNumber(15)
            .setType(FieldDescriptorProto.Type.TYPE_INT32)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
            .setOneofIndex(0));
    kitchenSink.addField(
        FieldDescriptorProto.newBuilder()
            .setName("opt_tag").setNumber(16)
            .setType(FieldDescriptorProto.Type.TYPE_STRING)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
            .setProto3Optional(true)
            .setOneofIndex(1));

    return FileDescriptorProto.newBuilder()
        .setName("bench.proto")
        .setPackage("bench")
        .setSyntax("proto3")
        .addMessageType(kitchenSink)
        .build();
  }

  private static CodeGeneratorRequest buildRequest(FileDescriptorProto proto, String parameter) {
    return CodeGeneratorRequest.newBuilder()
        .addProtoFile(proto)
        .addFileToGenerate(proto.getName())
        .setParameter(parameter)
        .build();
  }
}
