package dev.protocgen.textcodecs.jsonarray;

import com.google.protobuf.DescriptorProtos.DescriptorProto;
import com.google.protobuf.DescriptorProtos.EnumDescriptorProto;
import com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto;
import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.DescriptorProtos.FileDescriptorProto;
import com.google.protobuf.DescriptorProtos.MessageOptions;
import com.google.protobuf.DescriptorProtos.OneofDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorRequest;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * End-to-end parameterized code generation tests for all non-Java language targets. Runs the same
 * proto constructs through each of the 8 language generators (Python, JavaScript, TypeScript, C,
 * C++, Rust, Zig, Go) and verifies the generated source contains expected language-specific
 * patterns.
 */
class MultiLanguageCodeGenTest {

  private final PluginRunner runner = new PluginRunner();

  // ======================================================================
  // Language expectation record and data provider
  // ======================================================================

  record LangExpectation(String lang, Map<String, List<String>> patterns) {

    @Override
    public String toString() {
      return lang;
    }
  }

  static Stream<Arguments> languages() {
    return Stream.of(
        Arguments.of(
            new LangExpectation(
                "python",
                Map.ofEntries(
                    Map.entry("scalar_field_decl", List.of("self._name", "self._age")),
                    Map.entry("int64_as_string", List.of("self._big_val")),
                    Map.entry("enum_def", List.of("class Status:", "UNKNOWN = 0", "ACTIVE = 1")),
                    Map.entry("nested_class", List.of("class Inner:")),
                    Map.entry("repeated_field", List.of("list()")),
                    Map.entry("map_field", List.of("dict()")),
                    Map.entry("oneof_tracking", List.of("_case", "result.append(None)")),
                    Map.entry("optional_presence", List.of("_present_fields")),
                    Map.entry("bytes_base64", List.of("base64.b64encode(")),
                    Map.entry("cross_file_ref", List.of("Address")),
                    Map.entry("field_number_gap", List.of("# gap (no field number 2)")),
                    Map.entry("keyword_escape", List.of("class_")),
                    Map.entry("generated_marker", List.of("Generated from proto message"))))),
        Arguments.of(
            new LangExpectation(
                "javascript",
                Map.ofEntries(
                    Map.entry("scalar_field_decl", List.of("this.name = \"\"", "this.age = 0")),
                    Map.entry("int64_as_string", List.of("String(")),
                    Map.entry("enum_def", List.of("Object.freeze(", "UNKNOWN: 0", "ACTIVE: 1")),
                    Map.entry("nested_class", List.of("class Inner")),
                    Map.entry("repeated_field", List.of("[]")),
                    Map.entry("map_field", List.of("{}")),
                    Map.entry("oneof_tracking", List.of("Case", "array.push(null)")),
                    Map.entry("optional_presence", List.of("_presentFields")),
                    Map.entry("bytes_base64", List.of("base64", "toString('base64')")),
                    Map.entry("cross_file_ref", List.of("Address")),
                    Map.entry("field_number_gap", List.of("// gap (no field number 2)")),
                    Map.entry("keyword_escape", List.of("class_")),
                    Map.entry("generated_marker", List.of("Generated by protoc-gen-jsonarray"))))),
        Arguments.of(
            new LangExpectation(
                "typescript",
                Map.ofEntries(
                    Map.entry("scalar_field_decl", List.of("this.name = \"\"", "this.age = 0")),
                    Map.entry("int64_as_string", List.of("String(")),
                    Map.entry("enum_def", List.of("Object.freeze(", "UNKNOWN: 0", "ACTIVE: 1")),
                    Map.entry("nested_class", List.of("class Inner")),
                    Map.entry("repeated_field", List.of("[]")),
                    Map.entry("map_field", List.of("{}")),
                    Map.entry("oneof_tracking", List.of("Case", "array.push(null)")),
                    Map.entry("optional_presence", List.of("_presentFields")),
                    Map.entry("bytes_base64", List.of("base64", "toString('base64')")),
                    Map.entry("cross_file_ref", List.of("Address")),
                    Map.entry("field_number_gap", List.of("// gap (no field number 2)")),
                    Map.entry("keyword_escape", List.of("class_")),
                    Map.entry("generated_marker", List.of("Generated by protoc-gen-jsonarray"))))),
        Arguments.of(
            new LangExpectation(
                "c",
                Map.ofEntries(
                    Map.entry("scalar_field_decl", List.of("char*", "int32_t")),
                    Map.entry("int64_as_string", List.of("snprintf(", "%lld")),
                    Map.entry("enum_def", List.of("typedef enum", "UNKNOWN", "ACTIVE")),
                    Map.entry("nested_class", List.of("typedef struct")),
                    Map.entry("repeated_field", List.of("_count")),
                    Map.entry("map_field", List.of("_entry_t")),
                    Map.entry("oneof_tracking", List.of("_case", "CASE")),
                    Map.entry("optional_presence", List.of("has_")),
                    Map.entry("bytes_base64", List.of("jsonarray_base64_encode(")),
                    Map.entry("cross_file_ref", List.of("Address", "#include")),
                    Map.entry("field_number_gap", List.of("/* gap (no field number 2) */")),
                    Map.entry("keyword_escape", List.of("struct_pb")),
                    Map.entry("generated_marker", List.of("#ifndef", "#define"))))),
        Arguments.of(
            new LangExpectation(
                "cpp",
                Map.ofEntries(
                    Map.entry("scalar_field_decl", List.of("std::string", "int32_t")),
                    Map.entry("int64_as_string", List.of("big_val_")),
                    Map.entry("enum_def", List.of("enum class", "UNKNOWN", "ACTIVE")),
                    Map.entry("nested_class", List.of("class Inner")),
                    Map.entry("repeated_field", List.of("std::vector")),
                    Map.entry("map_field", List.of("std::map", "std::unordered_map")),
                    Map.entry("oneof_tracking", List.of("_case_", "push_back(nullptr)")),
                    Map.entry("optional_presence", List.of("has_value()")),
                    Map.entry("bytes_base64", List.of("jsonarray::base64_encode(")),
                    Map.entry("cross_file_ref", List.of("Address")),
                    Map.entry("field_number_gap", List.of("// gap (no field number 2)")),
                    Map.entry("keyword_escape", List.of("class_pb")),
                    Map.entry("generated_marker", List.of("#pragma once"))))),
        Arguments.of(
            new LangExpectation(
                "rust",
                Map.ofEntries(
                    Map.entry("scalar_field_decl", List.of("String", "i32")),
                    Map.entry("int64_as_string", List.of(".to_string()")),
                    Map.entry("enum_def", List.of("pub enum", "Unknown", "Active")),
                    Map.entry("nested_class", List.of("pub struct Inner")),
                    Map.entry("repeated_field", List.of("Vec<")),
                    Map.entry("map_field", List.of("HashMap<")),
                    Map.entry("oneof_tracking", List.of("_case", "Value::Null")),
                    Map.entry("optional_presence", List.of("Option<")),
                    Map.entry("bytes_base64", List.of("general_purpose::STANDARD.encode(")),
                    Map.entry("cross_file_ref", List.of("Address", "use super::")),
                    Map.entry("field_number_gap", List.of("// gap (no field number 2)")),
                    Map.entry("keyword_escape", List.of("r#type")),
                    Map.entry("generated_marker", List.of("use serde_json"))))),
        Arguments.of(
            new LangExpectation(
                "zig",
                Map.ofEntries(
                    Map.entry("scalar_field_decl", List.of("[]const u8", "i32")),
                    Map.entry("int64_as_string", List.of("std.fmt.allocPrint(")),
                    Map.entry(
                        "enum_def", List.of("pub const Status = enum(i32)", "unknown", "active")),
                    Map.entry("nested_class", List.of("pub const Inner = struct")),
                    Map.entry("repeated_field", List.of("std.ArrayList")),
                    Map.entry("map_field", List.of("std.AutoHashMap", "std.StringHashMap")),
                    Map.entry("oneof_tracking", List.of(".null")),
                    Map.entry("optional_presence", List.of("?")),
                    Map.entry("bytes_base64", List.of("std.base64")),
                    Map.entry("cross_file_ref", List.of("Address", "@import(")),
                    Map.entry("field_number_gap", List.of("// gap (no field number 2)")),
                    Map.entry("keyword_escape", List.of("@\"const\"")),
                    Map.entry("generated_marker", List.of("const std = @import(\"std\")"))))),
        Arguments.of(
            new LangExpectation(
                "go",
                Map.ofEntries(
                    Map.entry("scalar_field_decl", List.of("string", "int32")),
                    Map.entry("int64_as_string", List.of("strconv.FormatInt(")),
                    Map.entry("enum_def", List.of("const (")),
                    Map.entry("nested_class", List.of("type", "struct")),
                    Map.entry("repeated_field", List.of("[]")),
                    Map.entry("map_field", List.of("map[")),
                    Map.entry("oneof_tracking", List.of("Case")),
                    Map.entry("optional_presence", List.of("*")),
                    Map.entry("bytes_base64", List.of("base64.StdEncoding.EncodeToString(")),
                    Map.entry("cross_file_ref", List.of("Address")),
                    Map.entry("field_number_gap", List.of("gap (no field number 2)")),
                    Map.entry("keyword_escape", List.of("Type ")),
                    Map.entry("generated_marker", List.of("package"))))));
  }

  // ======================================================================
  // Helpers
  // ======================================================================

  private FieldDescriptorProto scalarField(
      String name, int number, FieldDescriptorProto.Type type) {
    return FieldDescriptorProto.newBuilder()
        .setName(name)
        .setNumber(number)
        .setType(type)
        .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
        .build();
  }

  private FieldDescriptorProto repeatedField(
      String name, int number, FieldDescriptorProto.Type type) {
    return FieldDescriptorProto.newBuilder()
        .setName(name)
        .setNumber(number)
        .setType(type)
        .setLabel(FieldDescriptorProto.Label.LABEL_REPEATED)
        .build();
  }

  private FieldDescriptorProto messageField(String name, int number, String typeName) {
    return FieldDescriptorProto.newBuilder()
        .setName(name)
        .setNumber(number)
        .setType(FieldDescriptorProto.Type.TYPE_MESSAGE)
        .setTypeName(typeName)
        .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
        .build();
  }

  private FieldDescriptorProto enumField(String name, int number, String typeName) {
    return FieldDescriptorProto.newBuilder()
        .setName(name)
        .setNumber(number)
        .setType(FieldDescriptorProto.Type.TYPE_ENUM)
        .setTypeName(typeName)
        .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
        .build();
  }

  /** Generate code for a single message with the given language. */
  private String generate(DescriptorProto msg, String lang) {
    return generate(msg, lang, "test", "proto3");
  }

  private String generate(DescriptorProto msg, String lang, String pkg, String syntax) {
    FileDescriptorProto file =
        FileDescriptorProto.newBuilder()
            .setName("test.proto")
            .setPackage(pkg)
            .setSyntax(syntax)
            .addMessageType(msg)
            .build();

    CodeGeneratorRequest request =
        CodeGeneratorRequest.newBuilder()
            .addProtoFile(file)
            .addFileToGenerate("test.proto")
            .setParameter("lang=" + lang)
            .build();

    CodeGeneratorResponse response = runner.run(request);
    assertFalse(response.hasError(), lang + ": Expected no error, got: " + response.getError());
    assertTrue(response.getFileCount() > 0, lang + ": Expected at least one generated file");

    // Concatenate all generated files to cover header+source (C, C++)
    StringBuilder all = new StringBuilder();
    for (int i = 0; i < response.getFileCount(); i++) {
      all.append(response.getFile(i).getContent());
    }
    return all.toString();
  }

  private void assertContainsAny(String code, List<String> patterns, String lang, String desc) {
    for (String pattern : patterns) {
      if (code.contains(pattern)) {
        return;
      }
    }
    // Build helpful failure message
    StringBuilder sb = new StringBuilder();
    sb.append("[").append(lang).append("] ").append(desc);
    sb.append(": expected at least one of ");
    sb.append(patterns);
    sb.append(" but none found in generated code.");
    assertTrue(false, sb.toString());
  }

  // ======================================================================
  // 1. Scalar field declarations
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testScalarFieldDeclarations(LangExpectation lang) {
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(scalarField("name", 1, FieldDescriptorProto.Type.TYPE_STRING))
            .addField(scalarField("age", 2, FieldDescriptorProto.Type.TYPE_INT32))
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(
        code, lang.patterns().get("scalar_field_decl"), lang.lang(), "scalar field declarations");
  }

  // ======================================================================
  // 2. Int64 serialized as string
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testInt64AsString(LangExpectation lang) {
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(scalarField("big_val", 1, FieldDescriptorProto.Type.TYPE_INT64))
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(
        code, lang.patterns().get("int64_as_string"), lang.lang(), "int64 string serialization");
  }

  // ======================================================================
  // 3. Enum definition
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testEnumGeneration(LangExpectation lang) {
    EnumDescriptorProto statusEnum =
        EnumDescriptorProto.newBuilder()
            .setName("Status")
            .addValue(EnumValueDescriptorProto.newBuilder().setName("UNKNOWN").setNumber(0).build())
            .addValue(EnumValueDescriptorProto.newBuilder().setName("ACTIVE").setNumber(1).build())
            .build();

    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addEnumType(statusEnum)
            .addField(enumField("status", 1, ".test.Msg.Status"))
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(code, lang.patterns().get("enum_def"), lang.lang(), "enum definition");
  }

  // ======================================================================
  // 4. Nested message
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testNestedMessage(LangExpectation lang) {
    DescriptorProto innerMsg =
        DescriptorProto.newBuilder()
            .setName("Inner")
            .addField(scalarField("value", 1, FieldDescriptorProto.Type.TYPE_STRING))
            .build();

    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Outer")
            .addNestedType(innerMsg)
            .addField(messageField("inner", 1, ".test.Outer.Inner"))
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(code, lang.patterns().get("nested_class"), lang.lang(), "nested message");
  }

  // ======================================================================
  // 5. Repeated field
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testRepeatedField(LangExpectation lang) {
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(repeatedField("tags", 1, FieldDescriptorProto.Type.TYPE_STRING))
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(code, lang.patterns().get("repeated_field"), lang.lang(), "repeated field");
  }

  // ======================================================================
  // 6. Map field
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testMapField(LangExpectation lang) {
    DescriptorProto mapEntry =
        DescriptorProto.newBuilder()
            .setName("MetadataEntry")
            .setOptions(MessageOptions.newBuilder().setMapEntry(true).build())
            .addField(scalarField("key", 1, FieldDescriptorProto.Type.TYPE_STRING))
            .addField(scalarField("value", 2, FieldDescriptorProto.Type.TYPE_STRING))
            .build();

    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addNestedType(mapEntry)
            .addField(
                FieldDescriptorProto.newBuilder()
                    .setName("metadata")
                    .setNumber(1)
                    .setType(FieldDescriptorProto.Type.TYPE_MESSAGE)
                    .setTypeName(".test.Msg.MetadataEntry")
                    .setLabel(FieldDescriptorProto.Label.LABEL_REPEATED)
                    .build())
            .build();

    FileDescriptorProto file =
        FileDescriptorProto.newBuilder()
            .setName("test.proto")
            .setPackage("test")
            .setSyntax("proto3")
            .addMessageType(msg)
            .build();

    CodeGeneratorRequest request =
        CodeGeneratorRequest.newBuilder()
            .addProtoFile(file)
            .addFileToGenerate("test.proto")
            .setParameter("lang=" + lang.lang())
            .build();

    CodeGeneratorResponse response = runner.run(request);
    assertFalse(
        response.hasError(), lang.lang() + ": Expected no error, got: " + response.getError());
    StringBuilder code = new StringBuilder();
    for (int i = 0; i < response.getFileCount(); i++) {
      code.append(response.getFile(i).getContent());
    }
    assertContainsAny(code.toString(), lang.patterns().get("map_field"), lang.lang(), "map field");
  }

  // ======================================================================
  // 7. Oneof case tracking
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testOneofCaseTracking(LangExpectation lang) {
    FieldDescriptorProto emailField =
        FieldDescriptorProto.newBuilder()
            .setName("email")
            .setNumber(2)
            .setType(FieldDescriptorProto.Type.TYPE_STRING)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
            .setOneofIndex(0)
            .build();

    FieldDescriptorProto phoneField =
        FieldDescriptorProto.newBuilder()
            .setName("phone")
            .setNumber(3)
            .setType(FieldDescriptorProto.Type.TYPE_STRING)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
            .setOneofIndex(0)
            .build();

    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(scalarField("name", 1, FieldDescriptorProto.Type.TYPE_STRING))
            .addField(emailField)
            .addField(phoneField)
            .addOneofDecl(OneofDescriptorProto.newBuilder().setName("contact").build())
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(
        code, lang.patterns().get("oneof_tracking"), lang.lang(), "oneof case tracking");
  }

  // ======================================================================
  // 8. Optional field presence
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testOptionalPresence(LangExpectation lang) {
    FieldDescriptorProto optField =
        FieldDescriptorProto.newBuilder()
            .setName("nickname")
            .setNumber(1)
            .setType(FieldDescriptorProto.Type.TYPE_STRING)
            .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
            .setProto3Optional(true)
            .setOneofIndex(0)
            .build();

    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(optField)
            .addOneofDecl(OneofDescriptorProto.newBuilder().setName("_nickname").build())
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(
        code, lang.patterns().get("optional_presence"), lang.lang(), "optional presence tracking");
  }

  // ======================================================================
  // 9. Bytes field with base64 encoding
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testBytesBase64(LangExpectation lang) {
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(scalarField("data", 1, FieldDescriptorProto.Type.TYPE_BYTES))
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(
        code, lang.patterns().get("bytes_base64"), lang.lang(), "bytes base64 encoding");
  }

  // ======================================================================
  // 10. Cross-file type reference
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testCrossFileReference(LangExpectation lang) {
    // Address message in address.proto
    DescriptorProto addressMsg =
        DescriptorProto.newBuilder()
            .setName("Address")
            .addField(scalarField("street", 1, FieldDescriptorProto.Type.TYPE_STRING))
            .build();

    FileDescriptorProto addressFile =
        FileDescriptorProto.newBuilder()
            .setName("address.proto")
            .setPackage("example")
            .setSyntax("proto3")
            .addMessageType(addressMsg)
            .build();

    // User message in user.proto that references Address
    DescriptorProto userMsg =
        DescriptorProto.newBuilder()
            .setName("User")
            .addField(scalarField("name", 1, FieldDescriptorProto.Type.TYPE_STRING))
            .addField(messageField("addr", 2, ".example.Address"))
            .build();

    FileDescriptorProto userFile =
        FileDescriptorProto.newBuilder()
            .setName("user.proto")
            .setPackage("example")
            .setSyntax("proto3")
            .addMessageType(userMsg)
            .addDependency("address.proto")
            .build();

    CodeGeneratorRequest request =
        CodeGeneratorRequest.newBuilder()
            .addProtoFile(addressFile)
            .addProtoFile(userFile)
            .addFileToGenerate("user.proto")
            .setParameter("lang=" + lang.lang())
            .build();

    CodeGeneratorResponse response = runner.run(request);
    assertFalse(
        response.hasError(), lang.lang() + ": Expected no error, got: " + response.getError());
    assertTrue(response.getFileCount() > 0, lang.lang() + ": Should generate at least one file");

    StringBuilder code = new StringBuilder();
    for (int i = 0; i < response.getFileCount(); i++) {
      code.append(response.getFile(i).getContent());
    }
    assertContainsAny(
        code.toString(),
        lang.patterns().get("cross_file_ref"),
        lang.lang(),
        "cross-file type reference");
  }

  // ======================================================================
  // 11. Field number gaps produce null padding
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testFieldNumberGaps(LangExpectation lang) {
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(scalarField("a", 1, FieldDescriptorProto.Type.TYPE_STRING))
            .addField(scalarField("b", 3, FieldDescriptorProto.Type.TYPE_STRING))
            .addField(scalarField("c", 5, FieldDescriptorProto.Type.TYPE_STRING))
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(
        code,
        lang.patterns().get("field_number_gap"),
        lang.lang(),
        "field number gap null padding");
  }

  // ======================================================================
  // 12. Keyword escaping
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testKeywordEscaping(LangExpectation lang) {
    // Each language has different reserved words:
    // Python/JS/TS/C++: "class" -> escaped
    // C: "struct" -> escaped with _pb suffix
    // Rust: "type" -> escaped with r# prefix
    // Go: "type" -> escaped with _ suffix
    // Zig: "const" -> escaped with @"..." syntax
    String fieldName =
        switch (lang.lang()) {
          case "c" -> "struct";
          case "rust" -> "type";
          case "go" -> "type";
          case "zig" -> "const";
          default -> "class"; // python, javascript, typescript, cpp
        };
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(
                FieldDescriptorProto.newBuilder()
                    .setName(fieldName)
                    .setNumber(1)
                    .setType(FieldDescriptorProto.Type.TYPE_STRING)
                    .setLabel(FieldDescriptorProto.Label.LABEL_OPTIONAL)
                    .build())
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(code, lang.patterns().get("keyword_escape"), lang.lang(), "keyword escaping");
  }

  // ======================================================================
  // 13. Generated file marker
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testGeneratedMarker(LangExpectation lang) {
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(scalarField("x", 1, FieldDescriptorProto.Type.TYPE_INT32))
            .build();
    String code = generate(msg, lang.lang());
    assertContainsAny(
        code,
        lang.patterns().get("generated_marker"),
        lang.lang(),
        "generated file marker or identifying header");
  }

  // ======================================================================
  // 14. Serialize method exists
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testSerializeMethodExists(LangExpectation lang) {
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(scalarField("x", 1, FieldDescriptorProto.Type.TYPE_INT32))
            .build();
    String code = generate(msg, lang.lang());
    // Every language must generate some form of serialize function/method
    List<String> serializePatterns =
        switch (lang.lang()) {
          case "python" -> List.of("def serialize(self):");
          case "javascript", "typescript" -> List.of("serialize()");
          case "c" -> List.of("_serialize(");
          case "cpp" -> List.of("serialize() const");
          case "rust" -> List.of("pub fn serialize(&self)");
          case "zig" -> List.of("pub fn serialize(");
          case "go" -> List.of("func (m *", "Serialize()");
          default -> List.of("serialize");
        };
    assertContainsAny(code, serializePatterns, lang.lang(), "serialize method exists");
  }

  // ======================================================================
  // 15. Deserialize method exists
  // ======================================================================

  @ParameterizedTest(name = "{0}")
  @MethodSource("languages")
  void testDeserializeMethodExists(LangExpectation lang) {
    DescriptorProto msg =
        DescriptorProto.newBuilder()
            .setName("Msg")
            .addField(scalarField("x", 1, FieldDescriptorProto.Type.TYPE_INT32))
            .build();
    String code = generate(msg, lang.lang());
    // Every language must generate some form of deserialize function/method
    List<String> deserializePatterns =
        switch (lang.lang()) {
          case "python" -> List.of("def deserialize(");
          case "javascript", "typescript" -> List.of("deserialize(");
          case "c" -> List.of("_deserialize(");
          case "cpp" -> List.of("deserialize(");
          case "rust" -> List.of("pub fn deserialize(");
          case "zig" -> List.of("pub fn deserialize(");
          case "go" -> List.of("func Deserialize");
          default -> List.of("deserialize");
        };
    assertContainsAny(code, deserializePatterns, lang.lang(), "deserialize method exists");
  }
}
