/*
 * Copyright 2026 protobuf-text-codecs contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.pbtkurl.codegen.zig;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.LanguageGenerator;
import dev.protocgen.textcodecs.jsonarray.codegen.ProtoTypeUtil;
import dev.protocgen.textcodecs.jsonarray.codegen.zig.ZigNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.zig.ZigTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import dev.protocgen.textcodecs.jsonarray.model.TypeRegistry;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Zig language code generator for pbtk URL encoding. Produces Zig source files with
 * toPbtkUrl()/fromPbtkUrl() serialization methods using the {@code !<fieldNumber><typeChar><value>}
 * format.
 */
public class PbtkZigGenerator implements LanguageGenerator {

  private static final String GENERATED_MARKER =
      "// @generated by protoc-gen-pbtkurl -- do not edit.";

  private final ZigNameResolver nameResolver = new ZigNameResolver();
  private final ZigTypeMapper typeMapper = new ZigTypeMapper();

  @Override
  public List<CodeGeneratorResponse.File> generate(ProtoFile file, TypeRegistry registry) {
    List<CodeGeneratorResponse.File> result = new ArrayList<>();

    for (ProtoMessage message : file.getMessages()) {
      nameResolver.validateFieldNames(message.getFields());
      String sourceCode = emitMessage(message, file);
      String outputPath = nameResolver.outputFilePath(file, message.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    for (ProtoEnum protoEnum : file.getEnums()) {
      String sourceCode = emitTopLevelEnum(protoEnum, file);
      String outputPath = nameResolver.outputFilePath(file, protoEnum.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    return result;
  }

  // ---------------------------------------------------------------------------
  // Code emission
  // ---------------------------------------------------------------------------

  private String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String structName = nameResolver.messageClassName(message.getName());

    w.line(GENERATED_MARKER);
    w.blankLine();

    emitImports(w);
    emitTypeImports(w, message, file);

    w.blankLine();

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
      w.blankLine();
    }

    // Nested messages
    for (ProtoMessage nested : message.getNestedMessages()) {
      emitNestedStruct(w, nested, file);
      w.blankLine();
    }

    // Oneof tagged unions
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      emitOneofUnion(w, group);
      w.blankLine();
    }

    // Main struct
    constBlock(
        w,
        "pub const " + structName + " = struct",
        () -> {
          emitFields(w, message);

          // toPbtkUrl
          emitToPbtkUrl(w, message, structName);

          // fromPbtkUrl
          emitFromPbtkUrl(w, message, structName);

          // deinit
          emitDeinit(w, message, structName);
        });

    return w.toString();
  }

  private String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    w.line(GENERATED_MARKER);
    w.blankLine();
    emitImports(w);
    w.blankLine();
    emitEnum(w, protoEnum);
    return w.toString();
  }

  // ---------------------------------------------------------------------------
  // Imports
  // ---------------------------------------------------------------------------

  private void emitImports(CodeWriter w) {
    w.line("const std = @import(\"std\");");
  }

  private void emitTypeImports(CodeWriter w, ProtoMessage message, ProtoFile file) {
    Set<String> imports = new LinkedHashSet<>();
    collectReferencedTypes(message, file, imports);
    for (String imp : imports) {
      w.line(imp);
    }
  }

  private void collectReferencedTypes(ProtoMessage message, ProtoFile file, Set<String> imports) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      addTypeImportIfNeeded(
          field.getTypeReference(), field.isWellKnownType(), message, currentPrefix, imports);
      if (field.isMap() && field.getMapValueTypeReference() != null) {
        addTypeImportIfNeeded(
            field.getMapValueTypeReference(), false, message, currentPrefix, imports);
      }
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      collectReferencedTypes(nested, file, imports);
    }
  }

  private void addTypeImportIfNeeded(
      String typeRef,
      boolean isWellKnown,
      ProtoMessage message,
      String currentPrefix,
      Set<String> imports) {
    if (typeRef == null || isWellKnown) return;
    for (ProtoMessage nested : message.getNestedMessages()) {
      if (typeRef.equals(message.getFullName() + "." + nested.getName())) return;
    }
    for (ProtoEnum nestedEnum : message.getEnums()) {
      if (typeRef.equals(message.getFullName() + "." + nestedEnum.getName())) return;
    }
    if (typeRef.startsWith(currentPrefix)) {
      String simpleName = typeRef.substring(typeRef.lastIndexOf('.') + 1);
      String moduleName = zigToSnakeCase(simpleName);
      imports.add(
          "const " + simpleName + " = @import(\"" + moduleName + ".zig\")." + simpleName + ";");
    }
  }

  // ---------------------------------------------------------------------------
  // Struct fields
  // ---------------------------------------------------------------------------

  private void emitFields(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.isOneofMember()) continue;
      String zigType = typeMapper.languageType(field);
      String zigName = nameResolver.fieldName(field.getName());
      String defaultVal = structFieldDefault(field);
      w.line("%s: %s = %s,", zigName, zigType, defaultVal);
    }

    // Oneof union fields
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String unionTypeName = pascalCase(group.name());
      String fieldName = nameResolver.fieldName(group.name());
      w.line("%s: ?%s = null,", fieldName, unionTypeName);
    }
  }

  private String structFieldDefault(ProtoField field) {
    if (field.isMap() || field.isRepeated()) return "undefined";
    return typeMapper.defaultValue(field);
  }

  // ---------------------------------------------------------------------------
  // pbtk URL serialization
  // ---------------------------------------------------------------------------

  private void emitToPbtkUrl(CodeWriter w, ProtoMessage message, String structName) {
    // Internal append helper
    w.blankLine();
    w.block(
        "fn appendPbtkFields(self: *const " + structName + ", buf: *std.ArrayList(u8)) void",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldSerialize(w, field);
          }
        });

    // Count helper
    w.blankLine();
    w.block(
        "fn countPbtkFields(self: *const " + structName + ") usize",
        () -> {
          w.line("var count: usize = 0;");
          for (ProtoField field : message.getFields()) {
            emitFieldCount(w, field);
          }
          w.line("return count;");
        });

    // Public method
    w.blankLine();
    w.block(
        "pub fn toPbtkUrl(self: *const " + structName + ", allocator: std.mem.Allocator) ![]u8",
        () -> {
          w.line("var buf = std.ArrayList(u8).init(allocator);");
          w.line("self.appendPbtkFields(&buf);");
          w.line("return buf.toOwnedSlice();");
        });
  }

  private void emitFieldSerialize(CodeWriter w, ProtoField field) {
    String zigField = "self." + nameResolver.fieldName(field.getName());
    int fieldNum = field.getFieldNumber();

    if (field.isOneofMember()) {
      String unionField = "self." + nameResolver.fieldName(field.getOneofName());
      String tagName = nameResolver.fieldName(field.getName());
      w.block(
          "if (" + unionField + ") |oneof_val|",
          () -> {
            w.block(
                "switch (oneof_val)",
                () -> {
                  w.block(
                      "." + tagName + " => |v|",
                      () -> emitSingleFieldSerialize(w, field, "v", fieldNum));
                  w.line("else => {},");
                });
          });
      return;
    }

    if (field.isMap()) {
      emitMapSerialize(w, field, zigField, fieldNum);
    } else if (field.isRepeated()) {
      emitRepeatedSerialize(w, field, zigField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      emitMessageSerialize(w, field, zigField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, zigField, fieldNum);
    } else {
      emitScalarSerialize(w, field, zigField, fieldNum);
    }
  }

  private void emitSingleFieldSerialize(
      CodeWriter w, ProtoField field, String zigField, int fieldNum) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      w.line("buf.writer().print(\"!%dm{d}\", .{v.countPbtkFields()}) catch {};", fieldNum);
      w.line("v.appendPbtkFields(buf);");
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      w.line("buf.writer().print(\"!%de{d}\", .{@intFromEnum(%s)}) catch {};", fieldNum, zigField);
    } else {
      emitScalarAppendDirect(w, field, zigField, fieldNum);
    }
  }

  private void emitScalarSerialize(CodeWriter w, ProtoField field, String zigField, int fieldNum) {
    FieldDescriptorProto.Type type = field.getProtoType();

    if (field.isProto3Optional()) {
      w.block("if (" + zigField + ") |v|", () -> emitScalarAppendDirect(w, field, "v", fieldNum));
      return;
    }

    emitScalarAppendDirect(w, field, zigField, fieldNum);
  }

  private void emitScalarAppendDirect(
      CodeWriter w, ProtoField field, String zigField, int fieldNum) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    switch (type) {
      case TYPE_BOOL:
        w.line(
            "buf.writer().print(\"!%d%s{s}\", .{if (%s) \"1\" else \"0\"}) catch {};",
            fieldNum, typeChar, zigField);
        break;
      case TYPE_BYTES:
        w.line("buf.writer().print(\"!%d%s\", .{}) catch {};", fieldNum, typeChar);
        w.line("const encoded = std.base64.standard.Encoder.encode(%s);", zigField);
        w.line("buf.appendSlice(encoded) catch {};");
        break;
      case TYPE_STRING:
        w.line("buf.writer().print(\"!%d%s\", .{}) catch {};", fieldNum, typeChar);
        w.line(
            "const pct = std.Uri.percentEncode(%s, std.Uri.Component.query) catch return;",
            zigField);
        w.line("buf.writer().writeAll(pct) catch {};");
        break;
      case TYPE_FLOAT:
        w.line("if (!std.math.isNan(%s) and !std.math.isInf(%s))", zigField, zigField);
        w.line(
            "    buf.writer().print(\"!%d%s{d}\", .{%s}) catch {};", fieldNum, typeChar, zigField);
        break;
      case TYPE_DOUBLE:
        w.line("if (!std.math.isNan(%s) and !std.math.isInf(%s))", zigField, zigField);
        w.line(
            "    buf.writer().print(\"!%d%s{d}\", .{%s}) catch {};", fieldNum, typeChar, zigField);
        break;
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32:
        w.line("buf.writer().print(\"!%d%s{d}\", .{%s}) catch {};", fieldNum, typeChar, zigField);
        break;
      case TYPE_UINT32, TYPE_FIXED32:
        w.line("buf.writer().print(\"!%d%s{d}\", .{%s}) catch {};", fieldNum, typeChar, zigField);
        break;
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64:
        w.line("buf.writer().print(\"!%d%s{d}\", .{%s}) catch {};", fieldNum, typeChar, zigField);
        break;
      case TYPE_UINT64, TYPE_FIXED64:
        w.line("buf.writer().print(\"!%d%s{d}\", .{%s}) catch {};", fieldNum, typeChar, zigField);
        break;
      default:
        w.line("buf.writer().print(\"!%d%s{d}\", .{%s}) catch {};", fieldNum, typeChar, zigField);
        break;
    }
  }

  private void emitEnumSerialize(CodeWriter w, ProtoField field, String zigField, int fieldNum) {
    if (field.isProto3Optional()) {
      w.block(
          "if (" + zigField + ") |v|",
          () -> w.line("buf.writer().print(\"!%de{d}\", .{@intFromEnum(v)}) catch {};", fieldNum));
    } else {
      w.line("buf.writer().print(\"!%de{d}\", .{@intFromEnum(%s)}) catch {};", fieldNum, zigField);
    }
  }

  private void emitMessageSerialize(CodeWriter w, ProtoField field, String zigField, int fieldNum) {
    w.block(
        "if (" + zigField + ") |v|",
        () -> {
          w.line("buf.writer().print(\"!%dm{d}\", .{v.countPbtkFields()}) catch {};", fieldNum);
          w.line("v.appendPbtkFields(buf);");
        });
  }

  private void emitRepeatedSerialize(
      CodeWriter w, ProtoField field, String zigField, int fieldNum) {
    w.block(
        "for (" + zigField + ".items) |item|",
        () -> {
          if (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
            w.line(
                "buf.writer().print(\"!%dm{d}\", .{item.countPbtkFields()}) catch {};", fieldNum);
            w.line("item.appendPbtkFields(buf);");
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            w.line("buf.writer().print(\"!%de{d}\", .{@intFromEnum(item)}) catch {};", fieldNum);
          } else {
            emitScalarAppendDirect(w, field, "item", fieldNum);
          }
        });
  }

  private void emitMapSerialize(CodeWriter w, ProtoField field, String zigField, int fieldNum) {
    w.block(
        "var it = " + zigField + ".iterator(); while (it.next()) |entry|",
        () -> {
          // Each map entry is a synthetic message with 2 sub-fields
          w.line("buf.writer().print(\"!%dm2\", .{}) catch {};", fieldNum);

          // Key (field 1)
          String keyTypeChar = pbtkTypeChar(field.getMapKeyType());
          if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("buf.writer().print(\"!1%s\", .{}) catch {};", keyTypeChar);
            w.line(
                "const pct_key = std.Uri.percentEncode(entry.key_ptr.*, std.Uri.Component.query) catch continue;");
            w.line("buf.writer().writeAll(pct_key) catch {};");
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line(
                "buf.writer().print(\"!1%s{s}\", .{if (entry.key_ptr.*) \"1\" else \"0\"}) catch {};",
                keyTypeChar);
          } else {
            w.line("buf.writer().print(\"!1%s{d}\", .{entry.key_ptr.*}) catch {};", keyTypeChar);
          }

          // Value (field 2)
          if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
            w.line(
                "buf.writer().print(\"!2m{d}\", .{entry.value_ptr.*.countPbtkFields()}) catch {};");
            w.line("entry.value_ptr.*.appendPbtkFields(buf);");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
            w.line("buf.writer().print(\"!2e{d}\", .{@intFromEnum(entry.value_ptr.*)}) catch {};");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("buf.writer().print(\"!2s\", .{}) catch {};");
            w.line(
                "const pct_val = std.Uri.percentEncode(entry.value_ptr.*, std.Uri.Component.query) catch continue;");
            w.line("buf.writer().writeAll(pct_val) catch {};");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
            w.line("buf.writer().print(\"!2z\", .{}) catch {};");
            w.line("const b64_val = std.base64.standard.Encoder.encode(entry.value_ptr.*);");
            w.line("buf.appendSlice(b64_val) catch {};");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line(
                "buf.writer().print(\"!2b{s}\", .{if (entry.value_ptr.*) \"1\" else \"0\"}) catch {};");
          } else {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.line("buf.writer().print(\"!2%s{d}\", .{entry.value_ptr.*}) catch {};", valTypeChar);
          }
        });
  }

  private void emitFieldCount(CodeWriter w, ProtoField field) {
    String zigField = "self." + nameResolver.fieldName(field.getName());

    if (field.isOneofMember()) {
      String unionField = "self." + nameResolver.fieldName(field.getOneofName());
      String tagName = nameResolver.fieldName(field.getName());
      w.block(
          "if (" + unionField + ") |oneof_val|",
          () -> {
            w.block(
                "switch (oneof_val)",
                () -> {
                  w.line(".%s => count += 1,", tagName);
                  w.line("else => {},");
                });
          });
      return;
    }

    if (field.isMap()) {
      w.line("count += %s.count();", zigField);
    } else if (field.isRepeated()) {
      w.line("count += %s.items.len;", zigField);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      w.line("if (%s != null) count += 1;", zigField);
    } else if (field.isProto3Optional()) {
      w.line("if (%s != null) count += 1;", zigField);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_FLOAT
        || field.getProtoType() == FieldDescriptorProto.Type.TYPE_DOUBLE) {
      w.line("if (!std.math.isNan(%s) and !std.math.isInf(%s)) count += 1;", zigField, zigField);
    } else {
      w.line("count += 1;");
    }
  }

  // ---------------------------------------------------------------------------
  // pbtk URL deserialization
  // ---------------------------------------------------------------------------

  private void emitFromPbtkUrl(CodeWriter w, ProtoMessage message, String structName) {
    // Internal parser
    w.blankLine();
    w.block(
        "fn parsePbtkTokens(tokens: []const []const u8, field_count: usize, offset: *usize) "
            + structName,
        () -> {
          w.line("var obj = %s{};", structName);
          w.line("var consumed: usize = 0;");
          w.block(
              "while (consumed < field_count and offset.* < tokens.len)",
              () -> {
                w.line("const token = tokens[offset.*];");
                w.line("var num_end: usize = 0;");
                w.block(
                    "while (num_end < token.len and token[num_end] >= '0' and token[num_end] <= '9')",
                    () -> w.line("num_end += 1;"));
                w.block(
                    "if (num_end == 0 or num_end >= token.len)",
                    () -> {
                      w.line("offset.* += 1;");
                      w.line("consumed += 1;");
                      w.line("continue;");
                    });
                w.line("const field_num = std.fmt.parseInt(i32, token[0..num_end], 10) catch 0;");
                w.line("const value = token[num_end + 1 ..];");

                // Switch on field number
                w.line("switch (field_num) {");
                w.indent();
                for (ProtoField field : message.getFields()) {
                  emitFieldCase(w, field);
                }
                w.block(
                    "else =>",
                    () -> {
                      w.line("offset.* += 1;");
                      w.line("consumed += 1;");
                    });
                w.dedent();
                w.line("}");
              });
          w.line("return obj;");
        });

    // Public fromPbtkUrl
    w.blankLine();
    w.block(
        "pub fn fromPbtkUrl(input: []const u8, allocator: std.mem.Allocator) !" + structName,
        () -> {
          w.line("if (input.len == 0) return %s{};", structName);
          w.line("const trimmed = if (input[0] == '!') input[1..] else input;");
          // Tokenize by splitting on '!'
          w.line("var token_list = std.ArrayList([]const u8).init(allocator);");
          w.line("defer token_list.deinit();");
          w.line("var start: usize = 0;");
          w.block(
              "for (trimmed, 0..) |ch, idx|",
              () -> {
                w.block(
                    "if (ch == '!')",
                    () -> {
                      w.line("try token_list.append(trimmed[start..idx]);");
                      w.line("start = idx + 1;");
                    });
              });
          w.line("if (start <= trimmed.len) try token_list.append(trimmed[start..]);");
          w.line("const tokens = token_list.items;");
          w.line("var offset: usize = 0;");
          w.line("return parsePbtkTokens(tokens, tokens.len, &offset);");
        });
  }

  private void emitFieldCase(CodeWriter w, ProtoField field) {
    int fieldNum = field.getFieldNumber();
    String zigName = nameResolver.fieldName(field.getName());

    w.block(
        fieldNum + " =>",
        () -> {
          if (field.isMap()) {
            emitMapDeserialize(w, field, zigName);
          } else if (field.isRepeated()) {
            emitRepeatedDeserialize(w, field, zigName);
          } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
            emitMessageDeserialize(w, field, zigName);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            emitEnumDeserialize(w, field, zigName);
          } else {
            emitScalarDeserialize(w, field, zigName);
          }
          w.line("offset.* += 1;");
          w.line("consumed += 1;");
        });
  }

  private void emitScalarDeserialize(CodeWriter w, ProtoField field, String zigName) {
    String readExpr = scalarReadExpr(field.getProtoType(), "value");
    if (field.isProto3Optional()) {
      w.line("obj.%s = %s;", zigName, readExpr);
    } else {
      w.line("obj.%s = %s;", zigName, readExpr);
    }
    if (field.isOneofMember()) {
      String unionField = nameResolver.fieldName(field.getOneofName());
      String tagName = nameResolver.fieldName(field.getName());
      w.line("obj.%s = .{ .%s = %s };", unionField, tagName, readExpr);
    }
  }

  private void emitEnumDeserialize(CodeWriter w, ProtoField field, String zigName) {
    w.line("obj.%s = @enumFromInt(std.fmt.parseInt(i32, value, 10) catch 0);", zigName);
    if (field.isOneofMember()) {
      String unionField = nameResolver.fieldName(field.getOneofName());
      String tagName = nameResolver.fieldName(field.getName());
      w.line(
          "obj.%s = .{ .%s = @enumFromInt(std.fmt.parseInt(i32, value, 10) catch 0) };",
          unionField, tagName);
    }
  }

  private void emitMessageDeserialize(CodeWriter w, ProtoField field, String zigName) {
    String msgType = zigSimpleTypeName(field.getTypeReference());
    w.line("const sub_count = std.fmt.parseInt(usize, value, 10) catch 0;");
    w.line("offset.* += 1;");
    w.line("obj.%s = %s.parsePbtkTokens(tokens, sub_count, offset);", zigName, msgType);
    w.line("offset.* -= 1;"); // compensate for outer increment
    if (field.isOneofMember()) {
      String unionField = nameResolver.fieldName(field.getOneofName());
      String tagName = nameResolver.fieldName(field.getName());
      w.line(
          "obj.%s = .{ .%s = %s.parsePbtkTokens(tokens, sub_count, offset) };",
          unionField, tagName, msgType);
    }
  }

  private void emitRepeatedDeserialize(CodeWriter w, ProtoField field, String zigName) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      String msgType = zigSimpleTypeName(field.getTypeReference());
      w.line("const sub_count = std.fmt.parseInt(usize, value, 10) catch 0;");
      w.line("offset.* += 1;");
      w.line(
          "obj.%s.append(%s.parsePbtkTokens(tokens, sub_count, offset)) catch {};",
          zigName, msgType);
      w.line("offset.* -= 1;");
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      w.line(
          "obj.%s.append(@enumFromInt(std.fmt.parseInt(i32, value, 10) catch 0)) catch {};",
          zigName);
    } else {
      String readExpr = scalarReadExpr(field.getProtoType(), "value");
      w.line("obj.%s.append(%s) catch {};", zigName, readExpr);
    }
  }

  private void emitMapDeserialize(CodeWriter w, ProtoField field, String zigName) {
    w.line("const entry_count = std.fmt.parseInt(usize, value, 10) catch 0;");
    w.line("offset.* += 1;");

    // Determine key/value types for temporaries
    String keyZigType = typeMapper.scalarType(field.getMapKeyType());
    String valZigType;
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE
        || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
      valZigType = zigSimpleTypeName(field.getMapValueTypeReference());
    } else {
      valZigType = typeMapper.scalarType(field.getMapValueType());
    }

    w.line("var entry_key: ?%s = null;", keyZigType);
    w.line("var entry_val: ?%s = null;", valZigType);

    w.line("var __mi: usize = 0;");
    w.block(
        "while (__mi < entry_count and offset.* < tokens.len) : (__mi += 1)",
        () -> {
          w.line("const mt = tokens[offset.*];");
          w.line("var mne: usize = 0;");
          w.block(
              "while (mne < mt.len and mt[mne] >= '0' and mt[mne] <= '9')",
              () -> w.line("mne += 1;"));
          w.block(
              "if (mne == 0 or mne >= mt.len)",
              () -> {
                w.line("offset.* += 1;");
                w.line("continue;");
              });
          w.line("const mfn = std.fmt.parseInt(i32, mt[0..mne], 10) catch 0;");
          w.line("const mval = mt[mne + 1 ..];");

          w.block(
              "if (mfn == 1)",
              () -> {
                String keyRead = scalarReadExpr(field.getMapKeyType(), "mval");
                w.line("entry_key = %s;", keyRead);
              });
          w.block(
              "if (mfn == 2)",
              () -> {
                if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
                  String msgType = zigSimpleTypeName(field.getMapValueTypeReference());
                  w.line("const vsc = std.fmt.parseInt(usize, mval, 10) catch 0;");
                  w.line("offset.* += 1;");
                  w.line("entry_val = %s.parsePbtkTokens(tokens, vsc, offset);", msgType);
                  w.line("offset.* -= 1;");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
                  w.line("entry_val = @enumFromInt(std.fmt.parseInt(i32, mval, 10) catch 0);");
                } else {
                  String valRead = scalarReadExpr(field.getMapValueType(), "mval");
                  w.line("entry_val = %s;", valRead);
                }
              });
          w.line("offset.* += 1;");
        });
    w.line("offset.* -= 1;"); // compensate for outer increment
    w.block(
        "if (entry_key) |k|",
        () -> {
          w.block("if (entry_val) |v|", () -> w.line("obj.%s.put(k, v) catch {};", zigName));
        });
  }

  private String scalarReadExpr(FieldDescriptorProto.Type type, String valueVar) {
    return switch (type) {
      case TYPE_DOUBLE -> "std.fmt.parseFloat(f64, " + valueVar + ") catch 0.0";
      case TYPE_FLOAT -> "std.fmt.parseFloat(f32, " + valueVar + ") catch 0.0";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64 ->
          "std.fmt.parseInt(i64, " + valueVar + ", 10) catch 0";
      case TYPE_UINT64, TYPE_FIXED64 -> "std.fmt.parseInt(u64, " + valueVar + ", 10) catch 0";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32 ->
          "std.fmt.parseInt(i32, " + valueVar + ", 10) catch 0";
      case TYPE_UINT32, TYPE_FIXED32 -> "std.fmt.parseInt(u32, " + valueVar + ", 10) catch 0";
      case TYPE_BOOL -> "std.mem.eql(u8, " + valueVar + ", \"1\")";
      case TYPE_STRING -> "std.Uri.percentDecode(" + valueVar + ") catch " + valueVar;
      case TYPE_BYTES -> "std.base64.standard.Decoder.decode(" + valueVar + ") catch \"\"";
      default -> valueVar;
    };
  }

  // ---------------------------------------------------------------------------
  // Enum and nested message emission
  // ---------------------------------------------------------------------------

  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    String enumName = nameResolver.messageClassName(protoEnum.getName());

    constBlock(
        w,
        "pub const " + enumName + " = enum(i32)",
        () -> {
          for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
            String constName = nameResolver.enumConstantName(val.name());
            w.line("%s = %d,", constName, val.number());
          }

          w.blankLine();
          w.block(
              "pub fn fromInt(value: i32) " + enumName,
              () -> w.line("return @enumFromInt(value);"));

          w.blankLine();
          w.block(
              "pub fn toInt(self: " + enumName + ") i32",
              () -> w.line("return @intFromEnum(self);"));
        });
  }

  private void emitOneofUnion(CodeWriter w, ProtoMessage.OneofGroup group) {
    String unionName = pascalCase(group.name());
    constBlock(
        w,
        "pub const " + unionName + " = union(enum)",
        () -> {
          for (ProtoField member : group.members()) {
            String tagName = nameResolver.fieldName(member.getName());
            String tagType = oneofMemberType(member);
            w.line("%s: %s,", tagName, tagType);
          }
        });
  }

  private String oneofMemberType(ProtoField field) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      return zigSimpleTypeName(field.getTypeReference());
    }
    if (field.getKind() == ProtoField.FieldKind.ENUM) {
      return zigSimpleTypeName(field.getTypeReference());
    }
    return typeMapper.scalarType(field.getProtoType());
  }

  private void emitNestedStruct(CodeWriter w, ProtoMessage nested, ProtoFile file) {
    String structName = nameResolver.messageClassName(nested.getName());

    for (ProtoEnum protoEnum : nested.getEnums()) {
      emitEnum(w, protoEnum);
      w.blankLine();
    }

    for (ProtoMessage deepNested : nested.getNestedMessages()) {
      emitNestedStruct(w, deepNested, file);
      w.blankLine();
    }

    for (ProtoMessage.OneofGroup group : nested.getOneofGroups()) {
      emitOneofUnion(w, group);
      w.blankLine();
    }

    constBlock(
        w,
        "pub const " + structName + " = struct",
        () -> {
          emitFields(w, nested);
          emitToPbtkUrl(w, nested, structName);
          emitFromPbtkUrl(w, nested, structName);
          emitDeinit(w, nested, structName);
        });
  }

  // ---------------------------------------------------------------------------
  // deinit
  // ---------------------------------------------------------------------------

  private void emitDeinit(CodeWriter w, ProtoMessage message, String structName) {
    w.blankLine();
    w.block(
        "pub fn deinit(self: *" + structName + ", allocator: std.mem.Allocator) void",
        () -> {
          boolean hasCleanup = false;
          for (ProtoField field : message.getFields()) {
            if (field.isOneofMember()) continue;
            String zigName = "self." + nameResolver.fieldName(field.getName());

            if (field.isMap()) {
              w.line("%s.deinit();", zigName);
              hasCleanup = true;
            } else if (field.isRepeated()) {
              w.line("%s.deinit();", zigName);
              hasCleanup = true;
            } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
                || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
              w.block("if (" + zigName + ") |*val|", () -> w.line("val.deinit(allocator);"));
              hasCleanup = true;
            }
          }

          for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
            String unionField = "self." + nameResolver.fieldName(group.name());
            w.block(
                "if (" + unionField + ") |*oneof_val|",
                () -> {
                  w.block(
                      "switch (oneof_val.*)",
                      () -> {
                        for (ProtoField member : group.members()) {
                          String tagName = nameResolver.fieldName(member.getName());
                          if (member.getKind() == ProtoField.FieldKind.MESSAGE
                              || member.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
                            w.line(".%s => |*msg| msg.deinit(allocator),", tagName);
                          } else {
                            w.line(".%s => {},", tagName);
                          }
                        }
                      });
                });
            hasCleanup = true;
          }

          if (!hasCleanup) {
            w.line("_ = allocator;");
          }
        });
  }

  // ---------------------------------------------------------------------------
  // Utilities
  // ---------------------------------------------------------------------------

  private void constBlock(CodeWriter w, String header, Runnable body) {
    w.line(header + " {");
    w.indent();
    body.run();
    w.dedent();
    w.line("};");
  }

  static String pbtkTypeChar(FieldDescriptorProto.Type type) {
    return switch (type) {
      case TYPE_BOOL -> "b";
      case TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64 ->
          "i";
      case TYPE_FLOAT -> "f";
      case TYPE_DOUBLE -> "d";
      case TYPE_STRING -> "s";
      case TYPE_ENUM -> "e";
      case TYPE_MESSAGE -> "m";
      case TYPE_BYTES -> "z";
      default -> "s";
    };
  }

  /** Convert PascalCase or UPPER_SNAKE_CASE to snake_case. */
  private static String zigToSnakeCase(String name) {
    if (name == null || name.isEmpty()) return name;
    if (name.contains("_")) return name.toLowerCase();
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < name.length(); i++) {
      char c = name.charAt(i);
      if (Character.isUpperCase(c)) {
        if (i > 0) {
          char prev = name.charAt(i - 1);
          boolean nextIsLower = i + 1 < name.length() && Character.isLowerCase(name.charAt(i + 1));
          if (Character.isLowerCase(prev) || (Character.isUpperCase(prev) && nextIsLower)) {
            sb.append('_');
          }
        }
        sb.append(Character.toLowerCase(c));
      } else {
        sb.append(c);
      }
    }
    return sb.toString();
  }

  /** Extract the simple type name from a fully-qualified proto type reference. */
  private static String zigSimpleTypeName(String protoFullName) {
    String simple = ProtoTypeUtil.simpleTypeName(protoFullName);
    return simple != null ? simple : "void";
  }

  static String pascalCase(String snake) {
    if (snake == null || snake.isEmpty()) return snake;
    StringBuilder sb = new StringBuilder();
    boolean nextUpper = true;
    for (int i = 0; i < snake.length(); i++) {
      char c = snake.charAt(i);
      if (c == '_') {
        nextUpper = true;
      } else if (nextUpper) {
        sb.append(Character.toUpperCase(c));
        nextUpper = false;
      } else {
        sb.append(c);
      }
    }
    return sb.toString();
  }
}
