// @generated by protoc-gen-pbtkurl -- do not edit.

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@interface EXAddress : NSObject

@property (nonatomic, copy, nullable) NSString *street;
@property (nonatomic, copy, nullable) NSString *city;
@property (nonatomic, copy, nullable) NSString *state;
@property (nonatomic, assign) int32_t zip;

/* pbtk URL serialization */
- (NSData *)data;

/* pbtk URL deserialization */
+ (instancetype)parseFromData:(NSData *)data error:(NSError **)errorPtr;

@end

NS_ASSUME_NONNULL_END
