// @generated by protoc-gen-pbtkurl -- do not edit.

#import "EXAddress.h"

static NSString *pbtk_url_encode(NSString *input) {
    if (!input) return @"";
    NSMutableCharacterSet *allowed = [[NSCharacterSet alphanumericCharacterSet] mutableCopy];
    [allowed addCharactersInString:@"-_.~"];
    return [input stringByAddingPercentEncodingWithAllowedCharacters:allowed] ?: @"";
}

static NSString *pbtk_url_decode(NSString *input) {
    if (!input) return @"";
    return [input stringByRemovingPercentEncoding] ?: @"";
}

static NSString *pbtk_base64_encode(NSData *data) {
    if (!data) return @"";
    return [data base64EncodedStringWithOptions:0];
}

static NSData *pbtk_base64_decode(NSString *str) {
    if (!str) return [NSData data];
    return [[NSData alloc] initWithBase64EncodedString:str options:0] ?: [NSData data];
}

static NSArray<NSString *> *pbtk_tokenize(NSString *input) {
    if (!input || input.length == 0) return @[];
    NSMutableArray<NSString *> *tokens = [NSMutableArray array];
    NSString *str = [input hasPrefix:@"!"] ? [input substringFromIndex:1] : input;
    NSArray *parts = [str componentsSeparatedByString:@"!"];
    for (NSString *part in parts) {
        if (part.length > 0) [tokens addObject:part];
    }
    return tokens;
}

@implementation EXAddress

- (NSData *)data {
    NSMutableString *buf = [NSMutableString string];
    [self appendPbtkFieldsTo:buf];
    return [buf dataUsingEncoding:NSUTF8StringEncoding];
}

- (void)appendPbtkFieldsTo:(NSMutableString *)buf {
    if (self.street != nil) {
        [buf appendFormat:@"!1s%@", pbtk_url_encode(self.street)];
    }
    if (self.city != nil) {
        [buf appendFormat:@"!2s%@", pbtk_url_encode(self.city)];
    }
    if (self.state != nil) {
        [buf appendFormat:@"!3s%@", pbtk_url_encode(self.state)];
    }
    [buf appendFormat:@"!4i%d", (int)self.zip];
}

- (NSInteger)countPbtkFields {
    NSInteger count = 0;
    if (self.street != nil) count++;
    if (self.city != nil) count++;
    if (self.state != nil) count++;
    count++;
    return count;
}

+ (instancetype)parseFromData:(NSData *)data error:(NSError **)errorPtr {
    if (!data || data.length == 0) return [[EXAddress alloc] init];
    NSString *input = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
    if (!input) {
        if (errorPtr) {
            *errorPtr = [NSError errorWithDomain:@"EXAddress" code:-1 userInfo:@{NSLocalizedDescriptionKey: @"Invalid UTF-8 data"}];
        }
        return nil;
    }
    NSArray<NSString *> *tokens = pbtk_tokenize(input);
    NSInteger offset = 0;
    return [EXAddress parsePbtkTokens:tokens fieldCount:(NSInteger)tokens.count offset:&offset];
}

+ (instancetype)parsePbtkTokens:(NSArray<NSString *> *)tokens fieldCount:(NSInteger)fieldCount offset:(NSInteger *)offset {
    EXAddress *obj = [[EXAddress alloc] init];
    NSInteger consumed = 0;
    while (consumed < fieldCount && *offset < (NSInteger)tokens.count) {
        NSString *token = tokens[*offset];
        // Parse field number and type char
        NSInteger numEnd = 0;
        while (numEnd < (NSInteger)token.length && [token characterAtIndex:numEnd] >= '0' && [token characterAtIndex:numEnd] <= '9') {
            numEnd++;
        }
        if (numEnd == 0 || numEnd >= (NSInteger)token.length) { (*offset)++; consumed++; continue; }
        NSInteger fieldNum = [[token substringToIndex:numEnd] integerValue];
        NSString *value = [token substringFromIndex:numEnd + 1];

        switch (fieldNum) {
            case 1: {
                obj.street = pbtk_url_decode(value);
                (*offset)++;
                consumed++;
                break;
            }
            case 2: {
                obj.city = pbtk_url_decode(value);
                (*offset)++;
                consumed++;
                break;
            }
            case 3: {
                obj.state = pbtk_url_decode(value);
                (*offset)++;
                consumed++;
                break;
            }
            case 4: {
                obj.zip = (int32_t)[value intValue];
                (*offset)++;
                consumed++;
                break;
            }
            default: (*offset)++; consumed++; break;
        }
    }
    return obj;
}

@end
