/*
 * Copyright 2026 coffeeandwork
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.pbtkurl.codegen.dart;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.LanguageGenerator;
import dev.protocgen.textcodecs.jsonarray.codegen.ProtoTypeUtil;
import dev.protocgen.textcodecs.jsonarray.codegen.dart.DartNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.dart.DartTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import dev.protocgen.textcodecs.jsonarray.model.TypeRegistry;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Dart language code generator for pbtk URL encoding. Produces Dart class files with
 * writeToBuffer()/fromBuffer() serialization using the {@code !<fieldNumber><typeChar><value>}
 * format.
 */
public class PbtkDartGenerator implements LanguageGenerator {

  private final DartNameResolver nameResolver = new DartNameResolver();
  private final DartTypeMapper typeMapper = new DartTypeMapper();

  @Override
  public List<CodeGeneratorResponse.File> generate(ProtoFile file, TypeRegistry registry) {
    List<CodeGeneratorResponse.File> result = new ArrayList<>();

    for (ProtoMessage message : file.getMessages()) {
      nameResolver.validateFieldNames(message.getFields());
      String sourceCode = emitMessage(message, file);
      String outputPath = nameResolver.outputFilePath(file, message.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    for (ProtoEnum protoEnum : file.getEnums()) {
      String sourceCode = emitTopLevelEnum(protoEnum, file);
      String outputPath = nameResolver.outputFilePath(file, protoEnum.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());
    }

    return result;
  }

  // ---------------------------------------------------------------------------
  // File-level emission
  // ---------------------------------------------------------------------------

  private String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    String className = nameResolver.messageClassName(message.getName());

    emitFileHeader(w, file);

    Set<String> importNames = new LinkedHashSet<>();
    collectReferencedTypeNames(message, file, importNames);
    emitImports(w, importNames);

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
      w.blankLine();
    }

    // Nested messages
    for (ProtoMessage nested : message.getNestedMessages()) {
      emitMessageClass(w, nested, file);
      w.blankLine();
    }

    // Main class
    emitMessageClass(w, message, file);

    return w.toString();
  }

  private String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter("  ");
    emitFileHeader(w, file);
    emitEnum(w, protoEnum);
    return w.toString();
  }

  private void emitFileHeader(CodeWriter w, ProtoFile file) {
    w.line("// Generated by protoc-gen-pbtkurl. DO NOT EDIT.");
    w.line("// Source: %s", file.getFileName());
    w.blankLine();
    w.line("import 'dart:convert';");
    w.blankLine();
  }

  private void emitImports(CodeWriter w, Set<String> importNames) {
    for (String name : importNames) {
      String fileName = DartNameResolver.pascalToSnake(name);
      w.line("import '%s.dart';", fileName);
    }
    if (!importNames.isEmpty()) {
      w.blankLine();
    }
  }

  // ---------------------------------------------------------------------------
  // Class emission
  // ---------------------------------------------------------------------------

  private void emitMessageClass(CodeWriter w, ProtoMessage message, ProtoFile file) {
    String className = nameResolver.messageClassName(message.getName());

    w.block(
        "class " + className,
        () -> {
          emitFields(w, message);
          emitConstructor(w, message, className);
          emitGettersSetters(w, message);
          emitHasMethods(w, message);
          emitToPbtkUrl(w, message);
          emitFromPbtkUrl(w, message, className);
          emitToString(w, message, className);
        });
  }

  // ---------------------------------------------------------------------------
  // Fields & Constructor
  // ---------------------------------------------------------------------------

  private void emitFields(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String dartName = nameResolver.fieldName(field.getName());
      String dartType = typeMapper.dartType(field);
      String defaultVal = typeMapper.defaultValue(field);

      if (field.getKind() == ProtoField.FieldKind.MESSAGE
          || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE
          || field.isProto3Optional()) {
        w.line("%s %s;", dartType, dartName);
      } else if (field.isMap() || field.isRepeated()) {
        w.line("%s %s = %s;", dartType, dartName, defaultVal);
      } else {
        w.line("%s %s = %s;", dartType, dartName, defaultVal);
      }
    }

    if (hasOptionalFields(message)) {
      w.blankLine();
      w.line("final Map<int, bool> _presentFields = {};");
    }

    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String caseProp = "_" + nameResolver.fieldName(group.name()) + "Case";
      w.line("int %s = 0; // 0 = not set", caseProp);
    }
  }

  private void emitConstructor(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.line("/// Creates a new [%s] instance.", className);
    w.line("%s();", className);
  }

  // ---------------------------------------------------------------------------
  // Getters / Setters / Has
  // ---------------------------------------------------------------------------

  private void emitGettersSetters(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String dartName = nameResolver.fieldName(field.getName());
      String getterName = nameResolver.getterName(field.getName());
      String setterName = nameResolver.setterName(field.getName());
      String dartType = typeMapper.dartType(field);

      w.blankLine();
      w.line("/// Returns the value of [%s].", field.getName());
      w.block(dartType + " " + getterName + "()", () -> w.line("return %s;", dartName));

      w.blankLine();
      w.line("/// Sets the value of [%s].", field.getName());
      w.block(
          "void " + setterName + "(" + dartType + " value)",
          () -> {
            w.line("%s = value;", dartName);
            if (field.isProto3Optional()) {
              w.line("_presentFields[%d] = true;", field.getArrayPosition());
            }
            if (field.isOneofMember()) {
              String caseProp = "_" + nameResolver.fieldName(field.getOneofName()) + "Case";
              w.line("%s = %d;", caseProp, field.getFieldNumber());
            }
          });
    }
  }

  private void emitHasMethods(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.isProto3Optional() || field.getKind() == ProtoField.FieldKind.MESSAGE) {
        String hasName = "has" + DartNameResolver.snakeToPascal(field.getName());
        w.blankLine();
        w.line("/// Returns whether the [%s] field is present.", field.getName());
        w.block(
            "bool " + hasName + "()",
            () -> {
              if (field.isProto3Optional()) {
                w.line("return _presentFields[%d] == true;", field.getArrayPosition());
              } else {
                w.line("return %s != null;", nameResolver.fieldName(field.getName()));
              }
            });
      }
    }
  }

  // ---------------------------------------------------------------------------
  // writeToBuffer() -- serialization
  // ---------------------------------------------------------------------------

  private void emitToPbtkUrl(CodeWriter w, ProtoMessage message) {
    // _countPbtkFields()
    w.blankLine();
    w.line("/// @private Counts how many top-level tokens this message produces.");
    w.block(
        "int _countPbtkFields()",
        () -> {
          w.line("int count = 0;");
          for (ProtoField field : message.getFields()) {
            emitFieldCount(w, field);
          }
          w.line("return count;");
        });

    // _appendPbtkFields(parts)
    w.blankLine();
    w.line("/// @private Appends pbtk tokens to the given list.");
    w.block(
        "void _appendPbtkFields(List<String> parts)",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldSerialize(w, field);
          }
        });

    // writeToBuffer() -- public method
    w.blankLine();
    w.line("/// Serialize this message to a Uint8List.");
    w.block(
        "Uint8List writeToBuffer()",
        () -> {
          w.line("final parts = <String>[];");
          w.line("_appendPbtkFields(parts);");
          w.line("return Uint8List.fromList(utf8.encode(parts.join('')));");
        });
  }

  private void emitFieldCount(CodeWriter w, ProtoField field) {
    String dartField = nameResolver.fieldName(field.getName());

    if (field.isOneofMember()) {
      String caseProp = "_" + nameResolver.fieldName(field.getOneofName()) + "Case";
      w.line("if (%s == %d) count++;", caseProp, field.getFieldNumber());
      return;
    }

    if (field.isMap()) {
      w.line("count += %s.length;", dartField);
    } else if (field.isRepeated()) {
      w.line("count += %s.length;", dartField);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      w.line("if (%s != null) count++;", dartField);
    } else if (field.isProto3Optional()) {
      w.line("if (_presentFields[%d] == true) count++;", field.getArrayPosition());
    } else {
      w.line("count++;");
    }
  }

  private void emitFieldSerialize(CodeWriter w, ProtoField field) {
    String dartField = nameResolver.fieldName(field.getName());
    int fieldNum = field.getFieldNumber();

    if (field.isOneofMember()) {
      String caseProp = "_" + nameResolver.fieldName(field.getOneofName()) + "Case";
      w.block(
          "if (" + caseProp + " == " + field.getFieldNumber() + ")",
          () -> emitSingleFieldSerialize(w, field, dartField, fieldNum));
      return;
    }

    if (field.isMap()) {
      emitMapSerialize(w, field, dartField, fieldNum);
    } else if (field.isRepeated()) {
      emitRepeatedSerialize(w, field, dartField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      emitMessageSerialize(w, field, dartField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, dartField, fieldNum);
    } else {
      emitScalarSerialize(w, field, dartField, fieldNum);
    }
  }

  private void emitSingleFieldSerialize(
      CodeWriter w, ProtoField field, String dartField, int fieldNum) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      emitMessageSerialize(w, field, dartField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, dartField, fieldNum);
    } else {
      emitScalarSerialize(w, field, dartField, fieldNum);
    }
  }

  private void emitScalarSerialize(CodeWriter w, ProtoField field, String dartField, int fieldNum) {
    if (field.isProto3Optional()) {
      w.block(
          "if (_presentFields[" + field.getArrayPosition() + "] == true)",
          () -> emitScalarAppend(w, field, dartField, fieldNum));
      return;
    }
    emitScalarAppend(w, field, dartField, fieldNum);
  }

  private void emitScalarAppend(CodeWriter w, ProtoField field, String dartField, int fieldNum) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    switch (type) {
      case TYPE_BOOL:
        w.line("parts.add('!%d%s${%s ? '1' : '0'}');", fieldNum, typeChar, dartField);
        break;
      case TYPE_BYTES:
        w.line("parts.add('!%d%s${base64Encode(%s)}');", fieldNum, typeChar, dartField);
        break;
      case TYPE_STRING:
        w.line("parts.add('!%d%s${Uri.encodeComponent(%s)}');", fieldNum, typeChar, dartField);
        break;
      default:
        w.line("parts.add('!%d%s$%s');", fieldNum, typeChar, dartField);
        break;
    }
  }

  private void emitEnumSerialize(CodeWriter w, ProtoField field, String dartField, int fieldNum) {
    if (field.isProto3Optional()) {
      w.block(
          "if (_presentFields[" + field.getArrayPosition() + "] == true)",
          () -> w.line("parts.add('!%de${%s ?? 0}');", fieldNum, dartField));
    } else {
      w.line("parts.add('!%de${%s ?? 0}');", fieldNum, dartField);
    }
  }

  private void emitMessageSerialize(
      CodeWriter w, ProtoField field, String dartField, int fieldNum) {
    w.block(
        "if (" + dartField + " != null)",
        () -> {
          w.line("parts.add('!%dm${%s!._countPbtkFields()}');", fieldNum, dartField);
          w.line("%s!._appendPbtkFields(parts);", dartField);
        });
  }

  private void emitRepeatedSerialize(
      CodeWriter w, ProtoField field, String dartField, int fieldNum) {
    String elemVar = "__${nameResolver.fieldName(field.getName())}Item";
    // Use a simpler variable name
    String elem = "elem";
    w.block(
        "for (final " + elem + " in " + dartField + ")",
        () -> {
          if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
            w.block(
                "if (" + elem + " != null)",
                () -> {
                  w.line("parts.add('!%dm${%s._countPbtkFields()}');", fieldNum, elem);
                  w.line("%s._appendPbtkFields(parts);", elem);
                });
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            w.line("parts.add('!%de${%s ?? 0}');", fieldNum, elem);
          } else {
            emitScalarAppend(w, field, elem, fieldNum);
          }
        });
  }

  private void emitMapSerialize(CodeWriter w, ProtoField field, String dartField, int fieldNum) {
    w.block(
        "for (final entry in " + dartField + ".entries)",
        () -> {
          w.line("parts.add('!%dm2');", fieldNum);

          // Key (field 1)
          String keyTypeChar = pbtkTypeChar(field.getMapKeyType());
          if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("parts.add('!1%s${Uri.encodeComponent(entry.key)}');", keyTypeChar);
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("parts.add('!1%s${entry.key == true ? '1' : '0'}');", keyTypeChar);
          } else {
            w.line("parts.add('!1%s${entry.key}');", keyTypeChar);
          }

          // Value (field 2)
          if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
            w.block(
                "if (entry.value != null)",
                () -> {
                  w.line("parts.add('!2m${entry.value._countPbtkFields()}');");
                  w.line("entry.value._appendPbtkFields(parts);");
                });
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
            w.line("parts.add('!2e${entry.value ?? 0}');");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("parts.add('!2s${Uri.encodeComponent(entry.value.toString())}');");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
            w.line("parts.add('!2z${base64Encode(entry.value)}');");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("parts.add('!2b${entry.value == true ? '1' : '0'}');");
          } else {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.line("parts.add('!2%s${entry.value}');", valTypeChar);
          }
        });
  }

  // ---------------------------------------------------------------------------
  // fromBuffer() -- deserialization
  // ---------------------------------------------------------------------------

  private void emitFromPbtkUrl(CodeWriter w, ProtoMessage message, String className) {
    // _parsePbtkTokens -- internal parser
    w.blankLine();
    w.line("/// @private Parses pbtk tokens into this message type.");
    w.block(
        "static "
            + className
            + " _parsePbtkTokens(List<String> tokens, int fieldCount, List<int> offset)",
        () -> {
          w.line("final obj = %s();", className);
          w.line("int consumed = 0;");
          w.block(
              "while (consumed < fieldCount && offset[0] < tokens.length)",
              () -> {
                w.line("final token = tokens[offset[0]];");
                w.line("int numEnd = 0;");
                w.line(
                    "while (numEnd < token.length && token.codeUnitAt(numEnd) >= 48 && token.codeUnitAt(numEnd) <= 57) { numEnd++; }");
                w.line(
                    "if (numEnd == 0 || numEnd >= token.length) { offset[0]++; consumed++; continue; }");
                w.line("final fieldNum = int.parse(token.substring(0, numEnd));");
                w.line("final value = token.substring(numEnd + 1);");
                w.blankLine();

                w.block(
                    "switch (fieldNum)",
                    () -> {
                      for (ProtoField field : message.getFields()) {
                        emitFieldCase(w, field);
                      }
                      w.line("default: offset[0]++; consumed++; break;");
                    });
              });
          w.line("return obj;");
        });

    // fromBuffer -- public factory constructor
    w.blankLine();
    w.line("/// Deserialize from a Uint8List.");
    w.block(
        "static " + className + " fromBuffer(Uint8List buffer)",
        () -> {
          w.line("final input = utf8.decode(buffer);");
          w.line("if (input.isEmpty) return %s();", className);
          w.line("final tokens = %s._tokenizePbtk(input);", className);
          w.line("final offset = [0];");
          w.line("return %s._parsePbtkTokens(tokens, tokens.length, offset);", className);
        });

    // _tokenizePbtk -- split on '!'
    w.blankLine();
    w.line("/// @private Tokenizes a pbtk URL string into individual tokens.");
    w.block(
        "static List<String> _tokenizePbtk(String input)",
        () -> {
          w.line("final tokens = <String>[];");
          w.line("int i = input.isNotEmpty && input[0] == '!' ? 1 : 0;");
          w.block(
              "while (i < input.length)",
              () -> {
                w.line("final next = input.indexOf('!', i);");
                w.block(
                    "if (next < 0)",
                    () -> {
                      w.line("tokens.add(input.substring(i));");
                      w.line("break;");
                    });
                w.line("tokens.add(input.substring(i, next));");
                w.line("i = next + 1;");
              });
          w.line("return tokens;");
        });
  }

  private void emitFieldCase(CodeWriter w, ProtoField field) {
    int fieldNum = field.getFieldNumber();
    String setter = "obj." + nameResolver.setterName(field.getName());
    String getter = "obj." + nameResolver.getterName(field.getName()) + "()";

    w.block(
        "case " + fieldNum + ":",
        () -> {
          if (field.isMap()) {
            emitMapDeserialize(w, field);
          } else if (field.isRepeated()) {
            emitRepeatedDeserialize(w, field, getter);
          } else if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
            emitMessageDeserialize(w, field, setter);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            emitEnumDeserialize(w, field, setter);
          } else {
            emitScalarDeserialize(w, field, setter);
          }
          w.line("offset[0]++;");
          w.line("consumed++;");
          w.line("break;");
        });
  }

  private void emitScalarDeserialize(CodeWriter w, ProtoField field, String setter) {
    String readExpr = dartScalarReadExpr(field.getProtoType(), "value");
    w.line("%s(%s);", setter, readExpr);
    if (field.isProto3Optional()) {
      w.line("obj._presentFields[%d] = true;", field.getArrayPosition());
    }
  }

  private void emitEnumDeserialize(CodeWriter w, ProtoField field, String setter) {
    w.line("%s(int.parse(value));", setter);
    if (field.isProto3Optional()) {
      w.line("obj._presentFields[%d] = true;", field.getArrayPosition());
    }
  }

  private void emitMessageDeserialize(CodeWriter w, ProtoField field, String setter) {
    String msgType = typeMapper.simpleTypeName(field.getTypeReference());
    w.line("final subCount = int.parse(value);");
    w.line("offset[0]++;");
    w.line("%s(%s._parsePbtkTokens(tokens, subCount, offset));", setter, msgType);
    w.line("offset[0]--;"); // compensate for outer offset[0]++
  }

  private void emitRepeatedDeserialize(CodeWriter w, ProtoField field, String getter) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE) {
      String msgType = typeMapper.simpleTypeName(field.getTypeReference());
      w.line("final subCount = int.parse(value);");
      w.line("offset[0]++;");
      w.line("%s.add(%s._parsePbtkTokens(tokens, subCount, offset));", getter, msgType);
      w.line("offset[0]--;");
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      w.line("%s.add(int.parse(value));", getter);
    } else {
      String readExpr = dartScalarReadExpr(field.getProtoType(), "value");
      w.line("%s.add(%s);", getter, readExpr);
    }
  }

  private void emitMapDeserialize(CodeWriter w, ProtoField field) {
    String dartField = "obj." + nameResolver.fieldName(field.getName());
    w.line("final entryCount = int.parse(value);");
    w.line("offset[0]++;");
    w.line("dynamic entryKey;");
    w.line("dynamic entryVal;");
    w.block(
        "for (int mi = 0; mi < entryCount && offset[0] < tokens.length; mi++)",
        () -> {
          w.line("final mapToken = tokens[offset[0]];");
          w.line("int mne = 0;");
          w.line(
              "while (mne < mapToken.length && mapToken.codeUnitAt(mne) >= 48 && mapToken.codeUnitAt(mne) <= 57) { mne++; }");
          w.line("if (mne == 0 || mne >= mapToken.length) { offset[0]++; continue; }");
          w.line("final mfn = int.parse(mapToken.substring(0, mne));");
          w.line("final mval = mapToken.substring(mne + 1);");

          // Key (field 1)
          w.block(
              "if (mfn == 1)",
              () -> {
                String keyRead = dartScalarReadExpr(field.getMapKeyType(), "mval");
                w.line("entryKey = %s;", keyRead);
              });

          // Value (field 2)
          w.block(
              "if (mfn == 2)",
              () -> {
                if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
                  String msgType = typeMapper.simpleTypeName(field.getMapValueTypeReference());
                  w.line("final valSubCount = int.parse(mval);");
                  w.line("offset[0]++;");
                  w.line("entryVal = %s._parsePbtkTokens(tokens, valSubCount, offset);", msgType);
                  w.line("offset[0]--;");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
                  w.line("entryVal = int.parse(mval);");
                } else {
                  String valRead = dartScalarReadExpr(field.getMapValueType(), "mval");
                  w.line("entryVal = %s;", valRead);
                }
              });
          w.line("offset[0]++;");
        });
    w.line("offset[0]--;"); // compensate for outer offset[0]++
    w.line("if (entryKey != null) %s[entryKey] = entryVal;", dartField);
  }

  // ---------------------------------------------------------------------------
  // Shared helpers
  // ---------------------------------------------------------------------------

  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    String enumName = protoEnum.getName();
    w.line("/// Enum values for %s.", enumName);
    w.block(
        "abstract class " + enumName,
        () -> {
          for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
            w.line(
                "static const int %s = %d;",
                nameResolver.enumConstantName(val.name()), val.number());
          }
        });
  }

  private void emitToString(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.line("@override");
    w.block(
        "String toString()",
        () -> {
          if (message.getFields().isEmpty()) {
            w.line("return '%s{}';", className);
            return;
          }
          StringBuilder sb = new StringBuilder();
          sb.append("return '").append(className).append("{");
          for (int i = 0; i < message.getFields().size(); i++) {
            ProtoField field = message.getFields().get(i);
            String dartName = nameResolver.fieldName(field.getName());
            if (i > 0) sb.append(", ");
            sb.append(field.getName()).append("=$").append(dartName);
          }
          sb.append("}';");
          w.line(sb.toString());
        });
  }

  private void collectReferencedTypeNames(ProtoMessage message, ProtoFile file, Set<String> names) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      String typeRef = field.getTypeReference();
      if (typeRef == null) continue;
      if (field.isWellKnownType()) continue;

      boolean isNested = false;
      for (ProtoMessage nested : message.getNestedMessages()) {
        if (typeRef.equals(message.getFullName() + "." + nested.getName())) {
          isNested = true;
          break;
        }
      }
      if (isNested) continue;

      String simpleName = ProtoTypeUtil.simpleTypeName(typeRef);
      if (typeRef.startsWith(currentPrefix)) {
        names.add(simpleName);
      }

      if (field.isMap() && field.getMapValueTypeReference() != null) {
        String valRef = field.getMapValueTypeReference();
        String valName = ProtoTypeUtil.simpleTypeName(valRef);
        if (valRef.startsWith(currentPrefix)) {
          names.add(valName);
        }
      }
    }

    for (ProtoMessage nested : message.getNestedMessages()) {
      collectReferencedTypeNames(nested, file, names);
    }
  }

  private boolean hasOptionalFields(ProtoMessage message) {
    return message.getFields().stream().anyMatch(ProtoField::isProto3Optional);
  }

  private String dartScalarReadExpr(FieldDescriptorProto.Type type, String valueVar) {
    return switch (type) {
      case TYPE_DOUBLE, TYPE_FLOAT -> "double.parse(" + valueVar + ")";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64, TYPE_UINT64, TYPE_FIXED64 -> valueVar;
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32, TYPE_UINT32, TYPE_FIXED32 ->
          "int.parse(" + valueVar + ")";
      case TYPE_BOOL -> valueVar + " == '1'";
      case TYPE_STRING -> "Uri.decodeComponent(" + valueVar + ")";
      case TYPE_BYTES -> "base64Decode(" + valueVar + ")";
      default -> valueVar;
    };
  }

  static String pbtkTypeChar(FieldDescriptorProto.Type type) {
    return switch (type) {
      case TYPE_BOOL -> "b";
      case TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64 ->
          "i";
      case TYPE_FLOAT -> "f";
      case TYPE_DOUBLE -> "d";
      case TYPE_STRING -> "s";
      case TYPE_ENUM -> "e";
      case TYPE_MESSAGE -> "m";
      case TYPE_BYTES -> "z";
      default -> "s";
    };
  }
}
