/*
 * Copyright 2026 coffeeandwork
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.pbtkurl.codegen.objc;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.LanguageGenerator;
import dev.protocgen.textcodecs.jsonarray.codegen.ProtoTypeUtil;
import dev.protocgen.textcodecs.jsonarray.codegen.objc.ObjCNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.objc.ObjCTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import dev.protocgen.textcodecs.jsonarray.model.TypeRegistry;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Objective-C language code generator for pbtk URL encoding. Produces .h header and .m
 * implementation file pairs with pbtk URL serialization/deserialization using the {@code
 * !<fieldNumber><typeChar><value>} format.
 *
 * <p>For each message, two CodeGeneratorResponse.File entries are produced:
 *
 * <ol>
 *   <li>ClassName.h - @interface with properties and method declarations
 *   <li>ClassName.m - @implementation with to_pbtk_url / from_pbtk_url logic
 * </ol>
 *
 * <p>For top-level enums, only a .h file is produced. Uses ARC and Foundation types. Pbtk URL
 * encoding uses pure string manipulation (NSMutableString), no external dependencies.
 */
public class PbtkObjCGenerator implements LanguageGenerator {

  private static final String GENERATED_MARKER =
      "// @generated by protoc-gen-pbtkurl -- do not edit.";

  private final ObjCNameResolver nameResolver = new ObjCNameResolver();
  private final ObjCTypeMapper typeMapper = new ObjCTypeMapper(nameResolver);

  @Override
  public List<CodeGeneratorResponse.File> generate(ProtoFile file, TypeRegistry registry) {
    List<CodeGeneratorResponse.File> result = new ArrayList<>();

    for (ProtoMessage message : file.getMessages()) {
      nameResolver.validateFieldNames(message.getFields());

      // Header file (.h)
      String headerCode = emitHeader(message, file);
      String headerPath = nameResolver.outputFilePath(file, message.getName());
      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(headerPath)
              .setContent(headerCode)
              .build());

      // Implementation file (.m)
      String sourceCode = emitSource(message, file);
      String sourcePath = nameResolver.outputSourcePath(file, message.getName());
      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(sourcePath)
              .setContent(sourceCode)
              .build());
    }

    // Generate .h for each top-level enum (no .m needed)
    for (ProtoEnum protoEnum : file.getEnums()) {
      String headerCode = emitTopLevelEnumHeader(protoEnum, file);
      String headerPath = nameResolver.outputFilePath(file, protoEnum.getName());
      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(headerPath)
              .setContent(headerCode)
              .build());
    }

    return result;
  }

  // ========================================================================
  // Header file (.h) generation
  // ========================================================================

  private String emitHeader(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String className = nameResolver.qualifiedClassName(file, message.getName());

    w.line(GENERATED_MARKER);
    w.blankLine();
    w.line("#import <Foundation/Foundation.h>");
    w.blankLine();

    // Import headers for cross-file referenced types
    emitCrossFileImports(w, message, file);

    // Forward declarations for message types
    emitForwardDeclarations(w, message, file);

    w.line("NS_ASSUME_NONNULL_BEGIN");
    w.blankLine();

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnumDef(w, protoEnum, file, message.getName() + "_");
    }

    // Nested message forward declarations
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedClass =
          nameResolver.qualifiedClassName(file, message.getName() + "_" + nested.getName());
      w.line("@class %s;", nestedClass);
    }
    if (!message.getNestedMessages().isEmpty()) {
      w.blankLine();
    }

    // Main @interface
    w.line("@interface %s : NSObject", className);
    w.blankLine();

    // Properties
    for (ProtoField field : message.getFields()) {
      if (field.isOneofMember()) continue;
      emitPropertyDecl(w, field);
    }

    // Oneof properties
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      for (ProtoField member : group.members()) {
        emitPropertyDecl(w, member);
      }
    }

    // Proto3 optional presence tracking
    for (ProtoField field : message.getFields()) {
      if (field.isProto3Optional() && !field.isOneofMember()) {
        String propName = nameResolver.fieldName(field.getName());
        w.line("@property (nonatomic, assign) BOOL has%s;", capitalize(propName));
      }
    }

    w.blankLine();

    // pbtk URL serialization methods
    w.line("/* pbtk URL serialization */");
    w.line("- (NSData *)data;");
    w.blankLine();
    w.line("/* pbtk URL deserialization */");
    w.line("+ (instancetype)parseFromData:(NSData *)data error:(NSError **)errorPtr;");

    w.blankLine();
    w.line("@end");
    w.blankLine();

    // Nested message interfaces
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedClassName =
          nameResolver.qualifiedClassName(file, message.getName() + "_" + nested.getName());
      emitNestedMessageHeader(w, nested, file, nestedClassName, message.getName() + "_");
    }

    w.line("NS_ASSUME_NONNULL_END");

    return w.toString();
  }

  private String emitTopLevelEnumHeader(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter();

    w.line(GENERATED_MARKER);
    w.blankLine();
    w.line("#import <Foundation/Foundation.h>");
    w.blankLine();
    w.line("NS_ASSUME_NONNULL_BEGIN");
    w.blankLine();

    emitEnumDef(w, protoEnum, file, "");

    w.line("NS_ASSUME_NONNULL_END");

    return w.toString();
  }

  // ========================================================================
  // Source file (.m) generation
  // ========================================================================

  private String emitSource(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    String className = nameResolver.qualifiedClassName(file, message.getName());

    w.line(GENERATED_MARKER);
    w.blankLine();

    // Import own header
    w.line("#import \"%s.h\"", className);
    w.blankLine();

    // Static helper: URL percent-encode
    emitUrlEncodeHelper(w);

    // Static helper: URL percent-decode
    emitUrlDecodeHelper(w);

    // Static helper: base64 encode NSData -> NSString
    emitBase64Helpers(w);

    // Static helper: tokenize pbtk URL string
    emitTokenizerHelper(w);

    // Nested message implementations first
    for (ProtoMessage nested : message.getNestedMessages()) {
      String nestedClassName =
          nameResolver.qualifiedClassName(file, message.getName() + "_" + nested.getName());
      emitNestedMessageSource(w, nested, file, nestedClassName, message.getName() + "_");
    }

    // Main @implementation
    w.line("@implementation %s", className);

    // data
    emitSerializeMethod(w, message, className);

    // Internal: appendPbtkFields
    emitAppendFieldsMethod(w, message, className);

    // Internal: countPbtkFields
    emitCountFieldsMethod(w, message, className);

    // parseFromData:error:
    emitDeserializeMethod(w, message, className);

    // Internal: parsePbtkTokens
    emitParseTokensMethod(w, message, className);

    w.blankLine();
    w.line("@end");

    return w.toString();
  }

  // ========================================================================
  // Static helpers (emitted once per .m file)
  // ========================================================================

  private void emitUrlEncodeHelper(CodeWriter w) {
    w.line("static NSString *pbtk_url_encode(NSString *input) {");
    w.indent();
    w.line("if (!input) return @\"\";");
    w.line(
        "NSMutableCharacterSet *allowed = [[NSCharacterSet alphanumericCharacterSet] mutableCopy];");
    w.line("[allowed addCharactersInString:@\"-_.~\"];");
    w.line("return [input stringByAddingPercentEncodingWithAllowedCharacters:allowed] ?: @\"\";");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  private void emitUrlDecodeHelper(CodeWriter w) {
    w.line("static NSString *pbtk_url_decode(NSString *input) {");
    w.indent();
    w.line("if (!input) return @\"\";");
    w.line("return [input stringByRemovingPercentEncoding] ?: @\"\";");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  private void emitBase64Helpers(CodeWriter w) {
    w.line("static NSString *pbtk_base64_encode(NSData *data) {");
    w.indent();
    w.line("if (!data) return @\"\";");
    w.line("return [data base64EncodedStringWithOptions:0];");
    w.dedent();
    w.line("}");
    w.blankLine();

    w.line("static NSData *pbtk_base64_decode(NSString *str) {");
    w.indent();
    w.line("if (!str) return [NSData data];");
    w.line("return [[NSData alloc] initWithBase64EncodedString:str options:0] ?: [NSData data];");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  private void emitTokenizerHelper(CodeWriter w) {
    w.line("static NSArray<NSString *> *pbtk_tokenize(NSString *input) {");
    w.indent();
    w.line("if (!input || input.length == 0) return @[];");
    w.line("NSMutableArray<NSString *> *tokens = [NSMutableArray array];");
    w.line("NSString *str = [input hasPrefix:@\"!\"] ? [input substringFromIndex:1] : input;");
    w.line("NSArray *parts = [str componentsSeparatedByString:@\"!\"];");
    w.block(
        "for (NSString *part in parts)",
        () -> {
          w.line("if (part.length > 0) [tokens addObject:part];");
        });
    w.line("return tokens;");
    w.dedent();
    w.line("}");
    w.blankLine();
  }

  // ========================================================================
  // Serialize implementation
  // ========================================================================

  private void emitSerializeMethod(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "- (NSData *)data",
        () -> {
          w.line("NSMutableString *buf = [NSMutableString string];");
          w.line("[self appendPbtkFieldsTo:buf];");
          w.line("return [buf dataUsingEncoding:NSUTF8StringEncoding];");
        });
  }

  private void emitCountFieldsMethod(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "- (NSInteger)countPbtkFields",
        () -> {
          w.line("NSInteger count = 0;");
          for (ProtoField field : message.getFields()) {
            emitFieldCount(w, field);
          }
          w.line("return count;");
        });
  }

  private void emitFieldCount(CodeWriter w, ProtoField field) {
    String propName = nameResolver.fieldName(field.getName());
    String accessor = "self." + propName;

    if (field.isOneofMember()) {
      // For ObjC, just check if the value is non-nil/non-zero
      if (typeMapper.isObjectType(field)) {
        w.line("if (%s != nil) count++;", accessor);
      } else {
        w.line("count++;");
      }
      return;
    }

    if (field.isMap()) {
      w.line("count += (NSInteger)%s.count;", accessor);
    } else if (field.isRepeated()) {
      w.line("count += (NSInteger)%s.count;", accessor);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      w.line("if (%s != nil) count++;", accessor);
    } else if (typeMapper.isObjectType(field)) {
      if (field.isProto3Optional()) {
        w.line("if (self.has%s) count++;", capitalize(propName));
      } else {
        w.line("if (%s != nil) count++;", accessor);
      }
    } else if (field.isProto3Optional()) {
      w.line("if (self.has%s) count++;", capitalize(propName));
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_DOUBLE
        || field.getProtoType() == FieldDescriptorProto.Type.TYPE_FLOAT) {
      w.line("if (!isnan(%s) && !isinf(%s)) count++;", accessor, accessor);
    } else {
      w.line("count++;");
    }
  }

  private void emitAppendFieldsMethod(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "- (void)appendPbtkFieldsTo:(NSMutableString *)buf",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldSerialize(w, field);
          }
        });
  }

  private void emitFieldSerialize(CodeWriter w, ProtoField field) {
    String propName = nameResolver.fieldName(field.getName());
    String accessor = "self." + propName;
    int fieldNum = field.getFieldNumber();

    if (field.isOneofMember()) {
      if (typeMapper.isObjectType(field)) {
        w.block(
            "if (" + accessor + " != nil)",
            () -> {
              emitSingleFieldAppend(w, field, accessor, fieldNum);
            });
      } else {
        emitSingleFieldAppend(w, field, accessor, fieldNum);
      }
      return;
    }

    if (field.isMap()) {
      emitMapSerialize(w, field, accessor, fieldNum);
    } else if (field.isRepeated()) {
      emitRepeatedSerialize(w, field, accessor, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      emitMessageSerialize(w, field, accessor, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, accessor, fieldNum);
    } else {
      emitScalarSerialize(w, field, accessor, fieldNum);
    }
  }

  private void emitSingleFieldAppend(
      CodeWriter w, ProtoField field, String accessor, int fieldNum) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      emitMessageSerialize(w, field, accessor, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, accessor, fieldNum);
    } else {
      emitScalarSerialize(w, field, accessor, fieldNum);
    }
  }

  private void emitScalarSerialize(CodeWriter w, ProtoField field, String accessor, int fieldNum) {
    String propName = nameResolver.fieldName(field.getName());
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    Runnable appendCode =
        () -> {
          switch (type) {
            case TYPE_BOOL:
              w.line(
                  "[buf appendFormat:@\"!%d%s%%@\", %s ? @\"1\" : @\"0\"];",
                  fieldNum, typeChar, accessor);
              break;
            case TYPE_BYTES:
              w.line(
                  "[buf appendFormat:@\"!%d%s%%@\", pbtk_base64_encode(%s)];",
                  fieldNum, typeChar, accessor);
              break;
            case TYPE_STRING:
              w.block(
                  "if (" + accessor + " != nil)",
                  () -> {
                    w.line(
                        "[buf appendFormat:@\"!%d%s%%@\", pbtk_url_encode(%s)];",
                        fieldNum, typeChar, accessor);
                  });
              break;
            case TYPE_DOUBLE:
              w.block(
                  "if (!isnan(" + accessor + ") && !isinf(" + accessor + "))",
                  () ->
                      w.line(
                          "[buf appendFormat:@\"!%d%s%%.17g\", %s];",
                          fieldNum, typeChar, accessor));
              break;
            case TYPE_FLOAT:
              w.block(
                  "if (!isnan(" + accessor + ") && !isinf(" + accessor + "))",
                  () ->
                      w.line(
                          "[buf appendFormat:@\"!%d%s%%.9g\", (double)%s];",
                          fieldNum, typeChar, accessor));
              break;
            case TYPE_UINT64:
            case TYPE_FIXED64:
              w.line(
                  "[buf appendFormat:@\"!%d%s%%llu\", (unsigned long long)%s];",
                  fieldNum, typeChar, accessor);
              break;
            case TYPE_INT64:
            case TYPE_SINT64:
            case TYPE_SFIXED64:
              w.line(
                  "[buf appendFormat:@\"!%d%s%%lld\", (long long)%s];",
                  fieldNum, typeChar, accessor);
              break;
            case TYPE_UINT32:
            case TYPE_FIXED32:
              w.line(
                  "[buf appendFormat:@\"!%d%s%%u\", (unsigned int)%s];",
                  fieldNum, typeChar, accessor);
              break;
            default:
              w.line("[buf appendFormat:@\"!%d%s%%d\", (int)%s];", fieldNum, typeChar, accessor);
              break;
          }
        };

    if (field.isProto3Optional()) {
      w.block("if (self.has" + capitalize(propName) + ")", appendCode);
    } else {
      appendCode.run();
    }
  }

  private void emitEnumSerialize(CodeWriter w, ProtoField field, String accessor, int fieldNum) {
    String propName = nameResolver.fieldName(field.getName());
    if (field.isProto3Optional()) {
      w.block(
          "if (self.has" + capitalize(propName) + ")",
          () -> {
            w.line("[buf appendFormat:@\"!%de%%ld\", (long)%s];", fieldNum, accessor);
          });
    } else {
      w.line("[buf appendFormat:@\"!%de%%ld\", (long)%s];", fieldNum, accessor);
    }
  }

  private void emitMessageSerialize(CodeWriter w, ProtoField field, String accessor, int fieldNum) {
    w.block(
        "if (" + accessor + " != nil)",
        () -> {
          w.line(
              "[buf appendFormat:@\"!%dm%%ld\", (long)[%s countPbtkFields]];", fieldNum, accessor);
          w.line("[%s appendPbtkFieldsTo:buf];", accessor);
        });
  }

  private void emitRepeatedSerialize(
      CodeWriter w, ProtoField field, String accessor, int fieldNum) {
    w.block(
        "for (id __elem in " + accessor + ")",
        () -> {
          if (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
            String refType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
            w.block(
                "if (__elem != nil && __elem != (id)[NSNull null])",
                () -> {
                  w.line(
                      "[buf appendFormat:@\"!%dm%%ld\", (long)[(%s *)__elem countPbtkFields]];",
                      fieldNum, refType);
                  w.line("[(%s *)__elem appendPbtkFieldsTo:buf];", refType);
                });
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            w.line(
                "[buf appendFormat:@\"!%de%%ld\", (long)[(NSNumber *)__elem integerValue]];",
                fieldNum);
          } else {
            emitScalarElementAppend(w, field, "__elem", fieldNum);
          }
        });
  }

  private void emitScalarElementAppend(
      CodeWriter w, ProtoField field, String elemAccessor, int fieldNum) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    switch (type) {
      case TYPE_BOOL:
        w.line(
            "[buf appendFormat:@\"!%d%s%%@\", [(NSNumber *)%s boolValue] ? @\"1\" : @\"0\"];",
            fieldNum, typeChar, elemAccessor);
        break;
      case TYPE_STRING:
        w.block(
            "if (" + elemAccessor + " != nil && " + elemAccessor + " != (id)[NSNull null])",
            () -> {
              w.line(
                  "[buf appendFormat:@\"!%d%s%%@\", pbtk_url_encode((NSString *)%s)];",
                  fieldNum, typeChar, elemAccessor);
            });
        break;
      case TYPE_BYTES:
        w.line(
            "[buf appendFormat:@\"!%d%s%%@\", pbtk_base64_encode((NSData *)%s)];",
            fieldNum, typeChar, elemAccessor);
        break;
      case TYPE_DOUBLE:
        w.block(
            "if (!isnan([(NSNumber *)"
                + elemAccessor
                + " doubleValue]) && !isinf([(NSNumber *)"
                + elemAccessor
                + " doubleValue]))",
            () ->
                w.line(
                    "[buf appendFormat:@\"!%d%s%%.17g\", [(NSNumber *)%s doubleValue]];",
                    fieldNum, typeChar, elemAccessor));
        break;
      case TYPE_FLOAT:
        w.block(
            "if (!isnan([(NSNumber *)"
                + elemAccessor
                + " doubleValue]) && !isinf([(NSNumber *)"
                + elemAccessor
                + " doubleValue]))",
            () ->
                w.line(
                    "[buf appendFormat:@\"!%d%s%%.9g\", [(NSNumber *)%s doubleValue]];",
                    fieldNum, typeChar, elemAccessor));
        break;
      case TYPE_UINT32:
      case TYPE_FIXED32:
      case TYPE_UINT64:
      case TYPE_FIXED64:
        w.line(
            "[buf appendFormat:@\"!%d%s%%llu\", [(NSNumber *)%s unsignedLongLongValue]];",
            fieldNum, typeChar, elemAccessor);
        break;
      default:
        w.line(
            "[buf appendFormat:@\"!%d%s%%lld\", [(NSNumber *)%s longLongValue]];",
            fieldNum, typeChar, elemAccessor);
        break;
    }
  }

  private void emitMapSerialize(CodeWriter w, ProtoField field, String accessor, int fieldNum) {
    w.block(
        "for (id __key in " + accessor + ")",
        () -> {
          w.line("[buf appendFormat:@\"!%dm2\"];", fieldNum);
          // Key (field 1)
          String keyTypeChar = pbtkTypeChar(field.getMapKeyType());
          if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line(
                "[buf appendFormat:@\"!1%s%%@\", pbtk_url_encode((NSString *)__key)];",
                keyTypeChar);
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line(
                "[buf appendFormat:@\"!1%s%%@\", [(NSNumber *)__key boolValue] ? @\"1\" : @\"0\"];",
                keyTypeChar);
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_UINT32
              || field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_FIXED32
              || field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_UINT64
              || field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_FIXED64) {
            w.line(
                "[buf appendFormat:@\"!1%s%%llu\", [(NSNumber *)__key unsignedLongLongValue]];",
                keyTypeChar);
          } else {
            w.line(
                "[buf appendFormat:@\"!1%s%%lld\", [(NSNumber *)__key longLongValue]];",
                keyTypeChar);
          }
          // Value (field 2)
          w.line("id __val = %s[__key];", accessor);
          if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
            String refType =
                nameResolver.resolveTypeReference(field.getMapValueTypeReference(), null);
            w.block(
                "if (__val != nil && __val != (id)[NSNull null])",
                () -> {
                  w.line(
                      "[buf appendFormat:@\"!2m%%ld\", (long)[(%s *)__val countPbtkFields]];",
                      refType);
                  w.line("[(%s *)__val appendPbtkFieldsTo:buf];", refType);
                });
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
            w.line("[buf appendFormat:@\"!2e%%ld\", (long)[(NSNumber *)__val integerValue]];");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("[buf appendFormat:@\"!2s%%@\", pbtk_url_encode((NSString *)__val)];");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line(
                "[buf appendFormat:@\"!2b%%@\", [(NSNumber *)__val boolValue] ? @\"1\" : @\"0\"];");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_DOUBLE
              || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_FLOAT) {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.block(
                "if (!isnan([(NSNumber *)__val doubleValue]) && !isinf([(NSNumber *)__val doubleValue]))",
                () ->
                    w.line(
                        "[buf appendFormat:@\"!2%s%%.17g\", [(NSNumber *)__val doubleValue]];",
                        valTypeChar));
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_UINT32
              || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_FIXED32
              || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_UINT64
              || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_FIXED64) {
            w.line("[buf appendFormat:@\"!2i%%llu\", [(NSNumber *)__val unsignedLongLongValue]];");
          } else {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.line(
                "[buf appendFormat:@\"!2%s%%lld\", [(NSNumber *)__val longLongValue]];",
                valTypeChar);
          }
        });
  }

  // ========================================================================
  // Deserialize implementation
  // ========================================================================

  private void emitDeserializeMethod(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "+ (instancetype)parseFromData:(NSData *)data error:(NSError **)errorPtr",
        () -> {
          w.line("if (!data || data.length == 0) return [[%s alloc] init];", className);
          w.line(
              "NSString *input = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];");
          w.line("if (!input) {");
          w.indent();
          w.line("if (errorPtr) {");
          w.indent();
          w.line(
              "*errorPtr = [NSError errorWithDomain:@\"%s\" code:-1 userInfo:@{NSLocalizedDescriptionKey: @\"Invalid UTF-8 data\"}];",
              className);
          w.dedent();
          w.line("}");
          w.line("return nil;");
          w.dedent();
          w.line("}");
          w.line("NSArray<NSString *> *tokens = pbtk_tokenize(input);");
          w.line("NSInteger offset = 0;");
          w.line(
              "return [%s parsePbtkTokens:tokens fieldCount:(NSInteger)tokens.count offset:&offset];",
              className);
        });
  }

  private void emitParseTokensMethod(CodeWriter w, ProtoMessage message, String className) {
    w.blankLine();
    w.block(
        "+ (instancetype)parsePbtkTokens:(NSArray<NSString *> *)tokens fieldCount:(NSInteger)fieldCount offset:(NSInteger *)offset",
        () -> {
          w.line("%s *obj = [[%s alloc] init];", className, className);
          w.line("NSInteger consumed = 0;");
          w.block(
              "while (consumed < fieldCount && *offset < (NSInteger)tokens.count)",
              () -> {
                w.line("NSString *token = tokens[*offset];");
                w.line("// Parse field number and type char");
                w.line("NSInteger numEnd = 0;");
                w.block(
                    "while (numEnd < (NSInteger)token.length && [token characterAtIndex:numEnd] >= '0' && [token characterAtIndex:numEnd] <= '9')",
                    () -> {
                      w.line("numEnd++;");
                    });
                w.line(
                    "if (numEnd == 0 || numEnd >= (NSInteger)token.length) { (*offset)++; consumed++; continue; }");
                w.line("NSInteger fieldNum = [[token substringToIndex:numEnd] integerValue];");
                w.line("NSString *value = [token substringFromIndex:numEnd + 1];");
                w.blankLine();
                emitFieldSwitch(w, message, className);
              });
          w.line("return obj;");
        });
  }

  private void emitFieldSwitch(CodeWriter w, ProtoMessage message, String className) {
    w.block(
        "switch (fieldNum)",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldCase(w, field, className);
          }
          w.line("default: (*offset)++; consumed++; break;");
        });
  }

  private void emitFieldCase(CodeWriter w, ProtoField field, String className) {
    int fieldNum = field.getFieldNumber();
    String propName = nameResolver.fieldName(field.getName());

    w.block(
        "case " + fieldNum + ":",
        () -> {
          if (field.isMap()) {
            emitMapDeserialize(w, field, className);
          } else if (field.isRepeated()) {
            emitRepeatedDeserialize(w, field, className);
          } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
            emitMessageDeserialize(w, field, className);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            emitEnumDeserializeField(w, field);
          } else {
            emitScalarDeserialize(w, field);
          }
          w.line("(*offset)++;");
          w.line("consumed++;");
          w.line("break;");
        });
  }

  private void emitScalarDeserialize(CodeWriter w, ProtoField field) {
    String propName = nameResolver.fieldName(field.getName());
    FieldDescriptorProto.Type type = field.getProtoType();

    switch (type) {
      case TYPE_STRING:
        w.line("obj.%s = pbtk_url_decode(value);", propName);
        break;
      case TYPE_BYTES:
        w.line("obj.%s = pbtk_base64_decode(value);", propName);
        break;
      case TYPE_BOOL:
        w.line("obj.%s = [value isEqualToString:@\"1\"];", propName);
        break;
      case TYPE_DOUBLE:
        w.line("obj.%s = [value doubleValue];", propName);
        break;
      case TYPE_FLOAT:
        w.line("obj.%s = (float)[value doubleValue];", propName);
        break;
      case TYPE_INT64:
      case TYPE_SINT64:
      case TYPE_SFIXED64:
        w.line("obj.%s = [value longLongValue];", propName);
        break;
      case TYPE_UINT64:
      case TYPE_FIXED64:
        w.line("obj.%s = (uint64_t)strtoull([value UTF8String], NULL, 10);", propName);
        break;
      case TYPE_INT32:
      case TYPE_SINT32:
      case TYPE_SFIXED32:
        w.line("obj.%s = (int32_t)[value intValue];", propName);
        break;
      case TYPE_UINT32:
      case TYPE_FIXED32:
        w.line("obj.%s = (uint32_t)[value integerValue];", propName);
        break;
      default:
        w.line("obj.%s = (int32_t)[value intValue];", propName);
        break;
    }
    if (field.isProto3Optional()) {
      w.line("obj.has%s = YES;", capitalize(propName));
    }
  }

  private void emitEnumDeserializeField(CodeWriter w, ProtoField field) {
    String propName = nameResolver.fieldName(field.getName());
    w.line("obj.%s = [value integerValue];", propName);
    if (field.isProto3Optional()) {
      w.line("obj.has%s = YES;", capitalize(propName));
    }
  }

  private void emitMessageDeserialize(CodeWriter w, ProtoField field, String className) {
    String propName = nameResolver.fieldName(field.getName());
    String refType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
    w.line("NSInteger subCount = [value integerValue];");
    w.line("(*offset)++;");
    w.line(
        "obj.%s = [%s parsePbtkTokens:tokens fieldCount:subCount offset:offset];",
        propName, refType);
    w.line("(*offset)--;"); // compensate for outer offset++
  }

  private void emitRepeatedDeserialize(CodeWriter w, ProtoField field, String className) {
    String propName = nameResolver.fieldName(field.getName());

    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      String refType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
      w.line("NSInteger subCount = [value integerValue];");
      w.line("(*offset)++;");
      w.line(
          "%s *__elem = [%s parsePbtkTokens:tokens fieldCount:subCount offset:offset];",
          refType, refType);
      w.line("(*offset)--;");
      w.line("if (!obj.%s) obj.%s = [NSMutableArray array];", propName, propName);
      w.line("if (__elem) [obj.%s addObject:__elem];", propName);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      w.line("if (!obj.%s) obj.%s = [NSMutableArray array];", propName, propName);
      w.line("[obj.%s addObject:@([value integerValue])];", propName);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_STRING) {
      w.line("if (!obj.%s) obj.%s = [NSMutableArray array];", propName, propName);
      w.line("[obj.%s addObject:pbtk_url_decode(value)];", propName);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_BYTES) {
      w.line("if (!obj.%s) obj.%s = [NSMutableArray array];", propName, propName);
      w.line("[obj.%s addObject:pbtk_base64_decode(value)];", propName);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_BOOL) {
      w.line("if (!obj.%s) obj.%s = [NSMutableArray array];", propName, propName);
      w.line("[obj.%s addObject:@([value isEqualToString:@\"1\"])];", propName);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_DOUBLE
        || field.getProtoType() == FieldDescriptorProto.Type.TYPE_FLOAT) {
      w.line("if (!obj.%s) obj.%s = [NSMutableArray array];", propName, propName);
      w.line("[obj.%s addObject:@([value doubleValue])];", propName);
    } else {
      w.line("if (!obj.%s) obj.%s = [NSMutableArray array];", propName, propName);
      w.line("[obj.%s addObject:@([value longLongValue])];", propName);
    }
  }

  private void emitMapDeserialize(CodeWriter w, ProtoField field, String className) {
    String propName = nameResolver.fieldName(field.getName());
    w.line("// Map entry: sub-message with key(1) and value(2)");
    w.line("NSInteger subCount = [value integerValue];");
    w.line("if (!obj.%s) obj.%s = [NSMutableDictionary dictionary];", propName, propName);
    w.line("// Parse key and value sub-tokens");
    w.line("id __mapKey = nil;");
    w.line("id __mapVal = nil;");
    w.line("NSInteger __mapEnd = *offset + 1 + subCount;");
    w.line("(*offset)++;");
    w.block(
        "while (*offset < __mapEnd && *offset < (NSInteger)tokens.count)",
        () -> {
          w.line("NSString *subToken = tokens[*offset];");
          w.line("NSInteger sNumEnd = 0;");
          w.block(
              "while (sNumEnd < (NSInteger)subToken.length && [subToken characterAtIndex:sNumEnd] >= '0' && [subToken characterAtIndex:sNumEnd] <= '9')",
              () -> {
                w.line("sNumEnd++;");
              });
          w.line(
              "if (sNumEnd == 0 || sNumEnd >= (NSInteger)subToken.length) { (*offset)++; continue; }");
          w.line("NSInteger subFieldNum = [[subToken substringToIndex:sNumEnd] integerValue];");
          w.line("NSString *subValue = [subToken substringFromIndex:sNumEnd + 1];");
          w.block(
              "if (subFieldNum == 1)",
              () -> {
                emitMapKeyRead(w, field);
              });
          w.block(
              "else if (subFieldNum == 2)",
              () -> {
                emitMapValueRead(w, field);
              });
          w.line("(*offset)++;");
        });
    w.line("if (__mapKey != nil && __mapVal != nil) obj.%s[__mapKey] = __mapVal;", propName);
    w.line("(*offset)--;"); // compensate for outer offset++
  }

  private void emitMapKeyRead(CodeWriter w, ProtoField field) {
    if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
      w.line("__mapKey = pbtk_url_decode(subValue);");
    } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
      w.line("__mapKey = @([subValue isEqualToString:@\"1\"]);");
    } else {
      w.line("__mapKey = @([subValue longLongValue]);");
    }
  }

  private void emitMapValueRead(CodeWriter w, ProtoField field) {
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
      String refType = nameResolver.resolveTypeReference(field.getMapValueTypeReference(), null);
      w.line("NSInteger mvCount = [subValue integerValue];");
      w.line("(*offset)++;");
      w.line("__mapVal = [%s parsePbtkTokens:tokens fieldCount:mvCount offset:offset];", refType);
      w.line("(*offset)--;");
    } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
      w.line("__mapVal = @([subValue integerValue]);");
    } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
      w.line("__mapVal = pbtk_url_decode(subValue);");
    } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
      w.line("__mapVal = pbtk_base64_decode(subValue);");
    } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
      w.line("__mapVal = @([subValue isEqualToString:@\"1\"]);");
    } else {
      w.line("__mapVal = @([subValue longLongValue]);");
    }
  }

  // ========================================================================
  // Shared helpers
  // ========================================================================

  private void emitEnumDef(CodeWriter w, ProtoEnum protoEnum, ProtoFile file, String parentPrefix) {
    String prefix = nameResolver.classPrefix(file);
    String enumTypeName = prefix + parentPrefix + protoEnum.getName();

    w.line("typedef NS_ENUM(NSInteger, %s) {", enumTypeName);
    w.indent();
    for (int i = 0; i < protoEnum.getValues().size(); i++) {
      ProtoEnum.EnumValue val = protoEnum.getValues().get(i);
      String constName = enumTypeName + val.name();
      String suffix = i < protoEnum.getValues().size() - 1 ? "," : "";
      w.line("%s = %d%s", constName, val.number(), suffix);
    }
    w.dedent();
    w.line("};");
    w.blankLine();
  }

  private void emitPropertyDecl(CodeWriter w, ProtoField field) {
    String propName = nameResolver.fieldName(field.getName());
    String attrs = typeMapper.propertyAttributes(field);
    boolean isObj = typeMapper.isObjectType(field);

    if (field.isMap()) {
      String keyType = typeMapper.mapKeyObjCType(field.getMapKeyType());
      String valType = typeMapper.mapValueObjCType(field);
      w.line(
          "@property (%s, nullable) NSMutableDictionary<%s, %s> *%s;",
          attrs, keyType, valType, propName);
    } else if (field.isRepeated()) {
      String elemType = typeMapper.elementType(field);
      w.line("@property (%s, nullable) NSMutableArray<%s> *%s;", attrs, elemType, propName);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      String refType = nameResolver.resolveTypeReference(field.getTypeReference(), null);
      w.line("@property (%s, nullable) %s *%s;", attrs, refType, propName);
    } else if (isObj) {
      w.line(
          "@property (%s, nullable) %s%s;",
          attrs, typeMapper.scalarType(field.getProtoType()), propName);
    } else {
      String type = typeMapper.scalarType(field.getProtoType());
      if (type.endsWith("*")) {
        w.line("@property (%s) %s%s;", attrs, type, propName);
      } else {
        w.line("@property (%s) %s %s;", attrs, type, propName);
      }
    }
  }

  private void emitForwardDeclarations(CodeWriter w, ProtoMessage message, ProtoFile file) {
    Set<String> forwardDecls = new LinkedHashSet<>();
    collectForwardDeclarations(message, file, forwardDecls);
    for (String decl : forwardDecls) {
      w.line(decl);
    }
    if (!forwardDecls.isEmpty()) {
      w.blankLine();
    }
  }

  private void collectForwardDeclarations(
      ProtoMessage message, ProtoFile file, Set<String> forwardDecls) {
    for (ProtoField field : message.getFields()) {
      if (field.getTypeReference() == null) continue;
      if (field.isWellKnownType()) continue;
      if (field.getKind() != ProtoField.FieldKind.MESSAGE
          && field.getKind() != ProtoField.FieldKind.WELL_KNOWN_TYPE) continue;

      // Check if nested
      boolean isNested = false;
      for (ProtoMessage nested : message.getNestedMessages()) {
        if (field.getTypeReference().equals(message.getFullName() + "." + nested.getName())) {
          isNested = true;
          break;
        }
      }
      if (!isNested) {
        String objcType = nameResolver.resolveTypeReference(field.getTypeReference(), file);
        forwardDecls.add("@class " + objcType + ";");
      }

      if (field.isMap()
          && field.getMapValueTypeReference() != null
          && field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
        String objcType = nameResolver.resolveTypeReference(field.getMapValueTypeReference(), file);
        forwardDecls.add("@class " + objcType + ";");
      }
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      collectForwardDeclarations(nested, file, forwardDecls);
    }
  }

  private void emitCrossFileImports(CodeWriter w, ProtoMessage message, ProtoFile file) {
    Set<String> imports = new LinkedHashSet<>();
    collectCrossFileImports(message, file, imports);
    for (String imp : imports) {
      w.line(imp);
    }
    if (!imports.isEmpty()) {
      w.blankLine();
    }
  }

  private void collectCrossFileImports(ProtoMessage message, ProtoFile file, Set<String> imports) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      if (field.getTypeReference() == null) continue;
      if (field.isWellKnownType()) continue;

      // Check if nested
      boolean isNested = false;
      for (ProtoMessage nested : message.getNestedMessages()) {
        if (field.getTypeReference().equals(message.getFullName() + "." + nested.getName())) {
          isNested = true;
          break;
        }
      }
      if (isNested) continue;

      if (field.getTypeReference().startsWith(currentPrefix)) {
        String simpleName = ProtoTypeUtil.simpleTypeName(field.getTypeReference());
        if (!simpleName.equals(message.getName())) {
          String className = nameResolver.resolveTypeReference(field.getTypeReference(), file);
          imports.add("#import \"" + className + ".h\"");
        }
      }
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      collectCrossFileImports(nested, file, imports);
    }
  }

  private void emitNestedMessageHeader(
      CodeWriter w, ProtoMessage nested, ProtoFile file, String className, String parentPrefix) {
    // Nested enums
    for (ProtoEnum protoEnum : nested.getEnums()) {
      emitEnumDef(w, protoEnum, file, parentPrefix + nested.getName() + "_");
    }

    w.line("@interface %s : NSObject", className);
    w.blankLine();

    for (ProtoField field : nested.getFields()) {
      if (field.isOneofMember()) continue;
      emitPropertyDecl(w, field);
    }
    for (ProtoMessage.OneofGroup group : nested.getOneofGroups()) {
      for (ProtoField member : group.members()) {
        emitPropertyDecl(w, member);
      }
    }
    for (ProtoField field : nested.getFields()) {
      if (field.isProto3Optional() && !field.isOneofMember()) {
        String propName = nameResolver.fieldName(field.getName());
        w.line("@property (nonatomic, assign) BOOL has%s;", capitalize(propName));
      }
    }

    w.blankLine();
    w.line("- (NSData *)data;");
    w.line("+ (instancetype)parseFromData:(NSData *)data error:(NSError **)errorPtr;");

    w.blankLine();
    w.line("@end");
    w.blankLine();

    for (ProtoMessage deepNested : nested.getNestedMessages()) {
      String deepClassName =
          nameResolver.qualifiedClassName(
              file, parentPrefix + nested.getName() + "_" + deepNested.getName());
      emitNestedMessageHeader(
          w, deepNested, file, deepClassName, parentPrefix + nested.getName() + "_");
    }
  }

  private void emitNestedMessageSource(
      CodeWriter w, ProtoMessage nested, ProtoFile file, String className, String parentPrefix) {
    // Recursively emit deeper nested messages first
    for (ProtoMessage deepNested : nested.getNestedMessages()) {
      String deepClassName =
          nameResolver.qualifiedClassName(
              file, parentPrefix + nested.getName() + "_" + deepNested.getName());
      emitNestedMessageSource(
          w, deepNested, file, deepClassName, parentPrefix + nested.getName() + "_");
    }

    w.line("@implementation %s", className);

    emitSerializeMethod(w, nested, className);
    emitAppendFieldsMethod(w, nested, className);
    emitCountFieldsMethod(w, nested, className);
    emitDeserializeMethod(w, nested, className);
    emitParseTokensMethod(w, nested, className);

    w.blankLine();
    w.line("@end");
    w.blankLine();
  }

  /** Map proto type to pbtk type character. */
  private static String pbtkTypeChar(FieldDescriptorProto.Type type) {
    return switch (type) {
      case TYPE_STRING -> "s";
      case TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_UINT64,
          TYPE_FIXED64 ->
          "i";
      case TYPE_DOUBLE -> "d";
      case TYPE_FLOAT -> "f";
      case TYPE_BOOL -> "b";
      case TYPE_BYTES -> "z";
      case TYPE_ENUM -> "e";
      case TYPE_MESSAGE -> "m";
      default -> "s";
    };
  }

  private static String capitalize(String s) {
    if (s == null || s.isEmpty()) return s;
    return Character.toUpperCase(s.charAt(0)) + s.substring(1);
  }
}
