/*
 * Copyright 2024 protobuf-text-codecs contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.protocgen.textcodecs.pbtkurl.codegen.rust;

import com.google.protobuf.DescriptorProtos.FieldDescriptorProto;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import dev.protocgen.textcodecs.jsonarray.CodeWriter;
import dev.protocgen.textcodecs.jsonarray.codegen.LanguageGenerator;
import dev.protocgen.textcodecs.jsonarray.codegen.rust.RustNameResolver;
import dev.protocgen.textcodecs.jsonarray.codegen.rust.RustTypeMapper;
import dev.protocgen.textcodecs.jsonarray.model.ProtoEnum;
import dev.protocgen.textcodecs.jsonarray.model.ProtoField;
import dev.protocgen.textcodecs.jsonarray.model.ProtoFile;
import dev.protocgen.textcodecs.jsonarray.model.ProtoMessage;
import dev.protocgen.textcodecs.jsonarray.model.TypeRegistry;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Rust language code generator for pbtk URL encoding. Produces Rust source files with
 * to_pbtk_url()/from_pbtk_url() serialization methods using the {@code
 * !<fieldNumber><typeChar><value>} format.
 */
public class PbtkRustGenerator implements LanguageGenerator {

  private static final String GENERATED_MARKER =
      "// @generated by protoc-gen-pbtkurl -- do not edit.";

  private final RustNameResolver nameResolver = new RustNameResolver();
  private final RustTypeMapper typeMapper = new RustTypeMapper();

  private final Set<String> emittedModFiles = new HashSet<>();
  private final java.util.Map<String, Set<String>> modulesByDir = new java.util.LinkedHashMap<>();

  @Override
  public List<CodeGeneratorResponse.File> generate(ProtoFile file, TypeRegistry registry) {
    List<CodeGeneratorResponse.File> result = new ArrayList<>();
    List<String> moduleNames = new ArrayList<>();

    for (ProtoMessage message : file.getMessages()) {
      nameResolver.validateFieldNames(message.getFields());
      String sourceCode = emitMessage(message, file);
      String outputPath = nameResolver.outputFilePath(file, message.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());

      moduleNames.add(toSnakeCase(message.getName()));
    }

    for (ProtoEnum protoEnum : file.getEnums()) {
      String sourceCode = emitTopLevelEnum(protoEnum, file);
      String outputPath = nameResolver.outputFilePath(file, protoEnum.getName());

      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(outputPath)
              .setContent(sourceCode)
              .build());

      moduleNames.add(toSnakeCase(protoEnum.getName()));
    }

    // mod.rs generation
    String pkg = nameResolver.resolvePackage(file);
    String dir = pkg.isEmpty() ? "" : pkg.replace('.', '/');
    modulesByDir.computeIfAbsent(dir, k -> new LinkedHashSet<>()).addAll(moduleNames);

    String modPath = dir.isEmpty() ? "mod.rs" : dir + "/mod.rs";
    if (!moduleNames.isEmpty() && emittedModFiles.add(modPath)) {
      StringBuilder modContent = new StringBuilder();
      for (String modName : modulesByDir.get(dir)) {
        modContent.append("pub mod ").append(modName).append(";\n");
      }
      modContent.append("// @@protoc_insertion_point(module_declarations)\n");
      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(modPath)
              .setContent(modContent.toString())
              .build());
    } else if (!moduleNames.isEmpty() && !emittedModFiles.add(modPath)) {
      StringBuilder newMods = new StringBuilder();
      for (String modName : moduleNames) {
        newMods.append("pub mod ").append(modName).append(";\n");
      }
      newMods.append("// @@protoc_insertion_point(module_declarations)\n");
      result.add(
          CodeGeneratorResponse.File.newBuilder()
              .setName(modPath)
              .setInsertionPoint("module_declarations")
              .setContent(newMods.toString())
              .build());
    }

    return result;
  }

  // ---------------------------------------------------------------------------
  // Code emission
  // ---------------------------------------------------------------------------

  private String emitMessage(ProtoMessage message, ProtoFile file) {
    CodeWriter w = new CodeWriter();

    w.line(GENERATED_MARKER);
    w.blankLine();

    // Imports
    emitImports(w, message);
    emitTypeImports(w, message, file);

    String structName = nameResolver.messageClassName(message.getName());

    // Nested enums
    for (ProtoEnum protoEnum : message.getEnums()) {
      emitEnum(w, protoEnum);
    }

    // Nested messages
    for (ProtoMessage nested : message.getNestedMessages()) {
      w.blankLine();
      emitNestedMessage(w, nested, file);
    }

    // Struct definition
    w.line("#[derive(Debug, Clone, Default)]");
    w.block(
        "pub struct " + structName,
        () -> {
          emitFields(w, message);
          emitOneofCaseFields(w, message);
        });

    // Impl block
    w.blankLine();
    w.block(
        "impl " + structName,
        () -> {
          w.block("pub fn new() -> Self", () -> w.line("Self::default()"));

          // Getters and setters
          emitGettersSetters(w, message);

          // pbtk URL serialize helpers
          emitAppendPbtkFields(w, message);
          emitCountPbtkFields(w, message);

          // Public serialize method
          w.blankLine();
          w.block(
              "pub fn to_pbtk_url(&self) -> String",
              () -> {
                w.line("let mut s = String::new();");
                w.line("self.append_pbtk_fields(&mut s);");
                w.line("s");
              });

          // Public deserialize method
          emitFromPbtkUrl(w, message, structName);
        });

    // Display impl
    emitDisplay(w, message, structName);

    return w.toString();
  }

  private String emitTopLevelEnum(ProtoEnum protoEnum, ProtoFile file) {
    CodeWriter w = new CodeWriter();
    w.line(GENERATED_MARKER);
    w.blankLine();
    emitEnum(w, protoEnum);
    return w.toString();
  }

  // ---------------------------------------------------------------------------
  // Imports
  // ---------------------------------------------------------------------------

  private void emitImports(CodeWriter w, ProtoMessage message) {
    if (hasFieldOfType(message, FieldDescriptorProto.Type.TYPE_BYTES)) {
      w.line("use base64::{Engine as _, engine::general_purpose};");
    }
    if (hasMapFields(message)) {
      w.line("use std::collections::HashMap;");
    }
    w.blankLine();
  }

  private void emitTypeImports(CodeWriter w, ProtoMessage message, ProtoFile file) {
    Set<String> imports = new LinkedHashSet<>();
    collectReferencedTypes(message, file, imports);
    for (String imp : imports) {
      w.line(imp);
    }
    if (!imports.isEmpty()) {
      w.blankLine();
    }
  }

  private void collectReferencedTypes(ProtoMessage message, ProtoFile file, Set<String> imports) {
    String currentPrefix =
        file.getProtoPackage().isEmpty() ? "." : "." + file.getProtoPackage() + ".";

    for (ProtoField field : message.getFields()) {
      addTypeImportIfNeeded(
          field.getTypeReference(), field.isWellKnownType(), message, currentPrefix, imports);
      if (field.isMap() && field.getMapValueTypeReference() != null) {
        addTypeImportIfNeeded(
            field.getMapValueTypeReference(), false, message, currentPrefix, imports);
      }
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      collectReferencedTypes(nested, file, imports);
    }
  }

  private void addTypeImportIfNeeded(
      String typeRef,
      boolean isWellKnown,
      ProtoMessage message,
      String currentPrefix,
      Set<String> imports) {
    if (typeRef == null || isWellKnown) return;
    for (ProtoMessage nested : message.getNestedMessages()) {
      if (typeRef.equals(message.getFullName() + "." + nested.getName())) return;
    }
    for (ProtoEnum nestedEnum : message.getEnums()) {
      if (typeRef.equals(message.getFullName() + "." + nestedEnum.getName())) return;
    }
    if (typeRef.startsWith(currentPrefix)) {
      String simpleName = typeRef.substring(typeRef.lastIndexOf('.') + 1);
      String moduleName = toSnakeCase(simpleName);
      imports.add("use super::" + moduleName + "::" + simpleName + ";");
    }
  }

  // ---------------------------------------------------------------------------
  // Struct fields
  // ---------------------------------------------------------------------------

  private void emitFields(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String rustType = typeMapper.languageType(field);
      String rustName = nameResolver.fieldName(field.getName());
      w.line("pub %s: %s,", rustName, rustType);
    }
  }

  private void emitOneofCaseFields(CodeWriter w, ProtoMessage message) {
    for (ProtoMessage.OneofGroup group : message.getOneofGroups()) {
      String caseName = nameResolver.fieldName(group.name()) + "_case";
      w.line("pub %s: i32, // 0 = not set", caseName);
    }
  }

  private void emitGettersSetters(CodeWriter w, ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      String rustType = typeMapper.languageType(field);
      String rustName = nameResolver.fieldName(field.getName());
      String getterName = nameResolver.getterName(field.getName());
      String setterName = nameResolver.setterName(field.getName());

      w.blankLine();
      if (isRustCopyType(field)) {
        w.block(
            "pub fn " + getterName + "(&self) -> " + rustType, () -> w.line("self.%s", rustName));
      } else {
        w.block(
            "pub fn " + getterName + "(&self) -> &" + rustType, () -> w.line("&self.%s", rustName));
      }

      w.blankLine();
      w.block(
          "pub fn " + setterName + "(&mut self, value: " + rustType + ")",
          () -> {
            w.line("self.%s = value;", rustName);
            if (field.isOneofMember()) {
              String caseField = nameResolver.fieldName(field.getOneofName()) + "_case";
              w.line("self.%s = %d;", caseField, field.getFieldNumber());
            }
          });

      if (field.isProto3Optional() || field.getKind() == ProtoField.FieldKind.MESSAGE) {
        w.blankLine();
        String hasName = "has_" + nameResolver.fieldName(field.getName());
        w.block(
            "pub fn " + hasName + "(&self) -> bool", () -> w.line("self.%s.is_some()", rustName));
      }
    }
  }

  // ---------------------------------------------------------------------------
  // pbtk URL serialization
  // ---------------------------------------------------------------------------

  private void emitAppendPbtkFields(CodeWriter w, ProtoMessage message) {
    w.blankLine();
    w.block(
        "fn append_pbtk_fields(&self, s: &mut String)",
        () -> {
          for (ProtoField field : message.getFields()) {
            emitFieldSerialize(w, field);
          }
        });
  }

  private void emitCountPbtkFields(CodeWriter w, ProtoMessage message) {
    w.blankLine();
    w.block(
        "fn count_pbtk_fields(&self) -> usize",
        () -> {
          w.line("let mut count: usize = 0;");
          for (ProtoField field : message.getFields()) {
            emitFieldCount(w, field);
          }
          w.line("count");
        });
  }

  private void emitFieldSerialize(CodeWriter w, ProtoField field) {
    String rustField = "self." + nameResolver.fieldName(field.getName());
    int fieldNum = field.getFieldNumber();

    if (field.isOneofMember()) {
      String caseField = "self." + nameResolver.fieldName(field.getOneofName()) + "_case";
      w.block(
          "if " + caseField + " == " + fieldNum,
          () -> emitSingleFieldSerialize(w, field, rustField, fieldNum));
      return;
    }

    if (field.isMap()) {
      emitMapSerialize(w, field, rustField, fieldNum);
    } else if (field.isRepeated()) {
      emitRepeatedSerialize(w, field, rustField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      emitMessageSerialize(w, field, rustField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, rustField, fieldNum);
    } else {
      emitScalarSerialize(w, field, rustField, fieldNum);
    }
  }

  private void emitSingleFieldSerialize(
      CodeWriter w, ProtoField field, String rustField, int fieldNum) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      emitMessageSerialize(w, field, rustField, fieldNum);
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      emitEnumSerialize(w, field, rustField, fieldNum);
    } else {
      emitScalarSerialize(w, field, rustField, fieldNum);
    }
  }

  private void emitScalarSerialize(CodeWriter w, ProtoField field, String rustField, int fieldNum) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);

    if (field.isProto3Optional()) {
      w.block(
          "if let Some(ref v) = " + rustField,
          () -> emitScalarAppend(w, field, "v", fieldNum, true));
      return;
    }

    emitScalarAppend(w, field, rustField, fieldNum, false);
  }

  private void emitScalarAppend(
      CodeWriter w, ProtoField field, String rustField, int fieldNum, boolean isRef) {
    FieldDescriptorProto.Type type = field.getProtoType();
    String typeChar = pbtkTypeChar(type);
    String prefix = String.format("!%d%s", fieldNum, typeChar);

    switch (type) {
      case TYPE_BOOL:
        w.line(
            "s.push_str(&format!(\"%%s%%s\", \"%s\", if %s%s { \"1\" } else { \"0\" }));",
            prefix, isRef ? "*" : "", rustField);
        break;
      case TYPE_BYTES:
        if (isRef) {
          w.line(
              "s.push_str(\"%s\"); s.push_str(&general_purpose::STANDARD.encode(%s));",
              prefix, rustField);
        } else {
          w.line(
              "s.push_str(\"%s\"); s.push_str(&general_purpose::STANDARD.encode(&%s));",
              prefix, rustField);
        }
        break;
      case TYPE_STRING:
        if (isRef) {
          w.line("s.push_str(\"%s\"); s.push_str(&urlencoding::encode(%s));", prefix, rustField);
        } else {
          w.line("s.push_str(\"%s\"); s.push_str(&urlencoding::encode(&%s));", prefix, rustField);
        }
        break;
      case TYPE_FLOAT:
        w.line(
            "if !%s%s.is_nan() && !%s%s.is_infinite() { s.push_str(\"%s\"); s.push_str(&%s%s.to_string()); }",
            isRef ? "*" : "",
            rustField,
            isRef ? "*" : "",
            rustField,
            prefix,
            isRef ? "*" : "",
            rustField);
        break;
      case TYPE_DOUBLE:
        w.line(
            "if !%s%s.is_nan() && !%s%s.is_infinite() { s.push_str(\"%s\"); s.push_str(&%s%s.to_string()); }",
            isRef ? "*" : "",
            rustField,
            isRef ? "*" : "",
            rustField,
            prefix,
            isRef ? "*" : "",
            rustField);
        break;
      default:
        w.line(
            "s.push_str(\"%s\"); s.push_str(&%s%s.to_string());",
            prefix, isRef ? "*" : "", rustField);
        break;
    }
  }

  private void emitEnumSerialize(CodeWriter w, ProtoField field, String rustField, int fieldNum) {
    String prefix = String.format("!%de", fieldNum);
    if (field.isProto3Optional()) {
      w.block(
          "if let Some(ref v) = " + rustField,
          () -> w.line("s.push_str(\"%s\"); s.push_str(&(*v as i32).to_string());", prefix));
    } else {
      w.line("s.push_str(\"%s\"); s.push_str(&(%s as i32).to_string());", prefix, rustField);
    }
  }

  private void emitMessageSerialize(
      CodeWriter w, ProtoField field, String rustField, int fieldNum) {
    w.block(
        "if let Some(ref v) = " + rustField,
        () -> {
          w.line("s.push_str(&format!(\"!%dm{}\", v.count_pbtk_fields()));", fieldNum);
          w.line("v.append_pbtk_fields(s);");
        });
  }

  private void emitRepeatedSerialize(
      CodeWriter w, ProtoField field, String rustField, int fieldNum) {
    String elemVar = "__" + nameResolver.fieldName(field.getName()) + "_item";
    w.block(
        "for " + elemVar + " in &" + rustField,
        () -> {
          if (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
            w.line("s.push_str(&format!(\"!%dm{}\", %s.count_pbtk_fields()));", fieldNum, elemVar);
            w.line("%s.append_pbtk_fields(s);", elemVar);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            w.line(
                "s.push_str(\"!%de\"); s.push_str(&(*%s as i32).to_string());", fieldNum, elemVar);
          } else {
            emitScalarAppend(w, field, elemVar, fieldNum, true);
          }
        });
  }

  private void emitMapSerialize(CodeWriter w, ProtoField field, String rustField, int fieldNum) {
    w.block(
        "for (k, v) in &" + rustField,
        () -> {
          // Each map entry is a synthetic message with 2 sub-fields: key=1, value=2
          w.line("s.push_str(\"!%dm2\");", fieldNum);

          // Key (field 1)
          String keyTypeChar = pbtkTypeChar(field.getMapKeyType());
          if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("s.push_str(\"!1%s\"); s.push_str(&urlencoding::encode(k));", keyTypeChar);
          } else if (field.getMapKeyType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line(
                "s.push_str(\"!1%s\"); s.push_str(if *k { \"1\" } else { \"0\" });", keyTypeChar);
          } else {
            w.line("s.push_str(\"!1%s\"); s.push_str(&k.to_string());", keyTypeChar);
          }

          // Value (field 2)
          if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
            w.line("s.push_str(&format!(\"!2m{}\", v.count_pbtk_fields()));");
            w.line("v.append_pbtk_fields(s);");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
            w.line("s.push_str(\"!2e\"); s.push_str(&(*v as i32).to_string());");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_STRING) {
            w.line("s.push_str(\"!2s\"); s.push_str(&urlencoding::encode(v));");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BYTES) {
            w.line("s.push_str(\"!2z\"); s.push_str(&general_purpose::STANDARD.encode(v));");
          } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_BOOL) {
            w.line("s.push_str(\"!2b\"); s.push_str(if *v { \"1\" } else { \"0\" });");
          } else {
            String valTypeChar = pbtkTypeChar(field.getMapValueType());
            w.line("s.push_str(\"!2%s\"); s.push_str(&v.to_string());", valTypeChar);
          }
        });
  }

  private void emitFieldCount(CodeWriter w, ProtoField field) {
    String rustField = "self." + nameResolver.fieldName(field.getName());

    if (field.isOneofMember()) {
      String caseField = "self." + nameResolver.fieldName(field.getOneofName()) + "_case";
      w.line("if %s == %d { count += 1; }", caseField, field.getFieldNumber());
      return;
    }

    if (field.isMap()) {
      w.line("count += %s.len();", rustField);
    } else if (field.isRepeated()) {
      w.line("count += %s.len();", rustField);
    } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      w.line("if %s.is_some() { count += 1; }", rustField);
    } else if (field.isProto3Optional()) {
      w.line("if %s.is_some() { count += 1; }", rustField);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_FLOAT) {
      w.line("if !%s.is_nan() && !%s.is_infinite() { count += 1; }", rustField, rustField);
    } else if (field.getProtoType() == FieldDescriptorProto.Type.TYPE_DOUBLE) {
      w.line("if !%s.is_nan() && !%s.is_infinite() { count += 1; }", rustField, rustField);
    } else {
      w.line("count += 1;");
    }
  }

  // ---------------------------------------------------------------------------
  // pbtk URL deserialization
  // ---------------------------------------------------------------------------

  private void emitFromPbtkUrl(CodeWriter w, ProtoMessage message, String structName) {
    // Internal parser
    w.blankLine();
    w.block(
        "fn parse_pbtk_tokens(tokens: &[&str], field_count: usize, offset: &mut usize) -> Self",
        () -> {
          w.line("let mut obj = %s::default();", structName);
          w.line("let mut consumed: usize = 0;");
          w.block(
              "while consumed < field_count && *offset < tokens.len()",
              () -> {
                w.line("let token = tokens[*offset];");
                w.line(
                    "let num_end = token.find(|c: char| !c.is_ascii_digit()).unwrap_or(token.len());");
                w.line(
                    "if num_end == 0 || num_end >= token.len() { *offset += 1; consumed += 1; continue; }");
                w.line("let field_num: i32 = token[..num_end].parse().unwrap_or(0);");
                w.line("let type_char = token.as_bytes()[num_end] as char;");
                w.line("let value = &token[num_end + 1..];");

                w.block(
                    "match field_num",
                    () -> {
                      for (ProtoField field : message.getFields()) {
                        emitFieldCase(w, field);
                      }
                      w.line("_ => { *offset += 1; consumed += 1; }");
                    });
              });
          w.line("obj");
        });

    // Public from_pbtk_url
    w.blankLine();
    w.block(
        "pub fn from_pbtk_url(input: &str) -> Self",
        () -> {
          w.line("if input.is_empty() { return Self::default(); }");
          w.line("let trimmed = if input.starts_with('!') { &input[1..] } else { input };");
          w.line("let tokens: Vec<&str> = trimmed.split('!').collect();");
          w.line("let mut offset: usize = 0;");
          w.line("Self::parse_pbtk_tokens(&tokens, tokens.len(), &mut offset)");
        });
  }

  private void emitFieldCase(CodeWriter w, ProtoField field) {
    int fieldNum = field.getFieldNumber();
    String rustName = nameResolver.fieldName(field.getName());

    w.block(
        fieldNum + " =>",
        () -> {
          if (field.isMap()) {
            emitMapDeserialize(w, field, rustName);
          } else if (field.isRepeated()) {
            emitRepeatedDeserialize(w, field, rustName);
          } else if (field.getKind() == ProtoField.FieldKind.MESSAGE
              || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
            emitMessageDeserialize(w, field, rustName);
          } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
            emitEnumDeserialize(w, field, rustName);
          } else {
            emitScalarDeserialize(w, field, rustName);
          }
          w.line("*offset += 1;");
          w.line("consumed += 1;");
        });
  }

  private void emitScalarDeserialize(CodeWriter w, ProtoField field, String rustName) {
    String readExpr = scalarReadExpr(field.getProtoType(), "value");
    if (field.isProto3Optional()) {
      w.line("obj.%s = Some(%s);", rustName, readExpr);
    } else {
      w.line("obj.%s = %s;", rustName, readExpr);
    }
    if (field.isOneofMember()) {
      w.line(
          "obj.%s_case = %d;",
          nameResolver.fieldName(field.getOneofName()), field.getFieldNumber());
    }
  }

  private void emitEnumDeserialize(CodeWriter w, ProtoField field, String rustName) {
    String enumType = simpleTypeName(field.getTypeReference());
    if (field.isProto3Optional()) {
      w.line("obj.%s = Some(%s::from(value.parse::<i32>().unwrap_or(0)));", rustName, enumType);
    } else {
      w.line("obj.%s = %s::from(value.parse::<i32>().unwrap_or(0));", rustName, enumType);
    }
    if (field.isOneofMember()) {
      w.line(
          "obj.%s_case = %d;",
          nameResolver.fieldName(field.getOneofName()), field.getFieldNumber());
    }
  }

  private void emitMessageDeserialize(CodeWriter w, ProtoField field, String rustName) {
    String msgType = simpleTypeName(field.getTypeReference());
    w.line("let sub_count: usize = value.parse().unwrap_or(0);");
    w.line("*offset += 1;");
    w.line("obj.%s = Some(%s::parse_pbtk_tokens(tokens, sub_count, offset));", rustName, msgType);
    w.line("*offset -= 1;"); // compensate for outer offset increment
    if (field.isOneofMember()) {
      w.line(
          "obj.%s_case = %d;",
          nameResolver.fieldName(field.getOneofName()), field.getFieldNumber());
    }
  }

  private void emitRepeatedDeserialize(CodeWriter w, ProtoField field, String rustName) {
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) {
      String msgType = simpleTypeName(field.getTypeReference());
      w.line("let sub_count: usize = value.parse().unwrap_or(0);");
      w.line("*offset += 1;");
      w.line("obj.%s.push(%s::parse_pbtk_tokens(tokens, sub_count, offset));", rustName, msgType);
      w.line("*offset -= 1;");
    } else if (field.getKind() == ProtoField.FieldKind.ENUM) {
      String enumType = simpleTypeName(field.getTypeReference());
      w.line("obj.%s.push(%s::from(value.parse::<i32>().unwrap_or(0)));", rustName, enumType);
    } else {
      String readExpr = scalarReadExpr(field.getProtoType(), "value");
      w.line("obj.%s.push(%s);", rustName, readExpr);
    }
  }

  private void emitMapDeserialize(CodeWriter w, ProtoField field, String rustName) {
    w.line("let entry_count: usize = value.parse().unwrap_or(0);");
    w.line("*offset += 1;");

    // Determine key/value Rust types
    String keyRustType = typeMapper.scalarType(field.getMapKeyType());
    String valRustType;
    if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE
        || field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
      valRustType = simpleTypeName(field.getMapValueTypeReference());
    } else {
      valRustType = typeMapper.scalarType(field.getMapValueType());
    }

    w.line("let mut entry_key: Option<%s> = None;", keyRustType);
    w.line("let mut entry_val: Option<%s> = None;", valRustType);

    w.block(
        "for _ in 0..entry_count",
        () -> {
          w.line("if *offset >= tokens.len() { break; }");
          w.line("let mt = tokens[*offset];");
          w.line("let mne = mt.find(|c: char| !c.is_ascii_digit()).unwrap_or(mt.len());");
          w.line("if mne == 0 || mne >= mt.len() { *offset += 1; continue; }");
          w.line("let mfn: i32 = mt[..mne].parse().unwrap_or(0);");
          w.line("let mval = &mt[mne + 1..];");

          w.block(
              "if mfn == 1",
              () -> {
                String keyRead = scalarReadExpr(field.getMapKeyType(), "mval");
                w.line("entry_key = Some(%s);", keyRead);
              });
          w.block(
              "if mfn == 2",
              () -> {
                if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_MESSAGE) {
                  String msgType = simpleTypeName(field.getMapValueTypeReference());
                  w.line("let vsc: usize = mval.parse().unwrap_or(0);");
                  w.line("*offset += 1;");
                  w.line("entry_val = Some(%s::parse_pbtk_tokens(tokens, vsc, offset));", msgType);
                  w.line("*offset -= 1;");
                } else if (field.getMapValueType() == FieldDescriptorProto.Type.TYPE_ENUM) {
                  String enumType = simpleTypeName(field.getMapValueTypeReference());
                  w.line("entry_val = Some(%s::from(mval.parse::<i32>().unwrap_or(0)));", enumType);
                } else {
                  String valRead = scalarReadExpr(field.getMapValueType(), "mval");
                  w.line("entry_val = Some(%s);", valRead);
                }
              });
          w.line("*offset += 1;");
        });

    w.line("*offset -= 1;"); // compensate for outer offset increment
    w.block(
        "if let (Some(k), Some(v)) = (entry_key, entry_val)",
        () -> w.line("obj.%s.insert(k, v);", rustName));
  }

  private String scalarReadExpr(FieldDescriptorProto.Type type, String valueVar) {
    return switch (type) {
      case TYPE_DOUBLE -> valueVar + ".parse::<f64>().unwrap_or(0.0)";
      case TYPE_FLOAT -> valueVar + ".parse::<f32>().unwrap_or(0.0)";
      case TYPE_INT64, TYPE_SINT64, TYPE_SFIXED64 -> valueVar + ".parse::<i64>().unwrap_or(0)";
      case TYPE_UINT64, TYPE_FIXED64 -> valueVar + ".parse::<u64>().unwrap_or(0)";
      case TYPE_INT32, TYPE_SINT32, TYPE_SFIXED32 -> valueVar + ".parse::<i32>().unwrap_or(0)";
      case TYPE_UINT32, TYPE_FIXED32 -> valueVar + ".parse::<u32>().unwrap_or(0)";
      case TYPE_BOOL -> valueVar + " == \"1\"";
      case TYPE_STRING -> "urlencoding::decode(" + valueVar + ").unwrap_or_default().into_owned()";
      case TYPE_BYTES -> "general_purpose::STANDARD.decode(" + valueVar + ").unwrap_or_default()";
      default -> valueVar + ".to_string()";
    };
  }

  // ---------------------------------------------------------------------------
  // Enum and nested message emission
  // ---------------------------------------------------------------------------

  private void emitEnum(CodeWriter w, ProtoEnum protoEnum) {
    w.blankLine();
    w.line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]");
    w.line("#[repr(i32)]");
    w.block(
        "pub enum " + protoEnum.getName(),
        () -> {
          for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
            String rustName = nameResolver.enumConstantName(val.name());
            w.line("%s = %d,", rustName, val.number());
          }
        });

    w.blankLine();
    w.block(
        "impl Default for " + protoEnum.getName(),
        () -> {
          w.block(
              "fn default() -> Self",
              () -> {
                if (!protoEnum.getValues().isEmpty()) {
                  String firstName =
                      nameResolver.enumConstantName(protoEnum.getValues().get(0).name());
                  w.line("%s::%s", protoEnum.getName(), firstName);
                } else {
                  w.line("unsafe { std::mem::zeroed() }");
                }
              });
        });

    w.blankLine();
    w.block(
        "impl From<i32> for " + protoEnum.getName(),
        () -> {
          w.block(
              "fn from(value: i32) -> Self",
              () -> {
                w.block(
                    "match value",
                    () -> {
                      for (ProtoEnum.EnumValue val : protoEnum.getValues()) {
                        String rustName = nameResolver.enumConstantName(val.name());
                        w.line("%d => %s::%s,", val.number(), protoEnum.getName(), rustName);
                      }
                      if (!protoEnum.getValues().isEmpty()) {
                        String firstName =
                            nameResolver.enumConstantName(protoEnum.getValues().get(0).name());
                        w.line("_ => %s::%s,", protoEnum.getName(), firstName);
                      }
                    });
              });
        });
  }

  private void emitNestedMessage(CodeWriter w, ProtoMessage nested, ProtoFile file) {
    String structName = nameResolver.messageClassName(nested.getName());

    for (ProtoEnum protoEnum : nested.getEnums()) {
      emitEnum(w, protoEnum);
    }

    for (ProtoMessage deepNested : nested.getNestedMessages()) {
      w.blankLine();
      emitNestedMessage(w, deepNested, file);
    }

    w.line("#[derive(Debug, Clone, Default)]");
    w.block(
        "pub struct " + structName,
        () -> {
          emitFields(w, nested);
          emitOneofCaseFields(w, nested);
        });

    w.blankLine();
    w.block(
        "impl " + structName,
        () -> {
          w.block("pub fn new() -> Self", () -> w.line("Self::default()"));
          emitGettersSetters(w, nested);
          emitAppendPbtkFields(w, nested);
          emitCountPbtkFields(w, nested);

          w.blankLine();
          w.block(
              "pub fn to_pbtk_url(&self) -> String",
              () -> {
                w.line("let mut s = String::new();");
                w.line("self.append_pbtk_fields(&mut s);");
                w.line("s");
              });

          emitFromPbtkUrl(w, nested, structName);
        });

    emitDisplay(w, nested, structName);
  }

  // ---------------------------------------------------------------------------
  // Display impl
  // ---------------------------------------------------------------------------

  private void emitDisplay(CodeWriter w, ProtoMessage message, String structName) {
    w.blankLine();
    w.block(
        "impl std::fmt::Display for " + structName,
        () -> {
          w.block(
              "fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result",
              () -> {
                if (message.getFields().isEmpty()) {
                  w.line("write!(f, \"%s{{}}\")", structName);
                  return;
                }
                StringBuilder formatParts = new StringBuilder();
                StringBuilder argParts = new StringBuilder();
                for (int i = 0; i < message.getFields().size(); i++) {
                  ProtoField field = message.getFields().get(i);
                  String rustName = nameResolver.fieldName(field.getName());
                  if (i > 0) {
                    formatParts.append(", ");
                  }
                  formatParts.append(field.getName()).append(": {:?}");
                  argParts.append(", self.").append(rustName);
                }
                w.line(
                    "write!(f, \"%s{{%s}}\"%s)",
                    structName, formatParts.toString(), argParts.toString());
              });
        });
  }

  // ---------------------------------------------------------------------------
  // Utilities
  // ---------------------------------------------------------------------------

  static String pbtkTypeChar(FieldDescriptorProto.Type type) {
    return switch (type) {
      case TYPE_BOOL -> "b";
      case TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64 ->
          "i";
      case TYPE_FLOAT -> "f";
      case TYPE_DOUBLE -> "d";
      case TYPE_STRING -> "s";
      case TYPE_ENUM -> "e";
      case TYPE_MESSAGE -> "m";
      case TYPE_BYTES -> "z";
      default -> "s";
    };
  }

  private String simpleTypeName(String protoFullName) {
    if (protoFullName == null) return "()";
    int lastDot = protoFullName.lastIndexOf('.');
    return lastDot >= 0 ? protoFullName.substring(lastDot + 1) : protoFullName;
  }

  /** Convert a string to snake_case. Handles PascalCase, camelCase, and already-snake_case. */
  private static String toSnakeCase(String name) {
    if (name == null || name.isEmpty()) return name;
    if (name.contains("_") && name.equals(name.toLowerCase())) return name;
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < name.length(); i++) {
      char c = name.charAt(i);
      if (c == '_') {
        sb.append('_');
      } else if (Character.isUpperCase(c)) {
        if (i > 0 && name.charAt(i - 1) != '_') sb.append('_');
        sb.append(Character.toLowerCase(c));
      } else {
        sb.append(c);
      }
    }
    return sb.toString();
  }

  private boolean isRustCopyType(ProtoField field) {
    if (field.isMap() || field.isRepeated()) return false;
    if (field.isProto3Optional()) return false;
    if (field.getKind() == ProtoField.FieldKind.MESSAGE
        || field.getKind() == ProtoField.FieldKind.WELL_KNOWN_TYPE) return false;
    if (field.getKind() == ProtoField.FieldKind.ENUM) return true;
    return switch (field.getProtoType()) {
      case TYPE_DOUBLE,
          TYPE_FLOAT,
          TYPE_INT64,
          TYPE_SINT64,
          TYPE_SFIXED64,
          TYPE_UINT64,
          TYPE_FIXED64,
          TYPE_INT32,
          TYPE_SINT32,
          TYPE_SFIXED32,
          TYPE_UINT32,
          TYPE_FIXED32,
          TYPE_BOOL ->
          true;
      default -> false;
    };
  }

  private boolean hasFieldOfType(ProtoMessage message, FieldDescriptorProto.Type type) {
    for (ProtoField field : message.getFields()) {
      if (field.getProtoType() == type) return true;
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      if (hasFieldOfType(nested, type)) return true;
    }
    return false;
  }

  private boolean hasMapFields(ProtoMessage message) {
    for (ProtoField field : message.getFields()) {
      if (field.isMap()) return true;
    }
    for (ProtoMessage nested : message.getNestedMessages()) {
      if (hasMapFields(nested)) return true;
    }
    return false;
  }
}
